<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../services/MessengerForwardService.php';
Auth::requireLogin();$user=Auth::user();$shareId=(int)($_GET['id']??0);$pageTitle='مشاهده گزارش فورواردشده';$adminExtraStylesheets=['/assets/css/messenger.css'];
try{$share=MessengerForwardService::shareForUser($shareId,$user);if(!$share){http_response_code(403);$viewError='این گزارش برای شما ارسال نشده یا در دسترس نیست.';}else{MessengerForwardService::markRead((int)($share['message_id']??0),(int)$user['id']);$snapshot=$share['snapshot'];}}catch(Throwable $e){error_log('messenger report view: '.$e->getMessage());http_response_code(500);$viewError='نمایش گزارش در حال حاضر ممکن نیست.';}
require __DIR__.'/../views/partials/admin-header.php';
?>
<?php if(!empty($viewError)):?><div class="card messenger-error"><h1>دسترسی به گزارش ممکن نیست</h1><p><?=e($viewError)?></p><a class="btn" href="/messenger/">بازگشت به پیام‌رسان</a></div><?php else:?><article class="report-snapshot"><header class="snapshot-head"><div><span>Snapshot فقط‌خواندنی</span><h1><?=e($snapshot['title']??$share['report_title'])?></h1><p>ارسال‌کننده: <?=e($share['sender_name'])?> · دوره: <?=e(!empty($snapshot['period'])?format_jalali_date($snapshot['period']):'—')?> · ارسال: <?=e(format_jalali_datetime($share['sent_at']??$share['created_at']))?></p></div><div class="snapshot-actions"><a class="btn btn-light" href="/messenger/">پیام‌رسان</a><?php if($share['attachment_path']):?><a class="btn" href="/messenger/report-attachment.php?id=<?=$shareId?>">دانلود پیوست</a><?php endif?><button class="btn btn-light" onclick="window.print()">چاپ</button></div></header>
<?php if($share['description']):?><section class="snapshot-note"><h2>توضیحات ارسال‌کننده</h2><p><?=nl2br(e($share['description']))?></p></section><?php endif?>
<?php if(!empty($snapshot['summary_cards'])):?><section class="snapshot-kpis"><?php foreach($snapshot['summary_cards'] as $card):?><article><span><?=e((string)($card['label']??''))?></span><strong><?=e((string)($card['value']??''))?></strong></article><?php endforeach?></section><?php endif?>
<?php if(!empty($snapshot['table']['columns'])):?><section class="snapshot-table"><h2>جدول گزارش</h2><div class="table-wrap"><table><thead><tr><?php foreach($snapshot['table']['columns'] as $column):?><th><?=e((string)$column['label'])?></th><?php endforeach?></tr></thead><tbody><?php foreach($snapshot['table']['rows'] as $row):?><tr><?php foreach($snapshot['table']['columns'] as $column):?><td><?=e((string)($row[$column['key']]??'—'))?></td><?php endforeach?></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<?php if(!empty($snapshot['chart']['data'])):$chartMax=max(array_column($snapshot['chart']['data'],'value'))?:1;?><section class="snapshot-analysis"><h2><?=e((string)($snapshot['chart']['label']??'نمودار گزارش'))?></h2><div class="snapshot-bars"><?php foreach($snapshot['chart']['data'] as $point):?><div><span><?=e((string)$point['label'])?></span><i style="--bar:<?=e((string)min(100,max(1,((float)$point['value']/$chartMax)*100)))?>%"></i><b><?=e((string)$point['value_label'])?></b></div><?php endforeach?></div></section><?php endif?>
<?php if(!empty($snapshot['ai_analysis'])):?><section class="snapshot-analysis"><h2>تحلیل هوش مصنوعی</h2><p><?=nl2br(e($snapshot['ai_analysis']))?></p></section><?php endif?>
<footer class="snapshot-foot">این نسخه در <?=e(format_jalali_datetime($share['created_at']))?> ساخته و با SHA-256 کنترل یکپارچگی شده است.</footer></article><?php endif?>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
