<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../lib/messenger/MessengerSecurity.php';Auth::requireLogin();if(!MessengerSecurity::can('messenger.view')){http_response_code(403);$pageTitle='دسترسی پیام‌رسان';require __DIR__.'/../views/partials/admin-header.php';?><section class="card"><h1>دسترسی پیام‌رسان برای شما فعال نیست</h1><p>از مدیر سامانه بخواهید مجوز <code>messenger.view</code> را در بخش کاربران و دسترسی‌ها برای حساب شما فعال کند.</p><a class="btn" href="/admin/index.php">بازگشت به داشبورد</a></section><?php require __DIR__.'/../views/partials/admin-footer.php';exit;}$pageTitle='پیام‌رسان سازمانی';$adminExtraStylesheets=['/assets/css/sobhan-messenger.css','/assets/css/sobhan-messenger-media.css'];require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="sm-app" data-messenger data-csrf="<?=e(Auth::csrfToken())?>" data-conversation="<?=(int)($_GET['conversation']??0)?>">
 <div class="alert alert-danger" data-messenger-error role="alert" hidden></div>
 <aside class="sm-sidebar"><header><div><small>مرکز ارتباطات سبحان</small><h1>پیام‌رسان</h1></div><button class="btn btn-small" data-new-chat>گفتگوی جدید</button></header><label class="sm-search"><input type="search" placeholder="جستجو در گفتگوها…" data-conversation-search></label><nav data-conversations><p class="muted">در حال دریافت گفتگوها…</p></nav></aside>
 <main class="sm-chat"><header class="sm-chat-head"><button type="button" data-back>‹</button><div><h2 data-chat-title>یک گفتگو را انتخاب کنید</h2><small data-chat-meta>پیام‌های امن سازمانی</small></div><div class="sm-actions"><a href="/employee/message-inbox.php">کارتابل</a><button type="button" data-toggle-info>اطلاعات</button></div></header><section class="sm-messages" data-messages><div class="sm-welcome"><span>س</span><h2>ارتباط سریع، امن و قابل پیگیری</h2><p>از فهرست کنار صفحه یک گفتگو را باز کنید.</p></div></section><form class="sm-composer" data-composer hidden><input type="file" accept="image/*,video/*,audio/*,.pdf,.txt,.zip" data-file hidden><button type="button" data-attach title="پیوست">＋</button><button type="button" data-location title="ارسال موقعیت">⌖</button><button type="button" data-voice title="ضبط صدا">●</button><textarea rows="1" maxlength="10000" placeholder="پیام بنویسید…" data-body></textarea><button class="sm-send" type="submit">ارسال</button></form></main>
 <aside class="sm-info" data-info><header><h3>جزئیات گفتگو</h3><button type="button" data-toggle-info>×</button></header><div data-info-body><p class="muted">برای مشاهده اعضا و تنظیمات، گفتگو را انتخاب کنید.</p></div></aside>
</div>
<dialog class="sm-dialog" data-new-dialog><form method="dialog" data-new-form><header><h2>گفتگوی جدید</h2><button value="cancel">×</button></header><label>نوع گفتگو<select name="type"><option value="private">خصوصی</option><?php if(MessengerSecurity::can('messenger.group.create','create')):?><option value="group">گروه</option><?php endif?><?php if(MessengerSecurity::can('messenger.channel.create','create')):?><option value="channel">کانال</option><?php endif?></select></label><label>عنوان<input name="title" maxlength="190"></label><label>انتخاب همکار<input type="search" data-user-search placeholder="نام، واحد یا سمت"><select name="participant_ids[]" data-users multiple size="8"></select></label><footer><button value="cancel" class="btn btn-light">انصراف</button><button type="submit" class="btn">ایجاد گفتگو</button></footer></form></dialog>
<script>window.SobhanUserId=<?=(int)Auth::user()['id']?>;window.alert=function(message){const box=document.querySelector('[data-messenger-error]');if(!box)return;box.textContent=String(message||'عملیات پیام‌رسان انجام نشد.');box.hidden=false;clearTimeout(window.__messengerErrorTimer);window.__messengerErrorTimer=setTimeout(()=>box.hidden=true,7000)};</script><script src="/assets/js/sobhan-messenger.js"></script><script src="/assets/js/sobhan-messenger-media.js"></script><script src="/assets/js/sobhan-messenger-realtime.js"></script>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
