<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Database.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../services/TestScoringService.php';Auth::requireLogin();$user=Auth::user();$assignmentId=(int)($_REQUEST['assignment_id']??0);
$assignment=Database::fetch('SELECT a.*,t.title,t.description,t.code test_code,t.time_limit_minutes FROM hr_assessment_assignments a JOIN hr_assessment_tests t ON t.id=a.test_id WHERE a.id=? AND a.employee_id=?',[$assignmentId,(int)$user['id']]);if(!$assignment){http_response_code(404);exit('رکورد موردنظر یافت نشد.');}
if($assignment['due_date']&&$assignment['due_date']<date('Y-m-d')&&!in_array($assignment['status'],['submitted','cancelled'],true)){Database::execute('UPDATE hr_assessment_assignments SET status="expired",updated_at=NOW() WHERE id=?',[$assignmentId]);$assignment['status']='expired';}
$response=Database::fetch('SELECT * FROM hr_assessment_responses WHERE assignment_id=? AND employee_id=?',[$assignmentId,(int)$user['id']]);
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Auth::verifyCsrf($_POST['csrf_token']??'')){http_response_code(419);exit('درخواست نامعتبر است.');}$action=$_POST['action']??'save';
    if($action==='retake'){if($assignment['status']!=='submitted'||!(int)$assignment['allow_retake']){http_response_code(403);exit('دسترسی غیرمجاز است.');}Database::execute('UPDATE hr_assessment_responses SET answers_json="{}",progress_json="{}",status="in_progress",started_at=NOW(),submitted_at=NULL,updated_at=NOW() WHERE assignment_id=?',[$assignmentId]);Database::execute('UPDATE hr_assessment_assignments SET status="in_progress",updated_at=NOW() WHERE id=?',[$assignmentId]);redirect('/employee/test_run.php?assignment_id='.$assignmentId);}
    if(in_array($assignment['status'],['submitted','expired','cancelled'],true)){flash('این آزمون قبلاً تکمیل شده است.','danger');redirect('/employee/tests.php');}
    $oldAnswers=$response?json_decode($response['answers_json']?:'{}',true):[];$answers=array_replace(is_array($oldAnswers)?$oldAnswers:[],array_filter($_POST['answer']??[],fn($v)=>$v!==''));$questions=Database::fetchAll('SELECT id,required FROM hr_assessment_questions WHERE test_id=? AND active=1',[$assignment['test_id']]);
    if($action==='submit')foreach($questions as $q)if((int)$q['required']&&!array_key_exists((string)$q['id'],$answers)){$missing=true;break;}
    if(!empty($missing)){flash('لطفاً به همه پرسش‌های الزامی پاسخ دهید.','danger');redirect('/employee/test_run.php?assignment_id='.$assignmentId);}
    $json=json_encode($answers,JSON_UNESCAPED_UNICODE);try{if($response)Database::execute('UPDATE hr_assessment_responses SET answers_json=?,progress_json=?,status=?,submitted_at='.($action==='submit'?'NOW()':'submitted_at').',updated_at=NOW() WHERE id=?',[$json,json_encode(['answered'=>count($answers),'total'=>count($questions)]),$action==='submit'?'submitted':'in_progress',$response['id']]);else{Database::execute('INSERT INTO hr_assessment_responses(assignment_id,employee_id,test_id,answers_json,progress_json,status,started_at,submitted_at,created_at,updated_at) VALUES (?,?,?,?,?,?,NOW(),'.($action==='submit'?'NOW()':'NULL').',NOW(),NOW())',[$assignmentId,(int)$user['id'],$assignment['test_id'],$json,json_encode(['answered'=>count($answers),'total'=>count($questions)]),$action==='submit'?'submitted':'in_progress']);}$response=Database::fetch('SELECT * FROM hr_assessment_responses WHERE assignment_id=?',[$assignmentId]);if($action==='submit'){(new TestScoringService())->calculate((int)$user['id'],(int)$assignment['test_id'],$answers,$assignmentId);Database::execute('UPDATE hr_assessment_assignments SET status="submitted",updated_at=NOW() WHERE id=?',[$assignmentId]);flash('عملیات با موفقیت انجام شد.');redirect('/employee/test_run.php?assignment_id='.$assignmentId);}Database::execute('UPDATE hr_assessment_assignments SET status="in_progress",updated_at=NOW() WHERE id=?',[$assignmentId]);flash('پاسخ‌های موقت ذخیره شد.');}catch(Throwable $e){error_log('Assessment response save: '.$e->getMessage());flash('خطا در ذخیره‌سازی اطلاعات. لطفاً مجدد تلاش کنید.','danger');}redirect('/employee/test_run.php?assignment_id='.$assignmentId);
}
$pageTitle=$assignment['title'];$result=Database::fetch('SELECT * FROM hr_assessment_results WHERE assignment_id=? ORDER BY id DESC LIMIT 1',[$assignmentId]);if($assignment['status']==='submitted'){$normalized=$result?json_decode($result['normalized_scores_json'],true):[];require __DIR__.'/../views/partials/admin-header.php';?><section class="card hr-result"><h1><?=e($assignment['title'])?></h1><p class="achievement-pill achievement-good"><?=e($result['final_result']??'ثبت شده')?></p><p><strong>سطح پیگیری:</strong> <?=e($result['risk_level']??'-')?></p><p><?=e($result['profile_summary']??'')?></p><p><?=e($result['recommendation_text']??'')?></p><div class="hr-dimension-grid"><?php foreach($normalized as $key=>$score):?><div><span><?=e($key)?></span><strong><?=e($score)?>٪</strong></div><?php endforeach?></div><?php if($assignment['allow_retake']):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="assignment_id" value="<?=$assignmentId?>"><button class="btn" name="action" value="retake">تکرار آزمون</button></form><?php endif?><a class="btn" href="/employee/tests.php">بازگشت</a></section></section></main></div><script src="/assets/js/app.js"></script></body></html><?php exit;}
if(in_array($assignment['status'],['expired','cancelled'],true)){http_response_code(403);exit('این آزمون قابل اجرا نیست.');}
if(!$response){Database::execute('INSERT INTO hr_assessment_responses(assignment_id,employee_id,test_id,answers_json,progress_json,status,started_at,created_at,updated_at) VALUES (?,?,?,"{}","{}","in_progress",NOW(),NOW(),NOW())',[$assignmentId,(int)$user['id'],$assignment['test_id']]);Database::execute('UPDATE hr_assessment_assignments SET status="in_progress",updated_at=NOW() WHERE id=?',[$assignmentId]);$response=Database::fetch('SELECT * FROM hr_assessment_responses WHERE assignment_id=?',[$assignmentId]);}
$answers=json_decode($response['answers_json']?:'{}',true)?:[];$questions=Database::fetchAll('SELECT * FROM hr_assessment_questions WHERE test_id=? AND active=1 ORDER BY sort_order,id',[$assignment['test_id']]);require __DIR__.'/../views/partials/admin-header.php';?>
<section class="card hr-test-run"><header><div><h1><?=e($assignment['title'])?></h1><p><?=e($assignment['description'])?></p></div><strong id="progressText">۰ / <?=count($questions)?></strong></header><div class="progress"><span id="progressBar" style="width:0"></span></div><form method="post" id="testForm"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="assignment_id" value="<?=$assignmentId?>"><?php foreach($questions as $index=>$q):$options=json_decode($q['options_json']?:'{}',true)?:[];?><fieldset class="hr-question" data-step="<?=$index?>" <?=$index?'hidden':''?>><legend><small>پرسش <?=$index+1?> از <?=count($questions)?></small><?=e($q['question_text'])?></legend><?php if(in_array($q['answer_type'],['scale_1_5','scale_1_7','choice','yesno'],true)):if($q['answer_type']==='yesno')$options=['1'=>'بله','0'=>'خیر'];foreach($options as $value=>$label):?><label class="hr-answer"><input type="radio" name="answer[<?=$q['id']?>]" value="<?=e((string)$value)?>" <?=isset($answers[$q['id']])&&(string)$answers[$q['id']]===(string)$value?'checked':''?>> <span><?=e((string)$label)?></span></label><?php endforeach;else:?><textarea name="answer[<?=$q['id']?>]" rows="5"><?=e($answers[$q['id']]??'')?></textarea><?php endif?></fieldset><?php endforeach?><div class="form-actions"><button type="button" class="btn" id="prev">قبلی</button><button type="button" class="btn btn-primary" id="next">بعدی</button><button class="btn" name="action" value="save">ذخیره موقت</button><button class="btn btn-primary" name="action" value="submit" onclick="return confirm('پاسخ‌ها نهایی شود؟')">ثبت نهایی</button><a class="btn" href="/employee/tests.php">بازگشت</a></div></form></section><script>const qs=[...document.querySelectorAll('.hr-question')],bar=document.getElementById('progressBar'),txt=document.getElementById('progressText');let step=0;function show(n){step=Math.max(0,Math.min(qs.length-1,n));qs.forEach((q,i)=>q.hidden=i!==step);bar.style.width=((step+1)/qs.length*100)+'%';txt.textContent=(step+1)+' / '+qs.length}document.getElementById('prev').onclick=()=>show(step-1);document.getElementById('next').onclick=()=>show(step+1);show(0);</script>
</section></main></div><script src="/assets/js/app.js"></script></body></html>
