<?php
require_once __DIR__.'/../../core/Database.php';require_once __DIR__.'/../../services/NotificationHubService.php';
ini_set('display_errors','0');header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
function notify_json(bool $success,mixed $data=null,?array $error=null,int $status=200,array $meta=[]): never{http_response_code($status);$out=['success'=>$success,'data'=>$data,'error'=>$error];if($meta)$out['meta']=$meta;echo json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function notify_headers(): array{$out=[];foreach(getallheaders()?:[] as $k=>$v)$out[strtolower($k)]=(string)$v;return $out;}
function notify_input(): array{$raw=file_get_contents('php://input');$json=json_decode((string)$raw,true);return is_array($json)?$json:$_POST;}
function notify_method(string $method): void{if($_SERVER['REQUEST_METHOD']!==$method)notify_json(false,null,['code'=>'method_not_allowed','message'=>'روش درخواست معتبر نیست.'],405);}
function notify_device(): array{try{return NotificationHubService::authenticate(notify_headers());}catch(Throwable $e){$code=$e->getMessage()==='device_auth_required'?'device_auth_required':'device_auth_invalid';notify_json(false,null,['code'=>$code,'message'=>'اتصال دستگاه معتبر نیست.'],401);}}
function notify_fail(Throwable $e): never{error_log('notify api: '.$e->getMessage());$known=['action_not_allowed'=>'این اقدام برای اعلان مجاز نیست.','action_not_supported'=>'این اقدام هنوز در سامانه مقصد فعال نیست.','notification_not_found'=>'اعلان پیدا نشد.','reply_not_allowed'=>'پاسخ سریع مجاز نیست.','pairing_rate_limited'=>'تعداد تلاش‌ها بیش از حد مجاز است؛ کمی بعد دوباره تلاش کنید.'];$raw=$e->getMessage();$code=array_key_exists($raw,$known)?$raw:($e instanceof InvalidArgumentException?'validation_error':'request_failed');$status=$raw==='pairing_rate_limited'?429:(in_array($raw,['action_not_allowed','reply_not_allowed'],true)?403:($raw==='notification_not_found'?404:422));notify_json(false,null,['code'=>$code,'message'=>$known[$raw]??($e instanceof InvalidArgumentException?$e->getMessage():'انجام درخواست ممکن نیست.')],$status);}
