<?php
return ['seed_key'=>'permissions','run'=>static function(PDO $pdo,array $options):array{
    $items=[
        ['dashboard','داشبورد',10],['users','کاربران',20],['kpis','شاخص‌ها',30],['surveys','نظرسنجی‌ها',40],['survey_results','نتایج ارزیابی',50],['files','فایل‌ها',60],['accounting','حسابداری',65],['ceo_dashboard','داشبورد مدیرعامل',68],['pharmacy_settings','تنظیمات داروخانه',69],['carousel','اسلایدر صفحه اصلی',70],['settings','تنظیمات سایت',80],
        ['view_ceo_dashboard','مشاهده داشبورد مدیرعامل',681],['view_sobhan_api_settings','مشاهده تنظیمات API سبحان',682],['manage_sobhan_api_settings','مدیریت تنظیمات API سبحان',683],['use_ai_assistant','استفاده از دستیار هوش مصنوعی',684],['view_ai_chat','مشاهده گفتگوی هوش مصنوعی',685],['manage_ai_chat_settings','مدیریت تنظیمات گفتگوی هوش مصنوعی',686],['manage_knowledge','مدیریت منابع دانش هوش مصنوعی',6865],['view_data_source_settings','مشاهده تنظیمات منبع داده',687],['manage_data_source_settings','مدیریت تنظیمات منبع داده',688],['toggle_ai_autofill','فعال‌سازی تکمیل خودکار هوش مصنوعی',689],['allow_ai_overwrite_manual_data','اجازه بازنویسی داده دستی با هوش مصنوعی',690],
        ['manager_dashboard.view','مشاهده پنل مدیران فروش',691],['manager_dashboard.edit','ویرایش پنل مدیران فروش',692],['manager_dashboard.import','ورود اکسل پنل مدیران فروش',693],['manager_dashboard.export','خروجی اکسل پنل مدیران فروش',694],['manager_dashboard.settings','تنظیمات پنل مدیران فروش',695],['manager_dashboard.ai','بینش هوشمند پنل مدیران فروش',696],['manager_dashboard.image_export','خروجی تصویری داشبورد مدیران',697],['manager_dashboard.ai_settings','تنظیمات هوش مصنوعی داشبورد مدیران',698],['manager_dashboard.ai_run','اجرای تحلیل هوش مصنوعی داشبورد مدیران',699],
        ['hr_kpi.view','مشاهده داشبورد KPI منابع انسانی',700],['hr_kpi.manage','مدیریت قالب‌ها و دوره‌های KPI',701],['hr_kpi.score','ثبت امتیاز KPI پرسنل',702],['hr_kpi.results','مشاهده نتایج KPI',703],['hr_assessments.manage','مدیریت آزمون‌های سازمانی',704],['hr_assessments.results','مشاهده نتایج آزمون‌های سازمانی',705],['hr_assessments.recalculate','محاسبه مجدد نتیجه آزمون',706],['hr_tests.own','مشاهده آزمون‌های خود',707],['ai_insights','مدیریت منابع گزارشی AI',708],['system_maintenance','بروزرسانی SQL و Seed',709],['ai_updates','اجرای بروزرسانی هوش مصنوعی',710],['hr_attendance.own','مشاهده کارکرد شخصی',148],
    ];
    $inserted=0;$skipped=0;$dry=($options['mode']??'safe')==='dry_run';$stmt=$pdo->prepare('INSERT IGNORE INTO modules(module_key,module_title,sort_order,status,created_at) VALUES (?,?,?,"active",NOW())');foreach($items as $item){if($pdo->query('SELECT COUNT(*) FROM modules WHERE module_key='.$pdo->quote($item[0]))->fetchColumn()){$skipped++;continue;}if(!$dry){$stmt->execute($item);$inserted+=$stmt->rowCount();}else $inserted++;}return ['inserted'=>$inserted,'updated'=>0,'skipped'=>$skipped,'errors'=>0,'details'=>['permissions'=>$inserted]];
}];
