<?php
$root=dirname(__DIR__);
$required=['core/SalesOperationsModule.php','services/SalesOperationsService.php','admin/supervisor-dashboard.php','admin/supervisor-sales-report.php','admin/supervisor-actions.php','admin/supervisor-action-view.php','admin/supervisor-settings.php','admin/sales-manager-supervisor-reports.php','admin/sales-actions.php','admin/sales-scripts.php','admin/sales-script-fields.php','admin/sales-purchase-suggestions.php','admin/sales-manager-daily-work-log.php','install/sales_supervisor_panel_repair.php','install/seeds/009_sales_operations_seed.php','lib/admin_menu.php'];
foreach($required as $file)if(!is_file($root.'/'.$file))throw new RuntimeException('Missing file: '.$file);
$service=file_get_contents($root.'/services/SalesOperationsService.php');
foreach(['requireSupervisorPermission','requireSalesManagerPermission','canAccessSupervisor','assertVisitorBelongsToSupervisor','canAccessSalesUser','plannerAvailable','related_module','related_record_id','FOR UPDATE'] as $token)if(!str_contains($service,$token))throw new RuntimeException('Missing hardening contract: '.$token);
if(preg_match('/\b(DROP|TRUNCATE|RENAME\s+TABLE)\b/i',file_get_contents($root.'/core/SalesOperationsModule.php')))throw new RuntimeException('Destructive migration found.');
foreach(array_slice($required,2,11) as $file){$source=file_get_contents($root.'/'.$file);if(str_contains($source,"REQUEST_METHOD']==='POST'")&&!str_contains($source,'verifyCsrf'))throw new RuntimeException('POST without CSRF: '.$file);}
$registry=require $root.'/install/seed_registry.php';if(!isset($registry['sales_operations']))throw new RuntimeException('Sales operations seed is not registered.');

$dsn=getenv('SALES_TEST_DSN');
if($dsn){
    $pdo=new PDO($dsn,getenv('SALES_TEST_USER')?:'root',getenv('SALES_TEST_PASS')?:'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
    $pdo->exec('CREATE TABLE IF NOT EXISTS modules(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,module_key VARCHAR(100) NOT NULL UNIQUE,module_title VARCHAR(190) NOT NULL,sort_order INT NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT "active",created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
    require_once $root.'/core/SalesOperationsModule.php';SalesOperationsModule::repair($pdo);$first=(int)$pdo->query('SELECT COUNT(*) FROM supervisor_action_field_templates')->fetchColumn();SalesOperationsModule::repair($pdo);$second=(int)$pdo->query('SELECT COUNT(*) FROM supervisor_action_field_templates')->fetchColumn();if($first!==$second)throw new RuntimeException('Repeated repair duplicated default fields.');
    $duplicates=(int)$pdo->query('SELECT COUNT(*) FROM (SELECT section_id,field_key,COUNT(*) c FROM supervisor_action_field_templates GROUP BY section_id,field_key HAVING c>1) x')->fetchColumn();if($duplicates!==0)throw new RuntimeException('Duplicate action fields found.');
    $pdo->exec('CREATE TABLE IF NOT EXISTS users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190),email VARCHAR(190),username VARCHAR(190),employee_no VARCHAR(80),mobile VARCHAR(40),force_password_change TINYINT DEFAULT 0,role VARCHAR(30),status VARCHAR(20),description TEXT,upload_quota_mb INT DEFAULT 0,department VARCHAR(190),role_key VARCHAR(100),sales_line VARCHAR(50),supervisor_id INT NULL,organization_manager_id INT NULL,org_unit_id INT NULL,org_role_id INT NULL,parent_user_id INT NULL,access_scope VARCHAR(20),employee_panel_enabled TINYINT DEFAULT 1,admin_panel_enabled TINYINT DEFAULT 0,display_order INT DEFAULT 0,last_login_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('CREATE TABLE IF NOT EXISTS user_permissions(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED,module_key VARCHAR(100),can_view TINYINT DEFAULT 0,can_create TINYINT DEFAULT 0,can_edit TINYINT DEFAULT 0,can_delete TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('CREATE TABLE IF NOT EXISTS work_planner_tasks(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,employee_id INT UNSIGNED NULL,assigned_by INT UNSIGNED NULL,title VARCHAR(190) NOT NULL,description TEXT NULL,task_type VARCHAR(40),priority VARCHAR(20),status VARCHAR(20),due_date DATE NULL,related_module VARCHAR(100) NULL,related_record_id BIGINT UNSIGNED NULL,is_visible_on_dashboard TINYINT DEFAULT 1,created_at DATETIME,updated_at DATETIME,INDEX idx_related(related_module,related_record_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('DELETE FROM users');$insert=$pdo->prepare('INSERT INTO users(id,name,username,role,status,role_key,sales_line,supervisor_id,organization_manager_id,parent_user_id,access_scope) VALUES(?,?,?,?,"active",?,?,?,?,?,?)');
    $insert->execute([1,'مدیر یک','manager1','manager','SALES_MANAGER','L1',null,null,null,'team']);$insert->execute([2,'سرپرست یک','supervisor1','manager','SALES_SUPERVISOR','L1',null,1,1,'team']);$insert->execute([3,'ویزیتور یک','visitor1','employee','VISITOR','L1',2,1,2,'self']);$insert->execute([4,'سرپرست خارج','supervisor2','manager','SALES_SUPERVISOR','L2',null,null,null,'team']);$insert->execute([5,'کاربر خارج','outsider','employee','VISITOR','L2',4,null,4,'self']);
    $pdo->exec('DELETE FROM sales_team_assignments');$pdo->exec('INSERT INTO sales_team_assignments(supervisor_id,visitor_id,sales_manager_id,sales_line,active) VALUES(2,3,1,"L1",1),(4,5,NULL,"L2",1)');
    $databaseReflection=new ReflectionClass(Database::class);$pdoProperty=$databaseReflection->getProperty('pdo');$pdoProperty->setAccessible(true);$pdoProperty->setValue(null,$pdo);$migratedProperty=$databaseReflection->getProperty('migrated');$migratedProperty->setAccessible(true);$migratedProperty->setValue(null,true);
    if(session_status()!==PHP_SESSION_ACTIVE)session_start();$_SESSION['user_id']=1;$_SESSION['role']='manager';
    require_once $root.'/services/SalesOperationsService.php';$manager=['id'=>1,'role'=>'manager','role_key'=>'SALES_MANAGER'];if(!SalesOperationsService::canAccessSupervisor(2,$manager)||SalesOperationsService::canAccessSupervisor(4,$manager))throw new RuntimeException('Manager supervisor scope failed.');if(!SalesOperationsService::assertVisitorBelongsToSupervisor(3,2)||SalesOperationsService::assertVisitorBelongsToSupervisor(5,2))throw new RuntimeException('Supervisor visitor scope failed.');
    $actionId=SalesOperationsService::createSalesAction(['sales_manager_id'=>1,'supervisor_id'=>2,'visitor_id'=>3,'assigned_to'=>2,'title'=>'پیگیری تست','description'=>'تست','add_to_planner'=>true]);SalesOperationsService::syncSalesActionToPlanner($actionId);$taskCount=(int)$pdo->query('SELECT COUNT(*) FROM work_planner_tasks WHERE related_module="sales_actions" AND related_record_id='.(int)$actionId)->fetchColumn();if($taskCount!==1)throw new RuntimeException('Planner sync is not idempotent.');
    $blocked=false;try{SalesOperationsService::createSalesAction(['sales_manager_id'=>1,'supervisor_id'=>4,'visitor_id'=>5,'assigned_to'=>5,'title'=>'خارج از محدوده']);}catch(InvalidArgumentException $e){$blocked=true;}if(!$blocked)throw new RuntimeException('Out-of-team action was accepted.');
    echo "Sales operations repair integration: PASS\n";
}
echo "Sales operations contract: PASS\n";
