<?php
$root=dirname(__DIR__);
require_once $root.'/core/SalesAggregateImportService.php';
require_once $root.'/tests/support/import_integration_bootstrap.php';
require_once $root.'/tests/support/xlsx_fixture.php';
$pdo=importIntegrationPdo($root);
seedImportIntegrationMappings($pdo);
$headers=SalesDataNormalizer::CANONICAL_HEADERS;
$row=array_fill(0,count($headers),'');
$values=['ردیف'=>'1','نوع فاکتور'=>'فروش','شماره فاکتور'=>'X-1001','تاریخ'=>'1405/04/25','کد فروشنده'=>'V-XLSX','نام فروشنده'=>'ویزیتور فایل','کد مشتری'=>'C-XLSX','نام مشتری'=>'مشتری فایل','کد کالا'=>'P-XLSX','نام کالا'=>'کالای فایل','تعداد کل'=>'1','مبلغ ناخالص'=>'100000','مجموع مبلغ تخفیف سطری'=>'5000','مبلغ خالص'=>'95000','کد یکتا'=>'XLSX-U-'.bin2hex(random_bytes(5)),'ماه گردش'=>'4- تیر'];
foreach($values as $header=>$value)$row[array_search($header,$headers,true)]=$value;
$rows=[$row];
$path=tempnam(sys_get_temp_dir(),'sales-xlsx-').'.xlsx';
createXlsxFixture($path,'گزارش تجمیعی فروش','tbltajmii',$headers,$rows);
$result=SalesAggregateImportService::readUploadedFile(['error'=>UPLOAD_ERR_OK,'tmp_name'=>$path,'size'=>filesize($path),'name'=>'name-must-not-matter.xlsx'],'skip_duplicates',1);
@unlink($path);
if($result['needs_selection']||$result['summary']['valid_rows']!==1)throw new RuntimeException('XLSX staging failed.');
$batch=Database::fetch('SELECT detected_sheet,detected_table FROM sales_import_batches WHERE id=?',[$result['batch_id']]);
if(($batch['detected_table']??'')!=='tbltajmii'||trim((string)($batch['detected_sheet']??''))!=='گزارش تجمیعی فروش')throw new RuntimeException('tbltajmii detection failed.');
$staged=Database::fetch('SELECT source_row_number,normalized_json FROM staging_sales_data WHERE import_batch_id=?',[$result['batch_id']]);
$normalized=json_decode((string)($staged['normalized_json']??''),true)?:[];
if((int)($staged['source_row_number']??0)!==1||($normalized['turnover_month']??'')!=='4- تیر'||($normalized['period_key']??'')!=='1405-04')throw new RuntimeException('Canonical row/turnover staging failed.');
$commit=SalesAggregateImportService::commitValidRows($result['batch_id'],1,true);
if($commit!==['imported'=>1,'updated'=>0,'skipped'=>0])throw new RuntimeException('XLSX commit failed.');
echo "Sales aggregate XLSX integration: PASS\n";
