<?php
$root=dirname(__DIR__);$fail=[];$read=static fn($f)=>(string)file_get_contents($root.'/'.$f);$ok=static function($condition,$message)use(&$fail){if(!$condition)$fail[]=$message;};
$files=['core/SmsModule.php','core/SmsGatewayService.php','core/SmsTemplateService.php','core/SmsNotificationService.php','admin/sms-settings.php','admin/sms-send.php','admin/sms-templates.php','admin/sms-messages.php','admin/sms-delivery-sync.php','install/sms_seed.php','docs/sms-module.md'];foreach($files as $file)$ok(is_file($root.'/'.$file),"Missing {$file}");
$module=$read('core/SmsModule.php');$service=$read('core/SmsGatewayService.php');$settings=$read('admin/sms-settings.php');$send=$read('admin/sms-send.php');$templates=$read('admin/sms-templates.php');$delivery=$read('admin/sms-delivery-sync.php');$schema=$read('database/schema.sql');$menu=$read('lib/admin_menu.php');
foreach(['sms_settings','sms_templates','sms_messages','sms_message_recipients','sms_gateway_logs'] as $table){$ok(str_contains($module,"CREATE TABLE IF NOT EXISTS {$table}"),"Runtime schema missing {$table}");$ok(str_contains($schema,"CREATE TABLE IF NOT EXISTS {$table}"),"Fresh schema missing {$table}");}
foreach(['sms_settings_manage','sms_template_manage','sms_send','sms_report_view','sms_delivery_sync'] as $permission)$ok(str_contains($module,$permission),"Permission missing {$permission}");
$ok(str_contains($settings,"requireAnyRole(['admin','super_admin'])"),'Settings is not admin-only');$ok(str_contains($settings,'verifyCsrf')&&str_contains($send,'verifyCsrf')&&str_contains($templates,'verifyCsrf')&&str_contains($delivery,'verifyCsrf'),'CSRF guard missing');
$ok(str_contains($settings,"if(\$password!=='')"),'Empty password preservation missing');$ok(!str_contains($settings,'password_encrypted]'),'Encrypted password exposed in UI');$ok(str_contains($service,"'soap.wsdl_cache_enabled','0'")&&str_contains($service,'WSDL_CACHE_NONE'),'SOAP cache controls missing');
foreach(['getDiagnostics','testConnection','getCredit','sendSimpleSms','getStatus','normalizeMobiles','translateProviderError','decodeProviderResponse','logSafeError','maskSensitive'] as $method)$ok(str_contains($service,"function {$method}"),"Gateway method missing {$method}");
$ok(str_contains($service,'array_chunk($valid,90)'),'90-recipient batching missing');$ok(str_contains($service,"hash('sha256',\$message)"),'Message hash missing');$ok(str_contains($service,'beginTransaction()')&&str_contains($service,'rollBack()'),'Atomic persistence missing');$ok(str_contains($service,'SendSimpleSMS')&&str_contains($service,'GetCredit')&&str_contains($service,'GetStatus'),'Provider methods missing');
$ok(str_contains($service,'GET_LOCK')&&str_contains($module,'uq_sms_request_key'),'Idempotency request lock missing');$ok(str_contains($service,'function segmentCount'),'SMS segment counter missing');
$ok(!preg_match('/\b(DROP|TRUNCATE)\b/i',$module.$schema),'Destructive SQL found');$ok(!preg_match('/url_api_base.*(curl|file_get_contents)/is',$service),'URL API usage found');
foreach(['request_created','request_updated','ticket_assigned','task_reminder','hr_assessment_assigned','system_alert'] as $code)$ok(str_contains($module,"'{$code}'"),"Seed missing {$code}");
foreach(['sms-settings.php','sms-send.php','sms-templates.php','sms-messages.php','sms-delivery-sync.php'] as $page)$ok(str_contains($menu,$page),"Menu missing {$page}");
require_once $root.'/core/SmsGatewayService.php';$gateway=new SmsGatewayService(['wsdl_url'=>'invalid','username'=>'','password'=>'','default_sender'=>'','is_active'=>1]);$normalized=$gateway->normalizeMobiles(['09123456789','9123456789','+989123456789','00989123456789','bad']);$ok($normalized===['09123456789'],'Mobile normalization or deduplication failed');$diagnostics=$gateway->getDiagnostics();$ok(isset($diagnostics['items']['soap_extension']),'SOAP diagnostics stage missing');$ok($gateway->translateProviderError('301')==='نام کاربری یا رمز عبور اشتباه است.','Provider error translation failed');
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "SMS_MODULE_CONTRACT_OK\n";
