using System.Net;using System.Net.Http.Json;using System.Reflection;using System.Security.Cryptography;using System.Text;using System.Text.Json;using SobhanNotificationHub.Models;
namespace SobhanNotificationHub.Services;public sealed class SobhanApiClient{private readonly HttpClient _http;private readonly AppSettings _settings;private readonly AuthTokenStore _tokens;private static readonly JsonSerializerOptions Json=new(){PropertyNameCaseInsensitive=true};public SobhanApiClient(AppSettings settings,AuthTokenStore tokens){_settings=settings;_tokens=tokens;var uri=new Uri(settings.SiteUrl);if(uri.Scheme!="https"&&!settings.DevelopmentAllowHttp)throw new InvalidOperationException("HTTPS برای اتصال به سایت الزامی است.");_http=new HttpClient{BaseAddress=new Uri(settings.SiteUrl.TrimEnd('/')+"/"),Timeout=TimeSpan.FromSeconds(20)};}
    private HttpRequestMessage Request(HttpMethod method,string path,object? body=null,bool authenticated=true){var req=new HttpRequestMessage(method,path);if(body is not null)req.Content=JsonContent.Create(body);if(authenticated){var c=_tokens.Load()??throw new DeviceUnauthorizedException();req.Headers.Add("X-Device-Uid",c.DeviceUid);req.Headers.Add("X-Device-Token",c.DeviceToken);}req.Headers.Add("X-App-Version",Version);return req;}
    private async Task<ApiResult<T>> SendAsync<T>(HttpRequestMessage request,CancellationToken ct){using var response=await _http.SendAsync(request,ct);var text=await response.Content.ReadAsStringAsync(ct);ApiResult<T>? result=null;try{result=JsonSerializer.Deserialize<ApiResult<T>>(text,Json);}catch{}if(response.StatusCode==HttpStatusCode.Unauthorized)throw new DeviceUnauthorizedException();if(result is null||!result.Success)throw new ApiException(result?.Error?.Message??$"HTTP {(int)response.StatusCode}",result?.Error?.Code);return result;}
    public async Task<PairResult> PairAsync(string code,string deviceName,CancellationToken ct){var fingerprint=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{Environment.MachineName}|{Environment.UserName}|{Environment.OSVersion.VersionString}")));var r=await SendAsync<PairResult>(Request(HttpMethod.Post,"api/notify/pair-device.php",new{pairing_code=code,device_name=deviceName,device_type="windows",app_version=Version,machine_fingerprint=fingerprint},false),ct);return r.Data!;}
    public async Task<ClientConfig> GetClientConfigAsync(CancellationToken ct)=>(await SendAsync<ClientConfig>(Request(HttpMethod.Get,"api/notify/client-config.php"),ct)).Data!;
    public async Task<(List<SobhanNotification> Items,int NextPoll)> GetPendingAsync(long since,int limit,CancellationToken ct){var r=await SendAsync<List<SobhanNotification>>(Request(HttpMethod.Get,$"api/notify/pending.php?since_id={since}&limit={limit}"),ct);return(r.Data??[],r.Meta?.NextPollSeconds??20);}
    public async Task AckAsync(long id,string status,CancellationToken ct){var c=_tokens.Load()!;await SendAsync<object>(Request(HttpMethod.Post,"api/notify/ack.php",new{notification_id=id,device_uid=c.DeviceUid,status}),ct);}
    public async Task<string?> ActionAsync(long id,string action,string? reply,CancellationToken ct){var c=_tokens.Load()!;var r=await SendAsync<JsonElement>(Request(HttpMethod.Post,"api/notify/action.php",new{notification_id=id,device_uid=c.DeviceUid,action,reply_text=reply}),ct);var data=r.Data;return data.ValueKind==JsonValueKind.Object&&data.TryGetProperty("action_url",out var url)?url.GetString():null;}
    public async Task UnregisterAsync(CancellationToken ct){var c=_tokens.Load()!;await SendAsync<object>(Request(HttpMethod.Post,"api/notify/unregister-device.php",new{device_uid=c.DeviceUid}),ct);}
    public async Task CheckVersionAsync(CancellationToken ct){try{var r=await SendAsync<JsonElement>(Request(HttpMethod.Get,"api/notify/app-version.php"),ct);var element=r.Data;if(element.ValueKind!=JsonValueKind.Object||!element.TryGetProperty("latest_version",out var latest)||!System.Version.TryParse(latest.GetString(),out var remote)||remote.CompareTo(Assembly.GetExecutingAssembly().GetName().Version??new System.Version(1,0))<=0)return;LoggingService.Info("update_available",latest.GetString());var message=element.TryGetProperty("message",out var msg)&&!string.IsNullOrWhiteSpace(msg.GetString())?msg.GetString():$"نسخه {remote} آماده است. دریافت شود؟";var url=element.TryGetProperty("download_url",out var download)?download.GetString():null;System.Windows.Application.Current.Dispatcher.Invoke(()=>{if(System.Windows.MessageBox.Show(message,"بروزرسانی Sobhan Notification Hub",MessageBoxButton.YesNo,MessageBoxImage.Information)==MessageBoxResult.Yes&&Uri.TryCreate(url,UriKind.Absolute,out var uri)&&uri.Scheme==Uri.UriSchemeHttps)System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(uri.ToString()){UseShellExecute=true});});}catch(Exception ex){LoggingService.Error("update_check",ex);}}
    public static string Version=>Assembly.GetExecutingAssembly().GetName().Version?.ToString(3)??"1.0.0";
}
public sealed class ApiException:Exception{public ApiException(string message,string? code=null):base(message){Code=code;}public string? Code{get;}}public sealed class DeviceUnauthorizedException:Exception{public DeviceUnauthorizedException():base("Device token is invalid"){}}
