<?php
require_once __DIR__.'/MessengerService.php';
final class MessengerAdminService
{
    public static function saveSettings(array $input,array $actor): void {MessengerSecurity::requirePermission('messenger.admin.settings','edit');$keys=['messenger.enabled','messenger.realtime_enabled','messenger.max_file_mb','messenger.allowed_mimes','messenger.voice_enabled','messenger.video_enabled','messenger.location_enabled','messenger.live_location_enabled','messenger.web_push_enabled','messenger.windows_agent_enabled','messenger.edit_window_minutes','messenger.delete_window_minutes','messenger.live_location_max_minutes','messenger.rate_messages_per_minute','messenger.retention_days','messenger.realtime_url','messenger.log_level','messenger.welcome_message','messenger.usage_rules'];foreach($keys as $key)Database::execute('INSERT INTO chat_settings(setting_key,setting_value,updated_by,updated_at) VALUES(?,?,?,NOW()) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by),updated_at=NOW()',[$key,MessengerSecurity::text($input[str_replace('.','_',$key)]??MessengerService::setting($key),2000),(int)$actor['id']]);MessengerService::audit((int)$actor['id'],'settings_updated');}
    public static function broadcast(array $input,array $actor): array {MessengerSecurity::requirePermission('messenger.broadcast.send','create');$ids=array_map('intval',array_column(Database::fetchAll('SELECT id FROM users WHERE status="active"'),'id'));$c=MessengerService::createConversation(['type'=>'broadcast','title'=>$input['title']??'اطلاعیه سازمانی','participant_ids'=>$ids,'is_official'=>1,'is_readonly'=>1],$actor);return MessengerService::send((int)$c['id'],['message_type'=>'official_notice','body'=>$input['body']??''],$actor);}
    public static function reviewReport(array $input,array $actor): void {MessengerSecurity::requirePermission('messenger.message.moderate','edit');$status=in_array($input['status']??'', ['reviewing','resolved','dismissed','rejected'],true)?$input['status']:'reviewing';Database::execute('UPDATE chat_reports SET status=?,reviewed_by=?,resolution_note=?,reviewed_at=NOW(),updated_at=NOW() WHERE id=?',[$status,(int)$actor['id'],MessengerSecurity::text($input['resolution_note']??'',2000),(int)($input['id']??0)]);MessengerService::audit((int)$actor['id'],'report_reviewed',null,null,['report_id'=>(int)($input['id']??0),'status'=>$status]);}
    public static function audit(int $limit=500): array {return Database::fetchAll('SELECT l.*,u.name actor_name,c.title conversation_title FROM chat_audit_logs l LEFT JOIN users u ON u.id=l.actor_id LEFT JOIN chat_conversations c ON c.id=l.conversation_id ORDER BY l.id DESC LIMIT '.max(1,min(1000,$limit)));}
    public static function conversations(string $type): array {return Database::fetchAll('SELECT c.*,u.name owner_name,(SELECT COUNT(*) FROM chat_participants p WHERE p.conversation_id=c.id AND p.deleted_at IS NULL) member_count,(SELECT COUNT(*) FROM chat_messages m WHERE m.conversation_id=c.id AND m.deleted_at IS NULL) message_count FROM chat_conversations c LEFT JOIN users u ON u.id=c.owner_id WHERE c.type=? AND c.deleted_at IS NULL ORDER BY c.id DESC',[$type]);}
    public static function reports(): array {return Database::fetchAll('SELECT r.*,u.name reporter_name,m.body message_body,c.title conversation_title FROM chat_reports r JOIN users u ON u.id=r.reported_by JOIN chat_messages m ON m.id=r.message_id JOIN chat_conversations c ON c.id=r.conversation_id ORDER BY r.id DESC LIMIT 300');}
    public static function analytics(): array {return ['by_type'=>Database::fetchAll('SELECT message_type,COUNT(*) total FROM chat_messages WHERE deleted_at IS NULL GROUP BY message_type ORDER BY total DESC'),'top_conversations'=>Database::fetchAll('SELECT c.id,c.title,c.type,COUNT(m.id) total FROM chat_conversations c LEFT JOIN chat_messages m ON m.conversation_id=c.id AND m.deleted_at IS NULL WHERE c.deleted_at IS NULL GROUP BY c.id,c.title,c.type ORDER BY total DESC LIMIT 10'),'notification_errors'=>(int)(Database::fetch('SELECT COUNT(*) n FROM chat_notifications WHERE status="error"')['n']??0),'official_unread'=>(int)(Database::fetch('SELECT COUNT(*) n FROM chat_message_status s JOIN chat_messages m ON m.id=s.message_id WHERE m.message_type IN("official_notice","notice") AND s.status<>"read"')['n']??0)];}
}
