<?php
require_once __DIR__ . '/MessengerSecurity.php';
require_once __DIR__ . '/../NotificationService.php';

final class MessengerService
{
    public static function conversations(int $userId, string $search='', int $limit=100): array
    {
        $limit=max(1,min(200,$limit)); $params=[$userId]; $where='';
        if ($search!=='') { $where=' AND (c.title LIKE ? OR EXISTS(SELECT 1 FROM chat_messages sm WHERE sm.conversation_id=c.id AND sm.body LIKE ? AND sm.deleted_at IS NULL))'; $q='%'.MessengerSecurity::text($search,100).'%';$params[]=$q;$params[]=$q; }
        return Database::fetchAll("SELECT c.id,c.uuid,c.title,c.description,c.type,c.is_official,c.is_readonly,c.last_message_at,p.participant_role,p.is_muted,p.is_archived,p.is_pinned,p.last_read_message_id,(SELECT COUNT(*) FROM chat_messages m LEFT JOIN chat_message_user_state us ON us.message_id=m.id AND us.user_id=p.user_id WHERE m.conversation_id=c.id AND m.id>COALESCE(p.last_read_message_id,0) AND m.deleted_at IS NULL AND us.hidden_at IS NULL) unread_count,(SELECT body FROM chat_messages lm WHERE lm.id=c.last_message_id AND lm.deleted_at IS NULL) last_message FROM chat_participants p JOIN chat_conversations c ON c.id=p.conversation_id WHERE p.user_id=? AND p.deleted_at IS NULL AND p.left_at IS NULL AND c.deleted_at IS NULL AND c.is_active=1{$where} ORDER BY p.is_pinned DESC,COALESCE(c.last_message_at,c.created_at) DESC LIMIT {$limit}",$params);
    }

    public static function createConversation(array $in, array $actor): array
    {
        $type=(string)($in['type']??'private'); if(!in_array($type,['private','group','channel','broadcast'],true)) throw new InvalidArgumentException('نوع گفتگو معتبر نیست.');
        $perm=match($type){'private'=>'messenger.private.send','group'=>'messenger.group.create','channel'=>'messenger.channel.create','broadcast'=>'messenger.broadcast.send'}; MessengerSecurity::requirePermission($perm,'create');
        $ids=array_values(array_unique(array_filter(array_map('intval',(array)($in['participant_ids']??[]))))); $actorId=(int)$actor['id'];$scope=(string)($in['scope_type']??'custom');$scopeValue=MessengerSecurity::text($in['scope_value']??'',190);
        if($scope!=='custom'){$sql=match($scope){'company'=>'SELECT id FROM users WHERE status="active"','department'=>'SELECT id FROM users WHERE status="active" AND department=?','role'=>'SELECT id FROM users WHERE status="active" AND role_key=?','sales_line'=>'SELECT id FROM users WHERE status="active" AND sales_line=?','supervisor_team'=>'SELECT id FROM users WHERE status="active" AND supervisor_id=?','manager_team'=>'SELECT id FROM users WHERE status="active" AND organization_manager_id=?',default=>null};if($sql){$param=$scope==='company'?[]:(in_array($scope,['supervisor_team','manager_team'],true)?[$actorId]:[$scopeValue]);$ids=array_merge($ids,array_map('intval',array_column(Database::fetchAll($sql,$param),'id')));$ids=array_values(array_unique($ids));}}
        if(!in_array($actorId,$ids,true))$ids[]=$actorId;
        if($type==='private'&&count($ids)!==2)throw new InvalidArgumentException('گفتگوی خصوصی باید دقیقاً دو عضو داشته باشد.');
        if($type==='private'){ $existing=Database::fetch('SELECT c.* FROM chat_conversations c JOIN chat_participants a ON a.conversation_id=c.id AND a.user_id=? AND a.deleted_at IS NULL JOIN chat_participants b ON b.conversation_id=c.id AND b.user_id=? AND b.deleted_at IS NULL WHERE c.type="private" AND c.deleted_at IS NULL AND (SELECT COUNT(*) FROM chat_participants x WHERE x.conversation_id=c.id AND x.deleted_at IS NULL)=2 LIMIT 1',[$ids[0],$ids[1]]);if($existing)return $existing; }
        $pdo=Database::connection();$pdo->beginTransaction();try{
            $uuid=MessengerSecurity::uuid();Database::execute('INSERT INTO chat_conversations(uuid,conversation_uuid,title,description,type,scope_type,scope_value,organization_scope,created_by,owner_id,is_official,is_readonly,is_read_only,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[$uuid,$uuid,MessengerSecurity::text($in['title']??'',190)?:null,MessengerSecurity::text($in['description']??'',2000)?:null,$type,in_array($scope,['custom','department','role','sales_line','supervisor_team','manager_team','company'],true)?$scope:'custom',$scopeValue?:null,$scope,$actorId,$actorId,!empty($in['is_official'])?1:0,!empty($in['is_readonly'])?1:0,!empty($in['is_readonly'])?1:0,json_encode(['created_from'=>'web'],JSON_UNESCAPED_UNICODE)]);
            $id=(int)Database::lastInsertId();$stmt=$pdo->prepare('INSERT INTO chat_participants(conversation_id,user_id,participant_role,can_send,joined_at) SELECT ?,id,?,?,NOW() FROM users WHERE id=? AND status="active"');foreach($ids as $uid)$stmt->execute([$id,$uid,$uid===$actorId?'owner':($type==='channel'?'subscriber':'member'),$type==='channel'&&$uid!==$actorId?0:1,$uid]);
            self::audit($actorId,'conversation_created',$id,null,['type'=>$type,'members'=>count($ids)]);$pdo->commit();return Database::fetch('SELECT * FROM chat_conversations WHERE id=?',[$id])?:[];
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public static function messages(int $conversationId,int $userId,int $before=0,int $limit=50): array
    {
        MessengerSecurity::participant($conversationId,$userId);$limit=max(1,min(100,$limit));$params=[$userId,$conversationId];$beforeSql='';if($before>0){$beforeSql=' AND m.id<?';$params[]=$before;}
        $rows=Database::fetchAll("SELECT m.*,u.name sender_name,u.role_key sender_role,(SELECT GROUP_CONCAT(CONCAT(r.reaction,':',r.user_id) SEPARATOR ',') FROM chat_reactions r WHERE r.message_id=m.id) reactions,(SELECT COUNT(*) FROM chat_message_status s WHERE s.message_id=m.id AND s.status='read') read_count FROM chat_messages m LEFT JOIN users u ON u.id=m.sender_id LEFT JOIN chat_message_user_state us ON us.message_id=m.id AND us.user_id=? WHERE m.conversation_id=? AND m.deleted_at IS NULL AND us.hidden_at IS NULL{$beforeSql} ORDER BY m.id DESC LIMIT {$limit}",$params);return array_reverse($rows);
    }

    public static function send(int $conversationId,array $in,array $actor): array
    {
        $uid=(int)$actor['id'];MessengerSecurity::assertSend($conversationId,$uid);$rate=(int)self::setting('messenger.rate_messages_per_minute','60');MessengerSecurity::rate('message:'.$uid,max(5,$rate));
        $type=(string)($in['message_type']??'text');if(!in_array($type,['text','file','image','video','voice','location','live_location','system','report_card','official_notice','notice'],true))$type='text';if(in_array($type,['official_notice','notice'],true))MessengerSecurity::requirePermission('messenger.official_notice.send','create');
        $body=MessengerSecurity::text($in['body']??'',10000);$fileId=(int)($in['file_id']??0);if($body===''&&!$fileId&&!in_array($type,['location','report_card'],true))throw new InvalidArgumentException('متن یا فایل پیام را وارد کنید.');
        $parent=(int)($in['parent_message_id']??0);if($parent&&!Database::fetch('SELECT id FROM chat_messages WHERE id=? AND conversation_id=? AND deleted_at IS NULL',[$parent,$conversationId]))throw new InvalidArgumentException('پیام مرجع معتبر نیست.');
        $pdo=Database::connection();$pdo->beginTransaction();try{$uuid=MessengerSecurity::uuid();Database::execute('INSERT INTO chat_messages(uuid,message_uuid,conversation_id,sender_id,parent_message_id,reply_to_message_id,forwarded_from_message_id,message_type,body,body_plain,file_id,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[$uuid,$uuid,$conversationId,$uid,$parent?:null,$parent?:null,(int)($in['forwarded_from_message_id']??0)?:null,$type,$body?:null,$body?:null,$fileId?:null,json_encode($in['payload']??[],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$id=(int)Database::lastInsertId();if($fileId)Database::execute('UPDATE chat_files SET message_id=? WHERE id=? AND conversation_id=? AND uploaded_by=? AND message_id IS NULL',[$id,$fileId,$conversationId,$uid]);Database::execute('UPDATE chat_conversations SET last_message_id=?,last_message_at=NOW(),updated_at=NOW() WHERE id=?',[$id,$conversationId]);Database::execute('INSERT IGNORE INTO chat_message_status(message_id,user_id,status,updated_at) SELECT ?,user_id,IF(user_id=? ,"read","sent"),NOW() FROM chat_participants WHERE conversation_id=? AND deleted_at IS NULL AND left_at IS NULL',[$id,$uid,$conversationId]);self::mentions($id,$conversationId,$body,$uid);self::queueNotifications($id,$conversationId,$uid,$body,$type);self::audit($uid,'message_sent',$conversationId,$id,['type'=>$type]);$pdo->commit();return Database::fetch('SELECT m.*,u.name sender_name FROM chat_messages m LEFT JOIN users u ON u.id=m.sender_id WHERE m.id=?',[$id])?:[];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public static function editMessage(int $id,string $body,array $actor): void
    { $m=self::message($id);MessengerSecurity::participant((int)$m['conversation_id'],(int)$actor['id']);$window=(int)self::setting('messenger.edit_window_minutes','30');if((int)$m['sender_id']!==(int)$actor['id']||strtotime($m['created_at'])<time()-$window*60)throw new DomainException('مهلت ویرایش پیام پایان یافته است.',403);$body=MessengerSecurity::text($body,10000);if($body==='')throw new InvalidArgumentException('متن پیام خالی است.');Database::execute('UPDATE chat_messages SET body=?,body_plain=?,is_edited=1,edited_at=NOW(),updated_at=NOW() WHERE id=?',[$body,$body,$id]);self::audit((int)$actor['id'],'message_edited',(int)$m['conversation_id'],$id); }

    public static function deleteMessage(int $id,string $scope,array $actor): void
    { $m=self::message($id);$uid=(int)$actor['id'];MessengerSecurity::participant((int)$m['conversation_id'],$uid);if($scope==='me'){Database::execute('INSERT INTO chat_message_user_state(message_id,user_id,hidden_at) VALUES(?,?,NOW()) ON DUPLICATE KEY UPDATE hidden_at=NOW()',[$id,$uid]);self::audit($uid,'message_deleted_for_me',(int)$m['conversation_id'],$id);return;}$window=(int)self::setting('messenger.delete_window_minutes','30');$own=(int)$m['sender_id']===$uid&&strtotime($m['created_at'])>=time()-$window*60;if(!$own&&!MessengerSecurity::can('messenger.message.delete_any','delete'))throw new DomainException('حذف پیام برای همه مجاز نیست.',403);Database::execute('UPDATE chat_messages SET body=NULL,body_plain=NULL,payload_json=NULL,is_deleted=1,deleted_by=?,delete_scope="everyone",deleted_at=NOW(),updated_at=NOW() WHERE id=?',[$uid,$id]);self::audit($uid,'message_deleted_for_everyone',(int)$m['conversation_id'],$id); }

    public static function react(int $messageId,string $reaction,int $userId,bool $remove=false): void
    { $m=self::message($messageId);MessengerSecurity::participant((int)$m['conversation_id'],$userId);$reaction=MessengerSecurity::text($reaction,16);if($remove)Database::execute('DELETE FROM chat_reactions WHERE message_id=? AND user_id=? AND reaction=?',[$messageId,$userId,$reaction]);else Database::execute('INSERT IGNORE INTO chat_reactions(message_id,user_id,reaction,created_at) VALUES(?,?,?,NOW())',[$messageId,$userId,$reaction]); }

    public static function read(int $conversationId,int $messageId,int $userId): void
    { MessengerSecurity::participant($conversationId,$userId);Database::execute('UPDATE chat_participants SET last_read_message_id=GREATEST(COALESCE(last_read_message_id,0),?),last_read_at=NOW() WHERE conversation_id=? AND user_id=?',[$messageId,$conversationId,$userId]);Database::execute('UPDATE chat_message_status s JOIN chat_messages m ON m.id=s.message_id SET s.status="read",s.delivered_at=COALESCE(s.delivered_at,NOW()),s.read_at=NOW() WHERE s.user_id=? AND m.conversation_id=? AND m.id<=?',[$userId,$conversationId,$messageId]); }

    public static function pin(int $messageId,bool $pinned,array $actor): void
    { $m=self::message($messageId);$p=MessengerSecurity::participant((int)$m['conversation_id'],(int)$actor['id']);if(!in_array($p['participant_role'],['owner','admin','moderator'],true)&&!MessengerSecurity::can('messenger.message.pin','edit'))throw new DomainException('سنجاق پیام مجاز نیست.',403);Database::execute('UPDATE chat_messages SET is_pinned=?,pinned_by=?,pinned_at=?,updated_at=NOW() WHERE id=?',[$pinned?1:0,$pinned?(int)$actor['id']:null,$pinned?date('Y-m-d H:i:s'):null,$messageId]);self::audit((int)$actor['id'],$pinned?'message_pinned':'message_unpinned',(int)$m['conversation_id'],$messageId); }

    public static function participantAction(int $conversationId,int $userId,array $in,array $actor): void
    { $me=MessengerSecurity::participant($conversationId,(int)$actor['id']);$action=(string)($in['action']??'');if(in_array($action,['mute','archive','pin'],true)&&$userId===(int)$actor['id']){$col=['mute'=>'is_muted','archive'=>'is_archived','pin'=>'is_pinned'][$action];Database::execute("UPDATE chat_participants SET {$col}=? WHERE conversation_id=? AND user_id=?",[!empty($in['enabled'])?1:0,$conversationId,$userId]);return;}if(!in_array($me['participant_role'],['owner','admin','moderator'],true)&&!MessengerSecurity::can('messenger.group.manage','edit'))throw new DomainException('مدیریت اعضا مجاز نیست.',403);if($action==='add')Database::execute('INSERT INTO chat_participants(conversation_id,user_id,participant_role,can_send,joined_at) VALUES(?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE deleted_at=NULL,left_at=NULL,participant_role=VALUES(participant_role),can_send=VALUES(can_send)',[$conversationId,$userId,in_array($in['role']??'', ['admin','moderator','member','subscriber'],true)?$in['role']:'member',!empty($in['can_send'])?1:0]);elseif($action==='remove')Database::execute('UPDATE chat_participants SET left_at=NOW(),deleted_at=NOW() WHERE conversation_id=? AND user_id=?',[$conversationId,$userId]);else Database::execute('UPDATE chat_participants SET participant_role=?,can_send=? WHERE conversation_id=? AND user_id=?',[in_array($in['role']??'', ['admin','moderator','member','subscriber'],true)?$in['role']:'member',!empty($in['can_send'])?1:0,$conversationId,$userId]);self::audit((int)$actor['id'],'participant_'.$action,$conversationId,null,['user_id'=>$userId]); }

    public static function report(int $messageId,array $in,int $userId): void
    { $m=self::message($messageId);MessengerSecurity::participant((int)$m['conversation_id'],$userId);Database::execute('INSERT INTO chat_reports(message_id,conversation_id,reported_by,reason,description,status,created_at) VALUES(?,?,?,?,?,"open",NOW())',[$messageId,(int)$m['conversation_id'],$userId,MessengerSecurity::text($in['reason']??'',190),MessengerSecurity::text($in['description']??'',2000)]);self::audit($userId,'message_reported',(int)$m['conversation_id'],$messageId); }

    public static function adminStats(): array
    { MessengerSecurity::requirePermission('messenger.admin.dashboard');return ['conversations'=>(int)(Database::fetch('SELECT COUNT(*) n FROM chat_conversations WHERE deleted_at IS NULL')['n']??0),'messages_today'=>(int)(Database::fetch('SELECT COUNT(*) n FROM chat_messages WHERE created_at>=CURDATE() AND deleted_at IS NULL')['n']??0),'active_users'=>(int)(Database::fetch('SELECT COUNT(*) n FROM chat_presence WHERE last_seen_at>=DATE_SUB(NOW(),INTERVAL 15 MINUTE)')['n']??0),'open_reports'=>(int)(Database::fetch('SELECT COUNT(*) n FROM chat_reports WHERE status IN("open","reviewing")')['n']??0),'files_bytes'=>(int)(Database::fetch('SELECT COALESCE(SUM(file_size),0) n FROM chat_files WHERE deleted_at IS NULL')['n']??0)]; }
    public static function setting(string $key,string $default=''): string {return (string)(Database::fetch('SELECT setting_value FROM chat_settings WHERE setting_key=?',[$key])['setting_value']??$default);}
    public static function audit(?int $actor,string $action,?int $conversation=null,?int $message=null,array $details=[]): void {Database::execute('INSERT INTO chat_audit_logs(actor_id,conversation_id,message_id,action,details_json,ip_address,user_agent,created_at) VALUES(?,?,?,?,?,?,?,NOW())',[$actor,$conversation,$message,$action,json_encode($details,JSON_UNESCAPED_UNICODE),substr((string)($_SERVER['REMOTE_ADDR']??''),0,45),substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255)]);}
    private static function message(int $id): array {$m=Database::fetch('SELECT * FROM chat_messages WHERE id=?',[$id]);if(!$m)throw new DomainException('پیام پیدا نشد.',404);return $m;}
    private static function mentions(int $id,int $conversation,string $body,int $sender): void {if(!preg_match_all('/@\[([0-9]+)\]/u',$body,$matches))return;$stmt=Database::connection()->prepare('INSERT IGNORE INTO chat_mentions(message_id,user_id,created_at) SELECT ?,user_id,NOW() FROM chat_participants WHERE conversation_id=? AND user_id=? AND user_id<>? AND deleted_at IS NULL');foreach(array_unique($matches[1]) as $uid)$stmt->execute([$id,$conversation,(int)$uid,$sender]);}
    private static function queueNotifications(int $id,int $conversation,int $sender,string $body,string $type): void {$stmt=Database::connection()->prepare('INSERT INTO chat_notifications(user_id,conversation_id,message_id,event_type,priority,payload_json,status,available_at,created_at) SELECT user_id,?,?,?, ?,?,"pending",NOW(),NOW() FROM chat_participants WHERE conversation_id=? AND user_id<>? AND deleted_at IS NULL AND left_at IS NULL AND is_muted=0');$priority=$type==='official_notice'?'high':'normal';$stmt->execute([$conversation,$id,$type==='official_notice'?'messenger_official_notice':'messenger_message',$priority,json_encode(['body'=>mb_substr($body,0,240),'url'=>'/employee/messenger.php?conversation='.$conversation],JSON_UNESCAPED_UNICODE),$conversation,$sender]);}
}
