<?php
require_once __DIR__ . '/MessengerService.php';
final class MessengerLocationService
{
    public static function start(int $conversationId,array $in,array $actor): array
    { $live=!empty($in['live']);MessengerSecurity::requirePermission($live?'messenger.live_location.send':'messenger.location.send','create');MessengerSecurity::assertSend($conversationId,(int)$actor['id']);$lat=(float)($in['latitude']??999);$lng=(float)($in['longitude']??999);if($lat<-90||$lat>90||$lng<-180||$lng>180)throw new InvalidArgumentException('مختصات معتبر نیست.');$minutes=$live?max(1,min((int)MessengerService::setting('messenger.live_location_max_minutes','480'),(int)($in['minutes']??60))):0;$message=MessengerService::send($conversationId,['message_type'=>$live?'live_location':'location','body'=>$live?'موقعیت زنده':'موقعیت مکانی','payload'=>['latitude'=>$lat,'longitude'=>$lng,'live'=>$live]],$actor);$params=[$conversationId,(int)$message['id'],(int)$actor['id'],$lat,$lng,isset($in['accuracy'])?(float)$in['accuracy']:null,$live?'live':'fixed'];if($live)$params[]=$minutes;Database::execute('INSERT INTO chat_live_locations(conversation_id,message_id,user_id,latitude,longitude,accuracy_m,location_type,started_at,expires_at) VALUES(?,?,?,?,?,?,?,NOW(),'.($live?'DATE_ADD(NOW(),INTERVAL ? MINUTE)':'NULL').')',$params);return ['id'=>(int)Database::lastInsertId(),'message'=>$message,'expires_in_minutes'=>$minutes]; }
    public static function update(int $id,array $in,array $actor): void { $row=Database::fetch('SELECT * FROM chat_live_locations WHERE id=? AND user_id=? AND location_type="live" AND stopped_at IS NULL AND expires_at>NOW()',[$id,(int)$actor['id']]);if(!$row)throw new DomainException('اشتراک موقعیت فعال نیست.',404);$lat=(float)($in['latitude']??999);$lng=(float)($in['longitude']??999);if($lat<-90||$lat>90||$lng<-180||$lng>180)throw new InvalidArgumentException('مختصات معتبر نیست.');Database::execute('UPDATE chat_live_locations SET latitude=?,longitude=?,accuracy_m=?,updated_at=NOW() WHERE id=?',[$lat,$lng,isset($in['accuracy'])?(float)$in['accuracy']:null,$id]);}
    public static function stop(int $id,array $actor): void {Database::execute('UPDATE chat_live_locations SET stopped_at=NOW(),updated_at=NOW() WHERE id=? AND user_id=? AND stopped_at IS NULL',[$id,(int)$actor['id']]);}
}
