<?php
require_once __DIR__.'/../../core/Auth.php';require_once __DIR__.'/../../core/Response.php';require_once __DIR__.'/../../core/Upload.php';require_once __DIR__.'/../../core/EmailHubModule.php';require_once __DIR__.'/../../services/EmailSyncService.php';
$adminExtraStylesheets=array_values(array_unique(array_merge($adminExtraStylesheets??[],['/assets/css/email-hub.css'])));$adminExtraScripts=array_values(array_unique(array_merge($adminExtraScripts??[],['/assets/js/email-hub.js'])));
function email_require(string $permission='view'): void{Auth::requireLogin();$allowed=$permission==='manage'?EmailHubModule::canManage():($permission==='providers'?EmailHubModule::canProviders():($permission==='view'?(Auth::isAdmin()||Auth::can('email_hub','view')||count(EmailHubModule::accessibleAccounts('read'))>0):(Auth::isAdmin()||Auth::can('email_hub',$permission))));if(!$allowed){http_response_code(403);$pageTitle='دسترسی غیرمجاز';require __DIR__.'/../../views/partials/admin-header.php';echo '<section class="card"><h2>دسترسی کافی ندارید</h2><p class="muted">برای دسترسی به هاب ایمیل با مدیر سامانه تماس بگیرید.</p></section>';require __DIR__.'/../../views/partials/admin-footer.php';exit;}}
function email_tabs(string $active): void{$tabs=['inbox'=>['صندوق ایمیل','/admin/email-inbox.php'],'compose'=>['ارسال ایمیل','/admin/email-compose.php'],'accounts'=>['حساب‌ها','/admin/email-accounts.php'],'providers'=>['سرویس‌دهندگان','/admin/email-providers.php'],'templates'=>['قالب‌ها','/admin/email-templates.php'],'rules'=>['قوانین','/admin/email-rules.php'],'reports'=>['گزارش‌ها','/admin/email-reports.php']];echo '<nav class="email-tabs">';foreach($tabs as $key=>$tab){if(in_array($key,['accounts','providers'],true)&&!EmailHubModule::canManage())continue;if($key==='providers'&&!EmailHubModule::canProviders())continue;if($key==='rules'&&!Auth::isAdmin()&&!Auth::can('email_hub.rules','edit'))continue;if($key==='reports'&&!Auth::isAdmin()&&!Auth::can('email_hub.reports','view'))continue;echo '<a class="'.($active===$key?'is-active':'').'" href="'.e($tab[1]).'">'.e($tab[0]).'</a>';}echo '</nav>';}
function email_parse_addresses(?string $input): array{$result=[];foreach(preg_split('/[,;\n]+/',(string)$input) as $part){$part=trim($part);if($part==='')continue;$name='';$email=$part;if(preg_match('/^(.*?)<([^>]+)>$/',$part,$m)){$name=trim($m[1]," \t\"");$email=trim($m[2]);}if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('نشانی ایمیل معتبر نیست: '.$email);$result[]=['name'=>$name,'email'=>strtolower($email)];}return $result;}
function email_addresses_text(?string $json): string{$items=json_decode($json?:'[]',true)?:[];return implode(', ',array_map(static fn($a)=>(($a['name']??'')!==''?$a['name'].' <'.$a['email'].'>':($a['email']??'')),$items));}
function email_message(int $id,string $action='read'): array{$message=Database::fetch('SELECT m.*,f.folder_name,f.folder_type,a.account_title,a.email_address,a.account_scope,a.owner_user_id,a.department_id,a.role_id,a.send_enabled,a.active FROM email_messages m JOIN email_folders f ON f.id=m.folder_id JOIN email_accounts a ON a.id=m.account_id WHERE m.id=?',[$id]);if(!$message||!EmailHubModule::access($message,$action))throw new RuntimeException('email_message_access_denied');return $message;}
function email_safe_error(Throwable $e,string $public='عملیات ایمیل انجام نشد. لطفاً تنظیمات و اتصال را بررسی کنید.'): string{error_log('Email Hub: '.$e->getMessage());return $public;}
function email_store_outbox_attachment(int $accountId,int $outboxId,array $file): void{if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return;$allowed=['pdf','doc','docx','xls','xlsx','jpg','jpeg','png','webp','txt','zip'];$upload=Upload::save($file,'uploads/email/outbox',$allowed,15*1024*1024);if(!$upload['ok'])throw new InvalidArgumentException($upload['error']);$mime=(string)$upload['mime_type'];$blocked=['text/x-php','application/x-httpd-php','application/x-executable','application/x-sh'];if(in_array($mime,$blocked,true))throw new InvalidArgumentException('نوع فایل پیوست مجاز نیست.');Database::execute('INSERT INTO email_attachments(message_id,account_id,outbox_id,file_name,mime_type,file_size,storage_path,is_inline,created_at) VALUES(NULL,?,?,?,?,?,?,0,NOW())',[$accountId,$outboxId,$upload['original_name'],$mime,$upload['file_size'],$upload['file_path']]);}
function email_status_label(string $status): string{return ['new'=>'جدید','read'=>'خوانده‌شده','pending_reply'=>'نیازمند پاسخ','replied'=>'پاسخ‌داده‌شده','forwarded'=>'فورواردشده','archived'=>'آرشیوشده','spam'=>'هرزنامه','deleted'=>'حذف‌شده'][$status]??'نامشخص';}
