<?php
require_once __DIR__.'/../../core/Auth.php';require_once __DIR__.'/../../core/Response.php';require_once __DIR__.'/../../lib/messenger/MessengerAdminService.php';Auth::requireLogin();if(!MessengerSecurity::can($requiredPermission??'messenger.admin.dashboard')){http_response_code(403);exit('دسترسی غیرمجاز');}$user=Auth::user();$view=$messengerAdminView??'dashboard';
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){if(!Auth::verifyCsrf($_POST['_csrf']??null))throw new RuntimeException('نشست امنیتی منقضی شده است.');
  if($view==='settings'){MessengerAdminService::saveSettings($_POST,$user);flash('تنظیمات پیام‌رسان ذخیره شد.');redirect($_SERVER['REQUEST_URI']);}
  if($view==='broadcast'){MessengerAdminService::broadcast($_POST,$user);flash('پیام سراسری برای کاربران فعال ثبت شد.');redirect($_SERVER['REQUEST_URI']);}
  if($view==='reports'){MessengerAdminService::reviewReport($_POST,$user);flash('وضعیت گزارش به‌روزرسانی شد.');redirect($_SERVER['REQUEST_URI']);}
 }
}catch(Throwable $e){error_log('messenger-admin: '.$e->getMessage());flash($e instanceof DomainException||$e instanceof InvalidArgumentException?$e->getMessage():'عملیات انجام نشد.','danger');redirect($_SERVER['REQUEST_URI']);}
$pageTitle=$messengerAdminTitle??'مدیریت پیام‌رسان';$adminExtraStylesheets=['/assets/css/sobhan-messenger-admin.css'];require __DIR__.'/../../views/partials/admin-header.php';$stats=$view==='dashboard'?MessengerService::adminStats():[];
?>
<div class="sma-page"><header class="sma-hero"><div><small>مرکز کنترل ارتباطات سازمانی</small><h1><?=e($pageTitle)?></h1><p>مدیریت امن گفتگوها، اعلان‌ها، تخلف‌ها و سیاست‌های نگهداری</p></div><a class="btn" href="/employee/messenger.php">باز کردن پیام‌رسان</a></header>
<nav class="sma-tabs"><a href="/admin/messenger-dashboard.php">داشبورد</a><a href="/admin/messenger-groups.php">گروه‌ها</a><a href="/admin/messenger-channels.php">کانال‌ها</a><a href="/admin/messenger-broadcast.php">ارسال سراسری</a><a href="/admin/messenger-reports.php">گزارش تخلف</a><a href="/admin/messenger-audit.php">ممیزی</a><a href="/admin/messenger-settings.php">تنظیمات</a></nav>
<?php if($view==='dashboard'):?><section class="sma-stats"><article><b><?=format_number($stats['conversations'])?></b><span>گفتگو</span></article><article><b><?=format_number($stats['messages_today'])?></b><span>پیام امروز</span></article><article><b><?=format_number($stats['active_users'])?></b><span>کاربر فعال</span></article><article><b><?=format_number($stats['open_reports'])?></b><span>گزارش باز</span></article><article><b><?=format_number($stats['files_bytes']/1048576)?> MB</b><span>فضای فایل</span></article></section><section class="card"><h2>فعالیت اخیر</h2><?php $rows=Database::fetchAll('SELECT l.*,u.name actor_name FROM chat_audit_logs l LEFT JOIN users u ON u.id=l.actor_id ORDER BY l.id DESC LIMIT 20');?><div class="table-wrap"><table><thead><tr><th>کاربر</th><th>رویداد</th><th>زمان</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['actor_name']??'سیستم')?></td><td><?=e($r['action'])?></td><td><?=e(format_jalali_datetime($r['created_at']))?></td></tr><?php endforeach?></tbody></table></div></section>
<?php elseif(in_array($view,['groups','channels'],true)): $type=$view==='groups'?'group':'channel';$rows=Database::fetchAll('SELECT c.*,u.name owner_name,(SELECT COUNT(*) FROM chat_participants p WHERE p.conversation_id=c.id AND p.deleted_at IS NULL) member_count,(SELECT COUNT(*) FROM chat_messages m WHERE m.conversation_id=c.id AND m.deleted_at IS NULL) message_count FROM chat_conversations c LEFT JOIN users u ON u.id=c.owner_id WHERE c.type=? AND c.deleted_at IS NULL ORDER BY c.id DESC',[$type]);?><section class="card"><div class="table-wrap"><table><thead><tr><th>عنوان</th><th>مالک</th><th>اعضا</th><th>پیام‌ها</th><th>وضعیت</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['title']?:'بدون عنوان')?></td><td><?=e($r['owner_name']??'—')?></td><td><?=format_number($r['member_count'])?></td><td><?=format_number($r['message_count'])?></td><td><span class="badge"><?=(int)$r['is_active']?'فعال':'غیرفعال'?></span></td><td><a href="/employee/messenger.php?conversation=<?=(int)$r['id']?>">مشاهده</a></td></tr><?php endforeach?></tbody></table></div></section>
<?php elseif($view==='broadcast'):?><section class="card sma-form"><h2>ارسال اطلاعیه سراسری</h2><form method="post"><input type="hidden" name="_csrf" value="<?=e(Auth::csrfToken())?>"><label>عنوان<input name="title" maxlength="190" required></label><label>متن اطلاعیه<textarea name="body" rows="8" maxlength="10000" required></textarea></label><button class="btn">ثبت و ارسال برای همه کاربران فعال</button></form></section>
<?php elseif($view==='reports'): $rows=Database::fetchAll('SELECT r.*,u.name reporter_name,m.body message_body,c.title conversation_title FROM chat_reports r JOIN users u ON u.id=r.reported_by JOIN chat_messages m ON m.id=r.message_id JOIN chat_conversations c ON c.id=r.conversation_id ORDER BY r.id DESC LIMIT 300');?><section class="sma-grid"><?php foreach($rows as $r):?><article class="card"><header><b><?=e($r['reason'])?></b><span class="badge"><?=e($r['status'])?></span></header><p><?=e($r['message_body'])?></p><small><?=e($r['reporter_name'])?> · <?=e($r['conversation_title']?:'گفتگو')?></small><form method="post"><input type="hidden" name="_csrf" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><textarea name="resolution_note" placeholder="یادداشت بررسی"><?=e($r['resolution_note'])?></textarea><select name="status"><option value="reviewing">در حال بررسی</option><option value="resolved">رسیدگی شد</option><option value="dismissed">رد گزارش</option></select><button class="btn btn-small">ذخیره</button></form></article><?php endforeach?></section>
<?php elseif($view==='audit'): $rows=Database::fetchAll('SELECT l.*,u.name actor_name,c.title conversation_title FROM chat_audit_logs l LEFT JOIN users u ON u.id=l.actor_id LEFT JOIN chat_conversations c ON c.id=l.conversation_id ORDER BY l.id DESC LIMIT 500');?><section class="card"><div class="table-wrap"><table><thead><tr><th>زمان</th><th>کاربر</th><th>عملیات</th><th>گفتگو</th><th>IP</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e(format_jalali_datetime($r['created_at']))?></td><td><?=e($r['actor_name']??'سیستم')?></td><td><?=e($r['action'])?></td><td><?=e($r['conversation_title']??'—')?></td><td dir="ltr"><?=e($r['ip_address'])?></td></tr><?php endforeach?></tbody></table></div></section>
<?php elseif($view==='settings'): $keys=['messenger.enabled'=>'فعال بودن پیام‌رسان','messenger.max_file_mb'=>'حداکثر فایل (MB)','messenger.allowed_mimes'=>'MIMEهای مجاز','messenger.edit_window_minutes'=>'مهلت ویرایش (دقیقه)','messenger.delete_window_minutes'=>'مهلت حذف برای همه (دقیقه)','messenger.live_location_max_minutes'=>'حداکثر موقعیت زنده (دقیقه)','messenger.rate_messages_per_minute'=>'پیام در دقیقه','messenger.retention_days'=>'نگهداری (روز؛ صفر یعنی دائمی)','messenger.realtime_url'=>'نشانی سرور بلادرنگ'];?><section class="card sma-form"><form method="post"><input type="hidden" name="_csrf" value="<?=e(Auth::csrfToken())?>"><?php foreach($keys as $key=>$label):?><label><?=e($label)?><input name="<?=e(str_replace('.','_',$key))?>" value="<?=e(MessengerService::setting($key))?>"></label><?php endforeach?><button class="btn">ذخیره تنظیمات</button></form></section><?php endif?></div>
<?php require __DIR__.'/../../views/partials/admin-footer.php';?>
