<?php require_once __DIR__.'/../../services/PersonalPlannerService.php';$plannerSettings=PersonalPlannerService::bootstrap((int)Auth::user()['id'],Auth::user());if((int)($plannerSettings['widget_enabled']??1)||!empty($personalPlannerFullPage)):?>
<section class="personal-planner<?=!empty($plannerSettings['compact_mode'])?' is-compact':''?>" data-personal-planner data-endpoint="/admin/ajax/personal-planner.php" data-csrf="<?=e(Auth::csrfToken())?>" data-default-view="<?=e($plannerSettings['default_view']??'daily')?>">
 <header class="personal-planner-head"><div><small>دفترچه شخصی و خصوصی شما</small><h2>برنامه کاری من</h2><p class="muted" data-planner-date-label>در حال بارگذاری…</p></div><div class="planner-head-actions"><a href="/admin/personal-planner-report.php">گزارش</a><a href="/admin/personal-planner-settings.php">تنظیمات</a></div></header>
 <nav class="planner-tabs" aria-label="نمای برنامه"><button type="button" data-view="daily">روزانه</button><button type="button" data-view="weekly">هفتگی</button><button type="button" data-view="monthly">ماهانه</button></nav>
 <div class="planner-navigation"><button type="button" data-period="previous">‹ قبلی</button><button type="button" data-period="today">امروز</button><button type="button" data-period="next">بعدی ›</button></div>
 <section data-daily-view>
  <form class="planner-quick-add" data-planner-add-task><input name="title" maxlength="255" autocomplete="off" placeholder="یک کار جدید بنویسید و Enter بزنید…" required><button class="btn btn-primary">افزودن</button><details><summary>موعد، یادآوری و تکرار</summary><div class="planner-options"><label>موعد<input type="datetime-local" name="due_at"></label><label>یادآوری<input type="datetime-local" name="reminder_at"></label><label>اولویت<select name="priority"><option value="normal">عادی</option><option value="high">زیاد</option><option value="urgent">فوری</option></select></label><label>تکرار<select name="recurrence_type"><option value="">بدون تکرار</option><option value="daily">روزانه</option><option value="weekly">هفتگی</option><option value="monthly">ماهانه</option><option value="yearly">سالانه</option><option value="weekdays">روزهای خاص هفته</option><option value="interval">هر X روز</option></select></label><label>فاصله تکرار<input type="number" name="recurrence_interval" min="1" max="365" value="1"></label><label>روزهای هفته<input name="recurrence_days" placeholder="شنبه 6، یکشنبه 0، …"></label><label>روز ماه<input type="number" name="recurrence_month_day" min="1" max="31"></label><label>پایان تکرار<input type="date" name="recurrence_end_date"></label></div></details></form>
  <div class="personal-planner-grid"><main class="personal-planner-main"><div class="planner-section-heading"><h3>کارهای روز</h3><button class="btn btn-small" type="button" data-move-all>انتقال انجام‌نشده‌ها به فردا</button></div><div class="planner-task-list" data-planner-tasks></div><section class="planner-overdue"><h3>کارهای عقب‌افتاده</h3><div data-planner-overdue></div></section></main><aside class="personal-planner-side"><section><h3>اولویت‌های امروز</h3><div class="planner-priority-list" data-planner-priorities></div></section><section><div class="planner-section-heading"><h3>یادداشت امروز</h3><span class="muted" data-note-state></span></div><textarea data-planner-note maxlength="10000" rows="6" placeholder="نکته‌ها و پیگیری‌های امروز…"></textarea><button class="btn btn-small" type="button" data-save-note>ذخیره یادداشت</button></section><section><h3>پیگیری‌های روزانه</h3><div class="planner-check-list" data-planner-checks></div><form class="planner-check-add" data-planner-add-check><input name="title" maxlength="255" placeholder="پیگیری جدید"><button class="btn btn-small">افزودن</button></form></section></aside></div>
 </section>
 <section data-weekly-view hidden><div class="planner-week" data-planner-week></div></section>
 <section data-monthly-view hidden><div class="planner-month-weekdays"><span>شنبه</span><span>یکشنبه</span><span>دوشنبه</span><span>سه‌شنبه</span><span>چهارشنبه</span><span>پنجشنبه</span><span>جمعه</span></div><div class="planner-month" data-planner-month></div></section>
 <footer class="planner-footer"><button type="button" class="btn btn-small" data-enable-notifications>فعال‌سازی اعلان مرورگر</button><span data-planner-summary></span></footer><div class="planner-toast" data-planner-toast role="status" aria-live="polite"></div>
</section>
<?php endif;?>
