<?php
require_once __DIR__ . '/Database.php';

class HrModule
{
    public const DISCLAIMER = 'این آزمون صرفاً برای شناخت سازمانی، توسعه منابع انسانی و بهبود چیدمان نقش‌ها استفاده می‌شود و تشخیص پزشکی، روان‌شناختی یا بالینی محسوب نمی‌شود.';

    public static function repair(PDO $pdo): void
    {
        foreach (self::schema() as $sql) $pdo->exec($sql);
        foreach ([
            'department' => 'VARCHAR(150) NULL', 'role_key' => 'VARCHAR(100) NULL', 'sales_line' => 'VARCHAR(50) NULL',
            'supervisor_id' => 'INT UNSIGNED NULL', 'organization_manager_id' => 'INT UNSIGNED NULL',
        ] as $column => $definition) {
            if (!Database::columnExists('users', $column)) $pdo->exec("ALTER TABLE users ADD `{$column}` {$definition}");
        }
        $seedVersion=(string)($pdo->query("SELECT setting_value FROM site_settings WHERE setting_key='sobhan_hr_seed_version' LIMIT 1")->fetchColumn()?:'');
        if($seedVersion!=='1'){
            self::seed($pdo);
            $pdo->exec("INSERT INTO site_settings(setting_key,setting_value,setting_type,updated_at) VALUES ('sobhan_hr_seed_version','1','number',NOW()) ON DUPLICATE KEY UPDATE setting_value='1',updated_at=NOW()");
        }
    }

    public static function schema(): array
    {
        $engine=' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';
        return [
            "CREATE TABLE IF NOT EXISTS hr_kpi_templates (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,code VARCHAR(100) NOT NULL UNIQUE,category VARCHAR(100) NULL,role_key VARCHAR(100) NULL,department VARCHAR(150) NULL,description TEXT NULL,active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_hr_kpi_templates_active(active)){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_kpi_criteria (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,template_id INT UNSIGNED NOT NULL,criteria_text TEXT NOT NULL,criteria_hash CHAR(64) NOT NULL,category VARCHAR(100) NULL,weight DECIMAL(8,2) NOT NULL DEFAULT 1,max_score DECIMAL(8,2) NOT NULL DEFAULT 10,sort_order INT NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_hr_kpi_criterion(template_id,criteria_hash),CONSTRAINT fk_hr_kpi_criteria_template FOREIGN KEY(template_id) REFERENCES hr_kpi_templates(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_kpi_periods (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,code VARCHAR(100) NOT NULL UNIQUE,start_date DATE NULL,end_date DATE NULL,period_type VARCHAR(50) NOT NULL DEFAULT 'custom',active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_kpi_employee_assignments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,employee_id INT UNSIGNED NOT NULL,template_id INT UNSIGNED NOT NULL,department VARCHAR(150) NULL,role_key VARCHAR(100) NULL,sales_line VARCHAR(50) NULL,supervisor_id INT UNSIGNED NULL,manager_id INT UNSIGNED NULL,assigned_by INT UNSIGNED NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_hr_kpi_assignment(employee_id,template_id),INDEX idx_hr_kpi_assignment_team(supervisor_id,manager_id),CONSTRAINT fk_hr_kpi_assignment_employee FOREIGN KEY(employee_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_hr_kpi_assignment_template FOREIGN KEY(template_id) REFERENCES hr_kpi_templates(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_kpi_scores (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,employee_id INT UNSIGNED NOT NULL,template_id INT UNSIGNED NOT NULL,criteria_id INT UNSIGNED NOT NULL,period_id INT UNSIGNED NOT NULL,score DECIMAL(8,2) NOT NULL DEFAULT 0,notes TEXT NULL,scored_by INT UNSIGNED NULL,scored_at DATETIME NULL,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_hr_kpi_score(employee_id,criteria_id,period_id),INDEX idx_hr_kpi_score_period(period_id),CONSTRAINT fk_hr_kpi_score_employee FOREIGN KEY(employee_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_hr_kpi_score_template FOREIGN KEY(template_id) REFERENCES hr_kpi_templates(id) ON DELETE CASCADE,CONSTRAINT fk_hr_kpi_score_criteria FOREIGN KEY(criteria_id) REFERENCES hr_kpi_criteria(id) ON DELETE CASCADE,CONSTRAINT fk_hr_kpi_score_period FOREIGN KEY(period_id) REFERENCES hr_kpi_periods(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_kpi_score_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,score_id INT UNSIGNED NULL,action VARCHAR(30) NOT NULL,old_value TEXT NULL,new_value TEXT NULL,performed_by INT UNSIGNED NULL,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_hr_kpi_log_score(score_id),CONSTRAINT fk_hr_kpi_log_score FOREIGN KEY(score_id) REFERENCES hr_kpi_scores(id) ON DELETE SET NULL){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_tests (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,code VARCHAR(100) NOT NULL UNIQUE,category VARCHAR(100) NULL,description TEXT NULL,age_range VARCHAR(80) NULL,scoring_type VARCHAR(50) NOT NULL DEFAULT 'dimensions',time_limit_minutes INT NOT NULL DEFAULT 20,active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,seeded TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_dimensions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,test_id INT UNSIGNED NOT NULL,dimension_key VARCHAR(100) NOT NULL,dimension_label VARCHAR(190) NOT NULL,description TEXT NULL,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_hr_dimension(test_id,dimension_key),CONSTRAINT fk_hr_dimension_test FOREIGN KEY(test_id) REFERENCES hr_assessment_tests(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_questions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,test_id INT UNSIGNED NOT NULL,question_text TEXT NOT NULL,question_hash CHAR(64) NOT NULL,answer_type VARCHAR(30) NOT NULL,options_json TEXT NULL,dimension_key VARCHAR(100) NULL,secondary_dimension_key VARCHAR(100) NULL,weight DECIMAL(8,2) NOT NULL DEFAULT 1,reverse_score TINYINT(1) NOT NULL DEFAULT 0,correct_answer VARCHAR(190) NULL,required TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,seeded TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_hr_question(test_id,question_hash),INDEX idx_hr_question_test(test_id),CONSTRAINT fk_hr_question_test FOREIGN KEY(test_id) REFERENCES hr_assessment_tests(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_assignments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,test_id INT UNSIGNED NOT NULL,employee_id INT UNSIGNED NOT NULL,department VARCHAR(150) NULL,role_key VARCHAR(100) NULL,sales_line VARCHAR(50) NULL,supervisor_id INT UNSIGNED NULL,manager_id INT UNSIGNED NULL,assigned_by INT UNSIGNED NULL,assignment_scope VARCHAR(40) NOT NULL DEFAULT 'employee',period_key VARCHAR(100) NULL,due_date DATE NULL,allow_retake TINYINT(1) NOT NULL DEFAULT 0,status VARCHAR(30) NOT NULL DEFAULT 'assigned',notes TEXT NULL,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_hr_assignment_employee(employee_id,status),INDEX idx_hr_assignment_team(supervisor_id,manager_id),CONSTRAINT fk_hr_assignment_test FOREIGN KEY(test_id) REFERENCES hr_assessment_tests(id) ON DELETE CASCADE,CONSTRAINT fk_hr_assignment_employee FOREIGN KEY(employee_id) REFERENCES users(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_responses (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,assignment_id INT UNSIGNED NOT NULL,employee_id INT UNSIGNED NOT NULL,test_id INT UNSIGNED NOT NULL,answers_json LONGTEXT NULL,progress_json TEXT NULL,status VARCHAR(30) NOT NULL DEFAULT 'in_progress',started_at DATETIME NULL,submitted_at DATETIME NULL,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_hr_response_assignment(assignment_id),CONSTRAINT fk_hr_response_assignment FOREIGN KEY(assignment_id) REFERENCES hr_assessment_assignments(id) ON DELETE CASCADE,CONSTRAINT fk_hr_response_employee FOREIGN KEY(employee_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_hr_response_test FOREIGN KEY(test_id) REFERENCES hr_assessment_tests(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_results (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,assignment_id INT UNSIGNED NOT NULL,employee_id INT UNSIGNED NOT NULL,test_id INT UNSIGNED NOT NULL,raw_answers_json LONGTEXT NULL,calculated_scores_json LONGTEXT NULL,normalized_scores_json LONGTEXT NULL,final_result TEXT NULL,risk_level VARCHAR(40) NULL,profile_summary TEXT NULL,recommendation_text TEXT NULL,calculated_at DATETIME NULL,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_hr_result_employee(employee_id),INDEX idx_hr_result_test(test_id),CONSTRAINT fk_hr_result_assignment FOREIGN KEY(assignment_id) REFERENCES hr_assessment_assignments(id) ON DELETE CASCADE,CONSTRAINT fk_hr_result_employee FOREIGN KEY(employee_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_hr_result_test FOREIGN KEY(test_id) REFERENCES hr_assessment_tests(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_result_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,result_id INT UNSIGNED NULL,action VARCHAR(30) NOT NULL,performed_by INT UNSIGNED NULL,old_value_json LONGTEXT NULL,new_value_json LONGTEXT NULL,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_hr_result_log FOREIGN KEY(result_id) REFERENCES hr_assessment_results(id) ON DELETE SET NULL){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_packages (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,code VARCHAR(100) NOT NULL UNIQUE,role_key VARCHAR(100) NULL,description TEXT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP){$engine}",
            "CREATE TABLE IF NOT EXISTS hr_assessment_package_tests (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,package_id INT UNSIGNED NOT NULL,test_id INT UNSIGNED NOT NULL,sort_order INT NOT NULL DEFAULT 0,UNIQUE KEY uq_hr_package_test(package_id,test_id),CONSTRAINT fk_hr_package_test_package FOREIGN KEY(package_id) REFERENCES hr_assessment_packages(id) ON DELETE CASCADE,CONSTRAINT fk_hr_package_test_test FOREIGN KEY(test_id) REFERENCES hr_assessment_tests(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS ai_reporting_sources (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,source_name VARCHAR(190) NOT NULL,source_type VARCHAR(50) NOT NULL DEFAULT 'view',connection_label VARCHAR(190) NULL,view_name VARCHAR(190) NOT NULL UNIQUE,description TEXT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP){$engine}",
            "CREATE TABLE IF NOT EXISTS ai_insight_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,requested_by INT UNSIGNED NULL,prompt TEXT NULL,source_context_json LONGTEXT NULL,result_json LONGTEXT NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_ai_insight_requested_by(requested_by),CONSTRAINT fk_ai_insight_user FOREIGN KEY(requested_by) REFERENCES users(id) ON DELETE SET NULL){$engine}",
        ];
    }

    public static function seed(PDO $pdo): array
    {
        $counts=['templates'=>0,'criteria'=>0,'periods'=>0,'tests'=>0,'questions'=>0,'sources'=>0];
        $periods=['ORDIBEHESHT'=>'اردیبهشت','KHORDAD_H1'=>'نیمه اول خرداد','KHORDAD_H2'=>'نیمه دوم خرداد','TIR_H1'=>'نیمه اول تیر','TIR_H2'=>'نیمه دوم تیر','MORDAD_H1'=>'نیمه اول مرداد','MORDAD_H2'=>'نیمه دوم مرداد'];
        $stmt=$pdo->prepare('INSERT IGNORE INTO hr_kpi_periods(title,code,period_type,sort_order,active,created_at,updated_at) VALUES (?,?,"custom",?,1,NOW(),NOW())');$i=10;foreach($periods as $code=>$title){$stmt->execute([$title,$code,$i]);$counts['periods']+=$stmt->rowCount();$i+=10;}
        $templateStmt=$pdo->prepare('INSERT IGNORE INTO hr_kpi_templates(title,code,category,role_key,active,sort_order,created_at,updated_at) VALUES (?,?,"organizational",?,1,?,NOW(),NOW())');
        $criterionStmt=$pdo->prepare('INSERT IGNORE INTO hr_kpi_criteria(template_id,criteria_text,criteria_hash,weight,max_score,sort_order,active,created_at,updated_at) VALUES (?,?,?,1,10,?,1,NOW(),NOW())');
        $sort=10;foreach(self::kpiTemplates() as $code=>$data){$templateStmt->execute([$data[0],$code,$code,$sort]);$counts['templates']+=$templateStmt->rowCount();$templateId=(int)$pdo->query('SELECT id FROM hr_kpi_templates WHERE code='.$pdo->quote($code))->fetchColumn();$cSort=10;foreach($data[1] as $text){$criterionStmt->execute([$templateId,$text,hash('sha256',self::normalize($text)),$cSort]);$counts['criteria']+=$criterionStmt->rowCount();$cSort+=10;}$sort+=10;}
        $testStmt=$pdo->prepare('INSERT IGNORE INTO hr_assessment_tests(title,code,category,description,scoring_type,time_limit_minutes,active,sort_order,seeded,created_at,updated_at) VALUES (?,?,?,?,"dimensions",?,1,?,1,NOW(),NOW())');
        $dimStmt=$pdo->prepare('INSERT IGNORE INTO hr_assessment_dimensions(test_id,dimension_key,dimension_label,sort_order,created_at,updated_at) VALUES (?,?,?,?,NOW(),NOW())');
        $qStmt=$pdo->prepare('INSERT IGNORE INTO hr_assessment_questions(test_id,question_text,question_hash,answer_type,options_json,dimension_key,weight,reverse_score,correct_answer,required,sort_order,active,seeded,created_at,updated_at) VALUES (?,?,?,?,?,?,1,?,?,1,?,1,1,NOW(),NOW())');
        $testSort=10;foreach(self::testDefinitions() as $code=>$test){$description=$test['description'].' '.self::DISCLAIMER;$testStmt->execute([$test['title'],$code,$test['category'],$description,$test['minutes'],$testSort]);$counts['tests']+=$testStmt->rowCount();$testId=(int)$pdo->query('SELECT id FROM hr_assessment_tests WHERE code='.$pdo->quote($code))->fetchColumn();$dSort=10;foreach($test['dimensions'] as $key=>$label){$dimStmt->execute([$testId,$key,$label,$dSort]);$dSort+=10;}$qSort=10;foreach(self::questionsFor($code,$test) as $q){$qStmt->execute([$testId,$q['text'],hash('sha256',self::normalize($q['text'])),$q['type'],$q['options']??null,$q['dimension'],$q['reverse']??0,$q['correct']??null,$qSort]);$counts['questions']+=$qStmt->rowCount();$qSort+=10;}$testSort+=10;}
        self::seedPackages($pdo);
        $sourceStmt=$pdo->prepare('INSERT IGNORE INTO ai_reporting_sources(source_name,source_type,connection_label,view_name,description,active,created_at,updated_at) VALUES (?,"view","SQL Server Reporting",?,?,1,NOW(),NOW())');foreach(self::reportingViews() as $view=>$description){$sourceStmt->execute([$view,$view,$description]);$counts['sources']+=$sourceStmt->rowCount();}
        return $counts;
    }

    private static function normalize(string $text): string { return mb_strtolower(preg_replace('/\s+/u',' ',trim($text)),'UTF-8'); }

    public static function kpiTemplates(): array
    {
        return [
            'OFFICE_MANAGER'=>['مسئول دفتر',['سرعت انجام کارهای روزانه','ارتباط موثر با واحدهای داخلی و مشتریان','پاسخ‌گویی مناسب به تلفن و مراجعه‌کننده','کار با آفیس و نرم‌افزارهای داخلی','تنظیم نامه‌ها و گزارش‌ها','هماهنگی جلسات و برنامه‌ها','حفظ اطلاعات محرمانه شرکت','ثبت دقیق و به‌موقع آفرها','ورود و خروج منظم']],
            'GENERAL_MANAGEMENT'=>['مدیریت',['برنامه‌ریزی و استراتژی مالی','تحلیل سودآوری','صورت سود و زیان','میزان تعامل با واحدهای دیگر','نظم در ورود و خروج']],
            'FINANCE_MANAGER'=>['مدیریت مالی',['نظارت بر ثبت صحیح اسناد حسابداری','تهیه صورت‌های مالی','نظارت بر عملکرد نیروهای واحد مالی','میزان تعامل با واحدهای دیگر','نظارت بر حساب‌های بانکی و مغایرت‌گیری روزانه','برنامه‌ریزی پرداخت‌ها','مدیریت مطالبات و بدهی‌ها','جلوگیری از کمبود نقدینگی','مذاکره با بانک‌ها برای تسهیلات','نظم در ورود و خروج']],
            'SALES_MANAGER'=>['مدیر فروش',['میزان تحقق اهداف فروش کل شرکت','رشد فروش نسبت به دوره قبل','برنامه‌ریزی و اجرای فروش ماهانه','مدیریت تیم فروش، نظم، انگیزش و عملکرد','پوشش مشتری','تحلیل بازار و پیشنهاد افزایش فروش','نیروسازی','دقت در پیش‌بینی فروش','میزان تعامل با واحدهای دیگر','گزارش‌دهی منظم و شفاف','نظم در ورود و خروج']],
            'WAREHOUSE_MANAGER'=>['مدیر انبار',['عدم اختلاف موجودی واقعی و سیستم','سرعت و دقت در دریافت، جانمایی و ارسال','کاهش ضایعات و خسارات','مدیریت نیروی انسانی انبار','ایمنی محیط کار','بهینه‌سازی فضای انبار','صحت بارگیری و ارسال','تعامل با واحدهای دیگر','کنترل کالای نزدیک انقضا','نظم در ورود و خروج']],
            'SALES_SUPERVISOR'=>['سرپرست فروش',['تحقق اهداف فروش منطقه یا تیم','نظارت بر حضور، مسیر و نتیجه ویزیتورها','آموزش و حمایت ویزیتورها','حضور در بازار و تحلیل رقبا','افزایش پوشش و مشتری جدید','کاهش مرجوعی و خطای سفارش','انضباط گزارش روزانه','حل مشکلات مشتریان و ویزیتورها','پیگیری وصول مطالبات','تعامل با واحدهای دیگر','نظم در ورود و خروج']],
            'VISITOR'=>['ویزیتور',['تحقق هدف فروش روزانه / ماهانه','تعداد ویزیت‌های موثر','تعداد فاکتور ثبت‌شده','وصول مطالبات','درصد پوشش مسیر','کیفیت ارتباط با مشتری','دقت ثبت سفارش','جذب مشتری جدید','اجرای درست برنامه مسیر','نظم و ارسال لوکیشن','تعامل با واحدهای دیگر','رعایت اصول ظاهری و بهداشتی']],
            'COMMERCIAL'=>['بازرگانی',['ارسال اوردر و پیگیری سفارش','ثبت دقیق فاکتورهای خرید','اعلام کسری یا اضافات کالا','مستندسازی و پیگیری جلسات','تعامل با واحدها','هماهنگی مالی و فروش','بررسی موجودی انبار','دقت در صورتحساب و پرداخت','ارسال گزارش تامین‌کننده','نظم در ورود و خروج']],
            'TAX_INSURANCE'=>['مسئول مالیات و بیمه',['ارسال به‌موقع لیست بیمه','برنامه‌ریزی مالیاتی قانونی','پیگیری اظهارنامه‌ها','رسیدگی به پرونده‌های مالیاتی','کاهش جرائم مالیاتی','عدم تاخیر در ارسال','محرمانگی اطلاعات مالی','پاسخگویی و پیگیری','تعامل با واحدها','نظم در ورود و خروج']],
            'TREASURY'=>['خزانه',['درصد خطای ثبت حواله و اسناد','درصد اسناد اصلاحی','میزان تعامل با بانک','پیگیری تکمیل موجودی چک‌ها','محرمانگی اطلاعات مالی','پاسخگو و پیگیر بودن','تعامل با واحدها','نظم در ورود و خروج']],
            'SALES_ACCOUNTING'=>['حسابداری فروش',['عدم مغایرت حساب مشتریان','ثبت چک‌های دریافتی','تعامل با فروش، انبار و مالی','کمترین درصد حساب باز','درصد خطای ثبت حواله','زمان ثبت وصولی','درصد اسناد اصلاحی','پاسخگویی و پیگیری','نظم و بایگانی اسناد','تعامل با واحدها','درستی گزارش‌های حساب باز','نظم در ورود و خروج']],
            'IT'=>['فناوری اطلاعات',['امنیت پایه، بکاپ موفق و بررسی دیتابیس','زمان پاسخگویی به درخواست‌ها','درصد سیستم‌های فعال بدون قطعی','در دسترس بودن سامانه‌های حیاتی','کاهش خرابی تکراری','رضایت کاربران داخلی','آموزش پرسنل','پیشنهاد و اجرای تغییرات مفید','تعامل با واحدها','نظم در ورود و خروج']],
            'COLLECTOR'=>['تحصیلدار',['دقت در وصول مطالبات','ثبت چک‌های دریافتی','تعامل با فروش، انبار و مالی','کمترین درصد حساب باز','برخورد مناسب با مشتری','تعامل با واحدها','وصول به‌موقع مانده سررسیدشده','انضباط گزارش‌دهی','نظم در ورود و خروج']],
            'WAREHOUSE_SUPERVISOR'=>['سرپرست انبار',self::warehouseCriteria()],
            'WAREHOUSE_STAFF'=>['نیروی انبار',self::warehouseCriteria()],
            'DISTRIBUTOR'=>['موزع',['زمان‌بندی تحویل کالا','رساندن کالا در زمان تعیین‌شده','توزیع همه فاکتورهای روز','ظاهر و رفتار مناسب','برخورد حرفه‌ای و مودبانه','دقت در پر کردن خروجی‌ها','نظم در ورود و خروج','تعامل با واحدها','جلب رضایت مشتری']],
            'DRIVER'=>['راننده',['رعایت اصول رانندگی ایمن','نگهداری صحیح از خودرو','گزارش به‌موقع خرابی‌ها','رعایت نظافت خودرو','صرفه‌جویی در هزینه‌های خودرو','نظم در ورود و خروج','تعامل با واحدها','عدم تکرار تخلف و تصادف','رعایت ظاهر مناسب','برخورد مناسب با مشتری','تردد در مسیرهای تعیین‌شده']],
        ];
    }

    private static function warehouseCriteria(): array { return ['دقت در دریافت و تطابق کالا با حواله','دقت در جانمایی کالا','سرعت عمل در جابه‌جایی','دقت در بسته‌بندی و آماده‌سازی','کاهش ضایعات و آسیب','نظم و نظافت محیط','دقت در تطابق کالا با فاکتور','رعایت نکات ایمنی','همکاری با همکاران و سرپرست','تعامل با واحدهای دیگر','نظم در ورود و خروج']; }

    public static function testDefinitions(): array
    {
        return [
            'MBTI_ORG'=>['title'=>'MBTI سازمانی','category'=>'personality','minutes'=>18,'dimensions'=>['E'=>'برون‌گرایی','I'=>'درون‌گرایی','S'=>'واقع‌گرایی','N'=>'شهودی','T'=>'تحلیلی','F'=>'ارزش‌محور','J'=>'ساختارمند','P'=>'انعطاف‌پذیر'],'description'=>'شناخت ترجیحات رفتاری در محیط کار.'],
            'DISC_ORG'=>['title'=>'DISC سازمانی','category'=>'behavior','minutes'=>15,'dimensions'=>['D'=>'قاطعیت','I'=>'تأثیرگذاری','S'=>'ثبات','C'=>'وجدان‌کاری'],'description'=>'شناخت سبک رفتاری و ارتباطی.'],
            'MII_ORG'=>['title'=>'هوش‌های چندگانه سازمانی','category'=>'ability','minutes'=>20,'dimensions'=>['linguistic'=>'زبانی','logical_mathematical'=>'منطقی-ریاضی','spatial'=>'فضایی','bodily_kinesthetic'=>'بدنی-حرکتی','musical'=>'موسیقایی','interpersonal'=>'میان‌فردی','intrapersonal'=>'درون‌فردی','naturalistic'=>'طبیعت‌گرا'],'description'=>'شناسایی حوزه‌های توانمندی برجسته.'],
            'COMMITMENT_ORG'=>['title'=>'تعهد سازمانی','category'=>'engagement','minutes'=>12,'dimensions'=>['affective_commitment'=>'تعهد عاطفی','continuance_commitment'=>'تعهد استمراری','normative_commitment'=>'تعهد هنجاری'],'description'=>'بررسی الگوی پیوند و ماندگاری سازمانی.'],
            'JOB_SATISFACTION'=>['title'=>'رضایت شغلی','category'=>'wellbeing','minutes'=>15,'dimensions'=>['work_conditions'=>'شرایط کار','supervisor_relation'=>'رابطه با سرپرست','compensation_perception'=>'برداشت از جبران خدمت','growth_opportunity'=>'فرصت رشد','role_clarity'=>'شفافیت نقش','team_environment'=>'محیط تیمی'],'description'=>'سنجش تجربه کاری و رضایت سازمانی.'],
            'EQ_ORG'=>['title'=>'هوش هیجانی سازمانی','category'=>'development','minutes'=>18,'dimensions'=>['self_awareness'=>'خودآگاهی','empathy'=>'همدلی','emotional_control'=>'مدیریت هیجان','stress_handling'=>'مدیریت فشار','communication_balance'=>'تعادل ارتباطی'],'description'=>'شناسایی توانمندی‌های هیجانی در کار.'],
            'RAVEN_ABSTRACT_ORG'=>['title'=>'استدلال انتزاعی سازمانی','category'=>'reasoning','minutes'=>25,'dimensions'=>['pattern_recognition'=>'تشخیص الگو','logical_sequence'=>'توالی منطقی','abstract_reasoning'=>'استدلال انتزاعی','visual_logic'=>'منطق دیداری'],'description'=>'این نتیجه تخمین غیررسمی توانایی استدلال انتزاعی در محیط کاری است و آزمون رسمی IQ محسوب نمی‌شود.'],
            'BURNOUT_ORG'=>['title'=>'پایش فرسودگی شغلی','category'=>'wellbeing','minutes'=>12,'dimensions'=>['emotional_exhaustion'=>'خستگی هیجانی','motivation_decline'=>'کاهش انگیزه','work_fatigue'=>'خستگی کاری','reduced_effectiveness'=>'کاهش اثربخشی'],'description'=>'پایش غیربالینی فشار و خستگی کاری.'],
            'HOLLAND_ORG'=>['title'=>'علایق شغلی هالند سازمانی','category'=>'role_fit','minutes'=>18,'dimensions'=>['realistic'=>'عملگرا','investigative'=>'جست‌وجوگر','artistic'=>'هنری','social'=>'اجتماعی','enterprising'=>'متقاعدکننده','conventional'=>'قراردادی'],'description'=>'شناسایی علایق شغلی و تناسب نقش.'],
            'SPATIAL_ORG'=>['title'=>'استدلال فضایی سازمانی','category'=>'ability','minutes'=>20,'dimensions'=>['rotation_reasoning'=>'چرخش ذهنی','layout_understanding'=>'درک چیدمان','route_visualization'=>'تجسم مسیر','visual_memory'=>'حافظه دیداری'],'description'=>'سنجش غیررسمی توانمندی فضایی برای نقش‌های عملیاتی.'],
        ];
    }

    private static function questionsFor(string $code,array $test): array
    {
        $needed=['MBTI_ORG'=>3,'DISC_ORG'=>6,'MII_ORG'=>4,'COMMITMENT_ORG'=>6,'JOB_SATISFACTION'=>4,'EQ_ORG'=>5,'RAVEN_ABSTRACT_ORG'=>5,'BURNOUT_ORG'=>5,'HOLLAND_ORG'=>5,'SPATIAL_ORG'=>4][$code];
        $stems=['در کارهای روزانه از این توانمندی به‌خوبی استفاده می‌کنم','هنگام حل مسئله، این رویکرد برایم طبیعی است','در همکاری تیمی این ویژگی را نشان می‌دهم','در شرایط پرفشار می‌توانم این جنبه را حفظ کنم','برای رشد شغلی، تمرکز بر این حوزه را مفید می‌دانم','همکاران معمولاً این ویژگی را در عملکرد من می‌بینند'];
        $questions=[];$options=json_encode(['1'=>'کاملاً مخالفم','2'=>'مخالفم','3'=>'نظری ندارم','4'=>'موافقم','5'=>'کاملاً موافقم'],JSON_UNESCAPED_UNICODE);
        foreach($test['dimensions'] as $key=>$label)for($i=0;$i<$needed;$i++){
            if(in_array($code,['RAVEN_ABSTRACT_ORG','SPATIAL_ORG'],true)){$n=$i+2;$text="در الگوی کاری {$label}، توالی {$n}، ".($n*2)."، ".($n*3)."، عدد بعدی کدام است؟";$opts=[$n*4,$n*4+1,$n*5,$n*3+1];$questions[]=['text'=>$text,'type'=>'choice','options'=>json_encode(array_combine(array_map('strval',$opts),array_map('strval',$opts)),JSON_UNESCAPED_UNICODE),'dimension'=>$key,'correct'=>(string)($n*4)];}
            else{$questions[]=['text'=>$label.': '.$stems[$i],'type'=>'scale_1_5','options'=>$options,'dimension'=>$key,'reverse'=>($code==='BURNOUT_ORG'?0:0)];}
        }
        return $questions;
    }

    private static function seedPackages(PDO $pdo): void
    {
        $packages=['VISITOR_PACKAGE'=>['بسته ویزیتور','VISITOR',['DISC_ORG','EQ_ORG','HOLLAND_ORG','JOB_SATISFACTION','BURNOUT_ORG']],'SALES_SUPERVISOR_PACKAGE'=>['بسته سرپرست فروش','SALES_SUPERVISOR',['DISC_ORG','EQ_ORG','COMMITMENT_ORG','JOB_SATISFACTION','BURNOUT_ORG','MBTI_ORG']],'SALES_MANAGER_PACKAGE'=>['بسته مدیر فروش','SALES_MANAGER',['DISC_ORG','EQ_ORG','MBTI_ORG','COMMITMENT_ORG','BURNOUT_ORG','RAVEN_ABSTRACT_ORG']],'WAREHOUSE_PACKAGE'=>['بسته انبار','WAREHOUSE',['SPATIAL_ORG','HOLLAND_ORG','JOB_SATISFACTION','BURNOUT_ORG']],'FINANCE_ADMIN_PACKAGE'=>['بسته مالی و اداری','FINANCE_ADMIN',['DISC_ORG','HOLLAND_ORG','JOB_SATISFACTION','EQ_ORG','RAVEN_ABSTRACT_ORG']],'IT_PLANNING_PACKAGE'=>['بسته IT و برنامه‌ریزی','IT',['RAVEN_ABSTRACT_ORG','MII_ORG','HOLLAND_ORG','EQ_ORG','JOB_SATISFACTION']]];
        $pStmt=$pdo->prepare('INSERT IGNORE INTO hr_assessment_packages(title,code,role_key,active,created_at,updated_at) VALUES (?,?,?,1,NOW(),NOW())');$ptStmt=$pdo->prepare('INSERT IGNORE INTO hr_assessment_package_tests(package_id,test_id,sort_order) VALUES (?,?,?)');foreach($packages as $code=>[$title,$role,$tests]){$pStmt->execute([$title,$code,$role]);$pid=(int)$pdo->query('SELECT id FROM hr_assessment_packages WHERE code='.$pdo->quote($code))->fetchColumn();$sort=10;foreach($tests as $testCode){$tid=(int)$pdo->query('SELECT id FROM hr_assessment_tests WHERE code='.$pdo->quote($testCode))->fetchColumn();if($tid)$ptStmt->execute([$pid,$tid,$sort]);$sort+=10;}}
    }

    public static function reportingViews(): array
    {
        return ['vw_sales_daily'=>'فروش روزانه و ماهانه','vw_sales_by_customer'=>'فروش بر اساس مشتری','vw_sales_by_visitor'=>'فروش بر اساس ویزیتور','vw_sales_by_product'=>'فروش بر اساس کالا','vw_sales_by_brand'=>'فروش بر اساس برند','vw_targets'=>'تارگت‌ها و تحقق','vw_discounts'=>'خلاصه تخفیفات','vw_inventory_status'=>'وضعیت موجودی','vw_customer_last_purchase'=>'آخرین خرید مشتری','vw_receivables_summary'=>'خلاصه مطالبات'];
    }

    public static function accessibleEmployeeIds(array $user): array
    {
        if (($user['role']??'')==='admin') return array_map('intval',array_column(Database::fetchAll('SELECT id FROM users WHERE status="active"'),'id'));
        if (($user['role']??'')==='manager') return Auth::assignedEmployeeIds((int)$user['id']);
        return [(int)$user['id']];
    }
}
