<?php
require_once __DIR__.'/Database.php';
require_once __DIR__.'/SalesReferenceRepository.php';

class InventoryRepository
{
    public const FINAL_FIELDS=['period_key','snapshot_date','period_id','product_code','product_name','index_code','index_name','consumer_price','expire_date','expire_date_raw','manufacturer_code','manufacturer_name','sales_carton_qty','sales_part_qty','sales_total_qty','sales_total_amount','sales_discount_amount','sales_tax_amount','sales_duty_amount','sales_payable_amount','sales_return_carton_qty','sales_return_part_qty','sales_return_total_qty','purchase_carton_qty','purchase_part_qty','purchase_total_qty','opening_carton_qty','opening_part_qty','opening_total_qty','inbound_carton_qty','inbound_part_qty','inbound_total_qty','outbound_carton_qty','outbound_part_qty','outbound_total_qty','current_period_carton_qty','current_period_part_qty','current_period_total_qty','carton_size','last_cost_price','last_purchase_price','stock_value_by_last_cost','stock_value_by_sale_price_1','retail_price','wholesale_price','sale_price_3','sale_price_4','sale_price_5','sale_price_6','sale_price_7','sale_price_8','sale_price_9','sale_price_10','sale_price_11','sale_price_12','retail_commission','wholesale_commission','commission_3','commission_4','commission_5','commission_6','commission_7','commission_8','commission_9','commission_10','commission_11','commission_12','current_weight','current_volume','product_tree_group_code','product_tree_group_name','barcode','control_code','group_code','group_name','retail_collection_days','current_base_stock','current_part_stock','current_total_stock','brand_name','last_purchase_date','last_purchase_date_raw'];
    public static function createBatch(array $d):int{Database::execute('INSERT INTO sales_import_batches(source_type,source_module,file_name,file_hash,detected_sheet,detected_table,import_mode,status,started_by,started_at,metadata_json,created_at,updated_at) VALUES (?,"inventory_aggregate",?,?,?,?,?,?,?,NOW(),?,NOW(),NOW())',[$d['source_type'],$d['file_name'],$d['file_hash'],$d['detected_sheet']??null,$d['detected_table']??null,$d['import_mode'],$d['status'],$d['started_by'],$d['metadata_json']]);$id=(int)Database::lastInsertId();SalesReferenceRepository::mirrorBatch($id,['source_module'=>'inventory_aggregate','source_type'=>$d['source_type'],'original_file_name'=>$d['file_name'],'stored_file_path'=>$d['stored_file_path']??null,'file_hash'=>$d['file_hash'],'detected_sheet'=>$d['detected_sheet']??null,'detected_table'=>$d['detected_table']??null,'detected_range'=>$d['detected_range']??null,'period_key'=>$d['period_key']??null,'import_mode'=>$d['import_mode'],'status'=>$d['status'],'started_by'=>$d['started_by'],'metadata_json'=>$d['metadata_json']]);return$id;}
    public static function batchForActor(int $id,int $actor,bool $admin=false,bool $lock=false):?array{$sql='SELECT * FROM sales_import_batches WHERE id=? AND source_module="inventory_aggregate"';$p=[$id];if(!$admin){$sql.=' AND started_by=?';$p[]=$actor;}if($lock)$sql.=' FOR UPDATE';return Database::fetch($sql,$p);}
    public static function mappings():array{return Database::fetchAll('SELECT source_header,normalized_key,required,data_type FROM sales_import_column_mappings WHERE source_module="inventory_aggregate" AND active=1 ORDER BY id');}
    public static function updateDetection(int $id,array $c,string $status,array $meta):void{Database::execute('UPDATE sales_import_batches SET detected_sheet=?,detected_table=?,status=?,metadata_json=?,updated_at=NOW() WHERE id=?',[$c['sheet_name']??null,$c['table_name']??null,$status,json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$id]);SalesReferenceRepository::mirrorBatchFromLegacy($id);}
    public static function stage(int $batch,int $row,array $raw,array $normalized,string $status,array $errors,string $key):void{Database::execute('INSERT INTO staging_sales_data(import_batch_id,source_module,`row_number`,source_row_number,raw_json,normalized_json,validation_status,validation_errors_json,source_unique_key,created_at) VALUES (?,"inventory_aggregate",?,?,?,?,?,?,?,NOW())',[$batch,$row,$row,self::json($raw),self::json($normalized),$status,$errors?self::json($errors):null,$key]);$sid=(int)Database::lastInsertId();Database::execute('UPDATE staging_sales_data SET source_row_hash=? WHERE id=?',[hash('sha256','inventory_aggregate|'.$row.'|'.self::json($raw)),$sid]);SalesReferenceRepository::mirrorStagingRow($sid,$batch,'inventory_aggregate',$row,$raw,$normalized,$status,$errors,$key);foreach($errors as$e){Database::execute('INSERT INTO sales_import_errors(import_batch_id,source_module,`row_number`,error_code,error_message,raw_json,normalized_json,created_at) VALUES (?,"inventory_aggregate",?,?,?,?,?,NOW())',[$batch,$row,$e['code']??null,$e['message'],self::json($raw),self::json($normalized)]);SalesReferenceRepository::mirrorError($batch,'inventory_aggregate',$row,$e['code']??null,(string)$e['message'],$raw,$normalized);}}
    public static function counts(int $id,array $s,string $status='preview'):void{Database::execute('UPDATE sales_import_batches SET status=?,pipeline_status=?,total_rows=?,valid_rows=?,invalid_rows=?,duplicate_rows=?,updated_at=NOW() WHERE id=?',[$status,($s['ready_rows']??0)>0?'ready_to_commit':'validation_failed',$s['total_rows'],$s['valid_rows'],$s['invalid_rows'],$s['duplicate_rows'],$id]);SalesReferenceRepository::mirrorBatchFromLegacy($id);}
    public static function rows(int $batch,string $status):array{return Database::fetchAll('SELECT * FROM staging_sales_data WHERE import_batch_id=? AND source_module="inventory_aggregate" AND validation_status=? ORDER BY `row_number`,id',[$batch,$status]);}
    public static function existing(string $key,bool $lock=false):?array{return Database::fetch('SELECT id FROM inventory_aggregate_rows WHERE source_unique_key=? LIMIT 1'.($lock?' FOR UPDATE':''),[$key]);}
    public static function save(int $batch,string $sourceType,string $key,array $data,array $raw,?int $id=null):void{$fields=self::FINAL_FIELDS;$values=array_map(static fn($f)=>$data[$f]??null,$fields);if($id){$set=implode(',',array_map(static fn($f)=>"`{$f}`=?",$fields));Database::execute("UPDATE inventory_aggregate_rows SET import_batch_id=?,source_type=?,source_unique_key=?,{$set},raw_json=?,updated_at=NOW() WHERE id=?",[$batch,$sourceType,$key,...$values,self::json($raw),$id]);}else{$names=implode(',',array_map(static fn($f)=>"`{$f}`",$fields));$marks=implode(',',array_fill(0,count($fields),'?'));Database::execute("INSERT INTO inventory_aggregate_rows(import_batch_id,source_type,source_unique_key,{$names},raw_json,created_at,updated_at) VALUES (?,?,?,{$marks},?,NOW(),NOW())",[$batch,$sourceType,$key,...$values,self::json($raw)]);}try{Database::execute('UPDATE inventory_aggregate_rows SET period_carton_stock=COALESCE(period_carton_stock,current_period_carton_qty),period_part_stock=COALESCE(period_part_stock,current_period_part_qty),period_total_stock=COALESCE(period_total_stock,current_period_total_qty),tree_group_code=COALESCE(tree_group_code,product_tree_group_code),tree_group_name=COALESCE(tree_group_name,product_tree_group_name) WHERE import_batch_id=?',[$batch]);}catch(Throwable$ignored){}}
    public static function mark(int $id,string $status):void{Database::execute('UPDATE staging_sales_data SET validation_status=? WHERE id=?',[$status,$id]);Database::execute('UPDATE staging_sales_reference_rows SET validation_status=? WHERE id=?',[$status,$id]);}
    public static function finish(int $id,string $status,int $inserted=0,int $updated=0,int $skipped=0,?string $error=null):void{Database::execute('UPDATE sales_import_batches SET status=?,pipeline_status=?,imported_rows=?,updated_rows=?,skipped_rows=?,error_message=?,finished_at=NOW(),updated_at=NOW() WHERE id=?',[$status,match($status){'committed','completed'=>'committed','failed'=>'rejected','cancelled'=>'rolled_back',default=>$status},$inserted,$updated,$skipped,$error,$id]);SalesReferenceRepository::mirrorBatchFromLegacy($id);}
    private static function json(array $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
}
