<?php
require_once __DIR__.'/Database.php';
final class ManagementMeetingsModule
{
 public static function repair(PDO $pdo):void{
  $e=' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';$sql=[
   "CREATE TABLE IF NOT EXISTS management_meetings(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,meeting_type VARCHAR(50) NOT NULL DEFAULT 'general',meeting_date DATE NOT NULL,start_time TIME NULL,end_time TIME NULL,location VARCHAR(255) NULL,organizer_user_id INT UNSIGNED NULL,secretary_user_id INT UNSIGNED NULL,attendees_json LONGTEXT NULL,absent_users_json LONGTEXT NULL,agenda TEXT NULL,meeting_summary LONGTEXT NULL,status VARCHAR(30) NOT NULL DEFAULT 'draft',attachments_json LONGTEXT NULL,created_by INT UNSIGNED NOT NULL,updated_by INT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,INDEX idx_management_meeting_date(meeting_date),INDEX idx_management_meeting_status(status),INDEX idx_management_meeting_organizer(organizer_user_id),CONSTRAINT fk_management_meeting_creator FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT){$e}",
   "CREATE TABLE IF NOT EXISTS management_decisions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meeting_id BIGINT UNSIGNED NOT NULL,title VARCHAR(255) NOT NULL,description LONGTEXT NULL,decision_type VARCHAR(50) NOT NULL DEFAULT 'decision',category VARCHAR(100) NULL,responsible_user_id INT UNSIGNED NULL,responsible_unit_id INT UNSIGNED NULL,supervisor_user_id INT UNSIGNED NULL,priority VARCHAR(20) NOT NULL DEFAULT 'normal',due_date DATE NULL,followup_status VARCHAR(30) NOT NULL DEFAULT 'not_started',progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,latest_followup_note TEXT NULL,is_rule TINYINT(1) NOT NULL DEFAULT 0,rule_effective_date DATE NULL,rule_expire_date DATE NULL,closed_at DATETIME NULL,closed_by INT UNSIGNED NULL,verified_by INT UNSIGNED NULL,verification_status VARCHAR(30) NULL,overdue_notified_at DATETIME NULL,created_by INT UNSIGNED NOT NULL,updated_by INT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,INDEX idx_decision_meeting(meeting_id),INDEX idx_decision_responsible(responsible_user_id),INDEX idx_decision_unit(responsible_unit_id),INDEX idx_decision_status(followup_status),INDEX idx_decision_due(due_date),INDEX idx_decision_overdue_notice(followup_status,due_date,overdue_notified_at),INDEX idx_decision_rule(is_rule),CONSTRAINT fk_decision_meeting FOREIGN KEY(meeting_id) REFERENCES management_meetings(id) ON DELETE RESTRICT,CONSTRAINT fk_decision_creator FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT){$e}",
   "CREATE TABLE IF NOT EXISTS management_decision_followups(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,decision_id BIGINT UNSIGNED NOT NULL,old_status VARCHAR(30) NULL,new_status VARCHAR(30) NOT NULL,progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,followup_note TEXT NULL,next_followup_date DATE NULL,attachment_json LONGTEXT NULL,created_by INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_followup_decision(decision_id),INDEX idx_followup_next(next_followup_date),CONSTRAINT fk_followup_decision FOREIGN KEY(decision_id) REFERENCES management_decisions(id) ON DELETE RESTRICT,CONSTRAINT fk_followup_creator FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT){$e}",
   "CREATE TABLE IF NOT EXISTS management_rule_versions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,decision_id BIGINT UNSIGNED NOT NULL,rule_code VARCHAR(100) NOT NULL,title VARCHAR(255) NOT NULL,content LONGTEXT NOT NULL,version_number INT UNSIGNED NOT NULL DEFAULT 1,effective_date DATE NOT NULL,expire_date DATE NULL,scope_type VARCHAR(30) NOT NULL DEFAULT 'company',scope_value VARCHAR(190) NULL,active TINYINT(1) NOT NULL DEFAULT 0,approved_by INT UNSIGNED NULL,approved_at DATETIME NULL,created_by INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_rule_version(rule_code,version_number),INDEX idx_rule_decision(decision_id),INDEX idx_rule_active(active),INDEX idx_rule_scope(scope_type,scope_value),CONSTRAINT fk_rule_decision FOREIGN KEY(decision_id) REFERENCES management_decisions(id) ON DELETE RESTRICT,CONSTRAINT fk_rule_creator FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT){$e}"
  ];foreach($sql as $s)$pdo->exec($s);
  $columns=[
   'management_meetings'=>['title'=>'VARCHAR(255) NOT NULL DEFAULT ""','meeting_type'=>'VARCHAR(50) NOT NULL DEFAULT "general"','meeting_date'=>'DATE NULL','start_time'=>'TIME NULL','end_time'=>'TIME NULL','location'=>'VARCHAR(255) NULL','organizer_user_id'=>'INT UNSIGNED NULL','secretary_user_id'=>'INT UNSIGNED NULL','attendees_json'=>'LONGTEXT NULL','absent_users_json'=>'LONGTEXT NULL','agenda'=>'TEXT NULL','meeting_summary'=>'LONGTEXT NULL','status'=>'VARCHAR(30) NOT NULL DEFAULT "draft"','attachments_json'=>'LONGTEXT NULL','created_by'=>'INT UNSIGNED NULL','updated_by'=>'INT UNSIGNED NULL','created_at'=>'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP','updated_at'=>'DATETIME NULL'],
   'management_decisions'=>['meeting_id'=>'BIGINT UNSIGNED NULL','title'=>'VARCHAR(255) NOT NULL DEFAULT ""','description'=>'LONGTEXT NULL','decision_type'=>'VARCHAR(50) NOT NULL DEFAULT "decision"','category'=>'VARCHAR(100) NULL','responsible_user_id'=>'INT UNSIGNED NULL','responsible_unit_id'=>'INT UNSIGNED NULL','supervisor_user_id'=>'INT UNSIGNED NULL','priority'=>'VARCHAR(20) NOT NULL DEFAULT "normal"','due_date'=>'DATE NULL','followup_status'=>'VARCHAR(30) NOT NULL DEFAULT "not_started"','progress_percent'=>'TINYINT UNSIGNED NOT NULL DEFAULT 0','latest_followup_note'=>'TEXT NULL','is_rule'=>'TINYINT(1) NOT NULL DEFAULT 0','rule_effective_date'=>'DATE NULL','rule_expire_date'=>'DATE NULL','closed_at'=>'DATETIME NULL','closed_by'=>'INT UNSIGNED NULL','verified_by'=>'INT UNSIGNED NULL','verification_status'=>'VARCHAR(30) NULL','overdue_notified_at'=>'DATETIME NULL','created_by'=>'INT UNSIGNED NULL','updated_by'=>'INT UNSIGNED NULL','created_at'=>'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP','updated_at'=>'DATETIME NULL'],
   'management_decision_followups'=>['decision_id'=>'BIGINT UNSIGNED NULL','old_status'=>'VARCHAR(30) NULL','new_status'=>'VARCHAR(30) NOT NULL DEFAULT "not_started"','progress_percent'=>'TINYINT UNSIGNED NOT NULL DEFAULT 0','followup_note'=>'TEXT NULL','next_followup_date'=>'DATE NULL','attachment_json'=>'LONGTEXT NULL','created_by'=>'INT UNSIGNED NULL','created_at'=>'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'],
   'management_rule_versions'=>['decision_id'=>'BIGINT UNSIGNED NULL','rule_code'=>'VARCHAR(100) NOT NULL DEFAULT ""','title'=>'VARCHAR(255) NOT NULL DEFAULT ""','content'=>'LONGTEXT NULL','version_number'=>'INT UNSIGNED NOT NULL DEFAULT 1','effective_date'=>'DATE NULL','expire_date'=>'DATE NULL','scope_type'=>'VARCHAR(30) NOT NULL DEFAULT "company"','scope_value'=>'VARCHAR(190) NULL','active'=>'TINYINT(1) NOT NULL DEFAULT 0','approved_by'=>'INT UNSIGNED NULL','approved_at'=>'DATETIME NULL','created_by'=>'INT UNSIGNED NULL','created_at'=>'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP']
  ];foreach($columns as $table=>$defs)foreach($defs as $column=>$definition)self::column($pdo,$table,$column,$definition);
  foreach([['management_decisions','idx_decision_meeting','meeting_id'],['management_decisions','idx_decision_responsible','responsible_user_id'],['management_decisions','idx_decision_unit','responsible_unit_id'],['management_decisions','idx_decision_status','followup_status'],['management_decisions','idx_decision_due','due_date'],['management_decisions','idx_decision_overdue_notice','followup_status,due_date,overdue_notified_at'],['management_decisions','idx_decision_rule','is_rule'],['management_decision_followups','idx_followup_decision','decision_id'],['management_rule_versions','idx_rule_active','active']] as [$table,$index,$cols])self::index($pdo,$table,$index,$cols);
  $m=$pdo->prepare('INSERT INTO modules(module_key,module_title,sort_order,status,created_at) VALUES(?,?,?,"active",NOW()) ON DUPLICATE KEY UPDATE module_title=VALUES(module_title),status="active"');foreach(['management_meetings'=>'صورتجلسات مدیریتی','management_decisions'=>'مصوبات و پیگیری‌ها','management_rules'=>'قوانین مصوب'] as $k=>$t)$m->execute([$k,$t,620]);
 }
 private static function column(PDO $pdo,string $table,string $column,string $definition):void{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$q->execute([$table,$column]);if(!(int)$q->fetchColumn())$pdo->exec("ALTER TABLE `{$table}` ADD `{$column}` {$definition}");}
 private static function index(PDO $pdo,string $table,string $index,string $columns):void{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?');$q->execute([$table,$index]);if(!(int)$q->fetchColumn())$pdo->exec("ALTER TABLE `{$table}` ADD INDEX `{$index}` ({$columns})");}
}
