<?php
require_once __DIR__.'/Database.php';

final class PersonalPlannerModule
{
    public static function repair(PDO $pdo): void
    {
        $engine=' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';
        $sql=[
            "CREATE TABLE IF NOT EXISTS personal_planner_tasks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,title VARCHAR(255) NOT NULL,description TEXT NULL,task_date DATE NOT NULL,due_at DATETIME NULL,status VARCHAR(30) NOT NULL DEFAULT 'todo',priority VARCHAR(30) NOT NULL DEFAULT 'normal',is_important TINYINT(1) NOT NULL DEFAULT 0,is_recurring TINYINT(1) NOT NULL DEFAULT 0,recurrence_type VARCHAR(30) NULL,recurrence_interval INT NULL,recurrence_days VARCHAR(100) NULL,recurrence_month_day INT NULL,recurrence_end_date DATE NULL,parent_task_id BIGINT UNSIGNED NULL,moved_from_date DATE NULL,moved_to_date DATE NULL,reminder_enabled TINYINT(1) NOT NULL DEFAULT 0,reminder_at DATETIME NULL,notification_sent_at DATETIME NULL,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,completed_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_user_date(user_id,task_date),INDEX idx_user_status(user_id,status),INDEX idx_reminder(reminder_enabled,reminder_at,notification_sent_at),INDEX idx_recurring(is_recurring,parent_task_id),INDEX idx_parent_instance(parent_task_id,user_id,task_date),CONSTRAINT fk_personal_planner_tasks_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS personal_planner_notes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,note_date DATE NOT NULL,note_text TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,UNIQUE KEY uniq_user_note_date(user_id,note_date),CONSTRAINT fk_personal_planner_notes_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS personal_planner_checks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,check_date DATE NOT NULL,title VARCHAR(255) NOT NULL,is_checked TINYINT(1) NOT NULL DEFAULT 0,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,deleted_at DATETIME NULL,INDEX idx_user_check_date(user_id,check_date),CONSTRAINT fk_personal_planner_checks_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS personal_planner_notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,task_id BIGINT UNSIGNED NULL,notification_type VARCHAR(50) NOT NULL,title VARCHAR(255) NOT NULL,message TEXT NULL,scheduled_at DATETIME NOT NULL,sent_at DATETIME NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',error_message TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,INDEX idx_user_notification(user_id,scheduled_at),INDEX idx_status_schedule(status,scheduled_at),UNIQUE KEY uq_planner_task_notification(task_id,notification_type,scheduled_at),CONSTRAINT fk_planner_notification_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS personal_planner_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,task_id BIGINT UNSIGNED NULL,action VARCHAR(50) NOT NULL,old_value_json LONGTEXT NULL,new_value_json LONGTEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_task_log(task_id),INDEX idx_user_log(user_id),CONSTRAINT fk_planner_log_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE){$engine}",
            "CREATE TABLE IF NOT EXISTS personal_planner_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,widget_enabled TINYINT(1) NOT NULL DEFAULT 1,default_view VARCHAR(30) NOT NULL DEFAULT 'daily',notifications_enabled TINYINT(1) NOT NULL DEFAULT 0,default_reminder_minutes INT NULL,unfinished_behavior VARCHAR(30) NOT NULL DEFAULT 'keep_overdue',compact_mode TINYINT(1) NOT NULL DEFAULT 0,show_done_tasks TINYINT(1) NOT NULL DEFAULT 1,seeded_suggestions_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,UNIQUE KEY uniq_user_planner_settings(user_id),CONSTRAINT fk_planner_settings_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE){$engine}",
        ];
        foreach($sql as $statement)$pdo->exec($statement);
        $columns=[
            'personal_planner_tasks'=>['description'=>'TEXT NULL AFTER title','due_at'=>'DATETIME NULL AFTER task_date','is_recurring'=>'TINYINT(1) NOT NULL DEFAULT 0 AFTER is_important','recurrence_type'=>'VARCHAR(30) NULL AFTER is_recurring','recurrence_interval'=>'INT NULL AFTER recurrence_type','recurrence_days'=>'VARCHAR(100) NULL AFTER recurrence_interval','recurrence_month_day'=>'INT NULL AFTER recurrence_days','recurrence_end_date'=>'DATE NULL AFTER recurrence_month_day','parent_task_id'=>'BIGINT UNSIGNED NULL AFTER recurrence_end_date','moved_from_date'=>'DATE NULL AFTER parent_task_id','moved_to_date'=>'DATE NULL AFTER moved_from_date','reminder_enabled'=>'TINYINT(1) NOT NULL DEFAULT 0 AFTER moved_to_date','reminder_at'=>'DATETIME NULL AFTER reminder_enabled','notification_sent_at'=>'DATETIME NULL AFTER reminder_at'],
            'personal_planner_settings'=>['seeded_suggestions_at'=>'DATETIME NULL AFTER show_done_tasks'],
        ];
        foreach($columns as $table=>$defs)foreach($defs as $column=>$definition)self::column($pdo,$table,$column,$definition);
        self::widen($pdo,'personal_planner_tasks','title','varchar(255)','VARCHAR(255) NOT NULL');
        self::widen($pdo,'personal_planner_tasks','status','varchar(30)',"VARCHAR(30) NOT NULL DEFAULT 'todo'");
        self::widen($pdo,'personal_planner_tasks','priority','varchar(30)',"VARCHAR(30) NOT NULL DEFAULT 'normal'");
        self::widen($pdo,'personal_planner_checks','title','varchar(255)','VARCHAR(255) NOT NULL');
        self::index($pdo,'personal_planner_tasks','idx_user_date','ALTER TABLE personal_planner_tasks ADD INDEX idx_user_date(user_id,task_date)');
        self::index($pdo,'personal_planner_tasks','idx_user_status','ALTER TABLE personal_planner_tasks ADD INDEX idx_user_status(user_id,status)');
        self::index($pdo,'personal_planner_tasks','idx_reminder','ALTER TABLE personal_planner_tasks ADD INDEX idx_reminder(reminder_enabled,reminder_at,notification_sent_at)');
        self::index($pdo,'personal_planner_tasks','idx_recurring','ALTER TABLE personal_planner_tasks ADD INDEX idx_recurring(is_recurring,parent_task_id)');
        self::index($pdo,'personal_planner_tasks','idx_parent_instance','ALTER TABLE personal_planner_tasks ADD INDEX idx_parent_instance(parent_task_id,user_id,task_date)');
        $module=$pdo->prepare('INSERT INTO modules(module_key,module_title,sort_order,status,created_at) VALUES(?,?,?,"active",NOW()) ON DUPLICATE KEY UPDATE module_title=VALUES(module_title),status="active"');
        $module->execute(['personal_planner','برنامه کاری من',330]);$module->execute(['personal_planner.reports_all','مشاهده گزارش پلنر کاربران',331]);
    }
    private static function column(PDO $pdo,string $table,string $column,string $definition):void{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$q->execute([$table,$column]);if(!(int)$q->fetchColumn())$pdo->exec("ALTER TABLE `{$table}` ADD `{$column}` {$definition}");}
    private static function index(PDO $pdo,string $table,string $index,string $sql):void{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?');$q->execute([$table,$index]);if(!(int)$q->fetchColumn())$pdo->exec($sql);}
    private static function widen(PDO $pdo,string $table,string $column,string $target,string $definition):void{$q=$pdo->prepare('SELECT COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$q->execute([$table,$column]);$type=strtolower((string)$q->fetchColumn());if($type!==strtolower($target))$pdo->exec("ALTER TABLE `{$table}` MODIFY `{$column}` {$definition}");}
}
