<?php
require_once __DIR__.'/Database.php';
final class TicketingModule
{
    public static function repair(PDO $pdo):void
    {
        $engine=' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';
        foreach([
            "CREATE TABLE IF NOT EXISTS ticket_categories(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,description TEXT NULL,assigned_unit_id INT UNSIGNED NULL,default_assignee_user_id INT UNSIGNED NULL,active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_ticket_category_active(active,sort_order)){$engine}",
            "CREATE TABLE IF NOT EXISTS tickets(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_no VARCHAR(40) NULL,subject VARCHAR(255) NOT NULL,category_id INT UNSIGNED NOT NULL,priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',requester_user_id INT UNSIGNED NOT NULL,assigned_user_id INT UNSIGNED NULL,assigned_unit_id INT UNSIGNED NULL,due_at DATETIME NULL,status ENUM('open','assigned','in_progress','waiting_user','waiting_admin','resolved','closed','cancelled') NOT NULL DEFAULT 'open',last_message_at DATETIME NULL,resolved_at DATETIME NULL,closed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_ticket_no(ticket_no),INDEX idx_ticket_requester(requester_user_id,status),INDEX idx_ticket_assignee(assigned_user_id,status),INDEX idx_ticket_unit(assigned_unit_id,status),INDEX idx_ticket_due(status,due_at),CONSTRAINT fk_ticket_category FOREIGN KEY(category_id) REFERENCES ticket_categories(id) ON DELETE RESTRICT,CONSTRAINT fk_ticket_requester FOREIGN KEY(requester_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_ticket_assignee FOREIGN KEY(assigned_user_id) REFERENCES users(id) ON DELETE SET NULL){$engine}",
            "CREATE TABLE IF NOT EXISTS ticket_messages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,message TEXT NOT NULL,is_internal TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,INDEX idx_ticket_message(ticket_id,created_at),CONSTRAINT fk_ticket_message_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE RESTRICT,CONSTRAINT fk_ticket_message_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT){$engine}",
            "CREATE TABLE IF NOT EXISTS ticket_attachments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,message_id BIGINT UNSIGNED NULL,uploaded_by INT UNSIGNED NOT NULL,original_name VARCHAR(255) NOT NULL,file_path VARCHAR(500) NOT NULL,mime_type VARCHAR(120) NULL,file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_ticket_attachment(ticket_id,message_id),CONSTRAINT fk_ticket_attachment_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE RESTRICT,CONSTRAINT fk_ticket_attachment_message FOREIGN KEY(message_id) REFERENCES ticket_messages(id) ON DELETE SET NULL){$engine}",
            "CREATE TABLE IF NOT EXISTS ticket_status_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,actor_user_id INT UNSIGNED NULL,old_status VARCHAR(30) NULL,new_status VARCHAR(30) NOT NULL,note TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_ticket_status_log(ticket_id,created_at),CONSTRAINT fk_ticket_status_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE RESTRICT){$engine}",
            "CREATE TABLE IF NOT EXISTS ticket_assignments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,assigned_user_id INT UNSIGNED NULL,assigned_unit_id INT UNSIGNED NULL,assigned_by INT UNSIGNED NOT NULL,note TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,ended_at DATETIME NULL,INDEX idx_ticket_assignment(ticket_id,created_at),CONSTRAINT fk_ticket_assignment_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE RESTRICT){$engine}",
            "CREATE TABLE IF NOT EXISTS ticket_sla_rules(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id INT UNSIGNED NULL,priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',first_response_minutes INT UNSIGNED NOT NULL DEFAULT 480,resolution_minutes INT UNSIGNED NOT NULL DEFAULT 2880,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_ticket_sla(category_id,priority),CONSTRAINT fk_ticket_sla_category FOREIGN KEY(category_id) REFERENCES ticket_categories(id) ON DELETE RESTRICT){$engine}"
        ] as $sql)$pdo->exec($sql);
        $module=$pdo->prepare('INSERT INTO modules(module_key,module_title,sort_order,status,created_at) VALUES(?,?,? ,"active",NOW()) ON DUPLICATE KEY UPDATE module_title=VALUES(module_title),status="active"');
        foreach(['ticketing.view'=>'مشاهده تیکت‌های خود','ticketing.create'=>'ثبت تیکت','ticketing.manage'=>'مدیریت تیکت‌ها','ticketing.categories'=>'مدیریت دسته‌بندی تیکت','ticketing.settings'=>'تنظیمات و SLA تیکت'] as $key=>$title)$module->execute([$key,$title,730]);
        $pdo->exec("INSERT INTO ticket_categories(title,description,active,sort_order,created_at,updated_at) SELECT 'عمومی','درخواست‌های عمومی سازمان',1,10,NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM ticket_categories WHERE title='عمومی')");
    }
}
