<?php

class WorkforceModule
{
    public static function repair(PDO $pdo): void
    {
        if(Database::tableExists('users')){
            if(!Database::columnExists('users','employee_no'))$pdo->exec('ALTER TABLE users ADD employee_no VARCHAR(50) NULL');
            if(!Database::columnExists('users','mobile'))$pdo->exec('ALTER TABLE users ADD mobile VARCHAR(30) NULL');
            if(!Database::columnExists('users','force_password_change'))$pdo->exec('ALTER TABLE users ADD force_password_change TINYINT(1) NOT NULL DEFAULT 0');
            $index=$pdo->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME="users" AND INDEX_NAME="uq_users_employee_no"');$index->execute();
            if((int)$index->fetchColumn()===0){$duplicate=$pdo->query('SELECT employee_no FROM users WHERE employee_no IS NOT NULL AND employee_no<>"" GROUP BY employee_no HAVING COUNT(*)>1 LIMIT 1')->fetchColumn();if($duplicate===false){try{$pdo->exec('ALTER TABLE users ADD UNIQUE KEY uq_users_employee_no(employee_no)');}catch(Throwable $e){error_log('employee_no unique index: '.$e->getMessage());}}}
        }
        $e=' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';
        $schema=[
            "CREATE TABLE IF NOT EXISTS user_import_batches(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,file_name VARCHAR(255) NOT NULL,imported_by INT UNSIGNED NULL,mode ENUM('create','update','upsert') NOT NULL DEFAULT 'create',allow_empty_employee_no TINYINT(1) NOT NULL DEFAULT 0,total_rows INT UNSIGNED NOT NULL DEFAULT 0,success_count INT UNSIGNED NOT NULL DEFAULT 0,error_count INT UNSIGNED NOT NULL DEFAULT 0,status ENUM('preview','committed','failed') NOT NULL DEFAULT 'preview',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,committed_at DATETIME NULL,INDEX idx_user_import_batches_user(imported_by),CONSTRAINT fk_user_import_batches_user FOREIGN KEY(imported_by) REFERENCES users(id) ON DELETE SET NULL){$e}",
            "CREATE TABLE IF NOT EXISTS user_import_rows(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT UNSIGNED NOT NULL,source_row INT UNSIGNED NOT NULL,employee_no VARCHAR(50) NULL,raw_data_json LONGTEXT NOT NULL,status ENUM('valid','error','created','updated','skipped') NOT NULL DEFAULT 'valid',error_message TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_user_import_rows_batch(batch_id,status),CONSTRAINT fk_user_import_rows_batch FOREIGN KEY(batch_id) REFERENCES user_import_batches(id) ON DELETE CASCADE){$e}",
            "CREATE TABLE IF NOT EXISTS docs_categories(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,parent_id INT UNSIGNED NULL,sort_order INT NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_docs_categories_parent(parent_id),CONSTRAINT fk_docs_categories_parent FOREIGN KEY(parent_id) REFERENCES docs_categories(id) ON DELETE SET NULL){$e}",
            "CREATE TABLE IF NOT EXISTS docs_articles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id INT UNSIGNED NULL,title VARCHAR(255) NOT NULL,slug VARCHAR(255) NOT NULL UNIQUE,summary TEXT NULL,content LONGTEXT NOT NULL,cover_image VARCHAR(500) NULL,attachment_path VARCHAR(500) NULL,attachment_name VARCHAR(255) NULL,attachment_mime VARCHAR(190) NULL,visibility_scope ENUM('all','units','roles','users') NOT NULL DEFAULT 'all',allowed_roles_json LONGTEXT NULL,allowed_units_json LONGTEXT NULL,allowed_users_json LONGTEXT NULL,require_read_confirmation TINYINT(1) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_by INT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_docs_articles_category(category_id),INDEX idx_docs_articles_active(active),CONSTRAINT fk_docs_articles_category FOREIGN KEY(category_id) REFERENCES docs_categories(id) ON DELETE SET NULL,CONSTRAINT fk_docs_articles_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL){$e}",
            "CREATE TABLE IF NOT EXISTS docs_read_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,doc_id BIGINT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,read_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,confirmed_at DATETIME NULL,ip_address VARCHAR(45) NULL,user_agent VARCHAR(255) NULL,UNIQUE KEY uq_docs_read_user(doc_id,user_id),INDEX idx_docs_read_logs_doc(doc_id),CONSTRAINT fk_docs_read_logs_doc FOREIGN KEY(doc_id) REFERENCES docs_articles(id) ON DELETE CASCADE,CONSTRAINT fk_docs_read_logs_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE){$e}",
            "CREATE TABLE IF NOT EXISTS payroll_periods(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,period_key VARCHAR(80) NOT NULL UNIQUE,year INT NOT NULL,month TINYINT UNSIGNED NOT NULL,start_date DATE NULL,end_date DATE NULL,status ENUM('draft','imported','published','locked','cancelled') NOT NULL DEFAULT 'draft',created_by INT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_payroll_periods_status(status),CONSTRAINT fk_payroll_periods_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL){$e}",
            "CREATE TABLE IF NOT EXISTS payroll_fields(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,field_key VARCHAR(100) NOT NULL UNIQUE,label VARCHAR(190) NOT NULL,field_type ENUM('earning','deduction','info','calculated','employer_cost') NOT NULL,data_type ENUM('text','number','money','date','percent') NOT NULL DEFAULT 'money',calculation_type ENUM('manual','formula','system') NOT NULL DEFAULT 'manual',formula VARCHAR(1000) NULL,default_value VARCHAR(500) NULL,visible_to_employee TINYINT(1) NOT NULL DEFAULT 1,visible_in_pdf TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_payroll_fields_active(active,sort_order)){$e}",
            "CREATE TABLE IF NOT EXISTS payroll_import_batches(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,period_id INT UNSIGNED NOT NULL,file_name VARCHAR(255) NOT NULL,imported_by INT UNSIGNED NULL,total_rows INT UNSIGNED NOT NULL DEFAULT 0,success_count INT UNSIGNED NOT NULL DEFAULT 0,error_count INT UNSIGNED NOT NULL DEFAULT 0,status ENUM('preview','committed','failed') NOT NULL DEFAULT 'preview',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,committed_at DATETIME NULL,INDEX idx_payroll_batches_period(period_id),CONSTRAINT fk_payroll_batches_period FOREIGN KEY(period_id) REFERENCES payroll_periods(id) ON DELETE CASCADE,CONSTRAINT fk_payroll_batches_user FOREIGN KEY(imported_by) REFERENCES users(id) ON DELETE SET NULL){$e}",
            "CREATE TABLE IF NOT EXISTS payroll_import_rows(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,batch_id BIGINT UNSIGNED NOT NULL,source_row INT UNSIGNED NOT NULL,employee_no VARCHAR(50) NULL,raw_data_json LONGTEXT NOT NULL,status ENUM('valid','error','committed','skipped') NOT NULL DEFAULT 'valid',error_message TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_payroll_rows_batch(batch_id,status),CONSTRAINT fk_payroll_rows_batch FOREIGN KEY(batch_id) REFERENCES payroll_import_batches(id) ON DELETE CASCADE){$e}",
            "CREATE TABLE IF NOT EXISTS payroll_slips(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,period_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,employee_no VARCHAR(50) NOT NULL,gross_amount DECIMAL(18,2) NOT NULL DEFAULT 0,total_earnings DECIMAL(18,2) NOT NULL DEFAULT 0,total_deductions DECIMAL(18,2) NOT NULL DEFAULT 0,net_pay DECIMAL(18,2) NOT NULL DEFAULT 0,status ENUM('draft','ready','published','cancelled') NOT NULL DEFAULT 'draft',published_at DATETIME NULL,tracking_code VARCHAR(64) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_payroll_period_user(period_id,user_id),UNIQUE KEY uq_payroll_tracking(tracking_code),INDEX idx_payroll_slips_status(status),CONSTRAINT fk_payroll_slips_period FOREIGN KEY(period_id) REFERENCES payroll_periods(id) ON DELETE CASCADE,CONSTRAINT fk_payroll_slips_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT){$e}",
            "CREATE TABLE IF NOT EXISTS payroll_slip_values(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slip_id BIGINT UNSIGNED NOT NULL,field_id INT UNSIGNED NULL,field_key VARCHAR(100) NOT NULL,label VARCHAR(190) NOT NULL,value_text LONGTEXT NULL,value_number DECIMAL(18,4) NULL,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_payroll_slip_field(slip_id,field_key),INDEX idx_payroll_values_slip(slip_id),CONSTRAINT fk_payroll_values_slip FOREIGN KEY(slip_id) REFERENCES payroll_slips(id) ON DELETE CASCADE,CONSTRAINT fk_payroll_values_field FOREIGN KEY(field_id) REFERENCES payroll_fields(id) ON DELETE SET NULL){$e}",
            "CREATE TABLE IF NOT EXISTS payroll_exports(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slip_id BIGINT UNSIGNED NULL,period_id INT UNSIGNED NULL,export_type ENUM('pdf','image','zip','group_pdf') NOT NULL,file_path VARCHAR(500) NULL,generated_by INT UNSIGNED NULL,generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_payroll_exports_slip(slip_id),CONSTRAINT fk_payroll_exports_slip FOREIGN KEY(slip_id) REFERENCES payroll_slips(id) ON DELETE CASCADE,CONSTRAINT fk_payroll_exports_period FOREIGN KEY(period_id) REFERENCES payroll_periods(id) ON DELETE CASCADE,CONSTRAINT fk_payroll_exports_user FOREIGN KEY(generated_by) REFERENCES users(id) ON DELETE SET NULL){$e}",
        ];foreach($schema as $sql)$pdo->exec($sql);
        $modules=[['docs.manage','مدیریت مستندات آموزشی'],['docs.view','مشاهده مستندات آموزشی'],['users.import_export','ایمپورت و اکسپورت کاربران'],['payroll.manage','مدیریت حقوق و دستمزد'],['payroll.import','ایمپورت حقوق و دستمزد'],['payroll.publish','انتشار و قفل فیش حقوقی'],['payroll.view_all','مشاهده همه فیش‌های حقوقی'],['payroll.own','مشاهده فیش حقوقی شخصی']];$stmt=$pdo->prepare("INSERT INTO modules(module_key,module_title,sort_order,status,created_at) VALUES(?,?,75,'active',NOW()) ON DUPLICATE KEY UPDATE module_title=VALUES(module_title)");foreach($modules as $module)$stmt->execute($module);
        $fields=[['employee_no','شماره پرسنلی','info','text','system',10],['full_name','نام و نام خانوادگی','info','text','system',20],['national_id','کد ملی','info','text','manual',30],['bank_account','شماره حساب','info','text','manual',40],['job_title','عنوان شغلی','info','text','system',50],['department','واحد سازمانی','info','text','system',60],['base_salary','حقوق پایه','earning','money','manual',100],['housing_allowance','حق مسکن','earning','money','manual',110],['food_allowance','بن کارگری','earning','money','manual',120],['overtime','اضافه‌کاری','earning','money','manual',130],['bonus','پاداش','earning','money','manual',140],['insurance','بیمه','deduction','money','manual',200],['tax','مالیات','deduction','money','manual',210],['loan','وام','deduction','money','manual',220],['advance','مساعده','deduction','money','manual',230],['total_earnings','جمع مزایا','calculated','money','system',900],['total_deductions','جمع کسورات','calculated','money','system',910],['net_pay','خالص پرداختی','calculated','money','system',920]];$f=$pdo->prepare('INSERT IGNORE INTO payroll_fields(field_key,label,field_type,data_type,calculation_type,sort_order,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,NOW(),NOW())');foreach($fields as $row)$f->execute($row);
    }
}
