<?php

require_once __DIR__ . '/EmailTransport.php';

class EmailSyncService
{
    public static function folderType(string $path,string $flags=''): string
    {
        $value=mb_strtolower($path.' '.$flags,'UTF-8');
        foreach(['inbox'=>['inbox','دریافتی'],'sent'=>['sent','ارسال'],'drafts'=>['draft','پیش‌نویس'],'spam'=>['spam','junk','هرز'],'trash'=>['trash','deleted','حذف'],'archive'=>['archive','all mail','آرشیو']] as $type=>$needles)foreach($needles as $needle)if(str_contains($value,$needle))return $type;
        return 'custom';
    }

    private static function date(?string $value): ?string
    {
        if(!$value)return null;try{return (new DateTimeImmutable($value))->format('Y-m-d H:i:s');}catch(Throwable){return null;}
    }
    private static function snippet(string $text): string{$text=trim(preg_replace('/\s+/u',' ',strip_tags($text))??'');return mb_substr($text,0,500);}
    private static function attachmentPath(int $accountId,string $name): array
    {
        $extension=strtolower(pathinfo($name,PATHINFO_EXTENSION));$extension=preg_match('/^[a-z0-9]{1,10}$/',$extension)?'.'.$extension:'';$root=dirname(__DIR__);$dir=$root.'/uploads/email/account_'.$accountId;if(!is_dir($dir)&&!mkdir($dir,0750,true))throw new RuntimeException('email_attachment_directory_failed');$stored=bin2hex(random_bytes(20)).$extension;return [$dir.'/'.$stored,'/uploads/email/account_'.$accountId.'/'.$stored,$stored];
    }
    private static function saveAttachment(int $accountId,int $messageId,array $attachment): void
    {
        if(strlen((string)$attachment['data'])>20*1024*1024)return;[$full,$relative]=self::attachmentPath($accountId,(string)$attachment['name']);if(file_put_contents($full,$attachment['data'],LOCK_EX)===false)throw new RuntimeException('email_attachment_write_failed');@chmod($full,0640);
        Database::execute('INSERT INTO email_attachments(message_id,account_id,file_name,mime_type,file_size,storage_path,content_id,is_inline,created_at) VALUES(?,?,?,?,?,?,?,?,NOW())',[$messageId,$accountId,mb_substr((string)$attachment['name'],0,255),mb_substr((string)$attachment['mime'],0,190),strlen((string)$attachment['data']),$relative,mb_substr((string)$attachment['content_id'],0,500),(int)$attachment['inline']]);
    }
    private static function headerAddress(array $headers,string $key): array{return EmailMimeParser::addresses($headers[$key]??'');}
    private static function saveMessage(array $account,array $folder,int $uid,array $fetched): ?int
    {
        $mime=EmailMimeParser::parse($fetched['raw']);$h=$mime['headers'];$from=self::headerAddress($h,'from')[0]??['name'=>'','email'=>''];$html=EmailHubModule::sanitizeHtml($mime['html']);$text=(string)$mime['text'];$status=$folder['folder_type']==='spam'?'spam':($folder['folder_type']==='trash'?'deleted':'new');$read=str_contains($fetched['flags'],'\\Seen')?1:0;if($read&&$status==='new')$status='read';$messageId=trim((string)($h['message-id']??''),'<> ');
        Database::execute('INSERT IGNORE INTO email_messages(account_id,folder_id,uid_validity,remote_uid,message_id,thread_id,subject,from_email,from_name,to_json,cc_json,bcc_json,reply_to_json,date_received,date_sent,body_text,body_html,snippet,has_attachments,is_read,is_starred,is_flagged,is_answered,importance,status,tags_json,raw_headers_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[
            (int)$account['id'],(int)$folder['id'],(int)$folder['uid_validity'],$uid,mb_substr($messageId,0,500),mb_substr(trim((string)($h['references']??$messageId),'<> '),0,500),mb_substr(EmailMimeParser::decodeHeader($h['subject']??'بدون موضوع'),0,500),mb_substr($from['email'],0,255),mb_substr($from['name'],0,255),json_encode(self::headerAddress($h,'to'),JSON_UNESCAPED_UNICODE),json_encode(self::headerAddress($h,'cc'),JSON_UNESCAPED_UNICODE),json_encode(self::headerAddress($h,'bcc'),JSON_UNESCAPED_UNICODE),json_encode(self::headerAddress($h,'reply-to'),JSON_UNESCAPED_UNICODE),self::date($h['date']??null),self::date($h['date']??null),$text,$html,self::snippet($text!==''?$text:$html),$mime['attachments']?1:0,$read,str_contains($fetched['flags'],'\\Flagged')?1:0,str_contains($fetched['flags'],'\\Flagged')?1:0,str_contains($fetched['flags'],'\\Answered')?1:0,stripos((string)($h['importance']??''),'high')!==false?'high':'normal',$status,null,json_encode($h,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)
        ]);
        $row=Database::fetch('SELECT id FROM email_messages WHERE account_id=? AND folder_id=? AND uid_validity=? AND remote_uid=?',[(int)$account['id'],(int)$folder['id'],(int)$folder['uid_validity'],$uid]);if(!$row)return null;$id=(int)$row['id'];
        if(!Database::fetch('SELECT id FROM email_attachments WHERE message_id=? LIMIT 1',[$id]))foreach($mime['attachments'] as $attachment)self::saveAttachment((int)$account['id'],$id,$attachment);
        self::applyRules($id);return $id;
    }
    public static function syncAccount(int $accountId,int $limitPerFolder=100): array
    {
        $account=EmailHubModule::account($accountId);if(!$account||!(int)$account['active']||!(int)$account['sync_enabled'])throw new RuntimeException('email_account_sync_disabled');if(!$account['imap_host'])throw new RuntimeException('imap_host_missing');
        Database::execute("UPDATE email_accounts SET sync_status='syncing',last_error=NULL,updated_at=NOW() WHERE id=?",[$accountId]);EmailHubModule::log($accountId,null,'sync_started','همگام‌سازی حساب آغاز شد.');$count=0;
        try{$client=new EmailImapClient($account);$remoteFolders=$client->folders();foreach($remoteFolders as $index=>$remote){$type=self::folderType($remote['path'],$remote['flags']);Database::execute('INSERT INTO email_folders(account_id,remote_folder_id,folder_name,folder_path,folder_type,sync_enabled,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,1,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE remote_folder_id=VALUES(remote_folder_id),folder_name=VALUES(folder_name),folder_type=VALUES(folder_type),sort_order=VALUES(sort_order),updated_at=NOW()',[$accountId,$remote['remote_path'],basename(str_replace('\\','/',$remote['path'])),$remote['path'],$type,$index*10]);$folder=Database::fetch('SELECT * FROM email_folders WHERE account_id=? AND folder_path=?',[$accountId,$remote['path']]);if(!$folder||(int)$folder['sync_enabled']!==1)continue;$selected=$client->select((string)$remote['remote_path']);$uidValidity=(int)$selected['uid_validity'];$last=((int)$folder['uid_validity']===$uidValidity)?(int)$folder['last_uid']:0;$uids=array_slice($client->searchAfter($last),0,max(1,min(500,$limitPerFolder)));$maxUid=$last;$folder['uid_validity']=$uidValidity;foreach($uids as $uid){if($uid<=0)continue;self::saveMessage($account,$folder,$uid,$client->fetch($uid));$maxUid=max($maxUid,$uid);$count++;}Database::execute('UPDATE email_folders SET total_messages=?,unread_count=(SELECT COUNT(*) FROM email_messages WHERE folder_id=? AND is_read=0 AND status<>"deleted"),uid_validity=?,last_uid=?,updated_at=NOW() WHERE id=?',[(int)$selected['exists'],(int)$folder['id'],$uidValidity,$maxUid,(int)$folder['id']]);}$client->close();Database::execute("UPDATE email_accounts SET sync_status='ok',last_sync_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=?",[$accountId]);EmailHubModule::log($accountId,null,'sync_completed','همگام‌سازی حساب تکمیل شد.',null,['new_messages'=>$count]);return ['ok'=>true,'count'=>$count];}
        catch(Throwable $e){Database::execute("UPDATE email_accounts SET sync_status='error',last_error=?,updated_at=NOW() WHERE id=?",[mb_substr($e->getMessage(),0,1000),$accountId]);EmailHubModule::log($accountId,null,'sync_failed','همگام‌سازی حساب ناموفق بود.',$e->getMessage());throw $e;}
    }
    public static function syncEnabled(int $limitAccounts=20): array{$rows=Database::fetchAll('SELECT id FROM email_accounts WHERE active=1 AND sync_enabled=1 ORDER BY COALESCE(last_sync_at,"1970-01-01") LIMIT '.max(1,min(100,$limitAccounts)));$result=[];foreach($rows as $row){try{$result[(int)$row['id']]=self::syncAccount((int)$row['id']);}catch(Throwable $e){$result[(int)$row['id']]=['ok'=>false];}}foreach(Database::fetchAll("SELECT id FROM email_messages WHERE status IN ('new','read','pending_reply') ORDER BY id DESC LIMIT 500") as $message)self::applyRules((int)$message['id']);return $result;}
    private static function condition(array $message,array $rule): bool
    {
        $field=match($rule['condition_field']){'from'=>(string)$message['from_email'],'subject'=>(string)$message['subject'],'body'=>(string)$message['body_text'],'has_attachment'=>(string)(int)$message['has_attachments'],'age_hours'=>(string)floor((time()-strtotime($message['date_received']?:$message['created_at']))/3600),default=>''};$wanted=(string)$rule['condition_value'];return match($rule['condition_operator']){'equals'=>mb_strtolower($field)===mb_strtolower($wanted),'domain'=>str_ends_with(mb_strtolower($field),'@'.ltrim(mb_strtolower($wanted),'@')),'greater_than'=>(float)$field>(float)$wanted,default=>mb_stripos($field,$wanted)!==false};
    }
    public static function applyRules(int $messageId): void
    {
        $message=Database::fetch('SELECT * FROM email_messages WHERE id=?',[$messageId]);if(!$message)return;$rules=Database::fetchAll('SELECT * FROM email_rules WHERE active=1 AND (account_id IS NULL OR account_id=?) ORDER BY priority,id',[(int)$message['account_id']]);foreach($rules as $rule){if(!self::condition($message,$rule))continue;switch($rule['action_type']){case'add_tag':$tags=json_decode($message['tags_json']?:'[]',true)?:[];$tags[]=trim((string)$rule['action_value']);$tags=array_values(array_unique(array_filter($tags)));Database::execute('UPDATE email_messages SET tags_json=? WHERE id=?',[json_encode($tags,JSON_UNESCAPED_UNICODE),$messageId]);break;case'assign_user':Database::execute('UPDATE email_messages SET assigned_user_id=? WHERE id=?',[(int)$rule['action_value']?:null,$messageId]);break;case'assign_group':Database::execute('UPDATE email_messages SET assigned_group=? WHERE id=?',[mb_substr((string)$rule['action_value'],0,190),$messageId]);break;case'set_pending_reply':Database::execute("UPDATE email_messages SET status='pending_reply' WHERE id=?",[$messageId]);break;case'mark_important':Database::execute("UPDATE email_messages SET importance='high',is_flagged=1 WHERE id=?",[$messageId]);break;case'create_ticket':self::queueIntegration($messageId,'ticket');break;}}
    }
    public static function queueIntegration(int $messageId,string $type='ticket',?int $userId=null): int
    {
        $type=$type==='cartable'?'cartable':'ticket';Database::execute('INSERT INTO email_integrations(message_id,integration_type,status,requested_by,payload_json,created_at,updated_at) VALUES(?,?,"pending",?,?,NOW(),NOW())',[$messageId,$type,$userId?:((int)(Auth::user()['id']??0)?:null),json_encode(['source'=>'email_hub'],JSON_UNESCAPED_UNICODE)]);return (int)Database::lastInsertId();
    }
    public static function moveMessage(int $messageId,string $destination): void
    {
        $message=Database::fetch('SELECT m.*,f.remote_folder_id source_remote,a.* FROM email_messages m JOIN email_folders f ON f.id=m.folder_id JOIN email_accounts a ON a.id=m.account_id WHERE m.id=?',[$messageId]);if(!$message)throw new RuntimeException('email_message_missing');$type=$destination==='archive'?'archive':($destination==='spam'?'spam':'trash');$target=Database::fetch('SELECT * FROM email_folders WHERE account_id=? AND folder_type=? ORDER BY id LIMIT 1',[(int)$message['account_id'],$type]);if($target&&!str_starts_with((string)$message['source_remote'],'local-')){try{$account=EmailHubModule::account((int)$message['account_id']);$client=new EmailImapClient($account);$client->connect();$client->select((string)$message['source_remote']);$client->move((int)$message['remote_uid'],(string)$target['remote_folder_id']);$client->close();}catch(Throwable $e){EmailHubModule::log((int)$message['account_id'],$messageId,'remote_move_failed','جابجایی راه‌دور ایمیل انجام نشد.',$e->getMessage());}}
        Database::execute('UPDATE email_messages SET folder_id=COALESCE(?,folder_id),status=?,updated_at=NOW() WHERE id=?',[$target['id']??null,$type==='archive'?'archived':($type==='spam'?'spam':'deleted'),$messageId]);EmailHubModule::log((int)$message['account_id'],$messageId,$type==='archive'?'message_archived':'message_deleted',$type==='archive'?'ایمیل آرشیو شد.':'ایمیل به حذف‌شده‌ها منتقل شد.');
    }
    public static function markRead(int $messageId): void
    {
        $message=Database::fetch('SELECT m.*,f.remote_folder_id,a.* FROM email_messages m JOIN email_folders f ON f.id=m.folder_id JOIN email_accounts a ON a.id=m.account_id WHERE m.id=?',[$messageId]);if(!$message||$message['is_read'])return;Database::execute("UPDATE email_messages SET is_read=1,status=IF(status='new','read',status),updated_at=NOW() WHERE id=?",[$messageId]);try{if(!str_starts_with((string)$message['remote_folder_id'],'local-')){$account=EmailHubModule::account((int)$message['account_id']);$client=new EmailImapClient($account);$client->connect();$client->select((string)$message['remote_folder_id']);$client->markSeen((int)$message['remote_uid']);$client->close();}}catch(Throwable $e){EmailHubModule::log((int)$message['account_id'],$messageId,'remote_seen_failed','وضعیت خواندن راه‌دور به‌روزرسانی نشد.',$e->getMessage());}EmailHubModule::log((int)$message['account_id'],$messageId,'message_read','ایمیل خوانده شد.');
    }
    public static function processOutbox(int $limit=20,?int $onlyId=null): array
    {
        $where="status='queued' AND (scheduled_at IS NULL OR scheduled_at<=NOW())";$params=[];if($onlyId){$where.=' AND id=?';$params[]=$onlyId;}$rows=Database::fetchAll("SELECT * FROM email_outbox WHERE {$where} ORDER BY id LIMIT ".max(1,min(100,$limit)),$params);$sent=0;$failed=0;foreach($rows as $outbox){$id=(int)$outbox['id'];Database::execute("UPDATE email_outbox SET status='sending',attempts=attempts+1,updated_at=NOW() WHERE id=? AND status='queued'",[$id]);try{$account=EmailHubModule::account((int)$outbox['account_id']);if(!$account||!(int)$account['send_enabled'])throw new RuntimeException('smtp_send_disabled');$attachments=Database::fetchAll('SELECT * FROM email_attachments WHERE outbox_id=?',[$id]);$mail=['to'=>json_decode($outbox['to_json'],true)?:[],'cc'=>json_decode($outbox['cc_json']?:'[]',true)?:[],'bcc'=>json_decode($outbox['bcc_json']?:'[]',true)?:[],'subject'=>$outbox['subject'],'body_html'=>$outbox['body_html'],'body_text'=>$outbox['body_text']];if($outbox['related_message_id']){$related=Database::fetch('SELECT message_id FROM email_messages WHERE id=?',[(int)$outbox['related_message_id']]);$mail['in_reply_to']=$related['message_id']??null;}$remoteId=(new EmailSmtpClient($account))->send($mail,$attachments);Database::execute("UPDATE email_outbox SET status='sent',sent_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=?",[$id]);self::storeSent($outbox,$account,$remoteId);if($outbox['related_message_id'])Database::execute("UPDATE email_messages SET status=?,is_answered=?,is_forwarded=?,updated_at=NOW() WHERE id=?",[$outbox['send_type']==='forward'?'forwarded':'replied',$outbox['send_type']==='forward'?0:1,$outbox['send_type']==='forward'?1:0,(int)$outbox['related_message_id']]);EmailHubModule::log((int)$account['id'],$outbox['related_message_id']?(int)$outbox['related_message_id']:null,$outbox['send_type']==='forward'?'message_forwarded':($outbox['send_type']==='compose'?'message_sent':'message_replied'),'ایمیل با موفقیت ارسال شد.');$sent++;}catch(Throwable $e){Database::execute("UPDATE email_outbox SET status=IF(attempts<3,'queued','failed'),last_error=?,updated_at=NOW() WHERE id=?",[mb_substr($e->getMessage(),0,1000),$id]);EmailHubModule::log((int)$outbox['account_id'],$outbox['related_message_id']?(int)$outbox['related_message_id']:null,'send_failed','ارسال ایمیل ناموفق بود.',$e->getMessage());$failed++;}}return ['sent'=>$sent,'failed'=>$failed];
    }
    public static function storeDraft(array $outbox,array $account): void
    {
        Database::execute('INSERT INTO email_folders(account_id,remote_folder_id,folder_name,folder_path,folder_type,sync_enabled,sort_order,created_at,updated_at) VALUES(?,"local-drafts","پیش‌نویس‌ها","local-drafts","drafts",0,30,NOW(),NOW()) ON DUPLICATE KEY UPDATE folder_type="drafts"',[(int)$account['id']]);$folder=Database::fetch('SELECT id FROM email_folders WHERE account_id=? AND folder_path="local-drafts"',[(int)$account['id']]);if(!$folder)return;$remote=7000000000000000000+(int)$outbox['id'];$has=Database::fetch('SELECT id FROM email_attachments WHERE outbox_id=? LIMIT 1',[(int)$outbox['id']])?1:0;Database::execute('INSERT INTO email_messages(account_id,folder_id,uid_validity,remote_uid,outbox_id,message_id,subject,from_email,from_name,to_json,cc_json,bcc_json,date_received,body_text,body_html,snippet,has_attachments,is_read,status,created_at,updated_at) VALUES(?,?,0,?,?,?, ?,?,?,?,?,?,NOW(),?,?,?,?,1,"read",NOW(),NOW()) ON DUPLICATE KEY UPDATE folder_id=VALUES(folder_id),subject=VALUES(subject),to_json=VALUES(to_json),cc_json=VALUES(cc_json),bcc_json=VALUES(bcc_json),body_text=VALUES(body_text),body_html=VALUES(body_html),snippet=VALUES(snippet),has_attachments=VALUES(has_attachments),updated_at=NOW()',[(int)$account['id'],(int)$folder['id'],$remote,(int)$outbox['id'],'draft-'.$outbox['id'],$outbox['subject'],$account['email_address'],$account['display_name'],$outbox['to_json'],$outbox['cc_json'],$outbox['bcc_json'],$outbox['body_text'],$outbox['body_html'],self::snippet((string)($outbox['body_text']?:strip_tags($outbox['body_html']))),$has]);
    }
    private static function storeSent(array $outbox,array $account,string $remoteId): void
    {
        Database::execute('INSERT INTO email_folders(account_id,remote_folder_id,folder_name,folder_path,folder_type,sync_enabled,sort_order,created_at,updated_at) VALUES(?,"local-sent","ارسال‌شده‌ها","local-sent","sent",0,20,NOW(),NOW()) ON DUPLICATE KEY UPDATE folder_type="sent"',[(int)$account['id']]);$folder=Database::fetch('SELECT id FROM email_folders WHERE account_id=? AND folder_path="local-sent"',[(int)$account['id']]);if(!$folder)return;$has=Database::fetch('SELECT id FROM email_attachments WHERE outbox_id=? LIMIT 1',[(int)$outbox['id']])?1:0;$existing=Database::fetch('SELECT id FROM email_messages WHERE outbox_id=?',[(int)$outbox['id']]);if($existing)Database::execute('UPDATE email_messages SET folder_id=?,remote_uid=?,message_id=?,subject=?,to_json=?,cc_json=?,bcc_json=?,date_received=NOW(),date_sent=NOW(),body_text=?,body_html=?,snippet=?,has_attachments=?,status="read",updated_at=NOW() WHERE id=?',[(int)$folder['id'],8000000000000000000+(int)$outbox['id'],trim($remoteId,'<>'),$outbox['subject'],$outbox['to_json'],$outbox['cc_json'],$outbox['bcc_json'],$outbox['body_text'],$outbox['body_html'],self::snippet((string)($outbox['body_text']?:strip_tags($outbox['body_html']))),$has,(int)$existing['id']]);else Database::execute('INSERT IGNORE INTO email_messages(account_id,folder_id,uid_validity,remote_uid,outbox_id,message_id,subject,from_email,from_name,to_json,cc_json,bcc_json,date_received,date_sent,body_text,body_html,snippet,has_attachments,is_read,status,created_at,updated_at) VALUES(?,?,0,?,?,?,?,?,?,?,?,?,NOW(),NOW(),?,?,?,?,1,"read",NOW(),NOW())',[(int)$account['id'],(int)$folder['id'],8000000000000000000+(int)$outbox['id'],(int)$outbox['id'],trim($remoteId,'<>'),$outbox['subject'],$account['email_address'],$account['display_name'],$outbox['to_json'],$outbox['cc_json'],$outbox['bcc_json'],$outbox['body_text'],$outbox['body_html'],self::snippet((string)($outbox['body_text']?:strip_tags($outbox['body_html']))),$has]);
    }
}
