<?php
require_once __DIR__.'/../core/Database.php';
require_once __DIR__.'/../core/JalaliDate.php';
require_once __DIR__.'/../lib/NotificationService.php';

final class PersonalPlannerService
{
    public static function bootstrap(int $userId,array $user=[]):array
    {
        Database::execute('INSERT IGNORE INTO personal_planner_settings(user_id,created_at,updated_at) VALUES(?,NOW(),NOW())',[$userId]);
        self::seedSuggestedTasks($userId,$user);
        self::applyUnfinishedBehavior($userId);
        self::generateDueNotifications($userId);
        return self::settings($userId);
    }
    public static function settings(int $userId):array{return Database::fetch('SELECT * FROM personal_planner_settings WHERE user_id=?',[$userId])?:['widget_enabled'=>1,'default_view'=>'daily','notifications_enabled'=>0,'unfinished_behavior'=>'keep_overdue','compact_mode'=>0,'show_done_tasks'=>1];}
    public static function saveSettings(int $userId,array $in):array
    {
        $view=in_array($in['default_view']??'',['daily','weekly','monthly'],true)?$in['default_view']:'daily';$behavior=in_array($in['unfinished_behavior']??'',['keep_overdue','auto_move','ask'],true)?$in['unfinished_behavior']:'keep_overdue';$minutes=trim((string)($in['default_reminder_minutes']??''));$minutes=$minutes===''?null:max(0,min(10080,(int)$minutes));
        Database::execute('INSERT INTO personal_planner_settings(user_id,widget_enabled,default_view,notifications_enabled,default_reminder_minutes,unfinished_behavior,compact_mode,show_done_tasks,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE widget_enabled=VALUES(widget_enabled),default_view=VALUES(default_view),notifications_enabled=VALUES(notifications_enabled),default_reminder_minutes=VALUES(default_reminder_minutes),unfinished_behavior=VALUES(unfinished_behavior),compact_mode=VALUES(compact_mode),show_done_tasks=VALUES(show_done_tasks),updated_at=NOW()',[$userId,!empty($in['widget_enabled'])?1:0,$view,!empty($in['notifications_enabled'])?1:0,$minutes,$behavior,!empty($in['compact_mode'])?1:0,!empty($in['show_done_tasks'])?1:0]);
        return self::settings($userId);
    }
    public static function loadDay(int $userId,string $date,array $user=[]):array
    {
        $date=self::date($date);self::bootstrap($userId,$user);self::seedChecks($userId,$date);$settings=self::settings($userId);$doneClause=(int)($settings['show_done_tasks']??1)?'':' AND status<>"done"';$note=Database::fetch('SELECT note_text FROM personal_planner_notes WHERE user_id=? AND note_date=?',[$userId,$date]);
        return ['view'=>'daily','date'=>$date,'date_jalali'=>JalaliDate::toJalali($date),'tasks'=>Database::fetchAll('SELECT * FROM personal_planner_tasks WHERE user_id=? AND task_date=? AND deleted_at IS NULL'.$doneClause.' ORDER BY status="done",is_important DESC,sort_order,id',[$userId,$date]),'overdue'=>Database::fetchAll('SELECT * FROM personal_planner_tasks WHERE user_id=? AND task_date<? AND status IN("todo","overdue") AND deleted_at IS NULL ORDER BY task_date,is_important DESC,id',[$userId,$date]),'note'=>(string)($note['note_text']??''),'checks'=>Database::fetchAll('SELECT id,title,is_checked,sort_order FROM personal_planner_checks WHERE user_id=? AND check_date=? AND deleted_at IS NULL ORDER BY sort_order,id',[$userId,$date]),'settings'=>$settings,'reminders'=>self::dueNotifications($userId)];
    }
    public static function loadWeek(int $userId,string $anchor):array
    {
        $anchor=self::date($anchor);$d=new DateTimeImmutable($anchor);$daysSinceSaturday=((int)$d->format('w')+1)%7;$start=$d->modify("-{$daysSinceSaturday} days");$end=$start->modify('+6 days');$rows=Database::fetchAll('SELECT * FROM personal_planner_tasks WHERE user_id=? AND task_date BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY task_date,sort_order,id',[$userId,$start->format('Y-m-d'),$end->format('Y-m-d')]);$group=[];foreach($rows as $r)$group[$r['task_date']][]=$r;$days=[];for($i=0;$i<7;$i++){$date=$start->modify("+{$i} days")->format('Y-m-d');$tasks=$group[$date]??[];$done=count(array_filter($tasks,fn($x)=>$x['status']==='done'));$days[]=['date'=>$date,'date_jalali'=>JalaliDate::toJalali($date),'tasks'=>$tasks,'total'=>count($tasks),'done'=>$done,'overdue'=>count(array_filter($tasks,fn($x)=>$x['status']!=='done'&&$date<date('Y-m-d'))),'important'=>array_values(array_filter($tasks,fn($x)=>(int)$x['is_important']))];}return ['view'=>'weekly','week_start'=>$start->format('Y-m-d'),'week_end'=>$end->format('Y-m-d'),'days'=>$days];
    }
    public static function loadMonth(int $userId,int $jy,int $jm):array
    {
        if($jy<1200||$jy>1600||$jm<1||$jm>12)throw new InvalidArgumentException('ماه انتخاب‌شده معتبر نیست.');$length=JalaliDate::monthLength($jy,$jm);$first=JalaliDate::toGregorian(sprintf('%04d/%02d/01',$jy,$jm));$last=JalaliDate::toGregorian(sprintf('%04d/%02d/%02d',$jy,$jm,$length));if(!$first||!$last)throw new InvalidArgumentException('ماه انتخاب‌شده معتبر نیست.');$rows=Database::fetchAll('SELECT id,title,task_date,status,is_important FROM personal_planner_tasks WHERE user_id=? AND task_date BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY task_date,id',[$userId,$first,$last]);$group=[];foreach($rows as $r)$group[$r['task_date']][]=$r;$days=[];for($day=1;$day<=$length;$day++){$date=JalaliDate::toGregorian(sprintf('%04d/%02d/%02d',$jy,$jm,$day));$tasks=$group[$date]??[];$done=count(array_filter($tasks,fn($x)=>$x['status']==='done'));$total=count($tasks);$color=$total===0?'empty':($done===$total?'complete':($date<date('Y-m-d')?'overdue':($done>0?'partial':'future')));$days[]=['day'=>$day,'date'=>$date,'total'=>$total,'done'=>$done,'percent'=>$total?round($done*100/$total):0,'status_color'=>$color,'tasks'=>$tasks];}return ['view'=>'monthly','jalali_year'=>$jy,'jalali_month'=>$jm,'first_weekday'=>((int)(new DateTimeImmutable($first))->format('w')+1)%7,'days'=>$days];
    }
    public static function addTask(int $userId,string $title,string $date,array $options=[]):array
    {
        $date=self::date($date);$title=self::title($title);if(empty($options['reminder_at'])&&!empty($options['due_at'])){$settings=self::settings($userId);if((int)($settings['notifications_enabled']??0)&&$settings['default_reminder_minutes']!==null){$due=self::datetime($options['due_at']);$options['reminder_at']=(new DateTimeImmutable($due))->modify('-'.max(0,(int)$settings['default_reminder_minutes']).' minutes')->format('Y-m-d H:i:s');$options['reminder_enabled']=1;}}$opt=self::taskOptions($options,$date);$sort=(int)(Database::fetch('SELECT COALESCE(MAX(sort_order),0)+10 n FROM personal_planner_tasks WHERE user_id=? AND task_date=?',[$userId,$date])['n']??10);
        Database::execute('INSERT INTO personal_planner_tasks(user_id,title,description,task_date,due_at,status,priority,is_important,is_recurring,recurrence_type,recurrence_interval,recurrence_days,recurrence_month_day,recurrence_end_date,parent_task_id,reminder_enabled,reminder_at,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,"todo",?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[$userId,$title,$opt['description'],$date,$opt['due_at'],$opt['priority'],$opt['is_important'],$opt['is_recurring'],$opt['recurrence_type'],$opt['recurrence_interval'],$opt['recurrence_days'],$opt['recurrence_month_day'],$opt['recurrence_end_date'],$opt['parent_task_id'],$opt['reminder_enabled'],$opt['reminder_at'],$sort]);$id=(int)Database::lastInsertId();self::logAction($userId,$id,'created',null,['title'=>$title,'task_date'=>$date]);return self::task($userId,$id);
    }
    public static function updateTask(int $userId,int $id,array $data):array
    {
        $old=self::task($userId,$id);$title=array_key_exists('title',$data)?self::title((string)$data['title']):$old['title'];$date=array_key_exists('task_date',$data)?self::date((string)$data['task_date']):$old['task_date'];$opt=self::taskOptions(array_merge($old,$data),$date);$notificationSent=$old['reminder_at']===$opt['reminder_at']?$old['notification_sent_at']:null;Database::execute('UPDATE personal_planner_tasks SET title=?,description=?,task_date=?,due_at=?,priority=?,is_important=?,is_recurring=?,recurrence_type=?,recurrence_interval=?,recurrence_days=?,recurrence_month_day=?,recurrence_end_date=?,reminder_enabled=?,reminder_at=?,notification_sent_at=?,updated_at=NOW() WHERE id=? AND user_id=? AND deleted_at IS NULL',[$title,$opt['description'],$date,$opt['due_at'],$opt['priority'],$opt['is_important'],$opt['is_recurring'],$opt['recurrence_type'],$opt['recurrence_interval'],$opt['recurrence_days'],$opt['recurrence_month_day'],$opt['recurrence_end_date'],$opt['reminder_enabled'],$opt['reminder_at'],$notificationSent,$id,$userId]);$new=self::task($userId,$id);self::logAction($userId,$id,'updated',$old,$new);return $new;
    }
    public static function toggleTask(int $userId,int $id):array
    { $old=self::task($userId,$id);$done=$old['status']!=='done';Database::execute('UPDATE personal_planner_tasks SET status=?,completed_at=?,updated_at=NOW() WHERE id=? AND user_id=? AND deleted_at IS NULL',[$done?'done':'todo',$done?date('Y-m-d H:i:s'):null,$id,$userId]);self::logAction($userId,$id,$done?'completed':'reopened',$old,null);if($done&&(int)$old['is_recurring'])self::createNextRecurringTask($userId,$id);return self::task($userId,$id);}
    public static function deleteTask(int $userId,int $id):void{$old=self::task($userId,$id);Database::execute('UPDATE personal_planner_tasks SET deleted_at=NOW(),updated_at=NOW() WHERE id=? AND user_id=?',[$id,$userId]);self::logAction($userId,$id,'deleted',$old,null);}
    public static function toggleImportant(int $userId,int $id):array{$old=self::task($userId,$id);$important=!(int)$old['is_important'];Database::execute('UPDATE personal_planner_tasks SET is_important=?,priority=?,updated_at=NOW() WHERE id=? AND user_id=?',[$important?1:0,$important?'high':'normal',$id,$userId]);$new=self::task($userId,$id);self::logAction($userId,$id,'important_toggled',$old,$new);return $new;}
    public static function moveTaskToTomorrow(int $userId,int $id):array{$old=self::task($userId,$id);if($old['status']==='done')throw new DomainException('کار انجام‌شده منتقل نمی‌شود.');$tomorrow=(new DateTimeImmutable('tomorrow'))->format('Y-m-d');Database::execute('UPDATE personal_planner_tasks SET moved_from_date=task_date,moved_to_date=?,task_date=?,status="todo",updated_at=NOW() WHERE id=? AND user_id=?',[$tomorrow,$tomorrow,$id,$userId]);$new=self::task($userId,$id);self::logAction($userId,$id,'moved_to_tomorrow',$old,$new);return $new;}
    public static function moveUnfinishedToTomorrow(int $userId,string $date):int{$date=self::date($date);$ids=array_map('intval',array_column(Database::fetchAll('SELECT id FROM personal_planner_tasks WHERE user_id=? AND task_date=? AND status IN("todo","overdue") AND deleted_at IS NULL',[$userId,$date]),'id'));foreach($ids as $id)self::moveTaskToTomorrow($userId,$id);return count($ids);}
    public static function moveTask(int $userId,int $id,string $targetDate):array{$old=self::task($userId,$id);$target=self::date($targetDate);Database::execute('UPDATE personal_planner_tasks SET moved_from_date=task_date,moved_to_date=?,task_date=?,updated_at=NOW() WHERE id=? AND user_id=?',[$target,$target,$id,$userId]);$new=self::task($userId,$id);self::logAction($userId,$id,'moved',$old,$new);return $new;}
    public static function createNextRecurringTask(int $userId,int $id):?array
    {
        $task=self::task($userId,$id);if(!(int)$task['is_recurring']||!$task['recurrence_type'])return null;$next=self::nextDate($task);if(!$next||($task['recurrence_end_date']&&$next>$task['recurrence_end_date']))return null;$root=(int)($task['parent_task_id']?:$task['id']);$lock='planner:'.$userId.':'.$root.':'.$next;$got=(int)(Database::fetch('SELECT GET_LOCK(?,3) ok',[$lock])['ok']??0);if(!$got)throw new RuntimeException('recurrence_lock_timeout');try{$existing=Database::fetch('SELECT id FROM personal_planner_tasks WHERE user_id=? AND parent_task_id=? AND task_date=? AND deleted_at IS NULL',[$userId,$root,$next]);if($existing)return self::task($userId,(int)$existing['id']);$due=$task['due_at']?$next.' '.substr($task['due_at'],11,8):null;$reminder=$task['reminder_at']?$next.' '.substr($task['reminder_at'],11,8):null;return self::addTask($userId,$task['title'],$next,['description'=>$task['description'],'due_at'=>$due,'priority'=>$task['priority'],'is_important'=>$task['is_important'],'is_recurring'=>1,'recurrence_type'=>$task['recurrence_type'],'recurrence_interval'=>$task['recurrence_interval'],'recurrence_days'=>$task['recurrence_days'],'recurrence_month_day'=>$task['recurrence_month_day'],'recurrence_end_date'=>$task['recurrence_end_date'],'parent_task_id'=>$root,'reminder_enabled'=>$task['reminder_enabled'],'reminder_at'=>$reminder]);}finally{Database::fetch('SELECT RELEASE_LOCK(?) released',[$lock]);}
    }
    public static function saveNote(int $userId,string $date,string $text):void{if(self::length($text)>10000)throw new InvalidArgumentException('یادداشت بیش از حد طولانی است.');Database::execute('INSERT INTO personal_planner_notes(user_id,note_date,note_text,created_at,updated_at) VALUES(?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE note_text=VALUES(note_text),updated_at=NOW()',[$userId,self::date($date),trim($text)]);}
    public static function getChecks(int $userId,string $date):array{$date=self::date($date);self::seedChecks($userId,$date);return Database::fetchAll('SELECT id,title,is_checked,sort_order FROM personal_planner_checks WHERE user_id=? AND check_date=? AND deleted_at IS NULL ORDER BY sort_order,id',[$userId,$date]);}
    public static function addCheck(int $userId,string $date,string $title):void{$date=self::date($date);$sort=(int)(Database::fetch('SELECT COALESCE(MAX(sort_order),0)+10 n FROM personal_planner_checks WHERE user_id=? AND check_date=?',[$userId,$date])['n']??10);Database::execute('INSERT INTO personal_planner_checks(user_id,check_date,title,sort_order,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())',[$userId,$date,self::title($title),$sort]);}
    public static function updateCheck(int $userId,int $id,string $title):void{self::owned('personal_planner_checks',$userId,$id);Database::execute('UPDATE personal_planner_checks SET title=?,updated_at=NOW() WHERE id=? AND user_id=?',[self::title($title),$id,$userId]);}
    public static function toggleCheck(int $userId,int $id):void{self::owned('personal_planner_checks',$userId,$id);Database::execute('UPDATE personal_planner_checks SET is_checked=1-is_checked,updated_at=NOW() WHERE id=? AND user_id=?',[$id,$userId]);}
    public static function deleteCheck(int $userId,int $id):void{self::owned('personal_planner_checks',$userId,$id);Database::execute('UPDATE personal_planner_checks SET deleted_at=NOW(),updated_at=NOW() WHERE id=? AND user_id=?',[$id,$userId]);}
    public static function reorderTasks(int $userId,array $ids):void{$sort=10;foreach(array_slice(array_map('intval',$ids),0,200) as $id){Database::execute('UPDATE personal_planner_tasks SET sort_order=?,updated_at=NOW() WHERE id=? AND user_id=? AND deleted_at IS NULL',[$sort,$id,$userId]);$sort+=10;}}
    public static function generateDueNotifications(int $userId):int
    {
        Database::execute('UPDATE personal_planner_tasks SET status="overdue",updated_at=NOW() WHERE user_id=? AND task_date<CURDATE() AND status="todo" AND deleted_at IS NULL',[$userId]);if(!(int)(self::settings($userId)['notifications_enabled']??0))return 0;$tasks=Database::fetchAll('SELECT * FROM personal_planner_tasks WHERE user_id=? AND reminder_enabled=1 AND reminder_at<=NOW() AND notification_sent_at IS NULL AND status<>"done" AND deleted_at IS NULL',[$userId]);foreach($tasks as $t){Database::execute('INSERT IGNORE INTO personal_planner_notifications(user_id,task_id,notification_type,title,message,scheduled_at,status,created_at,updated_at) VALUES(?,?,"reminder",?,?,?,"pending",NOW(),NOW())',[$userId,(int)$t['id'],'یادآوری برنامه کاری',(string)$t['title'],$t['reminder_at']]);}return count($tasks);
    }
    public static function dueNotifications(int $userId):array{return Database::fetchAll('SELECT n.id,n.task_id,n.title,n.message,n.scheduled_at FROM personal_planner_notifications n WHERE n.user_id=? AND n.status="pending" AND n.scheduled_at<=NOW() ORDER BY n.scheduled_at LIMIT 20',[$userId]);}
    public static function markNotificationSent(int $userId,int $id):void{$n=Database::fetch('SELECT * FROM personal_planner_notifications WHERE id=? AND user_id=?',[$id,$userId]);if(!$n)throw new DomainException('یادآوری پیدا نشد.');Database::execute('UPDATE personal_planner_notifications SET status="sent",sent_at=NOW(),updated_at=NOW() WHERE id=? AND user_id=?',[$id,$userId]);if($n['task_id'])Database::execute('UPDATE personal_planner_tasks SET notification_sent_at=NOW() WHERE id=? AND user_id=?',[(int)$n['task_id'],$userId]);}
    public static function processNotifications(?int $userId=null,int $limit=100):array
    {
        $params=[];$where='';if($userId){$where=' AND n.user_id=?';$params[]=$userId;}$rows=Database::fetchAll('SELECT n.* FROM personal_planner_notifications n WHERE n.status="pending" AND n.scheduled_at<=NOW()'.$where.' ORDER BY n.id LIMIT '.max(1,min(500,$limit)),$params);$sent=0;foreach($rows as $n){try{NotificationService::notifyPlannerReminder((int)$n['user_id'],(int)$n['task_id'],(string)$n['message'],substr((string)$n['scheduled_at'],0,10));Database::execute('UPDATE personal_planner_notifications SET status="sent",sent_at=NOW(),updated_at=NOW() WHERE id=?',[(int)$n['id']]);Database::execute('UPDATE personal_planner_tasks SET notification_sent_at=NOW() WHERE id=?',[(int)$n['task_id']]);$sent++;}catch(Throwable $e){error_log('Planner notification '.$n['id'].': '.$e->getMessage());Database::execute('UPDATE personal_planner_notifications SET status="error",error_message=?,updated_at=NOW() WHERE id=?',[substr($e->getMessage(),0,1000),(int)$n['id']]);}}return ['processed'=>count($rows),'sent'=>$sent];
    }
    public static function runMaintenance(int $limit=200):array
    { $users=array_map('intval',array_column(Database::fetchAll('SELECT id FROM users WHERE status="active" ORDER BY id LIMIT '.max(1,min(5000,$limit))),'id'));$generated=0;foreach($users as $uid)$generated+=self::generateDueNotifications($uid);$recurring=Database::fetchAll('SELECT id,user_id FROM personal_planner_tasks t WHERE t.is_recurring=1 AND t.status="done" AND t.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM personal_planner_tasks n WHERE n.parent_task_id=COALESCE(t.parent_task_id,t.id) AND n.user_id=t.user_id AND n.task_date>t.task_date AND n.deleted_at IS NULL) ORDER BY t.id LIMIT 500');foreach($recurring as $task){try{self::createNextRecurringTask((int)$task['user_id'],(int)$task['id']);}catch(Throwable $e){error_log('Planner recurring '.$task['id'].': '.$e->getMessage());}}$notifications=self::processNotifications(null,500);return ['users'=>count($users),'generated'=>$generated,'recurring_checked'=>count($recurring),'notifications'=>$notifications]; }
    public static function report(int $userId,string $from,string $to):array
    {
        $from=self::date($from);$to=self::date($to);if($to<$from)throw new InvalidArgumentException('بازه گزارش معتبر نیست.');$tasks=Database::fetchAll('SELECT * FROM personal_planner_tasks WHERE user_id=? AND task_date BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY task_date,id',[$userId,$from,$to]);$days=[];foreach($tasks as $t){$days[$t['task_date']][]=$t;}$daily=[];foreach($days as $date=>$list){$done=count(array_filter($list,fn($x)=>$x['status']==='done'));$daily[]=['date'=>$date,'date_jalali'=>JalaliDate::toJalali($date),'total'=>count($list),'done'=>$done,'overdue'=>count(array_filter($list,fn($x)=>$x['status']==='overdue')),'moved'=>count(array_filter($list,fn($x)=>!empty($x['moved_to_date']))),'percent'=>count($list)?round($done*100/count($list)):0];}$total=count($tasks);$done=count(array_filter($tasks,fn($x)=>$x['status']==='done'));$ranked=$daily;usort($ranked,fn($a,$b)=>$b['percent']<=>$a['percent']);return ['from'=>$from,'to'=>$to,'tasks'=>$tasks,'total'=>$total,'done'=>$done,'todo'=>$total-$done,'overdue'=>count(array_filter($tasks,fn($x)=>$x['status']==='overdue')),'moved'=>count(array_filter($tasks,fn($x)=>!empty($x['moved_to_date']))),'recurring_done'=>count(array_filter($tasks,fn($x)=>(int)$x['is_recurring']&&$x['status']==='done')),'percent'=>$total?round($done*100/$total):0,'best_day'=>$ranked[0]??null,'worst_day'=>$ranked?end($ranked):null,'daily'=>$daily];
    }
    public static function canAccessTask(int $userId,int $id):bool{return (bool)Database::fetch('SELECT id FROM personal_planner_tasks WHERE id=? AND user_id=? AND deleted_at IS NULL',[$id,$userId]);}
    public static function logAction(int $userId,?int $taskId,string $action,mixed $old,mixed $new):void{Database::execute('INSERT INTO personal_planner_logs(user_id,task_id,action,old_value_json,new_value_json,created_at) VALUES(?,?,?,?,?,NOW())',[$userId,$taskId,$action,$old===null?null:json_encode($old,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$new===null?null:json_encode($new,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}
    private static function task(int $userId,int $id):array{$row=Database::fetch('SELECT * FROM personal_planner_tasks WHERE id=? AND user_id=? AND deleted_at IS NULL',[$id,$userId]);if(!$row)throw new DomainException('این کار پیدا نشد یا متعلق به حساب شما نیست.');return $row;}
    private static function owned(string $table,int $userId,int $id):void{if(!in_array($table,['personal_planner_checks'],true)||!Database::fetch("SELECT id FROM `{$table}` WHERE id=? AND user_id=? AND deleted_at IS NULL",[$id,$userId]))throw new DomainException('این مورد پیدا نشد یا متعلق به حساب شما نیست.');}
    private static function taskOptions(array $o,string $date):array{$types=['daily','weekly','monthly','yearly','weekdays','interval'];$type=in_array($o['recurrence_type']??'', $types,true)?$o['recurrence_type']:null;$due=self::datetime($o['due_at']??null);$reminder=self::datetime($o['reminder_at']??null);$days=preg_replace('/[^0-6,]/','',(string)($o['recurrence_days']??''));$end=trim((string)($o['recurrence_end_date']??''));$end=$end===''?null:self::date($end);$monthDay=trim((string)($o['recurrence_month_day']??''));$monthDay=$monthDay===''?(int)substr($date,8,2):(int)$monthDay;return ['description'=>self::text($o['description']??'',5000),'due_at'=>$due,'priority'=>in_array($o['priority']??'normal',['low','normal','high','urgent'],true)?$o['priority']:'normal','is_important'=>!empty($o['is_important'])?1:0,'is_recurring'=>!empty($o['is_recurring'])&&$type?1:0,'recurrence_type'=>$type,'recurrence_interval'=>max(1,min(365,(int)($o['recurrence_interval']??1))),'recurrence_days'=>$days?:null,'recurrence_month_day'=>max(1,min(31,$monthDay)),'recurrence_end_date'=>$end,'parent_task_id'=>(int)($o['parent_task_id']??0)?:null,'reminder_enabled'=>!empty($o['reminder_enabled'])&&$reminder?1:0,'reminder_at'=>$reminder];}
    private static function nextDate(array $t):?string{$d=new DateTimeImmutable($t['task_date']);$n=max(1,(int)($t['recurrence_interval']??1));return match($t['recurrence_type']){'daily'=>$d->modify("+{$n} days")->format('Y-m-d'),'weekly'=>$d->modify("+{$n} weeks")->format('Y-m-d'),'monthly'=>self::nextMonthly($d,$n,(int)($t['recurrence_month_day']??$d->format('j'))),'yearly'=>$d->modify("+{$n} years")->format('Y-m-d'),'interval'=>$d->modify("+{$n} days")->format('Y-m-d'),'weekdays'=>self::nextWeekday($d,(string)$t['recurrence_days']),default=>null};}
    private static function nextMonthly(DateTimeImmutable $d,int $months,int $day):string{$first=$d->modify('first day of this month')->modify("+{$months} months");$last=(int)$first->format('t');return $first->setDate((int)$first->format('Y'),(int)$first->format('m'),min(max(1,$day),$last))->format('Y-m-d');}
    private static function nextWeekday(DateTimeImmutable $d,string $days):string{$allowed=array_map('intval',array_filter(explode(',',$days),'strlen'));if(!$allowed)$allowed=[0,1,2,3,4,5,6];for($i=1;$i<=14;$i++){$x=$d->modify("+{$i} days");if(in_array((int)$x->format('w'),$allowed,true))return $x->format('Y-m-d');}return $d->modify('+1 week')->format('Y-m-d');}
    private static function seedChecks(int $userId,string $date):void{if(Database::fetch('SELECT id FROM personal_planner_checks WHERE user_id=? AND check_date=? LIMIT 1',[$userId,$date]))return;$items=['بررسی پیام‌ها','پیگیری کارهای عقب‌افتاده','ثبت گزارش روزانه','بررسی برنامه فردا'];foreach($items as $i=>$title)Database::execute('INSERT INTO personal_planner_checks(user_id,check_date,title,sort_order,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())',[$userId,$date,$title,($i+1)*10]);}
    private static function seedSuggestedTasks(int $userId,array $user):void{$s=self::settings($userId);if(!empty($s['seeded_suggestions_at']))return;$role=self::lower(implode(' ',[$user['role_key']??'',$user['department']??'',$user['role']??'']));$sets=['it'=>['بررسی بکاپ','بررسی سلامت سرور','رسیدگی به تیکت‌ها','بررسی اینترنت و شبکه','ثبت تغییرات سیستم'],'visitor'=>['بررسی مسیر امروز','ثبت ویزیت‌ها','پیگیری مشتریان','ثبت سفارش‌ها','ارسال گزارش پایان روز'],'supervisor'=>['بررسی عملکرد ویزیتورها','کنترل پوشش مسیر','پیگیری وصولی تیم','ارسال گزارش تیم','پیگیری مشکلات مشتریان'],'manager'=>['بررسی فروش روزانه','تحلیل تحقق تارگت','پیگیری سرپرستان','بررسی تخفیفات','ثبت برنامه عملیاتی'],'finance'=>['بررسی اسناد','پیگیری چک‌ها','مغایرت‌گیری','ثبت وصولی‌ها','گزارش حساب‌های باز'],'warehouse'=>['کنترل ورودی کالا','بررسی مغایرت موجودی','کنترل آماده‌سازی سفارش‌ها','بررسی کالاهای نزدیک انقضا','گزارش ضایعات']];$key=match(true){self::contains($role,['it','فناوری','شبکه'])=>'it',self::contains($role,['visitor','ویزیتور'])=>'visitor',self::contains($role,['supervisor','سرپرست'])=>'supervisor',self::contains($role,['sales_manager','مدیر فروش'])=>'manager',self::contains($role,['finance','account','مالی'])=>'finance',self::contains($role,['warehouse','انبار'])=>'warehouse',default=>null};if($key)foreach($sets[$key] as $title)self::addTask($userId,$title,date('Y-m-d'));Database::execute('UPDATE personal_planner_settings SET seeded_suggestions_at=NOW(),updated_at=NOW() WHERE user_id=?',[$userId]);}
    private static function applyUnfinishedBehavior(int $userId):void{$s=self::settings($userId);if(($s['unfinished_behavior']??'')==='auto_move'){Database::execute('UPDATE personal_planner_tasks SET moved_from_date=task_date,moved_to_date=DATE_ADD(CURDATE(),INTERVAL 1 DAY),task_date=DATE_ADD(CURDATE(),INTERVAL 1 DAY),status="todo",updated_at=NOW() WHERE user_id=? AND task_date<CURDATE() AND status IN("todo","overdue") AND deleted_at IS NULL',[$userId]);}}
    private static function date(string $v):string{$v=trim($v);if(str_contains($v,'/'))$v=JalaliDate::toGregorian($v)??'';$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new InvalidArgumentException('تاریخ معتبر نیست.');return $v;}
    private static function datetime(mixed $v):?string{$v=trim((string)$v);if($v==='')return null;$v=str_replace('T',' ',$v);$d=DateTimeImmutable::createFromFormat('Y-m-d H:i',$v)?:DateTimeImmutable::createFromFormat('Y-m-d H:i:s',$v);if(!$d)throw new InvalidArgumentException('زمان یادآوری یا موعد معتبر نیست.');return $d->format('Y-m-d H:i:s');}
    private static function title(string $v):string{$v=trim(preg_replace('/\s+/u',' ',$v)??$v);if($v===''||self::length($v)>255)throw new InvalidArgumentException('عنوان باید بین ۱ تا ۲۵۵ نویسه باشد.');return $v;}
    private static function text(mixed $v,int $max):string{$v=trim(strip_tags((string)$v));return function_exists('mb_substr')?mb_substr($v,0,$max,'UTF-8'):substr($v,0,$max);}
    private static function length(string $v):int{return function_exists('mb_strlen')?mb_strlen($v,'UTF-8'):strlen($v);}private static function lower(string $v):string{return function_exists('mb_strtolower')?mb_strtolower($v,'UTF-8'):strtolower($v);}private static function contains(string $v,array $n):bool{foreach($n as $x)if(str_contains($v,$x))return true;return false;}
}
