<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Database.php';require_once __DIR__.'/../lib/NotificationService.php';
final class TicketService
{
    public const STATUSES=['open'=>'باز','assigned'=>'ارجاع‌شده','in_progress'=>'در حال انجام','waiting_user'=>'در انتظار کاربر','waiting_admin'=>'در انتظار پشتیبانی','resolved'=>'حل‌شده','closed'=>'بسته','cancelled'=>'لغوشده'];
    public const PRIORITIES=['low'=>'کم','normal'=>'عادی','high'=>'بالا','urgent'=>'فوری'];
    public static function canManage():bool{return Auth::isAdmin()||Auth::can('ticketing.manage','edit');}
    public static function categories(bool $activeOnly=true):array{return Database::fetchAll('SELECT c.*,u.title unit_title,a.name assignee_name FROM ticket_categories c LEFT JOIN org_units u ON u.id=c.assigned_unit_id LEFT JOIN users a ON a.id=c.default_assignee_user_id'.($activeOnly?' WHERE c.active=1':'').' ORDER BY c.sort_order,c.title');}
    public static function list(array $filters=[]):array
    {
        $user=Auth::user();if(!$user)return [];$where=[];$params=[];if(!self::canManage()){$where[]='(t.requester_user_id=? OR t.assigned_user_id=?)';$params[]=(int)$user['id'];$params[]=(int)$user['id'];}
        foreach(['status'=>'t.status','priority'=>'t.priority','category_id'=>'t.category_id','assigned_user_id'=>'t.assigned_user_id'] as $key=>$column)if(trim((string)($filters[$key]??''))!==''){$where[]="$column=?";$params[]=$filters[$key];}
        return Database::fetchAll('SELECT t.*,c.title category_title,r.name requester_name,a.name assignee_name,u.title unit_title FROM tickets t JOIN ticket_categories c ON c.id=t.category_id JOIN users r ON r.id=t.requester_user_id LEFT JOIN users a ON a.id=t.assigned_user_id LEFT JOIN org_units u ON u.id=t.assigned_unit_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY FIELD(t.status,"open","assigned","in_progress","waiting_admin","waiting_user","resolved","closed","cancelled"),FIELD(t.priority,"urgent","high","normal","low"),COALESCE(t.due_at,"9999-12-31"),t.id DESC',$params);
    }
    public static function find(int $id):?array
    {
        $rows=self::list();foreach($rows as $row)if((int)$row['id']===$id){$row['messages']=Database::fetchAll('SELECT m.*,u.name user_name FROM ticket_messages m JOIN users u ON u.id=m.user_id WHERE m.ticket_id=?'.(self::canManage()?'':' AND m.is_internal=0').' ORDER BY m.id',[$id]);$row['attachments']=Database::fetchAll('SELECT * FROM ticket_attachments WHERE ticket_id=? ORDER BY id',[$id]);$row['logs']=Database::fetchAll('SELECT l.*,u.name actor_name FROM ticket_status_logs l LEFT JOIN users u ON u.id=l.actor_user_id WHERE l.ticket_id=? ORDER BY l.id DESC',[$id]);return $row;}return null;
    }
    public static function create(array $input,int $userId):int
    {
        $subject=self::text($input['subject']??'',255);$message=self::text($input['message']??'',20000);$categoryId=(int)($input['category_id']??0);$category=Database::fetch('SELECT * FROM ticket_categories WHERE id=? AND active=1',[$categoryId]);if($subject===''||$message===''||!$category)throw new InvalidArgumentException('عنوان، متن و دسته‌بندی معتبر الزامی است.');
        $priority=in_array($input['priority']??'',array_keys(self::PRIORITIES),true)?$input['priority']:'normal';$assigned=(int)($category['default_assignee_user_id']??0)?:null;$unit=(int)($category['assigned_unit_id']??0)?:null;$status=$assigned?'assigned':'open';$sla=Database::fetch('SELECT resolution_minutes FROM ticket_sla_rules WHERE active=1 AND priority=? AND (category_id=? OR category_id IS NULL) ORDER BY category_id IS NULL LIMIT 1',[$priority,$categoryId]);$due=$sla?date('Y-m-d H:i:s',time()+(int)$sla['resolution_minutes']*60):null;
        $pdo=Database::connection();$pdo->beginTransaction();try{Database::execute('INSERT INTO tickets(subject,category_id,priority,requester_user_id,assigned_user_id,assigned_unit_id,due_at,status,last_message_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?, ?,NOW(),NOW(),NOW())',[$subject,$categoryId,$priority,$userId,$assigned,$unit,$due,$status]);$id=(int)Database::lastInsertId();$number='T-'.date('ym').'-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);Database::execute('UPDATE tickets SET ticket_no=? WHERE id=?',[$number,$id]);Database::execute('INSERT INTO ticket_messages(ticket_id,user_id,message,is_internal,created_at) VALUES(?,?,?,0,NOW())',[$id,$userId,$message]);Database::execute('INSERT INTO ticket_status_logs(ticket_id,actor_user_id,old_status,new_status,note,created_at) VALUES(?,?,NULL,?,"ایجاد تیکت",NOW())',[$id,$userId,$status]);if($assigned||$unit)Database::execute('INSERT INTO ticket_assignments(ticket_id,assigned_user_id,assigned_unit_id,assigned_by,note,created_at) VALUES(?,?,?, ?,"ارجاع خودکار بر اساس دسته‌بندی",NOW())',[$id,$assigned,$unit,$userId]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
        $recipients=$assigned?[$assigned]:self::responsibleUsers($unit);foreach(array_values(array_unique(array_filter($recipients,static fn($target)=>(int)$target!==$userId))) as $target)self::notify(static fn()=>NotificationService::notifyTicketAssigned((int)$target,$id,$subject));Auth::log($userId,'ticket_created','tickets',$id);return $id;
    }
    public static function reply(int $id,string $message,int $userId,bool $internal=false):int
    {
        $ticket=self::find($id);if(!$ticket)throw new DomainException('تیکت در دسترس نیست.');if($internal&&!self::canManage())throw new DomainException('یادداشت داخلی مجاز نیست.');$message=self::text($message,20000);if($message==='')throw new InvalidArgumentException('متن پاسخ الزامی است.');Database::execute('INSERT INTO ticket_messages(ticket_id,user_id,message,is_internal,created_at) VALUES(?,?,?,?,NOW())',[$id,$userId,$message,$internal?1:0]);$messageId=(int)Database::lastInsertId();Database::execute('UPDATE tickets SET last_message_at=NOW(),status=IF(status IN("resolved","closed"),status,?),updated_at=NOW() WHERE id=?',[$userId===(int)$ticket['requester_user_id']?'waiting_admin':'waiting_user',$id]);if(!$internal){$target=$userId===(int)$ticket['requester_user_id']?(int)($ticket['assigned_user_id']??0):(int)$ticket['requester_user_id'];if($target&&$target!==$userId)self::notify(static fn()=>NotificationService::notifyTicketReply($target,$id,$ticket['subject']));}Auth::log($userId,'ticket_reply','tickets',$id);return $messageId;
    }
    public static function manage(int $id,array $input,int $actorId):void
    {
        if(!self::canManage())throw new DomainException('مدیریت تیکت مجاز نیست.');$ticket=self::find($id);if(!$ticket)throw new DomainException('تیکت پیدا نشد.');$status=in_array($input['status']??'',array_keys(self::STATUSES),true)?$input['status']:$ticket['status'];$assigned=(int)($input['assigned_user_id']??0)?:null;$unit=(int)($input['assigned_unit_id']??0)?:null;$due=trim((string)($input['due_at']??''))?:null;$pdo=Database::connection();$pdo->beginTransaction();try{Database::execute('UPDATE tickets SET status=?,assigned_user_id=?,assigned_unit_id=?,due_at=?,resolved_at=IF(?="resolved",COALESCE(resolved_at,NOW()),resolved_at),closed_at=IF(?="closed",COALESCE(closed_at,NOW()),closed_at),updated_at=NOW() WHERE id=?',[$status,$assigned,$unit,$due,$status,$status,$id]);if($status!==$ticket['status'])Database::execute('INSERT INTO ticket_status_logs(ticket_id,actor_user_id,old_status,new_status,note,created_at) VALUES(?,?,?,?,?,NOW())',[$id,$actorId,$ticket['status'],$status,self::text($input['note']??'',2000)]);if($assigned!==(int)($ticket['assigned_user_id']??0)||$unit!==(int)($ticket['assigned_unit_id']??0)){Database::execute('UPDATE ticket_assignments SET ended_at=COALESCE(ended_at,NOW()) WHERE ticket_id=? AND ended_at IS NULL',[$id]);Database::execute('INSERT INTO ticket_assignments(ticket_id,assigned_user_id,assigned_unit_id,assigned_by,note,created_at) VALUES(?,?,?,?,?,NOW())',[$id,$assigned,$unit,$actorId,self::text($input['note']??'',2000)]);}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}if($assigned&&$assigned!==(int)($ticket['assigned_user_id']??0))self::notify(static fn()=>NotificationService::notifyTicketReassigned($assigned,$id,$ticket['subject']));if($status!==$ticket['status'])self::notify(static fn()=>NotificationService::notifyTicketStatusChanged((int)$ticket['requester_user_id'],$id,self::STATUSES[$status]));
    }
    public static function addAttachment(int $ticketId,int $messageId,int $userId,array $file):void{Database::execute('INSERT INTO ticket_attachments(ticket_id,message_id,uploaded_by,original_name,file_path,mime_type,file_size,created_at) VALUES(?,?,?,?,?,?,?,NOW())',[$ticketId,$messageId?:null,$userId,$file['original_name'],$file['file_path'],$file['mime_type'],$file['file_size']]);}
    private static function responsibleUsers(?int $unitId):array{$params=[];$unitSql='';if($unitId){$unitSql=' OR (u.org_unit_id=? AND p.can_view=1)';$params[]=$unitId;}return array_map('intval',array_column(Database::fetchAll('SELECT DISTINCT u.id FROM users u LEFT JOIN user_permissions p ON p.user_id=u.id AND p.module_key="ticketing.manage" WHERE u.status="active" AND (u.role IN("super_admin","admin") OR (p.module_key IS NOT NULL AND (p.can_view=1 OR p.can_edit=1))'.$unitSql.')',$params),'id'));}
    private static function notify(callable $callback):void{try{$notificationId=$callback();if(!$notificationId)error_log('Ticket notification was not created.');}catch(Throwable $e){error_log('Ticket notification: '.$e->getMessage());}}
    private static function text(mixed $value,int $max):string{$value=trim(strip_tags((string)$value));return mb_substr($value,0,$max);}
}
