using System.Text.Json.Serialization;
namespace SobhanNotificationHub.Models;
public sealed class ApiResult<T>{[JsonPropertyName("success")]public bool Success{get;set;}[JsonPropertyName("data")]public T? Data{get;set;}[JsonPropertyName("error")]public ApiError? Error{get;set;}[JsonPropertyName("meta")]public ApiMeta? Meta{get;set;}}
public sealed class ApiError{[JsonPropertyName("code")]public string Code{get;set;}="";[JsonPropertyName("message")]public string Message{get;set;}="";}public sealed class ApiMeta{[JsonPropertyName("next_poll_seconds")]public int NextPollSeconds{get;set;}=20;}
public sealed class ClientConfig{[JsonPropertyName("user")]public ClientUser User{get;set;}=new();[JsonPropertyName("client")]public ClientOptions Client{get;set;}=new();[JsonPropertyName("modules")]public Dictionary<string,ModuleOptions> Modules{get;set;}=new();}
public sealed class ClientUser{[JsonPropertyName("id")]public int Id{get;set;}[JsonPropertyName("display_name")]public string DisplayName{get;set;}="";[JsonPropertyName("role")]public string Role{get;set;}="";[JsonPropertyName("unit")]public string Unit{get;set;}="";}
public sealed class ClientOptions{[JsonPropertyName("poll_seconds")]public int PollSeconds{get;set;}=20;[JsonPropertyName("enable_sound")]public bool EnableSound{get;set;}=true;[JsonPropertyName("enable_quick_reply")]public bool EnableQuickReply{get;set;}[JsonPropertyName("enable_action_buttons")]public bool EnableActionButtons{get;set;}[JsonPropertyName("max_notifications_per_poll")]public int MaxNotificationsPerPoll{get;set;}=20;[JsonPropertyName("silent_hours_enabled")]public bool SilentHoursEnabled{get;set;}[JsonPropertyName("silent_hours_from")]public string? SilentFrom{get;set;}[JsonPropertyName("silent_hours_to")]public string? SilentTo{get;set;}}
public sealed class ModuleOptions{[JsonPropertyName("enabled")]public bool Enabled{get;set;}=true;[JsonPropertyName("show_body")]public bool ShowBody{get;set;}=true;[JsonPropertyName("sound")]public string Sound{get;set;}="default";[JsonPropertyName("priority")]public string Priority{get;set;}="normal";[JsonPropertyName("allow_quick_reply")]public bool AllowQuickReply{get;set;}[JsonPropertyName("direct_action_enabled")]public bool DirectActionEnabled{get;set;}}
public sealed class SobhanNotification{[JsonPropertyName("id")]public long Id{get;set;}[JsonPropertyName("module")]public string Module{get;set;}="system";[JsonPropertyName("type")]public string Type{get;set;}="general";[JsonPropertyName("priority")]public string Priority{get;set;}="normal";[JsonPropertyName("title")]public string Title{get;set;}="";[JsonPropertyName("body")]public string Body{get;set;}="";[JsonPropertyName("safe_body")]public string SafeBody{get;set;}="";[JsonPropertyName("sender_name")]public string? SenderName{get;set;}[JsonPropertyName("action_url")]public string? ActionUrl{get;set;}[JsonPropertyName("actions")]public List<NotificationAction> Actions{get;set;}=[];[JsonPropertyName("created_at")]public string CreatedAt{get;set;}="";}
public sealed class NotificationAction{[JsonPropertyName("id")]public string Id{get;set;}="";[JsonPropertyName("label")]public string Label{get;set;}="";}
public sealed class DeviceCredentials{public string DeviceUid{get;set;}="";public string DeviceToken{get;set;}="";}public sealed class PairResult{[JsonPropertyName("device_uid")]public string DeviceUid{get;set;}="";[JsonPropertyName("device_token")]public string DeviceToken{get;set;}="";}
