<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Database.php';
class DocsAccessService
{
    public static function canView(array $doc,?array $user=null): bool{$user??=Auth::user()?:[];if(!$user)return false;if(in_array($user['role']??'',['admin','super_admin'],true))return true;if(!(int)($doc['active']??0))return false;$scope=$doc['visibility_scope']??'all';if($scope==='all')return true;$map=['units'=>['allowed_units_json','org_unit_id'],'roles'=>['allowed_roles_json','org_role_id'],'users'=>['allowed_users_json','id']];if(!isset($map[$scope]))return false;[$json,$field]=$map[$scope];$allowed=array_map('intval',json_decode($doc[$json]?:'[]',true)?:[]);return in_array((int)($user[$field]??0),$allowed,true);}
    public static function requireDoc(int $id): array{Auth::requireLogin();$doc=Database::fetch('SELECT a.*,c.title category_title,u.name creator_name FROM docs_articles a LEFT JOIN docs_categories c ON c.id=a.category_id LEFT JOIN users u ON u.id=a.created_by WHERE a.id=?',[$id]);if(!$doc||!self::canView($doc)){http_response_code(404);throw new RuntimeException('doc_not_available');}return $doc;}
    public static function logRead(int $docId,bool $confirm=false): void{$user=Auth::user();if(!$user)return;Database::execute('INSERT INTO docs_read_logs(doc_id,user_id,read_at,confirmed_at,ip_address,user_agent) VALUES(?,?,NOW(),'.($confirm?'NOW()':'NULL').',?,?) ON DUPLICATE KEY UPDATE read_at=COALESCE(read_at,NOW()),confirmed_at='.($confirm?'NOW()':'confirmed_at'),[$docId,(int)$user['id'],substr((string)($_SERVER['REMOTE_ADDR']??''),0,45),substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255)]);}
    public static function sanitize(?string $html): string{$html=trim((string)$html);if(strlen($html)>5000000)throw new InvalidArgumentException('حجم متن مستند بیش از حد مجاز است.');$html=preg_replace('#<(script|style|iframe|object|embed|form|input|button|textarea|select|meta|link|base)[^>]*>.*?</\\1>#is','',$html)??'';$html=preg_replace('/\\son[a-z]+\\s*=\\s*("[^"]*"|\'[^\']*\'|[^\\s>]+)/iu','',$html)??'';$html=preg_replace('/\\s(href|src)\\s*=\\s*(["\'])\\s*(javascript:|vbscript:|data:text\\/html)[^"\']*\\2/iu','',$html)??'';return strip_tags($html,'<p><br><div><span><strong><b><em><i><u><s><h1><h2><h3><h4><blockquote><ul><ol><li><table><thead><tbody><tfoot><tr><th><td><img><hr><sub><sup><a><pre><code>');}
}
