<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Database.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/SobhanApiClient.php';Auth::requirePermission('ai_insights');$pageTitle='تحلیل هوشمند و منابع گزارشی';$notice='';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Auth::verifyCsrf($_POST['csrf_token']??'')){http_response_code(419);exit('درخواست نامعتبر است.');}$action=$_POST['action']??'';try{if($action==='save')foreach(Database::fetchAll('SELECT id FROM ai_reporting_sources') as $source)Database::execute('UPDATE ai_reporting_sources SET source_name=?,connection_label=?,description=?,active=?,updated_at=NOW() WHERE id=?',[trim($_POST['source_name'][$source['id']]??''),trim($_POST['connection_label'][$source['id']]??''),trim($_POST['description'][$source['id']]??''),isset($_POST['active'][$source['id']])?1:0,$source['id']]);elseif($action==='test'){$test=(new SobhanApiClient())->get('/health');$notice=$test['ok']?'اتصال به سرویس گزارش‌گیری با موفقیت برقرار شد.':'اتصال به سرویس گزارش‌گیری برقرار نشد.';if(!$test['ok'])throw new RuntimeException('connection_failed');}if($action==='save')flash('عملیات با موفقیت انجام شد.');}catch(Throwable $e){if($notice==='')$notice='خطا در ذخیره‌سازی اطلاعات. لطفاً مجدد تلاش کنید.';error_log('AI insight source: '.$e->getMessage());}if($action==='save')redirect('/admin/ai-insights.php');}
$sources=Database::fetchAll('SELECT * FROM ai_reporting_sources ORDER BY id');$outputs=['فروش امروز / این ماه','تحقق تارگت','فروش بر اساس ویزیتور','فروش بر اساس کالا','مشتریان بدون خرید اخیر','وضعیت موجودی','خلاصه مطالبات'];require __DIR__.'/../views/partials/admin-header.php';?>
<?php if($notice):?><div class="alert <?=str_contains($notice,'موفقیت')?'alert-success':'alert-danger'?>"><?=e($notice)?></div><?php endif?>
<section class="card"><div class="section-heading-row"><div><h1>منابع امن تحلیل AI</h1><p class="muted">هوش مصنوعی فقط مجاز به خواندن reporting viewهای تاییدشده است و نباید به جدول‌های خام ERP یا عملیات نوشتن دسترسی داشته باشد.</p></div><a class="btn" href="/admin/sobhan-api-settings.php">تنظیمات Sobhan API</a></div><div class="actions"><?php foreach($outputs as $output):?><span class="badge"><?=e($output)?></span><?php endforeach?></div></section>
<form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="save"><div class="table-wrap"><table><thead><tr><th>View</th><th>عنوان</th><th>برچسب اتصال</th><th>توضیح</th><th>فعال</th></tr></thead><tbody><?php foreach($sources as $s):?><tr><td><code><?=e($s['view_name'])?></code></td><td><input name="source_name[<?=$s['id']?>]" value="<?=e($s['source_name'])?>"></td><td><input name="connection_label[<?=$s['id']?>]" value="<?=e($s['connection_label'])?>"></td><td><input name="description[<?=$s['id']?>]" value="<?=e($s['description'])?>"></td><td><input type="checkbox" name="active[<?=$s['id']?>]" <?=$s['active']?'checked':''?>></td></tr><?php endforeach?></tbody></table></div><button class="btn btn-primary">ذخیره منابع</button></form>
<form class="card" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><button class="btn" name="action" value="test">تست اتصال خواندنی</button><p class="muted">این تست هیچ داده ERP یا داشبوردی ارسال نمی‌کند.</p></form>
</section></main></div><script src="/assets/js/app.js"></script></body></html>
