<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../lib/HrAttendanceRepository.php';
Auth::requireLogin();if(!HrAttendanceRepository::canSettings()){http_response_code(403);exit('دسترسی غیرمجاز');}$user=Auth::user();
if($_SERVER['REQUEST_METHOD']==='POST'){try{if(!Auth::verifyCsrf($_POST['csrf_token']??null))throw new DomainException('اعتبار فرم منقضی شده است.');HrAttendanceRepository::saveSettings($_POST,(int)$user['id']);flash('نسخه جدید ساعات کاری با موفقیت ثبت شد.');}catch(InvalidArgumentException|DomainException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('HR attendance settings: '.$e->getMessage());flash('ذخیره تنظیمات ساعات کاری انجام نشد.','danger');}redirect('/admin/hr-attendance-settings.php');}
$groups=HrAttendanceRepository::groups();$latest=HrAttendanceRepository::latestSettings();$history=HrAttendanceRepository::settingsHistory();$pageTitle='تنظیمات ساعات کاری';$adminExtraStylesheets=['/assets/css/hr-attendance.css'];require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="attendance-page"><header class="attendance-hero"><div><small>منابع انسانی</small><h1>تنظیمات ساعات کاری</h1><p>نسخه‌بندی بازه‌های مصوب فروش و اداری/انبار</p></div></header><?php require __DIR__.'/includes/hr-attendance-nav.php';?>
<section class="attendance-settings-grid"><?php foreach($groups as $group):$item=$latest[$group['code']]??[];?><article class="card"><h2><?=e($group['title'])?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="work_group_id" value="<?=e((string)$group['id'])?>"><label>شروع اجرا<input class="jalali-date-input" name="effective_from" required value="<?=e(JalaliDate::toJalali(date('Y-m-d')))?>"></label><label>پایان اجرا<input class="jalali-date-input" name="effective_to" placeholder="بدون پایان"></label><label>ساعت ورود مصوب<input type="time" name="default_start_time" required value="<?=e(substr($item['default_start_time']??'08:00',0,5))?>"></label><label>ساعت خروج مصوب<input type="time" name="default_end_time" required value="<?=e(substr($item['default_end_time']??'16:00',0,5))?>"></label><label>تلورانس تأخیر (دقیقه)<input type="number" name="late_tolerance_minutes" min="0" max="180" value="<?=e((string)($item['late_tolerance_minutes']??0))?>"></label><label>تلورانس تعجیل (دقیقه)<input type="number" name="early_leave_tolerance_minutes" min="0" max="180" value="<?=e((string)($item['early_leave_tolerance_minutes']??0))?>"></label><label>شروع بازه مجاز ورود<input type="time" name="allowed_checkin_from" value="<?=e(substr($item['allowed_checkin_from']??'',0,5))?>"></label><label>پایان بازه مجاز ورود<input type="time" name="allowed_checkin_to" value="<?=e(substr($item['allowed_checkin_to']??'',0,5))?>"></label><label>شروع بازه مجاز خروج<input type="time" name="allowed_checkout_from" value="<?=e(substr($item['allowed_checkout_from']??'',0,5))?>"></label><label>پایان بازه مجاز خروج<input type="time" name="allowed_checkout_to" value="<?=e(substr($item['allowed_checkout_to']??'',0,5))?>"></label><label class="checkbox-item"><input type="checkbox" name="allow_before_shift_overtime" value="1" <?=!empty($item['allow_before_shift_overtime'])?'checked':''?>> اضافه‌کاری قبل از شیفت</label><label class="checkbox-item"><input type="checkbox" name="allow_after_shift_overtime" value="1" <?=!isset($item['allow_after_shift_overtime'])||$item['allow_after_shift_overtime']?'checked':''?>> اضافه‌کاری بعد از شیفت</label><label class="checkbox-item"><input type="checkbox" name="require_overtime_approval" value="1" <?=!isset($item['require_overtime_approval'])||$item['require_overtime_approval']?'checked':''?>> نیازمند تأیید اضافه‌کاری</label><button class="btn btn-primary">ثبت نسخه جدید</button></form></article><?php endforeach?></section>
<section class="card attendance-card-history"><h2>تاریخچه تنظیمات</h2><div class="table-wrap"><table><thead><tr><th>گروه</th><th>بازه اجرا</th><th>ورود–خروج</th><th>تلورانس‌ها</th><th>قواعد اضافه‌کاری</th><th>وضعیت</th></tr></thead><tbody><?php foreach($history as $row):?><tr><td><?=e($row['group_title'])?></td><td><?=e(JalaliDate::toJalali($row['effective_from']).' تا '.(!empty($row['effective_to'])?JalaliDate::toJalali($row['effective_to']):'بدون پایان'))?></td><td><?=e(substr($row['default_start_time'],0,5).' تا '.substr($row['default_end_time'],0,5))?></td><td><?=e('تأخیر '.$row['late_tolerance_minutes'].'، تعجیل '.$row['early_leave_tolerance_minutes'].' دقیقه')?></td><td><?=e(($row['allow_before_shift_overtime']?'قبل ':'').($row['allow_after_shift_overtime']?'بعد ':'').($row['require_overtime_approval']?'با تأیید':'قطعی'))?></td><td><span class="badge"><?=$row['active']?'فعال':'غیرفعال'?></span></td></tr><?php endforeach?><?php if(!$history):?><tr><td colspan="6">هنوز تنظیماتی ثبت نشده است.</td></tr><?php endif?></tbody></table></div></section></div>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
