<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../lib/HrAttendanceRepository.php';
Auth::requireLogin();if(!HrAttendanceRepository::canReports()){http_response_code(403);exit('دسترسی غیرمجاز');}
$todayJ=explode('/',JalaliDate::toJalali(date('Y-m-d')));$year=(int)($_GET['year']??$todayJ[0]);$month=(int)($_GET['month']??$todayJ[1]);
$filters=['date_from'=>trim((string)($_GET['date_from']??'')),'date_to'=>trim((string)($_GET['date_to']??'')),'employee_id'=>(int)($_GET['employee_id']??0),'work_group_id'=>(int)($_GET['work_group_id']??0),'org_unit_id'=>(int)($_GET['org_unit_id']??0),'org_role_id'=>(int)($_GET['org_role_id']??0),'day_status'=>trim((string)($_GET['day_status']??'')),'overtime_status'=>trim((string)($_GET['overtime_status']??''))];
if($filters['date_from']===''&&$year&&$month)$filters['date_from']=JalaliDate::toGregorian(sprintf('%04d/%02d/01',$year,$month))??'';
if($filters['date_to']===''&&$year&&$month)$filters['date_to']=JalaliDate::toGregorian(sprintf('%04d/%02d/%02d',$year,$month,JalaliDate::monthLength($year,$month)))??'';
foreach(['date_from','date_to'] as $key)if(str_contains($filters[$key],'/'))$filters[$key]=JalaliDate::toGregorian($filters[$key])??'';
$rows=HrAttendanceRepository::report($filters);$stats=HrAttendanceRepository::reportStats($rows);
if(($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="hr-attendance-'.date('Ymd-His').'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','wb');fputcsv($out,['تاریخ','شماره پرسنلی','نام پرسنل','گروه','واحد','نقش','وضعیت روز','ورود','خروج','کارکرد دقیقه','تأخیر','تعجیل','اضافه‌کاری عادی','اضافه‌کاری تعطیل','وضعیت اضافه‌کاری','توضیحات']);$safe=static fn($v)=>(is_string($v)&&preg_match('/^[=+\-@]/u',$v)?"'":'').$v;foreach($rows as $row)fputcsv($out,[JalaliDate::toJalali($row['attendance_date']),$safe($row['employee_no']??''),$safe($row['employee_name']),$safe($row['group_title']),$safe($row['unit_title']??$row['department']??''),$safe($row['role_title']??$row['role_key']??''),HrAttendanceRepository::DAY_STATUSES[$row['day_status']]??$row['day_status'],substr($row['actual_in_time']??'',0,5),substr($row['actual_out_time']??'',0,5),$row['work_minutes'],$row['late_minutes'],$row['early_leave_minutes'],$row['normal_overtime_minutes'],$row['holiday_overtime_minutes'],HrAttendanceRepository::OVERTIME_STATUSES[$row['overtime_status']]??$row['overtime_status'],$safe($row['notes']??'')]);fclose($out);exit;}
$groups=HrAttendanceRepository::groups();$units=HrAttendanceRepository::units();$roles=HrAttendanceRepository::roles();$employees=HrAttendanceRepository::employees();$query=$_GET;unset($query['export']);$pageTitle='گزارش حضور و کارکرد';$adminExtraStylesheets=['/assets/css/hr-attendance.css'];require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="attendance-page"><header class="attendance-hero"><div><small>گزارش روزانه، ماهانه و پرسنلی</small><h1>گزارش حضور و کارکرد</h1><p>مبالغ زمانی قطعی فقط از اضافه‌کاری تأییدشده محاسبه می‌شوند.</p></div><div class="attendance-actions no-print"><a class="btn" href="?<?=e(http_build_query([...$query,'export'=>'csv']))?>">خروجی CSV/Excel</a><button class="btn" type="button" onclick="window.print()">چاپ / ذخیره PDF</button></div></header><?php require __DIR__.'/includes/hr-attendance-nav.php';?>
<section class="card attendance-filter-card"><form class="attendance-filter" method="get"><label>سال شمسی<input type="number" name="year" min="1300" max="1600" value="<?=$year?>"></label><label>ماه<select name="month"><option value="">همه</option><?php for($m=1;$m<=12;$m++):?><option value="<?=$m?>" <?=$month===$m?'selected':''?>><?=$m?></option><?php endfor?></select></label><label>از تاریخ شمسی<input class="jalali-date-input" name="date_from" inputmode="numeric" value="<?=e(JalaliDate::toJalali($filters['date_from']))?>"></label><label>تا تاریخ شمسی<input class="jalali-date-input" name="date_to" inputmode="numeric" value="<?=e(JalaliDate::toJalali($filters['date_to']))?>"></label><label>گروه<select name="work_group_id"><option value="">همه</option><?php foreach($groups as $item):?><option value="<?=$item['id']?>" <?=$filters['work_group_id']==$item['id']?'selected':''?>><?=e($item['title'])?></option><?php endforeach?></select></label><label>واحد<select name="org_unit_id"><option value="">همه</option><?php foreach($units as $item):?><option value="<?=$item['id']?>" <?=$filters['org_unit_id']==$item['id']?'selected':''?>><?=e($item['title'])?></option><?php endforeach?></select></label><label>نقش<select name="org_role_id"><option value="">همه</option><?php foreach($roles as $item):?><option value="<?=$item['id']?>" <?=$filters['org_role_id']==$item['id']?'selected':''?>><?=e($item['title'])?></option><?php endforeach?></select></label><label>پرسنل<select name="employee_id"><option value="">همه</option><?php foreach($employees as $item):?><option value="<?=$item['id']?>" <?=$filters['employee_id']==$item['id']?'selected':''?>><?=e($item['name'])?></option><?php endforeach?></select></label><label>وضعیت روز<select name="day_status"><option value="">همه</option><?php foreach(HrAttendanceRepository::DAY_STATUSES as $key=>$label):?><option value="<?=$key?>" <?=$filters['day_status']===$key?'selected':''?>><?=e($label)?></option><?php endforeach?></select></label><label>وضعیت اضافه‌کاری<select name="overtime_status"><option value="">همه</option><?php foreach(HrAttendanceRepository::OVERTIME_STATUSES as $key=>$label):?><option value="<?=$key?>" <?=$filters['overtime_status']===$key?'selected':''?>><?=e($label)?></option><?php endforeach?></select></label><div class="attendance-actions"><button class="btn btn-primary">اعمال فیلتر</button><a class="btn" href="/admin/hr-attendance-reports.php">ماه جاری</a></div></form></section>
<section class="attendance-kpis"><?php foreach(['late'=>'مجموع تأخیر','early'=>'مجموع تعجیل','normal_overtime'=>'اضافه‌کاری عادی تأییدشده','holiday_overtime'=>'اضافه‌کاری تعطیل تأییدشده','absent'=>'تعداد غیبت','leave'=>'تعداد مرخصی','mission'=>'تعداد مأموریت','punctual'=>'پرسنل بدون تأخیر'] as $key=>$label):?><article class="attendance-kpi"><span><?=e($label)?></span><strong><?=format_number($stats[$key])?><?=$key==='late'||$key==='early'||str_contains($key,'overtime')?' دقیقه':''?></strong></article><?php endforeach?></section>
<section class="card"><h2 class="attendance-print-only">گزارش حضور و کارکرد — <?=e(JalaliDate::toJalali($filters['date_from']).' تا '.JalaliDate::toJalali($filters['date_to']))?></h2><div class="table-wrap"><table><thead><tr><th>تاریخ</th><th>پرسنل</th><th>گروه / واحد</th><th>وضعیت</th><th>ورود–خروج</th><th>تأخیر / تعجیل</th><th>اضافه‌کاری عادی / تعطیل</th><th>تأیید</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?=e(JalaliDate::toJalali($row['attendance_date']))?></td><td><strong><?=e($row['employee_name'])?></strong><small><?=e($row['employee_no']??'')?></small></td><td><?=e($row['group_title'])?><small><?=e($row['unit_title']??$row['department']??'—')?></small></td><td><span class="attendance-badge attendance-<?=e($row['day_status'])?>"><?=e(HrAttendanceRepository::DAY_STATUSES[$row['day_status']]??$row['day_status'])?></span></td><td><?=e(substr($row['actual_in_time']??'',0,5).'–'.substr($row['actual_out_time']??'',0,5))?><small><?=$row['work_minutes']?> دقیقه کارکرد</small></td><td><span class="attendance-badge attendance-late"><?=$row['late_minutes']?>د</span> <span class="attendance-badge attendance-early"><?=$row['early_leave_minutes']?>د</span></td><td><span class="attendance-badge attendance-overtime"><?=$row['normal_overtime_minutes']?> / <?=$row['holiday_overtime_minutes']?> دقیقه</span></td><td><?=e(HrAttendanceRepository::OVERTIME_STATUSES[$row['overtime_status']]??$row['overtime_status'])?><small><?=e($row['approver_name']??'')?></small></td></tr><?php endforeach?><?php if(!$rows):?><tr><td colspan="8">داده‌ای مطابق فیلترها و محدوده دسترسی یافت نشد.</td></tr><?php endif?></tbody></table></div></section></div>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
