<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../lib/HrAttendanceRepository.php';
Auth::requireLogin();if(!HrAttendanceRepository::canSettings()){http_response_code(403);exit('دسترسی غیرمجاز');}$user=Auth::user();
if($_SERVER['REQUEST_METHOD']==='POST'){try{if(!Auth::verifyCsrf($_POST['csrf_token']??null))throw new DomainException('اعتبار فرم منقضی شده است.');if(($_POST['action']??'save')==='toggle')HrAttendanceRepository::toggleHoliday((int)($_POST['id']??0),(int)$user['id']);else HrAttendanceRepository::saveHoliday($_POST,(int)$user['id']);flash('اطلاعات تعطیلی ذخیره شد.');}catch(InvalidArgumentException|DomainException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('HR holidays: '.$e->getMessage());flash('ذخیره روز تعطیل انجام نشد.','danger');}redirect('/admin/hr-holidays.php');}
$filters=['year'=>(int)($_GET['year']??0),'month'=>(int)($_GET['month']??0),'group'=>trim((string)($_GET['group']??''))];$rows=HrAttendanceRepository::holidays($filters);$edit=isset($_GET['edit'])?HrAttendanceRepository::holidayById((int)$_GET['edit']):null;$pageTitle='روزهای تعطیل';$adminExtraStylesheets=['/assets/css/hr-attendance.css'];require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="attendance-page"><header class="attendance-hero"><div><small>تقویم کارکرد</small><h1>روزهای تعطیل</h1><p>تعطیلات رسمی، شرکتی، داخلی و نیمه‌روز</p></div></header><?php require __DIR__.'/includes/hr-attendance-nav.php';?>
<section class="card attendance-filter-card"><form class="attendance-filter" method="get"><label>سال شمسی<input type="number" name="year" value="<?=e($filters['year']?:'')?>"></label><label>ماه<select name="month"><option value="">همه</option><?php for($m=1;$m<=12;$m++):?><option value="<?=$m?>" <?=$filters['month']===$m?'selected':''?>><?=$m?></option><?php endfor?></select></label><label>گروه<select name="group"><option value="">همه</option><?php foreach(HrAttendanceRepository::HOLIDAY_SCOPES as $k=>$v):?><option value="<?=$k?>" <?=$filters['group']===$k?'selected':''?>><?=e($v)?></option><?php endforeach?></select></label><div class="attendance-actions"><button class="btn btn-primary">فیلتر</button><a class="btn" href="/admin/hr-holidays.php">پاکسازی</a></div></form></section>
<section class="attendance-settings-grid"><article class="card"><h2><?=$edit?'ویرایش تعطیلی':'ثبت تعطیلی'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><label>تاریخ شمسی<input name="holiday_date" required placeholder="۱۴۰۵/۰۴/۰۸" value="<?=e(JalaliDate::toJalali($edit['holiday_date']??''))?>"></label><label>عنوان<input name="title" required maxlength="190" value="<?=e($edit['title']??'')?>"></label><label>نوع<select name="holiday_type"><?php foreach(HrAttendanceRepository::HOLIDAY_TYPES as $k=>$v):?><option value="<?=$k?>" <?=($edit['holiday_type']??'official')===$k?'selected':''?>><?=e($v)?></option><?php endforeach?></select></label><label>گروه مشمول<select name="applies_to_group"><?php foreach(HrAttendanceRepository::HOLIDAY_SCOPES as $k=>$v):?><option value="<?=$k?>" <?=($edit['applies_to_group']??'all')===$k?'selected':''?>><?=e($v)?></option><?php endforeach?></select></label><label class="checkbox-item"><input type="checkbox" name="is_half_day" value="1" <?=!empty($edit['is_half_day'])?'checked':''?>> نیمه‌روز</label><label class="checkbox-item"><input type="checkbox" name="active" value="1" <?=!isset($edit['active'])||$edit['active']?'checked':''?>> فعال</label><label>توضیحات<textarea name="description" rows="3"><?=e($edit['description']??'')?></textarea></label><div class="attendance-actions"><button class="btn btn-primary">ذخیره</button><?php if($edit):?><a class="btn" href="/admin/hr-holidays.php">انصراف</a><?php endif?></div></form></article>
<article class="card"><h2>تعطیلات ثبت‌شده</h2><div class="table-wrap"><table><thead><tr><th>تاریخ</th><th>عنوان</th><th>نوع</th><th>گروه</th><th>وضعیت</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?=e(JalaliDate::toJalali($row['holiday_date']))?></td><td><?=e($row['title'])?></td><td><?=e(HrAttendanceRepository::HOLIDAY_TYPES[$row['holiday_type']]??$row['holiday_type'])?></td><td><?=e(HrAttendanceRepository::HOLIDAY_SCOPES[$row['applies_to_group']]??$row['applies_to_group'])?></td><td><?=$row['active']?'فعال':'غیرفعال'?></td><td><div class="attendance-actions"><a class="btn btn-small" href="?edit=<?=$row['id']?>">ویرایش</a><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$row['id']?>"><button class="btn btn-small"><?=$row['active']?'غیرفعال‌سازی':'فعال‌سازی'?></button></form></div></td></tr><?php endforeach?><?php if(!$rows):?><tr><td colspan="6">تعطیلی‌ای مطابق فیلتر ثبت نشده است.</td></tr><?php endif?></tbody></table></div></article></section></div>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
