<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Database.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/HrModule.php';
Auth::requirePermission('hr_kpi.view');$pageTitle='شاخص‌های KPI منابع انسانی';$user=Auth::user();$ids=HrModule::accessibleEmployeeIds($user);$ph=implode(',',array_fill(0,max(1,count($ids)),'?'));if(!$ids)$ids=[-1];
$active=(int)(Database::fetch('SELECT COUNT(*) c FROM hr_kpi_templates WHERE active=1')['c']??0);
$people=(int)(Database::fetch("SELECT COUNT(DISTINCT employee_id) c FROM hr_kpi_scores WHERE employee_id IN ($ph)",$ids)['c']??0);
$avg=(float)(Database::fetch("SELECT AVG(score/max_score*100) a FROM hr_kpi_scores s JOIN hr_kpi_criteria c ON c.id=s.criteria_id WHERE s.employee_id IN ($ph)",$ids)['a']??0);
$unitAverages=['sales'=>0.0,'warehouse'=>0.0,'finance'=>0.0];$unitRoleMap=['sales'=>['SALES_MANAGER','SALES_SUPERVISOR','VISITOR','DISTRIBUTOR'],'warehouse'=>['WAREHOUSE_MANAGER','WAREHOUSE_SUPERVISOR','WAREHOUSE_STAFF','DRIVER'],'finance'=>['FINANCE_MANAGER','TAX_INSURANCE','TREASURY','SALES_ACCOUNTING']];foreach($unitRoleMap as $unit=>$roles){$rolePh=implode(',',array_fill(0,count($roles),'?'));$unitAverages[$unit]=(float)(Database::fetch("SELECT AVG(s.score/c.max_score*100) a FROM hr_kpi_scores s JOIN hr_kpi_criteria c ON c.id=s.criteria_id JOIN users u ON u.id=s.employee_id WHERE s.employee_id IN ($ph) AND u.role_key IN ($rolePh)",array_merge($ids,$roles))['a']??0);}
$departmentRows=Database::fetchAll("SELECT COALESCE(NULLIF(u.department,''),'بدون واحد') department,ROUND(AVG(s.score/c.max_score*100),1) average_score FROM hr_kpi_scores s JOIN hr_kpi_criteria c ON c.id=s.criteria_id JOIN users u ON u.id=s.employee_id WHERE s.employee_id IN ($ph) GROUP BY u.department ORDER BY average_score DESC",$ids);
$ranking=Database::fetchAll("SELECT u.id,u.name,u.department,ROUND(AVG(s.score/c.max_score*100),1) average_score,COUNT(DISTINCT s.period_id) periods FROM hr_kpi_scores s JOIN hr_kpi_criteria c ON c.id=s.criteria_id JOIN users u ON u.id=s.employee_id WHERE s.employee_id IN ($ph) GROUP BY u.id ORDER BY average_score DESC LIMIT 20",$ids);
$follow=count(array_filter($ranking,fn($r)=>(float)$r['average_score']<60));$best=$ranking[0]['name']??'-';
require __DIR__.'/../views/partials/admin-header.php';?>
<div class="section-heading-row"><div><h1>ارزیابی عملکرد</h1><p class="muted">خلاصه KPI در دامنه دسترسی شما</p></div><div class="actions"><?php if(Auth::can('hr_kpi.score')):?><a class="btn btn-primary" href="/admin/hr-kpi-scores.php">ثبت امتیاز</a><?php endif?><a class="btn" href="/admin/hr-kpi-results.php">نتایج</a></div></div>
<div class="stats"><div class="stat-card"><span>قالب‌های فعال</span><strong><?=$active?></strong></div><div class="stat-card"><span>پرسنل دارای ارزیابی</span><strong><?=$people?></strong></div><div class="stat-card"><span>میانگین کل</span><strong><?=e(number_format($avg,1))?>٪</strong></div><div class="stat-card"><span>میانگین فروش</span><strong><?=e(number_format($unitAverages['sales'],1))?>٪</strong></div><div class="stat-card"><span>میانگین انبار</span><strong><?=e(number_format($unitAverages['warehouse'],1))?>٪</strong></div><div class="stat-card"><span>میانگین مالی</span><strong><?=e(number_format($unitAverages['finance'],1))?>٪</strong></div><div class="stat-card"><span>نیازمند پیگیری</span><strong><?=$follow?></strong></div><div class="stat-card"><span>بهترین عملکرد</span><strong><?=e($best)?></strong></div></div>
<div class="grid grid-2"><section class="card"><h2>مقایسه واحدها</h2><div class="score-list"><?php foreach($departmentRows as $r):?><div class="score-row"><strong><?=e($r['department'])?></strong><div class="score-meter"><div class="progress"><span style="width:<?=min(100,(float)$r['average_score'])?>%"></span></div><b><?=e($r['average_score'])?>٪</b></div></div><?php endforeach?><?php if(!$departmentRows):?><p class="muted">هنوز امتیازی ثبت نشده است.</p><?php endif?></div></section><section class="card"><h2>رتبه‌بندی پرسنل</h2><div class="table-wrap"><table><thead><tr><th>نام</th><th>واحد</th><th>امتیاز</th><th>دوره</th></tr></thead><tbody><?php foreach($ranking as $r):?><tr><td><?=e($r['name'])?></td><td><?=e($r['department']?:'-')?></td><td><span class="achievement-pill <?=((float)$r['average_score']>=75?'achievement-good':((float)$r['average_score']>=60?'achievement-warn':'achievement-bad'))?>"><?=e($r['average_score'])?>٪</span></td><td><?=e($r['periods'])?></td></tr><?php endforeach?></tbody></table></div></section></div>
</section></main></div><script src="/assets/js/app.js"></script></body></html>
