<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Database.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/JalaliDate.php';Auth::requirePermission('hr_kpi.manage');$pageTitle='دوره‌های ارزیابی KPI';$edit=null;
if(isset($_GET['edit']))$edit=Database::fetch('SELECT * FROM hr_kpi_periods WHERE id=?',[(int)$_GET['edit']]);
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Auth::verifyCsrf($_POST['csrf_token']??'')){http_response_code(419);exit('درخواست نامعتبر است.');}try{$id=(int)($_POST['id']??0);if(($_POST['action']??'')==='toggle_active'){if(!$id||!Database::fetch('SELECT id FROM hr_kpi_periods WHERE id=?',[$id]))throw new InvalidArgumentException('دوره معتبر نیست.');Database::execute('UPDATE hr_kpi_periods SET active=IF(active=1,0,1),updated_at=NOW() WHERE id=?',[$id]);flash('وضعیت دوره تغییر کرد.');redirect('/admin/hr-kpi-periods.php');}$start=JalaliDate::toGregorian($_POST['start_date']??'')?:null;$end=JalaliDate::toGregorian($_POST['end_date']??'')?:null;if(!$start||!$end||$end<$start)throw new InvalidArgumentException('بازه دوره معتبر نیست.');$code=strtoupper(preg_replace('/[^A-Z0-9_]/','',$_POST['code']??''));if($id)Database::execute('UPDATE hr_kpi_periods SET title=?,code=?,start_date=?,end_date=?,period_type=?,active=?,sort_order=?,updated_at=NOW() WHERE id=?',[trim($_POST['title']),$code,$start,$end,trim($_POST['period_type']),isset($_POST['active'])?1:0,(int)$_POST['sort_order'],$id]);else Database::execute('INSERT INTO hr_kpi_periods(title,code,start_date,end_date,period_type,active,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,NOW(),NOW())',[trim($_POST['title']),$code,$start,$end,trim($_POST['period_type']),isset($_POST['active'])?1:0,(int)$_POST['sort_order']]);flash('عملیات با موفقیت انجام شد.');}catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('KPI period save: '.$e->getMessage());flash('خطا در ذخیره‌سازی اطلاعات. لطفاً مجدد تلاش کنید.','danger');}redirect('/admin/hr-kpi-periods.php');}
$periods=Database::fetchAll('SELECT * FROM hr_kpi_periods ORDER BY sort_order,id');require __DIR__.'/../views/partials/admin-header.php';?>
<section class="card admin-form"><h2><?=$edit?'ویرایش دوره':'دوره جدید'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><div class="grid grid-3"><label class="form-field"><span>عنوان</span><input name="title" required value="<?=e($edit['title']??'')?>"></label><label class="form-field"><span>کد</span><input dir="ltr" name="code" required value="<?=e($edit['code']??'')?>"></label><label class="form-field"><span>نوع دوره</span><input name="period_type" value="<?=e($edit['period_type']??'custom')?>"></label><label class="form-field"><span>شروع</span><input class="jalali-date-input" name="start_date" value="<?=e(isset($edit['start_date'])?jalali_input_value($edit['start_date']):'')?>"></label><label class="form-field"><span>پایان</span><input class="jalali-date-input" name="end_date" value="<?=e(isset($edit['end_date'])?jalali_input_value($edit['end_date']):'')?>"></label><label class="form-field"><span>ترتیب</span><input type="number" name="sort_order" value="<?=e($edit['sort_order']??100)?>"></label></div><label class="checkbox-item"><input type="checkbox" name="active" <?=!$edit||$edit['active']?'checked':''?>> فعال</label><div class="form-actions"><button class="btn btn-primary">ذخیره</button><a class="btn" href="/admin/hr-kpi-periods.php">بازگشت</a></div></form></section>
<section class="card"><div class="table-wrap"><table><thead><tr><th>عنوان</th><th>کد</th><th>بازه</th><th>نوع</th><th>وضعیت</th><th></th></tr></thead><tbody><?php foreach($periods as $p):?><tr><td><?=e($p['title'])?></td><td><code><?=e($p['code'])?></code></td><td><?=e($p['start_date']?format_jalali_date($p['start_date']):'-')?> تا <?=e($p['end_date']?format_jalali_date($p['end_date']):'-')?></td><td><?=e($p['period_type'])?></td><td><?=$p['active']?'فعال':'غیرفعال'?></td><td><a class="btn btn-small" href="?edit=<?=$p['id']?>">ویرایش</a></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><h2>تغییر سریع وضعیت</h2><div class="form-actions"><?php foreach($periods as $p):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="toggle_active"><input type="hidden" name="id" value="<?=e((string)$p['id'])?>"><button class="btn btn-small"><?=e($p['title'])?> — <span class="badge"><?=($p['active']&&(!$p['end_date']||$p['end_date']>=date('Y-m-d')))?'فعال':'غیرفعال'?></span></button></form><?php endforeach?></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
