<?php
require_once __DIR__ . '/../core/Auth.php';
require_once __DIR__ . '/../core/Database.php';
require_once __DIR__ . '/../core/Response.php';
require_once __DIR__ . '/../lib/OrgAccess.php';

Auth::requirePermission('hr_kpi.view');
$pageTitle = 'شاخص‌های KPI منابع انسانی';
$user = Auth::user();
[$scopeSql,$scopeParams] = OrgAccess::scopeSql($user, 'u.id');
$where = [$scopeSql];$params=$scopeParams;
foreach(['org_unit_id'=>'u.org_unit_id','org_role_id'=>'u.org_role_id','employee_id'=>'u.id','period_id'=>'s.period_id','scored_by'=>'s.scored_by'] as $key=>$column){$value=(int)($_GET[$key]??0);if($value){$where[]="{$column}=?";$params[]=$value;}}
$whereSql=implode(' AND ',$where);
$summary=Database::fetch('SELECT COUNT(DISTINCT s.employee_id) people,ROUND(AVG(s.score/c.max_score*100),1) average_score FROM hr_kpi_scores s JOIN hr_kpi_criteria c ON c.id=s.criteria_id JOIN users u ON u.id=s.employee_id WHERE '.$whereSql,$params)?:[];
$unitRows=Database::fetchAll('SELECT ou.id,ou.title,ou.sort_order,COUNT(DISTINCT s.employee_id) people,ROUND(AVG(s.score/c.max_score*100),1) average_score FROM org_units ou LEFT JOIN users u ON u.org_unit_id=ou.id AND '.$scopeSql.' LEFT JOIN hr_kpi_scores s ON s.employee_id=u.id LEFT JOIN hr_kpi_criteria c ON c.id=s.criteria_id WHERE ou.active=1 GROUP BY ou.id ORDER BY ou.sort_order,ou.title',$scopeParams);
$rankings=Database::fetchAll('SELECT u.id,u.name,COALESCE(ou.title,NULLIF(u.department,""),"بدون واحد") unit_title,COALESCE(orr.title,NULLIF(u.role_key,""),"بدون نقش") role_title,ROUND(AVG(s.score/c.max_score*100),1) average_score,COUNT(DISTINCT s.period_id) periods FROM hr_kpi_scores s JOIN hr_kpi_criteria c ON c.id=s.criteria_id JOIN users u ON u.id=s.employee_id LEFT JOIN org_units ou ON ou.id=u.org_unit_id LEFT JOIN org_roles orr ON orr.id=u.org_role_id WHERE '.$whereSql.' GROUP BY u.id,ou.title,orr.title ORDER BY average_score DESC LIMIT 30',$params);
$scoredUnits=array_values(array_filter($unitRows,fn($row)=>$row['average_score']!==null));
usort($scoredUnits,fn($a,$b)=>(float)$b['average_score']<=>(float)$a['average_score']);$bestUnit=$scoredUnits[0]??null;$weakUnit=$scoredUnits?$scoredUnits[count($scoredUnits)-1]:null;
$follow=count(array_filter($rankings,fn($row)=>(float)$row['average_score']<60));
$units=Database::fetchAll('SELECT id,title FROM org_units WHERE active=1 ORDER BY sort_order,title');$roles=Database::fetchAll('SELECT id,title FROM org_roles WHERE active=1 ORDER BY sort_order,title');$accessibleIds=OrgAccess::accessibleUserIds($user);if(!$accessibleIds)$accessibleIds=[-1];$employees=Database::fetchAll('SELECT id,name FROM users WHERE id IN ('.implode(',',array_fill(0,count($accessibleIds),'?')).') ORDER BY name',$accessibleIds);$periods=Database::fetchAll('SELECT id,title FROM hr_kpi_periods WHERE active=1 ORDER BY sort_order');$scorers=Database::fetchAll('SELECT DISTINCT u.id,u.name FROM users u JOIN hr_kpi_scores s ON s.scored_by=u.id ORDER BY u.name');
require __DIR__ . '/../views/partials/admin-header.php';
?>
<div class="section-heading-row"><div><h1>ارزیابی عملکرد</h1><p class="muted">خلاصه پویا بر اساس ساختار سازمانی و دامنه دسترسی شما</p></div><div class="actions"><?php if(Auth::can('hr_kpi.score')):?><a class="btn btn-primary" href="/admin/hr-kpi-scores.php">ثبت امتیاز</a><?php endif?><a class="btn" href="/admin/hr-kpi-results.php">نتایج کامل</a></div></div>
<form class="card admin-form" method="get"><h2>فیلتر داشبورد KPI</h2><div class="grid grid-3"><label class="form-field"><span>واحد</span><select name="org_unit_id"><option value="">همه</option><?php foreach($units as $item):?><option value="<?=$item['id']?>" <?=(int)($_GET['org_unit_id']??0)===(int)$item['id']?'selected':''?>><?=e($item['title'])?></option><?php endforeach?></select></label><label class="form-field"><span>نقش سازمانی</span><select name="org_role_id"><option value="">همه</option><?php foreach($roles as $item):?><option value="<?=$item['id']?>" <?=(int)($_GET['org_role_id']??0)===(int)$item['id']?'selected':''?>><?=e($item['title'])?></option><?php endforeach?></select></label><label class="form-field"><span>کاربر</span><select name="employee_id"><option value="">همه</option><?php foreach($employees as $item):?><option value="<?=$item['id']?>" <?=(int)($_GET['employee_id']??0)===(int)$item['id']?'selected':''?>><?=e($item['name'])?></option><?php endforeach?></select></label><label class="form-field"><span>دوره</span><select name="period_id"><option value="">همه</option><?php foreach($periods as $item):?><option value="<?=$item['id']?>" <?=(int)($_GET['period_id']??0)===(int)$item['id']?'selected':''?>><?=e($item['title'])?></option><?php endforeach?></select></label><label class="form-field"><span>ثبت‌کننده</span><select name="scored_by"><option value="">همه</option><?php foreach($scorers as $item):?><option value="<?=$item['id']?>" <?=(int)($_GET['scored_by']??0)===(int)$item['id']?'selected':''?>><?=e($item['name'])?></option><?php endforeach?></select></label></div><div class="form-actions"><button class="btn btn-primary">اعمال فیلتر</button><a class="btn" href="/admin/hr-kpi.php">پاکسازی</a></div></form>
<div class="stats"><div class="stat-card"><span>کل پرسنل دارای KPI</span><strong><?=e((string)($summary['people']??0))?></strong></div><div class="stat-card"><span>میانگین کل KPI</span><strong><?=e(number_format((float)($summary['average_score']??0),1))?>٪</strong></div><div class="stat-card"><span>بهترین واحد</span><strong><?=e($bestUnit['title']??'داده‌ای ثبت نشده')?></strong></div><div class="stat-card"><span>ضعیف‌ترین واحد</span><strong><?=e($weakUnit['title']??'داده‌ای ثبت نشده')?></strong></div><div class="stat-card"><span>نیازمند پیگیری</span><strong><?=e((string)$follow)?></strong></div><?php foreach($unitRows as $row):?><div class="stat-card"><span><?=e($row['title'])?></span><strong><?=$row['average_score']===null?'داده‌ای ثبت نشده':e(number_format((float)$row['average_score'],1)).'٪'?></strong><small><?=e((string)$row['people'])?> نفر</small></div><?php endforeach?></div>
<section class="card"><h2>رتبه‌بندی در دامنه مجاز</h2><div class="table-wrap"><table><thead><tr><th>نام</th><th>واحد</th><th>نقش</th><th>امتیاز</th><th>دوره‌ها</th></tr></thead><tbody><?php foreach($rankings as $row):?><tr><td><?=e($row['name'])?></td><td><?=e($row['unit_title'])?></td><td><?=e($row['role_title'])?></td><td><span class="achievement-pill <?=((float)$row['average_score']>=75?'achievement-good':((float)$row['average_score']>=60?'achievement-warn':'achievement-bad'))?>"><?=e($row['average_score'])?>٪</span></td><td><?=e($row['periods'])?></td></tr><?php endforeach?><?php if(!$rankings):?><tr><td colspan="5">داده‌ای ثبت نشده است.</td></tr><?php endif?></tbody></table></div></section>
<?php require __DIR__ . '/../views/partials/admin-footer.php'; ?>
