<?php
require_once __DIR__ . '/includes/letters.php';
LetterModule::requireCapability('settings');
$pageTitle = 'قالب‌های نامه';
if ($_SERVER['REQUEST_METHOD']==='POST') {
    if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('اعتبار درخواست منقضی شده است.','danger');redirect('/admin/letter-templates.php');}
    try {
        $id=(int)($_POST['id']??0);$title=trim((string)($_POST['title']??''));if($title==='')throw new InvalidArgumentException('عنوان قالب الزامی است.');
        $data=[$title,trim((string)($_POST['default_subject']??'')),LetterModule::sanitizeHtml($_POST['default_body']??''),LetterModule::sanitizeDelta($_POST['default_delta_json']??''),(int)($_POST['letterhead_id']??0)?:null,(int)($_POST['signature_id']??0)?:null,in_array($_POST['paper_size']??'',['A4','A5'],true)?$_POST['paper_size']:'A4',($_POST['orientation']??'')==='landscape'?'landscape':'portrait',isset($_POST['is_active'])?1:0];
        if($id)Database::execute('UPDATE letter_templates SET title=?,default_subject=?,default_body=?,default_delta_json=?,letterhead_id=?,signature_id=?,paper_size=?,orientation=?,is_active=?,updated_at=NOW() WHERE id=?',[...$data,$id]);
        else Database::execute('INSERT INTO letter_templates(title,default_subject,default_body,default_delta_json,letterhead_id,signature_id,paper_size,orientation,is_active,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[...$data,(int)Auth::user()['id']]);
        Auth::log((int)Auth::user()['id'],$id?'letter_template_updated':'letter_template_created','letter_templates',$id?:((int)Database::lastInsertId()));flash('قالب نامه ذخیره شد.');
    }catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('Letter template: '.$e->getMessage());flash('ذخیره قالب انجام نشد.','danger');}redirect('/admin/letter-templates.php');
}
$edit=isset($_GET['edit'])?Database::fetch('SELECT * FROM letter_templates WHERE id=?',[(int)$_GET['edit']]):null;
$items=Database::fetchAll('SELECT t.*,h.title letterhead_title,s.signer_name FROM letter_templates t LEFT JOIN letter_letterheads h ON h.id=t.letterhead_id LEFT JOIN letter_signatures s ON s.id=t.signature_id ORDER BY t.is_active DESC,t.title');
$letterheads=Database::fetchAll('SELECT id,title FROM letter_letterheads ORDER BY is_active DESC,title');$signatures=Database::fetchAll('SELECT id,signer_name,signer_title FROM letter_signatures ORDER BY is_active DESC,signer_name');
require __DIR__.'/../views/partials/admin-header.php';?>
<div class="letters-page-head"><div><h1>قالب‌های نامه</h1><p>متن و موضوع پیش‌فرض را با متغیرهای هوشمند آماده کنید.</p></div><a class="btn" href="/admin/letters.php">نامه‌ها</a></div><nav class="letter-tabs"><a href="/admin/letters.php">نامه‌ها</a><a class="is-active" href="/admin/letter-templates.php">قالب‌ها</a><a href="/admin/letter-letterheads.php">سربرگ‌ها</a><a href="/admin/letter-signatures.php">امضاها</a><a href="/admin/letter-settings.php">تنظیمات</a></nav>
<section class="card letter-form-section"><h2><?=$edit?'ویرایش قالب':'قالب جدید'?></h2><form method="post" data-letter-form><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><textarea hidden name="default_body" data-editor-input><?=e($edit['default_body']??'<p>متن پیش‌فرض نامه</p>')?></textarea><textarea hidden name="default_delta_json" data-editor-delta><?=e($edit['default_delta_json']??'')?></textarea><div class="grid grid-3"><label class="form-field"><span>عنوان قالب</span><input name="title" value="<?=e($edit['title']??'')?>" required></label><label class="form-field grid-span-2"><span>موضوع پیش‌فرض</span><input name="default_subject" value="<?=e($edit['default_subject']??'')?>"></label><label class="form-field"><span>سربرگ پیش‌فرض</span><select name="letterhead_id"><option value="">بدون انتخاب</option><?php foreach($letterheads as $h):?><option value="<?=$h['id']?>" <?=(int)($edit['letterhead_id']??0)===(int)$h['id']?'selected':''?>><?=e($h['title'])?></option><?php endforeach?></select></label><label class="form-field"><span>امضاکننده پیش‌فرض</span><select name="signature_id"><option value="">بدون انتخاب</option><?php foreach($signatures as $s):?><option value="<?=$s['id']?>" <?=(int)($edit['signature_id']??0)===(int)$s['id']?'selected':''?>><?=e($s['signer_name'].' — '.$s['signer_title'])?></option><?php endforeach?></select></label><label class="form-field"><span>کاغذ</span><select name="paper_size"><option value="A4" <?=($edit['paper_size']??'A4')==='A4'?'selected':''?>>A4</option><option value="A5" <?=($edit['paper_size']??'')==='A5'?'selected':''?>>A5</option></select></label><label class="form-field"><span>جهت</span><select name="orientation"><option value="portrait" <?=($edit['orientation']??'portrait')==='portrait'?'selected':''?>>عمودی</option><option value="landscape" <?=($edit['orientation']??'')==='landscape'?'selected':''?>>افقی</option></select></label><label class="checkbox-item"><input type="checkbox" name="is_active" <?=!isset($edit['is_active'])||(int)$edit['is_active']?'checked':''?>> فعال</label></div>
<div class="letter-editor compact" data-rich-editor><div class="editor-toolbar" data-quill-toolbar><select class="ql-font"></select><select class="ql-size"></select><button class="ql-bold" type="button"></button><button class="ql-italic" type="button"></button><button class="ql-underline" type="button"></button><select class="ql-color"></select><select class="ql-background"></select><button class="ql-direction" value="rtl" type="button"></button><select class="ql-align"></select><button class="ql-list" value="ordered" type="button"></button><button class="ql-list" value="bullet" type="button"></button><button class="ql-indent" value="-1" type="button"></button><button class="ql-indent" value="+1" type="button"></button><button class="ql-link" type="button"></button><button class="ql-clean" type="button"></button><button class="ql-undo" type="button"></button><button class="ql-redo" type="button"></button></div><div class="editor-surface" dir="rtl" data-editor-surface><?=LetterModule::sanitizeHtml($edit['default_body']??'<p>متن پیش‌فرض نامه</p>')?></div></div><div class="letter-variable-hint"><?php foreach(['{letter_number}','{letter_date}','{subject}','{recipient_name}','{recipient_title}','{recipient_organization}','{sender_unit}','{signer_name}','{signer_title}','{company_name}','{current_user_name}'] as $v):?><button type="button" data-insert-variable="<?=e($v)?>"><?=e($v)?></button><?php endforeach?></div><div class="form-actions"><button class="btn btn-primary">ذخیره قالب</button><?php if($edit):?><a class="btn" href="/admin/letter-templates.php">انصراف</a><?php endif?></div></form></section>
<section class="card"><div class="table-wrap"><table><thead><tr><th>قالب</th><th>موضوع</th><th>سربرگ / امضا</th><th>چاپ</th><th>وضعیت</th><th></th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><strong><?=e($i['title'])?></strong></td><td><?=e($i['default_subject']?:'—')?></td><td><?=e(($i['letterhead_title']?:'بدون سربرگ').' / '.($i['signer_name']?:'بدون امضا'))?></td><td><?=e($i['paper_size'].' / '.($i['orientation']==='portrait'?'عمودی':'افقی'))?></td><td><?=((int)$i['is_active']?'فعال':'غیرفعال')?></td><td><a class="btn btn-small" href="?edit=<?=$i['id']?>">ویرایش</a></td></tr><?php endforeach?></tbody></table></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
