<?php
require_once __DIR__.'/../core/Auth.php';
require_once __DIR__.'/../core/Response.php';
require_once __DIR__.'/../core/Upload.php';
require_once __DIR__.'/../lib/ManagementReportsRepository.php';
Auth::requireLogin();
$type=(string)($_GET['type']??$_POST['report_type']??'');
if(!isset(ManagementReportsRepository::TYPES[$type])||!ManagementReportsRepository::canPrepare($type)){http_response_code(403);exit('شما به آماده‌سازی این نوع گزارش دسترسی ندارید.');}
$template=ManagementReportsRepository::template($type);if(!$template){http_response_code(503);exit('قالب فعال این گزارش هنوز راه‌اندازی نشده است.');}
$id=(int)($_GET['id']??$_POST['submission_id']??0);$submission=$id?ManagementReportsRepository::submission($id):null;if($id&&!$submission){http_response_code(404);exit('گزارش در دسترس نیست.');}
if($submission&&((int)$submission['submitter_id']!==(int)Auth::user()['id']||$submission['report_type']!==$type)){http_response_code(403);exit('دسترسی غیرمجاز است.');}
$editable=!$submission||in_array($submission['status'],['draft','returned'],true);
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('اعتبار درخواست منقضی شده است.','danger');redirect('/admin/management-report-prepare.php?type='.$type.($id?'&id='.$id:''));}
    try{
        if(!$editable)throw new InvalidArgumentException('گزارش ثبت‌شده تا زمان برگشت برای اصلاح قابل ویرایش نیست.');
        $periods=ManagementReportsRepository::periods();$periodMap=[];foreach($periods as $period)$periodMap[$period['period_key']]=$period;$periodKey=(string)($_POST['period_key']??'');if(!isset($periodMap[$periodKey])&&$submission&&$submission['period_key']===$periodKey)$periodMap[$periodKey]=['period_key'=>$submission['period_key'],'period_title'=>$submission['period_title'],'period_start'=>$submission['period_start'],'period_end'=>$submission['period_end']];if(!isset($periodMap[$periodKey]))throw new InvalidArgumentException('دوره گزارش معتبر نیست.');
        $target=($_POST['action']??'draft')==='submit'?'submitted':'draft';
        if($target==='submitted')foreach($template['sections'] as $section)foreach($section['fields'] as $field)if($field['field_type']==='file'&&(int)$field['is_required']){$hasExisting=$submission&&array_filter($submission['attachments'],static fn($a)=>(int)$a['field_id']===(int)$field['id']);$file=$_FILES['files']['error'][$field['id']]??UPLOAD_ERR_NO_FILE;if(!$hasExisting&&$file!==UPLOAD_ERR_OK)throw new InvalidArgumentException('بارگذاری فایل «'.$field['label'].'» الزامی است.');}
        $id=ManagementReportsRepository::saveSubmission($type,$id,$periodMap[$periodKey],$_POST['values']??[],'draft');
        foreach($template['sections'] as $section)foreach($section['fields'] as $field)if($field['field_type']==='file'){
            $fieldId=(int)$field['id'];$error=$_FILES['files']['error'][$fieldId]??UPLOAD_ERR_NO_FILE;if($error===UPLOAD_ERR_NO_FILE)continue;
            $file=['name'=>$_FILES['files']['name'][$fieldId]??'','type'=>$_FILES['files']['type'][$fieldId]??'','tmp_name'=>$_FILES['files']['tmp_name'][$fieldId]??'','error'=>$error,'size'=>$_FILES['files']['size'][$fieldId]??0];
            $upload=Upload::save($file,'uploads/management-reports',['pdf','doc','docx','xls','xlsx','csv','jpg','jpeg','png','webp','txt'],15*1024*1024);if(!$upload['ok'])throw new InvalidArgumentException($field['label'].': '.$upload['error']);ManagementReportsRepository::addAttachment($id,$fieldId,$upload);
        }
        if($target==='submitted')$id=ManagementReportsRepository::saveSubmission($type,$id,$periodMap[$periodKey],$_POST['values']??[],'submitted');
        Auth::log((int)Auth::user()['id'],$target==='submitted'?'management_report_submitted':'management_report_draft_saved','management_report_submissions',$id);
        flash($target==='submitted'?'گزارش با موفقیت ثبت نهایی شد.':'پیش‌نویس گزارش ذخیره شد.');redirect($target==='submitted'?'/admin/management-report-view.php?id='.$id:'/admin/management-report-prepare.php?type='.$type.'&id='.$id);
    }catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('Management report prepare: '.$e->getMessage());flash('ذخیره گزارش انجام نشد. لطفاً دوباره تلاش کنید.','danger');}
    redirect('/admin/management-report-prepare.php?type='.$type.($id?'&id='.$id:''));
}
$periods=ManagementReportsRepository::periods();if($submission&&!array_filter($periods,static fn($period)=>$period['period_key']===$submission['period_key']))array_unshift($periods,['period_key'=>$submission['period_key'],'period_title'=>$submission['period_title'],'period_start'=>$submission['period_start'],'period_end'=>$submission['period_end']]);$valueMap=[];$attachmentMap=[];if($submission){foreach($submission['values'] as $value)$valueMap[(int)$value['field_id']]=$value;foreach($submission['attachments'] as $attachment)$attachmentMap[(int)$attachment['field_id']][]=$attachment;}
$selectedPeriod=$submission['period_key']??($periods[0]['period_key']??'');$history=ManagementReportsRepository::list(['report_type'=>$type]);
$pageTitle='آماده‌سازی '.ManagementReportsRepository::TYPES[$type];$adminExtraStylesheets=['/assets/css/management-reports.css'];$adminExtraScripts=['/assets/js/management-reports.js'];require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="mr-head"><div><h1><?=e($pageTitle)?></h1><p><?=e($template['description'])?></p></div><div class="mr-actions"><a class="btn" href="/admin/management-reports.php">گزارشات مدیران</a><?php if($submission):?><span class="mr-status mr-status-<?=e($submission['status'])?>"><?=e(ManagementReportsRepository::STATUSES[$submission['status']]??'')?></span><?php endif?></div></div>
<nav class="mr-tabs no-print"><?php foreach(ManagementReportsRepository::TYPES as $key=>$label):if(!ManagementReportsRepository::canPrepare($key))continue;?><a class="<?=$key===$type?'is-active':''?>" href="?type=<?=$key?>"><?=e($label)?></a><?php endforeach?></nav>
<?php if($submission&&$submission['status']==='returned'):?><div class="mr-review-note"><strong>برگشت برای اصلاح:</strong> <?=e($submission['return_note'])?></div><?php endif?>
<?php if(!$editable):?><section class="card mr-empty"><h2>این گزارش ثبت شده و قابل ویرایش مستقیم نیست.</h2><p>در صورت برگشت گزارش توسط مدیر داخلی، امکان اصلاح دوباره فعال می‌شود.</p><a class="btn btn-primary" href="/admin/management-report-view.php?id=<?=$submission['id']?>">مشاهده گزارش</a></section><?php else:?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="report_type" value="<?=e($type)?>"><input type="hidden" name="submission_id" value="<?=e($submission['id']??'')?>"><input type="hidden" name="period_title" data-period-title><input type="hidden" name="period_start" data-period-start><input type="hidden" name="period_end" data-period-end>
<div class="mr-layout"><main><section class="card mr-section"><header><h2>دوره گزارش</h2><p>هر مدیر برای هر دوره یک گزارش از این قالب دارد.</p></header><label class="mr-field"><span>انتخاب دوره <b class="mr-required">*</b></span><select name="period_key" data-report-period required><?php foreach($periods as $period):?><option value="<?=e($period['period_key'])?>" data-title="<?=e($period['period_title'])?>" data-start="<?=e($period['period_start'])?>" data-end="<?=e($period['period_end'])?>" <?=$selectedPeriod===$period['period_key']?'selected':''?>><?=e($period['period_title'])?></option><?php endforeach?></select></label></section>
<?php foreach($template['sections'] as $section):?><section class="card mr-section"><header><h2><?=e($section['title'])?></h2><?php if($section['description']):?><p><?=e($section['description'])?></p><?php endif?></header><div class="mr-fields">
<?php foreach($section['fields'] as $field):$fieldId=(int)$field['id'];$saved=$valueMap[$fieldId]??null;$fieldType=$field['field_type'];$wide=in_array($fieldType,['textarea','table','repeater','file'],true);$raw=$saved?($saved['value_json']!==null?$saved['value_json']:($saved['value_number']!==null?(string)$saved['value_number']:(string)$saved['value_text'])):(string)$field['default_value'];?>
<label class="mr-field <?=$wide?'is-wide':''?>"><span><?=e($field['label'])?><?php if($field['is_required']):?> <b class="mr-required">*</b><?php endif?></span>
<?php if($field['linked_source_key']):?><code class="mr-linked"><?=e($field['linked_source_key'])?></code><?php endif?>
<?php if($fieldType==='textarea'):?><textarea name="values[<?=$fieldId?>]" rows="6" placeholder="<?=e($field['placeholder'])?>"><?=e($raw)?></textarea>
<?php elseif(in_array($fieldType,['number','currency','percent'],true)):?><input type="number" step="any" name="values[<?=$fieldId?>]" value="<?=e($raw)?>" placeholder="<?=e($field['placeholder'])?>" <?=$field['is_required']?'required':''?>>
<?php elseif($fieldType==='date'):?><input type="date" name="values[<?=$fieldId?>]" value="<?=e($raw)?>" <?=$field['is_required']?'required':''?>>
<?php elseif($fieldType==='select'):?><select name="values[<?=$fieldId?>]" <?=$field['is_required']?'required':''?>><option value="">انتخاب کنید</option><?php foreach($field['options'] as $option):$ov=is_array($option)?($option['value']??''):($option);$ol=is_array($option)?($option['label']??$ov):$option;?><option value="<?=e((string)$ov)?>" <?=$raw==(string)$ov?'selected':''?>><?=e((string)$ol)?></option><?php endforeach?></select>
<?php elseif($fieldType==='checkbox'):?><span class="mr-checkbox"><input type="checkbox" name="values[<?=$fieldId?>]" value="1" <?=$raw==='1'?'checked':''?>> تأیید می‌کنم</span>
<?php elseif(in_array($fieldType,['table','repeater'],true)):$columns=$field['options']['columns']??[['key'=>'value','label'=>'مقدار']];?><div class="mr-repeater" data-repeater data-columns="<?=e(json_encode($columns,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>"><input type="hidden" name="values[<?=$fieldId?>]" value="<?=e($raw?:'[]')?>"><table><thead><tr><?php foreach($columns as $column):?><th><?=e($column['label']??$column['key']??'مقدار')?></th><?php endforeach?><th>عملیات</th></tr></thead><tbody></tbody></table><footer><button class="btn btn-small" type="button" data-add-row>افزودن ردیف</button></footer></div>
<?php elseif($fieldType==='file'):?><input type="file" name="files[<?=$fieldId?>]" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.jpg,.jpeg,.png,.webp,.txt"><?php foreach($attachmentMap[$fieldId]??[] as $attachment):?><a href="/admin/management-report-attachment.php?id=<?=$attachment['id']?>">فایل فعلی: <?=e($attachment['original_name'])?></a><?php endforeach?>
<?php elseif($fieldType==='readonly_metric'):?><div class="mr-readonly"><?=e($raw!==''?$raw:'هنوز به منبع داده متصل نشده است.')?></div>
<?php else:?><input type="text" name="values[<?=$fieldId?>]" value="<?=e($raw)?>" placeholder="<?=e($field['placeholder'])?>" <?=$field['is_required']?'required':''?>><?php endif?>
<?php if($field['help_text']):?><small><?=e($field['help_text'])?></small><?php endif?></label><?php endforeach?></div></section><?php endforeach?></main>
<aside><section class="card mr-sticky"><h2>ثبت گزارش</h2><p class="muted">پیش‌نویس قابل ویرایش است. پس از ثبت نهایی، ویرایش تا زمان برگشت برای اصلاح بسته می‌شود.</p><div class="mr-actions"><button class="btn" name="action" value="draft">ذخیره پیش‌نویس</button><button class="btn btn-primary" name="action" value="submit" onclick="return confirm('گزارش ثبت نهایی شود؟')">ثبت نهایی</button></div></section></aside></div></form><?php endif?>
<section class="card no-print"><h2>گزارش‌های قبلی من</h2><div class="table-wrap"><table><thead><tr><th>دوره</th><th>وضعیت</th><th>آخرین بروزرسانی</th><th></th></tr></thead><tbody><?php foreach($history as $item):?><tr><td><?=e($item['period_title'])?></td><td><span class="mr-status mr-status-<?=e($item['status'])?>"><?=e(ManagementReportsRepository::STATUSES[$item['status']]??'')?></span></td><td><?=e(format_jalali_datetime($item['updated_at']))?></td><td><a class="btn btn-small" href="<?=in_array($item['status'],['draft','returned'],true)?'/admin/management-report-prepare.php?type='.$type.'&id='.$item['id']:'/admin/management-report-view.php?id='.$item['id']?>"><?=in_array($item['status'],['draft','returned'],true)?'ادامه ویرایش':'مشاهده'?></a></td></tr><?php endforeach?><?php if(!$history):?><tr><td colspan="4">هنوز گزارشی ثبت نشده است.</td></tr><?php endif?></tbody></table></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
