<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/Upload.php';require_once __DIR__.'/../core/JalaliDate.php';require_once __DIR__.'/../lib/ManagementMeetingsRepository.php';require_once __DIR__.'/../lib/OkrMeetingIntegration.php';Auth::requireLogin();$u=Auth::user();$id=(int)($_GET['id']??$_POST['id']??0);$d=ManagementMeetingsRepository::getDecisionById($id,$u);if(!$d){http_response_code(404);exit('مصوبه در دسترس نیست.');}
function mg_followup_attachment():?string{global $d,$u;if(!ManagementMeetingsRepository::canFollowupDecision($d,$u))throw new DomainException('فقط مسئول یا ناظر مجاز به ثبت پیگیری است.');if(empty($_FILES['attachment']['name']))return null;$s=Upload::save($_FILES['attachment'],'uploads/management-followups',['pdf','doc','docx','xls','xlsx','jpg','jpeg','png','webp'],10*1024*1024);if(!$s['ok'])throw new InvalidArgumentException($s['error']);return json_encode(['original_name'=>$s['original_name'],'file_path'=>$s['file_path'],'mime_type'=>$s['mime_type'],'file_size'=>$s['file_size']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
if($_SERVER['REQUEST_METHOD']==='POST'){try{if(!Auth::verifyCsrf($_POST['_csrf']??null))throw new DomainException('اعتبار فرم منقضی شده است.');$action=(string)($_POST['action']??'followup');if($action==='followup')ManagementMeetingsRepository::updateDecisionStatus($id,(string)($_POST['new_status']??''),(int)($_POST['progress_percent']??0),(string)($_POST['followup_note']??''),(int)$u['id'],trim((string)($_POST['next_followup_date']??''))?:null,mg_followup_attachment());elseif($action==='verify')ManagementMeetingsRepository::verifyDecision($id,(int)$u['id']);elseif($action==='update')ManagementMeetingsRepository::updateDecision($id,$_POST,(int)$u['id']);elseif($action==='convert_rule')ManagementMeetingsRepository::convertDecisionToRule($id,$_POST,(int)$u['id']);elseif($action==='link_okr'){$input=$_POST;$input['due_date']=app_date_to_iso((string)($_POST['due_date']??''))?:'';OkrMeetingIntegration::linkDecision($id,$input,(int)$u['id']);}flash(['followup'=>'وضعیت پیگیری بروزرسانی شد.','verify'=>'انجام مصوبه تأیید شد.','update'=>'مصوبه بروزرسانی شد.','convert_rule'=>'قانون مصوب با موفقیت فعال شد.','link_okr'=>'مصوبه به OKR و اقدام‌های انتخاب‌شده متصل شد.'][$action]??'عملیات انجام شد.');}catch(InvalidArgumentException|DomainException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('Decision view: '.$e->getMessage());flash('انجام عملیات مصوبه ممکن نشد.','danger');}redirect('/admin/management-decision-view.php?id='.$id);}
$d=ManagementMeetingsRepository::getDecisionById($id,$u);$timeline=ManagementMeetingsRepository::getDecisionFollowups($id);$users=ManagementMeetingsRepository::users();$units=ManagementMeetingsRepository::units();$okrObjectives=OkrMeetingIntegration::availableObjectives($u);$okrOwners=OkrService::availableOwners($u);$okrLinks=OkrMeetingIntegration::decisionLinks($id);$okrKeyResults=[];foreach($okrObjectives as $okrObjective)$okrKeyResults[(int)$okrObjective['id']]=OkrMeetingIntegration::keyResults((int)$okrObjective['id']);$pageTitle='جزئیات مصوبه';$adminExtraStylesheets=['/assets/css/management-governance.css','/assets/css/okr.css'];$adminExtraScripts=['/assets/js/okr.js','/assets/js/okr-decision-link.js'];require __DIR__.'/../views/partials/admin-header.php';?>
<div class="mg-page"><header class="mg-hero"><div><small><?=e($d['meeting_title'])?></small><h1><?=e($d['title'])?></h1><p>مهلت <?=e(JalaliDate::toJalali($d['due_date']))?> · مسئول <?=e($d['responsible_name']??'تعیین نشده')?></p></div><div class="mg-actions"><a class="btn" href="/admin/management-decisions.php">بازگشت</a><a class="btn" href="/admin/management-meeting-view.php?id=<?=$d['meeting_id']?>">صورتجلسه</a><?php if(ManagementMeetingsRepository::canEditDecision($d,$u)):?><a class="btn" href="/admin/management-decision-edit.php?id=<?=$id?>">ویرایش</a><?php endif?></div></header><?php require __DIR__.'/includes/management-governance-nav.php';?><section class="card"><div class="mg-detail-grid"><div class="mg-detail"><span>نوع</span><strong><?=e(ManagementMeetingsRepository::DECISION_TYPES[$d['decision_type']]??$d['decision_type'])?></strong></div><div class="mg-detail"><span>وضعیت</span><strong><?=e(ManagementMeetingsRepository::DECISION_STATUSES[$d['display_status']]??$d['display_status'])?></strong></div><div class="mg-detail"><span>پیشرفت</span><strong><?=(int)$d['progress_percent']?>٪</strong><div class="mg-progress"><i style="width:<?=(int)$d['progress_percent']?>%"></i></div></div><div class="mg-detail"><span>واحد</span><strong><?=e($d['responsible_unit_title']??'—')?></strong></div><div class="mg-detail"><span>ناظر</span><strong><?=e($d['supervisor_name']??'—')?></strong></div><div class="mg-detail"><span>اولویت</span><strong><?=e(ManagementMeetingsRepository::PRIORITIES[$d['priority']]??$d['priority'])?></strong></div></div><h3>شرح مصوبه</h3><p><?=nl2br(e($d['description']?:'ثبت نشده'))?></p></section>
<section class="card"><h2>ثبت پیگیری</h2><form method="post" enctype="multipart/form-data" class="mg-form-grid"><input type="hidden" name="_csrf" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="followup"><label>وضعیت جدید<select name="new_status"><?php foreach(ManagementMeetingsRepository::DECISION_STATUSES as $k=>$v):if($k!=='overdue'):?><option value="<?=$k?>" <?=$d['followup_status']===$k?'selected':''?>><?=e($v)?></option><?php endif;endforeach?></select></label><label>درصد پیشرفت<input type="number" name="progress_percent" min="0" max="100" value="<?=(int)$d['progress_percent']?>"></label><label>پیگیری بعدی<?=app_date_input('next_followup_date')?></label><label>پیوست<input type="file" name="attachment" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.webp"></label><label class="wide">یادداشت پیگیری<textarea name="followup_note" rows="4" required></textarea></label><div class="wide mg-actions"><button class="btn btn-primary">ثبت پیگیری</button><?php if((int)$d['progress_percent']===100||$d['followup_status']==='done'):?><button class="btn" name="action" value="verify">تأیید انجام</button><?php endif?></div></form></section>
<section class="card okr-decision-integration" data-okr-reveal><div class="section-heading-row"><div><h2>اتصال مصوبه به OKR</h2><p class="muted">مصوبه را به Objective یا KR متصل کنید و در همان مرحله Initiative یا Task بسازید.</p></div><span class="badge"><?=count($okrLinks)?> اتصال</span></div>
<?php if(ManagementMeetingsRepository::canEditDecision($d,$u)&&$okrObjectives):?><form method="post" class="mg-form-grid" data-okr-decision-form><input type="hidden" name="_csrf" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="link_okr">
<label class="wide">Objective<select name="objective_id" required data-okr-decision-objective><option value="">انتخاب هدف</option><?php foreach($okrObjectives as $objective):?><option value="<?=$objective['id']?>"><?=e($objective['title'].' · '.$objective['owner_name'])?></option><?php endforeach?></select></label>
<label class="wide">Key Result اختیاری<select name="key_result_id" data-okr-decision-kr><option value="">کل Objective</option><?php foreach($okrKeyResults as $objectiveId=>$rows):foreach($rows as $kr):?><option value="<?=$kr['id']?>" data-objective-id="<?=$objectiveId?>"><?=e($kr['title'])?></option><?php endforeach;endforeach?></select></label>
<label>مسئول اقدام<select name="owner_user_id" required><?php foreach($okrOwners as $owner):?><option value="<?=$owner['id']?>" <?=(int)$owner['id']===(int)($d['responsible_user_id']?:$d['created_by'])?'selected':''?>><?=e($owner['name'])?></option><?php endforeach?></select></label>
<label>مهلت<?=app_date_input('due_date',$d['due_date']?:date('Y-m-d'),['required'=>true])?></label>
<label>اولویت<select name="priority"><?php foreach(OkrService::PRIORITIES as $key=>$label):?><option value="<?=$key?>" <?=$key===$d['priority']?'selected':''?>><?=e($label)?></option><?php endforeach?></select></label>
<label class="wide">عنوان Initiative / Task<input name="initiative_title" maxlength="255" required value="<?=e($d['title'])?>"></label>
<label class="wide">شرح<textarea name="initiative_description" rows="4"><?=e($d['description'])?></textarea></label>
<label class="wide">یادداشت ارتباط<input name="link_note" maxlength="500" placeholder="علت ارتباط این مصوبه با نتیجه انتخاب‌شده"></label>
<label><input type="checkbox" name="create_initiative" value="1" checked data-create-initiative> ایجاد Initiative و Task پلنر</label>
<label><input type="checkbox" name="create_task" value="1" data-create-task> فقط ایجاد Task در پلنر</label>
<button class="btn btn-primary">ثبت اتصال و اقدام</button></form><?php elseif(!$okrObjectives):?><div class="mg-empty">Objective قابل مدیریت برای اتصال یافت نشد.</div><?php endif?>
<div class="okr-decision-links"><?php foreach($okrLinks as $link):?><article><div><strong><?=e($link['objective_title'])?></strong><small><?=e($link['key_result_title']?:'کل Objective')?> · پیشرفت <?=e((string)$link['progress_score'])?>٪</small></div><div><?php if($link['initiative_id']):?><span class="badge">Initiative #<?=$link['initiative_id']?></span><?php endif?><?php if($link['planner_task_id']):?><a class="btn btn-small" href="/employee/work-planner.php">Task #<?=$link['planner_task_id']?></a><?php endif?></div></article><?php endforeach?><?php if(!$okrLinks):?><p class="muted">هنوز به OKR متصل نشده است.</p><?php endif?></div>
</section>
<?php if(ManagementMeetingsRepository::canManageRules($u)):?><section class="card"><h2>تبدیل به قانون / نسخه جدید</h2><form method="post" class="mg-form-grid"><input type="hidden" name="_csrf" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="convert_rule"><label>کد قانون<input name="rule_code" maxlength="100" required></label><label>عنوان قانون<input name="title" maxlength="255" required value="<?=e($d['title'])?>"></label><label>تاریخ اجرا<?=app_date_input('effective_date',$d['rule_effective_date']?:date('Y-m-d'),['required'=>true])?></label><label>تاریخ انقضا<?=app_date_input('expire_date',$d['rule_expire_date'])?></label><label>دامنه<select name="scope_type"><option value="company">کل شرکت</option><option value="department">واحد</option><option value="role">نقش</option><option value="sales_line">لاین فروش</option><option value="user">کاربر خاص</option></select></label><label>مقدار دامنه<input name="scope_value" maxlength="190"></label><label><input type="checkbox" name="active" value="1" checked> فعال‌سازی نسخه</label><label class="wide">متن قانون<textarea name="content" rows="7" required><?=e($d['description'])?></textarea></label><button class="btn btn-primary">ذخیره نسخه قانون</button></form></section><?php endif?>
<section class="card"><h2>تاریخچه پیگیری</h2><div class="mg-timeline"><?php foreach($timeline as $f):?><article><header><strong><?=e(ManagementMeetingsRepository::DECISION_STATUSES[$f['new_status']]??$f['new_status'])?> · <?=(int)$f['progress_percent']?>٪</strong><small><?=e(($f['creator_name']??'سیستم').' — '.format_jalali_datetime($f['created_at']))?></small></header><?php if($f['followup_note']):?><p><?=nl2br(e($f['followup_note']))?></p><?php endif?><?php $a=json_decode((string)$f['attachment_json'],true);if(is_array($a)):?><a href="/admin/management-followup-attachment.php?id=<?=$f['id']?>">دریافت پیوست</a><?php endif?></article><?php endforeach?><?php if(!$timeline):?><div class="mg-empty">هنوز پیگیری ثبت نشده است.</div><?php endif?></div></section></div><?php require __DIR__.'/../views/partials/admin-footer.php';?>
