<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../lib/ManagementReportsRepository.php';Auth::requireLogin();$id=(int)($_GET['id']??$_POST['submission_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('اعتبار درخواست منقضی شده است.','danger');redirect('/admin/management-report-view.php?id='.$id);}
    try{$action=(string)($_POST['action']??'');ManagementReportsRepository::review($id,$action,trim((string)($_POST['note']??'')));flash(['approve'=>'گزارش تأیید شد.','return'=>'گزارش برای اصلاح برگشت داده شد.','archive'=>'گزارش بایگانی شد.'][$action]??'وضعیت گزارش بروزرسانی شد.');}catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('Management report view review: '.$e->getMessage());flash('عملیات بررسی انجام نشد.','danger');}redirect('/admin/management-report-view.php?id='.$id);
}
$report=ManagementReportsRepository::submission($id);if(!$report){http_response_code(404);exit('گزارش در دسترس نیست.');}$groups=[];foreach($report['values'] as $value)$groups[$value['section_title']][]=$value;$linkMap=[];foreach($report['links']??[] as $link)$linkMap[(int)($link['field_id']??0)][]=$link;
$print=($_GET['print']??'')==='1';$pageTitle='جزئیات '.(ManagementReportsRepository::TYPES[$report['report_type']]??'گزارش مدیران');$adminExtraStylesheets=['/assets/css/management-reports.css'];if(!$print)require __DIR__.'/../views/partials/admin-header.php';else {?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title><?=e($pageTitle)?></title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/admin.css"><link rel="stylesheet" href="/assets/css/management-reports.css"></head><body class="payroll-output"><?php }
function management_report_value_html(array $value,array $links=[]): string{$type=$value['field_type'];if(in_array($type,['table','repeater'],true)){$rows=json_decode($value['value_json']?:'[]',true)?:[];$options=json_decode($value['options_json']?:'[]',true)?:[];$columns=$options['columns']??[];if(!$rows)return '<span class="muted">بدون ردیف</span>';ob_start();?><div class="table-wrap"><table><thead><tr><?php foreach($columns as $column):?><th><?=e($column['label']??$column['key']??'مقدار')?></th><?php endforeach?></tr></thead><tbody><?php foreach($rows as $row):?><tr><?php foreach($columns as $column):?><td><?=e((string)($row[$column['key']??'']??''))?></td><?php endforeach?></tr><?php endforeach?></tbody></table></div><?php return (string)ob_get_clean();}if($type==='checkbox')return ($value['value_text']??'0')==='1'?'بله':'خیر';if(in_array($type,['currency','amount','number'],true))return e(format_number($value['value_number']));if(in_array($type,['percent','percentage'],true))return e(format_number($value['value_number'])).'٪';if(in_array($type,['date','jalali_date','jalali_deadline'],true))return e(($value['value_text']??'')?format_jalali_date($value['value_text']):'—');if(in_array($type,['task_selector','action_selector','user_selector'],true)){foreach($links as $link){$label=e($link['label']?:'مشاهده مورد مرتبط');if(!empty($link['link_url']))return '<a class="mr-related-link" href="'.e($link['link_url']).'">'.$label.'</a>';return $label;}return '—';}return nl2br(e((string)($value['value_text']??$value['value_number']??'')));}
?>
<main class="<?=$print?'mr-print-paper':''?>"><div class="mr-head"><div><h1><?=e($pageTitle)?></h1><p><?=e($report['period_title'].' — '.$report['submitter_name'])?></p></div><div class="mr-actions no-print"><a class="btn" href="/admin/management-reports.php">بازگشت</a><?php if((int)$report['submitter_id']===(int)Auth::user()['id']&&in_array($report['status'],['draft','returned'],true)):?><a class="btn" href="/admin/management-report-prepare.php?type=<?=e($report['report_type'])?>&id=<?=$report['id']?>">ویرایش</a><?php endif?><a class="btn" target="_blank" href="?id=<?=$id?>&print=1">چاپ / PDF</a><span class="mr-status mr-status-<?=e($report['status'])?>"><?=e(ManagementReportsRepository::STATUSES[$report['status']]??'')?></span></div></div>
<section class="card"><div class="mr-fields"><div class="mr-value"><span>نوع گزارش</span><strong><?=e(ManagementReportsRepository::TYPES[$report['report_type']]??$report['template_title'])?></strong></div><div class="mr-value"><span>دوره</span><strong><?=e($report['period_title'])?></strong></div><div class="mr-value"><span>ثبت‌کننده</span><strong><?=e($report['submitter_name'].' — '.($report['employee_no']?:'بدون شماره پرسنلی'))?></strong></div><div class="mr-value"><span>نسخه قالب</span><strong><?=e($report['template_version_no']??1)?></strong></div></div><?php if($report['return_note']):?><div class="mr-review-note"><strong>توضیح برگشت:</strong> <?=e($report['return_note'])?></div><?php endif?></section>
<?php foreach($groups as $section=>$values):?><section class="card mr-section"><header><h2><?=e($section)?></h2></header><?php foreach($values as $value):?><div class="mr-value"><span><?=e($value['label'])?><?php if($value['linked_source_key']):?> <code class="mr-linked"><?=e($value['linked_source_key'])?></code><?php endif?></span><strong><?=management_report_value_html($value,$linkMap[(int)$value['field_id']]??[])?></strong></div><?php endforeach?></section><?php endforeach?>
<?php $generatedLinks=array_filter($report['links']??[],static fn($link)=>$link['link_type']==='generated_action');if($generatedLinks):?><section class="card"><h2>اقدامات ساخته‌شده از پیشنهادات</h2><div class="mr-actions"><?php foreach($generatedLinks as $link):?><a class="btn" href="<?=e($link['link_url'])?>"><?=e($link['label']?:'مشاهده اقدام')?></a><?php endforeach?></div></section><?php endif?>
<?php if($report['attachments']):?><section class="card"><h2>فایل‌های ضمیمه</h2><div class="mr-actions"><?php foreach($report['attachments'] as $attachment):?><a class="btn" href="/admin/management-report-attachment.php?id=<?=$attachment['id']?>"><?=e(($attachment['field_label']?:'پیوست').' — '.$attachment['original_name'])?></a><?php endforeach?></div></section><?php endif?>
<?php if(!$print&&ManagementReportsRepository::canReview()&&$report['status']==='submitted'):?><section class="card"><h2>بررسی گزارش</h2><div class="mr-actions"><form method="post" onsubmit="return confirm('گزارش تأیید شود؟')"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="submission_id" value="<?=$id?>"><input type="hidden" name="action" value="approve"><button class="btn btn-primary">تأیید گزارش</button></form><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="submission_id" value="<?=$id?>"><input type="hidden" name="action" value="return"><textarea name="note" rows="3" placeholder="توضیح اصلاحات لازم" required></textarea><button class="btn">برگشت برای اصلاح</button></form></div></section><?php endif?>
<?php if(!$print):?><section class="card"><h2>تاریخچه تغییرات و بررسی</h2><div class="mr-timeline"><?php foreach($report['reviews'] as $review):?><article><h3><?=e(['created'=>'ایجاد گزارش','draft_saved'=>'ذخیره پیش‌نویس','submitted'=>'ثبت نهایی','returned'=>'برگشت برای اصلاح','approved'=>'تأیید گزارش','archived'=>'بایگانی','reopened'=>'بازگشایی'][$review['action']]??'بروزرسانی گزارش')?></h3><?php if($review['note']):?><p><?=e($review['note'])?></p><?php endif?><small><?=e(($review['reviewer_name']?:'سیستم').' — '.format_jalali_datetime($review['created_at']))?></small></article><?php endforeach?></div></section><?php endif?></main>
<?php if($print):?><script>addEventListener('load',()=>setTimeout(()=>print(),250))</script></body></html><?php else:require __DIR__.'/../views/partials/admin-footer.php';endif?>
