<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/CeoDashboardExcel.php';require_once __DIR__.'/../lib/ManagementReportsRepository.php';Auth::requireLogin();
$hasAccess=ManagementReportsRepository::canAggregate()||ManagementReportsRepository::canReview();foreach(array_keys(ManagementReportsRepository::TYPES) as $reportType)$hasAccess=$hasAccess||ManagementReportsRepository::canPrepare($reportType);if(!$hasAccess){http_response_code(403);exit('دسترسی غیرمجاز است.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('اعتبار درخواست منقضی شده است.','danger');redirect('/admin/management-reports.php');}
    try{ManagementReportsRepository::review((int)($_POST['submission_id']??0),(string)($_POST['action']??''),trim((string)($_POST['note']??'')));flash(($_POST['action']??'')==='approve'?'گزارش با موفقیت تأیید شد.':(($_POST['action']??'')==='return'?'گزارش برای اصلاح برگشت داده شد.':'گزارش بایگانی شد.'));}
    catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('Management report review: '.$e->getMessage());flash('عملیات بررسی گزارش انجام نشد.','danger');}
    redirect('/admin/management-reports.php'.(!empty($_POST['return_query'])?'?'.ltrim((string)$_POST['return_query'],'?'):''));
}
$filters=['period_key'=>trim((string)($_GET['period_key']??'')),'report_type'=>trim((string)($_GET['report_type']??'')),'submitter_id'=>(int)($_GET['submitter_id']??0),'status'=>trim((string)($_GET['status']??'')),'unit_id'=>(int)($_GET['unit_id']??0),'date_from'=>trim((string)($_GET['date_from']??'')),'date_to'=>trim((string)($_GET['date_to']??''))];
$rows=ManagementReportsRepository::list($filters);$allRows=ManagementReportsRepository::list();$stats=ManagementReportsRepository::stats($allRows);
if(($_GET['action']??'')==='excel'){
    $details=[];$fieldCatalog=[];
    foreach($rows as $row){$detail=ManagementReportsRepository::submission((int)$row['id']);if(!$detail)continue;$details[(int)$row['id']]=$detail;foreach($detail['values'] as $value){$catalogKey=$row['report_type'].'|'.($detail['template_version_no']??1).'|'.$value['field_key'];$fieldCatalog[$catalogKey]=$value['label'].' — نسخه '.($detail['template_version_no']??1);}}
    $headers=['شناسه','نوع گزارش','نسخه قالب','دوره','ثبت‌کننده','واحد','وضعیت','تاریخ ثبت'];foreach($fieldCatalog as $label)$headers[]=$label;$sheet=[$headers];
    foreach($rows as $row){$detail=$details[(int)$row['id']]??null;if(!$detail)continue;$map=[];foreach($detail['values'] as $value){$catalogKey=$row['report_type'].'|'.($detail['template_version_no']??1).'|'.$value['field_key'];$map[$catalogKey]=$value;}$line=[$row['id'],ManagementReportsRepository::TYPES[$row['report_type']]??$row['report_type'],$detail['template_version_no']??1,$row['period_title'],$row['submitter_name'],$row['unit_title'],ManagementReportsRepository::STATUSES[$row['status']]??$row['status'],$row['created_at']];foreach(array_keys($fieldCatalog) as $catalogKey){$value=$map[$catalogKey]??null;$line[]=$value?($value['value_json']!==null?self_join_report_json($value['value_json']):($value['value_number']!==null?$value['value_number']:$value['value_text'])):'';}$sheet[]=$line;}
    CeoDashboardExcel::output(['گزارشات مدیران'=>$sheet],'management-reports-'.date('Y-m-d').'.xlsx');
}
function self_join_report_json(?string $json): string{$rows=json_decode((string)$json,true);if(!is_array($rows))return '';$parts=[];foreach($rows as $row)$parts[]=is_array($row)?implode(' | ',array_values($row)):(string)$row;return implode("\n",$parts);}
$periods=ManagementReportsRepository::periods();$users=Database::fetchAll('SELECT id,name,employee_no FROM users WHERE status="active" ORDER BY name');$units=Database::fetchAll('SELECT id,title FROM org_units WHERE active=1 ORDER BY title');$query=http_build_query(array_filter($filters,static fn($v)=>$v!==''&&$v!==0));
$pageTitle='گزارشات مدیران';$adminExtraStylesheets=['/assets/css/management-reports.css'];require __DIR__.'/../views/partials/admin-header.php';?>
<div class="mr-head"><div><h1>گزارشات مدیران</h1><p>مشاهده، بررسی و خروجی گزارش‌های مدیریتی</p></div><div class="mr-actions"><?php foreach(ManagementReportsRepository::TYPES as $type=>$label):if(ManagementReportsRepository::canPrepare($type)):?><a class="btn" href="/admin/management-report-prepare.php?type=<?=$type?>">ثبت <?=e($label)?></a><?php endif;endforeach?><?php if(ManagementReportsRepository::canManageTemplates()):?><a class="btn btn-primary" href="/admin/management-report-template-settings.php">تنظیمات قالب‌ها</a><?php endif?></div></div>
<div class="mr-kpis"><article class="mr-kpi"><span>پیش‌نویس</span><strong><?=$stats['draft']?></strong></article><article class="mr-kpi"><span>ثبت‌شده</span><strong><?=$stats['submitted']?></strong></article><article class="mr-kpi"><span>تأییدشده</span><strong><?=$stats['approved']?></strong></article><article class="mr-kpi"><span>برگشت‌خورده</span><strong><?=$stats['returned']?></strong></article></div>
<section class="card no-print"><form method="get" class="mr-filter"><label class="form-field"><span>دوره</span><?=app_period_select('period_key',$filters['period_key'],['daily','weekly','monthly','quarterly','half_yearly','yearly'],['placeholder'=>'همه دوره‌ها'])?></label><label class="form-field"><span>نوع گزارش</span><select name="report_type"><option value="">همه انواع</option><?php foreach(ManagementReportsRepository::TYPES as $type=>$label):?><option value="<?=$type?>" <?=$filters['report_type']===$type?'selected':''?>><?=e($label)?></option><?php endforeach?></select></label><label class="form-field"><span>ثبت‌کننده</span><select name="submitter_id"><option value="">همه</option><?php foreach($users as $user):?><option value="<?=$user['id']?>" <?=$filters['submitter_id']===(int)$user['id']?'selected':''?>><?=e($user['name'].' — '.($user['employee_no']?:'بدون شماره'))?></option><?php endforeach?></select></label><label class="form-field"><span>وضعیت</span><select name="status"><option value="">همه</option><?php foreach(ManagementReportsRepository::STATUSES as $status=>$label):?><option value="<?=$status?>" <?=$filters['status']===$status?'selected':''?>><?=e($label)?></option><?php endforeach?></select></label><label class="form-field"><span>واحد</span><select name="unit_id"><option value="">همه</option><?php foreach($units as $unit):?><option value="<?=$unit['id']?>" <?=$filters['unit_id']===(int)$unit['id']?'selected':''?>><?=e($unit['title'])?></option><?php endforeach?></select></label><label class="form-field"><span>از تاریخ (پیشرفته)</span><?=app_date_input('date_from',$filters['date_from'])?></label><label class="form-field"><span>تا تاریخ (پیشرفته)</span><?=app_date_input('date_to',$filters['date_to'])?></label><div class="mr-actions"><button class="btn btn-primary">اعمال فیلتر</button><a class="btn" href="/admin/management-reports.php">پاکسازی</a><a class="btn" href="?<?=e($query.($query?'&':'').'action=excel')?>">خروجی Excel</a></div></form></section>
<section class="card"><div class="table-wrap"><table><thead><tr><th>گزارش</th><th>دوره</th><th>ثبت‌کننده / واحد</th><th>وضعیت</th><th>آخرین تغییر</th><th>عملیات</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><strong><?=e(ManagementReportsRepository::TYPES[$row['report_type']]??$row['template_title'])?></strong><small>#<?=$row['id']?></small></td><td><?=e($row['period_title'])?></td><td><?=e($row['submitter_name'])?><small><?=e($row['unit_title']?:'بدون واحد')?></small></td><td><span class="mr-status mr-status-<?=e($row['status'])?>"><?=e(ManagementReportsRepository::STATUSES[$row['status']]??'')?></span></td><td><?=e(format_jalali_datetime($row['updated_at']))?></td><td><div class="mr-actions"><a class="btn btn-small" href="/admin/management-report-view.php?id=<?=$row['id']?>">جزئیات</a><?php if((int)$row['submitter_id']===(int)Auth::user()['id']&&in_array($row['status'],['draft','returned'],true)):?><a class="btn btn-small" href="/admin/management-report-prepare.php?type=<?=e($row['report_type'])?>&id=<?=$row['id']?>">ویرایش</a><?php endif?><?php if(ManagementReportsRepository::canReview()&&$row['status']==='submitted'):?><form method="post" onsubmit="return confirm('گزارش تأیید شود؟')"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="submission_id" value="<?=$row['id']?>"><input type="hidden" name="action" value="approve"><input type="hidden" name="return_query" value="<?=e($query)?>"><button class="btn btn-small btn-primary">تأیید</button></form><details><summary class="btn btn-small">برگشت</summary><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="submission_id" value="<?=$row['id']?>"><input type="hidden" name="action" value="return"><input type="hidden" name="return_query" value="<?=e($query)?>"><textarea name="note" rows="3" placeholder="توضیح اصلاحات لازم" required></textarea><button class="btn btn-small">ثبت برگشت</button></form></details><?php endif?></div></td></tr><?php endforeach?><?php if(!$rows):?><tr><td colspan="6"><div class="mr-empty">گزارشی مطابق فیلترها پیدا نشد.</div></td></tr><?php endif?></tbody></table></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
