<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Database.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/ManagerDashboard.php';
Auth::requireLogin();if(!Auth::can('manager_dashboard.import')){http_response_code(403);exit('شما اجازه ایمپورت اکسل را ندارید.');}$pageTitle='ورودی / خروجی اکسل';$result=null;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 Auth::requirePermission('manager_dashboard.import');if(!Auth::verifyCsrf($_POST['csrf_token']??null)){http_response_code(419);exit('درخواست نامعتبر است.');}
 $maxBytes=max(1,(int)ManagerDashboard::setting('excel_max_size_mb'))*1024*1024;
 if(!isset($_FILES['excel'])||$_FILES['excel']['error']!==UPLOAD_ERR_OK)$error='فایل اکسل معتبر انتخاب کنید.';
 elseif($_FILES['excel']['size']>$maxBytes)$error='حجم فایل از حد مجاز بیشتر است.';
 elseif(strtolower(pathinfo($_FILES['excel']['name'],PATHINFO_EXTENSION))!=='xlsx')$error='فرمت فایل باید xlsx باشد.';
 elseif(file_get_contents($_FILES['excel']['tmp_name'],false,null,0,2)!=='PK')$error='ساختار فایل XLSX معتبر نیست.';
 else{$user=Auth::user();$safeName=preg_replace('/[^\pL\pN._-]+/u','-',basename($_FILES['excel']['name']));$strict=isset($_POST['strict'])||ManagerDashboard::setting('excel_strict_default')==='1';$result=ManagerDashboard::import($_FILES['excel']['tmp_name'],$safeName,$_POST['mode']??'append',(int)$user['id'],trim($_POST['report_title']??''),$strict);if(!empty($result['report_id']))Auth::log((int)$user['id'],'import','manager_dashboard',(int)$result['report_id']);}
}
require __DIR__.'/../views/partials/admin-header.php';?>
<div class="manager-import-grid"><section class="card"><h2>ورود گزارش اکسل</h2><p>فایل باید دقیقاً از قالب چندشیتی همین سامانه پیروی کند. خطاهای هر ردیف جداگانه گزارش می‌شوند.</p><?php if($error):?><div class="alert alert-error"><?=e($error)?></div><?php endif?><form method="post" enctype="multipart/form-data" class="manager-form-grid"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><label><span>عنوان گزارش</span><input name="report_title" placeholder="گزارش فروش خرداد"></label><label><span>حالت به‌روزرسانی</span><select name="mode"><option value="append">افزودن گزارش جدید</option><option value="replace">جایگزینی گزارش فعلی</option><option value="numeric">به‌روزرسانی فقط فیلدهای عددی</option></select></label><label class="full"><span>فایل اکسل</span><input type="file" name="excel" accept=".xlsx" required></label><label class="toggle-row"><input type="checkbox" name="strict"><span>حالت سخت‌گیرانه (با اولین خطا کل ورود متوقف شود)</span></label><div class="full actions"><a class="btn btn-light" href="/admin/manager-dashboard-export.php?template=1">دانلود قالب اکسل</a><button class="btn">بررسی و ورود فایل</button></div></form></section><aside class="card"><h2>قالب و خروجی</h2><p>قالب شامل ۱۱ شیت با عنوان و سرستون‌های فارسی استاندارد است.</p><div class="actions"><a class="btn" href="/admin/manager-dashboard-export.php?template=1">دانلود قالب اکسل</a><?php if(Auth::can('manager_dashboard.export')):?><a class="btn btn-light" href="/admin/manager-dashboard-export.php">خروجی آخرین گزارش</a><?php endif?></div><hr><h3>راهنمای کوتاه</h3><ol><li>قالب را دریافت کنید.</li><li>نام شیت‌ها و ترتیب ستون‌ها را تغییر ندهید.</li><li>اعداد فارسی، عربی، انگلیسی، جداکننده هزارگان و علامت درصد پذیرفته می‌شوند.</li><li>فایل تکمیل‌شده را با حالت مناسب وارد کنید.</li></ol></aside></div>
<?php if($result):?><section class="card import-result"><h2>خلاصه ورود</h2><div class="manager-kpis"><article><span>کل ردیف‌ها</span><strong><?=$result['total']?></strong></article><article><span>واردشده</span><strong><?=$result['imported']?></strong></article><article><span>به‌روزشده</span><strong><?=$result['updated']?></strong></article><article><span>ردشده</span><strong><?=$result['skipped']?></strong></article><article><span>خطاها</span><strong><?=count($result['errors'])?></strong></article></div><?php if($result['errors']):?><div class="table-wrap"><table><thead><tr><th>شیت</th><th>ردیف</th><th>خطا</th></tr></thead><tbody><?php foreach($result['errors'] as $e):?><tr><td><?=e($e['sheet'])?></td><td><?=e((string)$e['row'])?></td><td><?=e($e['message'])?></td></tr><?php endforeach?></tbody></table></div><?php endif?><?php if(!empty($result['report_id'])):?><a class="btn" href="/admin/manager-dashboard.php?report_id=<?=$result['report_id']?>">مشاهده گزارش واردشده</a><?php endif?></section><?php endif?>
</section></main></div><script src="/assets/js/app.js"></script></body></html>
