<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../services/NotificationHubService.php';
Auth::requireLogin();$user=Auth::user();$userId=(int)$user['id'];$pageTitle='اتصال Sobhan Notification Hub';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Auth::verifyCsrf($_POST['csrf_token']??null)){flash('اعتبار درخواست منقضی شده است.','danger');redirect('/admin/notification-devices.php');}
    try{$action=(string)($_POST['action']??'');if($action==='pair'){$pair=NotificationHubService::createPairingCode($userId);Auth::start();$_SESSION['notification_pair_code']=$pair;flash('کد اتصال جدید ساخته شد؛ این کد فقط پنج دقیقه معتبر است.');}
        elseif($action==='revoke'){$id=(int)($_POST['device_id']??0);Database::execute('UPDATE sobhan_notification_devices SET active=0,revoked_at=NOW(),updated_at=NOW() WHERE id=? AND user_id=?',[$id,$userId]);Auth::log($userId,'notification_device_revoked','notification_hub',$id);flash('اتصال دستگاه لغو شد.');}
        else throw new InvalidArgumentException('عملیات معتبر نیست.');
    }catch(Throwable $e){error_log('notification devices admin: '.$e->getMessage());flash('انجام عملیات ممکن نشد. لطفاً دوباره تلاش کنید.','danger');}redirect('/admin/notification-devices.php');
}
Auth::start();$pair=$_SESSION['notification_pair_code']??null;unset($_SESSION['notification_pair_code']);$devices=Database::fetchAll('SELECT * FROM sobhan_notification_devices WHERE user_id=? ORDER BY active DESC,id DESC',[$userId]);
require __DIR__.'/../views/partials/admin-header.php';?>
<div class="manager-hero"><div><span>اعلان ویندوز بدون نیاز به مرورگر</span><h1>Sobhan Notification Hub</h1><p>اتصال امن و اختصاصی دستگاه‌های ویندوز به حساب شما</p></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><button class="btn" name="action" value="pair">اتصال این ویندوز به پنل من</button></form></div>
<?php if($pair):?><section class="card" style="text-align:center"><h2>کد اتصال موقت</h2><strong style="font:700 2.5rem monospace;letter-spacing:.35em;direction:ltr;display:block;margin:18px"><?=e($pair['code'])?></strong><p>کد را در برنامه ویندوز وارد کنید. اعتبار آن پنج دقیقه و فقط برای یک‌بار استفاده است.</p></section><?php endif?>
<section class="card"><h2>دستگاه‌های متصل</h2><div class="table-wrap"><table><thead><tr><th>دستگاه</th><th>نسخه</th><th>آخرین ارتباط</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody><?php foreach($devices as $device):?><tr><td><?=e($device['device_name'])?><small style="display:block"><?=e($device['device_uid'])?></small></td><td><?=e($device['app_version'])?></td><td><?=e($device['last_seen_at']?format_jalali_datetime($device['last_seen_at']):'هنوز متصل نشده')?></td><td><span class="badge"><?=$device['active']?'فعال':'لغوشده'?></span></td><td><?php if($device['active']):?><form method="post" onsubmit="return confirm('اتصال این دستگاه لغو شود؟')"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="device_id" value="<?=$device['id']?>"><button class="link-btn danger" name="action" value="revoke">قطع اتصال</button></form><?php else:?>—<?php endif?></td></tr><?php endforeach?><?php if(!$devices):?><tr><td colspan="5">هنوز دستگاهی متصل نشده است.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><h2>روش اتصال</h2><ol><li>برنامه Sobhan Notification Hub را روی ویندوز اجرا کنید.</li><li>دکمه «اتصال این ویندوز» را بزنید.</li><li>کد شش‌رقمی را در برنامه وارد کنید.</li><li>توکن دستگاه فقط به‌صورت رمزنگاری‌شده در ویندوز ذخیره می‌شود.</li></ol></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
