<?php
require_once __DIR__ . '/../core/Auth.php';
require_once __DIR__ . '/../core/Database.php';
require_once __DIR__ . '/../core/Response.php';
require_once __DIR__ . '/../services/SalesOperationsService.php';
SalesOperationsService::boot(); SalesOperationsService::requireSalesManagerPermission('sales_manager.purchase_suggestions.manage');
$user=Auth::user();$errors=[];$allowedStatuses=['draft','submitted','under_review','approved','rejected','needs_revision','converted_to_purchase_order'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!Auth::verifyCsrf($_POST['csrf_token']??null)) throw new RuntimeException('درخواست نامعتبر است.');
  $id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'draft');if(!in_array($status,$allowedStatuses,true))$status='draft';$suggestionDate=app_date_to_iso($_POST['suggestion_date']??'');if(!$suggestionDate)throw new InvalidArgumentException('تاریخ پیشنهاد معتبر نیست.');$managerId=SalesOperationsService::canViewAll($user)?(int)($_POST['sales_manager_id']??0):(int)$user['id'];if(!SalesOperationsService::isSalesManagerUserId($managerId))throw new InvalidArgumentException('مدیر فروش معتبر نیست.');
  $params=[$suggestionDate,$managerId,$_POST['sales_line']??null,(int)($_POST['brand_id']??0)?:null,(int)($_POST['product_id']??0)?:null,(float)($_POST['suggested_quantity']??0),trim((string)($_POST['reason']??'')),trim((string)($_POST['market_demand_note']??'')),trim((string)($_POST['requested_by_customers']??'')),($_POST['current_stock']??'')===''?null:(float)$_POST['current_stock'],($_POST['current_month_sales']??'')===''?null:(float)$_POST['current_month_sales'],($_POST['previous_month_sales']??'')===''?null:(float)$_POST['previous_month_sales'],$_POST['shortage_risk']??null,SalesOperationsService::validPriority($_POST['priority']??'normal'),$status,trim((string)($_POST['purchasing_comment']??'')),trim((string)($_POST['management_comment']??'')),(int)$user['id'],(int)$user['id']];
  if($params[6]==='') throw new InvalidArgumentException('دلیل پیشنهاد خرید اجباری است.');
  if($id){$old=Database::fetch('SELECT * FROM sales_purchase_suggestions WHERE id=?',[$id]);if(!$old||(!SalesOperationsService::canViewAll($user)&&(int)$old['sales_manager_id']!==(int)$user['id']))throw new InvalidArgumentException('دسترسی ویرایش این پیشنهاد را ندارید.');Database::execute('UPDATE sales_purchase_suggestions SET suggestion_date=?,sales_manager_id=?,sales_line=?,brand_id=?,product_id=?,suggested_quantity=?,reason=?,market_demand_note=?,requested_by_customers=?,current_stock=?,current_month_sales=?,previous_month_sales=?,shortage_risk=?,priority=?,status=?,purchasing_comment=?,management_comment=?,updated_by=?,updated_at=NOW() WHERE id=?',array_merge(array_slice($params,0,18),[$id]));Database::execute('INSERT INTO sales_purchase_suggestion_logs(suggestion_id,action,old_value_json,new_value_json,performed_by,created_at) VALUES (?,?,?,?,?,NOW())',[$id,'update',json_encode($old,JSON_UNESCAPED_UNICODE),json_encode(['status'=>$status,'manager_id'=>$managerId],JSON_UNESCAPED_UNICODE),(int)$user['id']]);}
  else{Database::execute('INSERT INTO sales_purchase_suggestions(suggestion_date,sales_manager_id,sales_line,brand_id,product_id,suggested_quantity,reason,market_demand_note,requested_by_customers,current_stock,current_month_sales,previous_month_sales,shortage_risk,priority,status,purchasing_comment,management_comment,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',$params);$newId=(int)Database::connection()->lastInsertId();Database::execute('INSERT INTO sales_purchase_suggestion_logs(suggestion_id,action,new_value_json,performed_by,created_at) VALUES (?,?,?, ?,NOW())',[$newId,'create',json_encode($_POST,JSON_UNESCAPED_UNICODE),(int)$user['id']]);}
  flash('پیشنهاد اردر خرید ذخیره شد.');redirect('/admin/sales-purchase-suggestions.php');
 }catch(Throwable $e){$errors[]=SalesOperationsService::uiError($e,'ذخیره پیشنهاد خرید انجام نشد.');}
}
$where=[];$params=[];if(!SalesOperationsService::canViewAll($user)){$where[]='p.sales_manager_id=?';$params[]=(int)$user['id'];}$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$rows=Database::fetchAll("SELECT p.*,u.name manager_name FROM sales_purchase_suggestions p LEFT JOIN users u ON u.id=p.sales_manager_id {$whereSql} ORDER BY p.suggestion_date DESC,p.id DESC LIMIT 200",$params);
$managers=Database::fetchAll('SELECT DISTINCT u.id,u.name FROM users u LEFT JOIN sales_team_assignments a ON a.sales_manager_id=u.id AND a.active=1 WHERE u.status="active" AND (u.role_key IN ("SALES_MANAGER","sales_manager","مدیر فروش") OR a.id IS NOT NULL) ORDER BY u.name LIMIT 500');
$pageTitle='پیشنهاد اردر خرید';require __DIR__ . '/../views/partials/admin-header.php';
?>
<div class="section-heading-row"><div><h1>پیشنهاد اردر خرید</h1><p class="muted">ثبت نیاز بازار، کمبود کالا و پیشنهاد خرید برای پیگیری بازرگانی / مدیریت.</p></div><div class="actions"><a class="btn" href="/admin/sales-manager-supervisor-reports.php">گزارش سرپرستان</a></div></div>
<?php foreach($errors as $error):?><div class="alert alert-danger"><?=e($error)?></div><?php endforeach;?>
<form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><h2>ثبت پیشنهاد خرید</h2><div class="grid grid-4"><label class="form-field"><span>تاریخ پیشنهاد</span><?=app_date_input('suggestion_date',date('Y-m-d'))?></label><?php if(SalesOperationsService::canViewAll($user)):?><label class="form-field"><span>مدیر فروش</span><select name="sales_manager_id"><?php foreach($managers as $m):?><option value="<?=(int)$m['id']?>"><?=e($m['name'])?></option><?php endforeach;?></select></label><?php endif;?><label class="form-field"><span>لاین فروش</span><input name="sales_line"></label><label class="form-field"><span>شناسه برند</span><input type="number" name="brand_id"></label><label class="form-field"><span>شناسه کالا</span><input type="number" name="product_id"></label><label class="form-field"><span>تعداد پیشنهادی</span><input type="number" step="0.01" name="suggested_quantity"></label><label class="form-field"><span>موجودی فعلی</span><input type="number" step="0.01" name="current_stock"></label><label class="form-field"><span>فروش ماه جاری</span><input type="number" step="0.01" name="current_month_sales"></label><label class="form-field"><span>فروش ماه قبل</span><input type="number" step="0.01" name="previous_month_sales"></label><label class="form-field"><span>ریسک کمبود</span><input name="shortage_risk" placeholder="پایین / متوسط / بالا"></label><label class="form-field"><span>اولویت</span><select name="priority"><option value="normal">متوسط</option><option value="high">بالا</option><option value="urgent">فوری</option><option value="low">پایین</option></select></label><label class="form-field"><span>وضعیت</span><select name="status"><option value="draft">پیش‌نویس</option><option value="submitted">ارسال‌شده</option><option value="under_review">در حال بررسی</option><option value="approved">تأیید شد</option><option value="rejected">رد شد</option><option value="needs_revision">نیازمند بازبینی</option></select></label></div><label class="form-field"><span>دلیل پیشنهاد</span><textarea name="reason" required rows="3"></textarea></label><div class="grid grid-2"><label class="form-field"><span>یادداشت تقاضای بازار</span><textarea name="market_demand_note" rows="3"></textarea></label><label class="form-field"><span>مشتریان درخواست‌کننده</span><textarea name="requested_by_customers" rows="3"></textarea></label></div><div class="grid grid-2"><label class="form-field"><span>نظر بازرگانی</span><textarea name="purchasing_comment" rows="3"></textarea></label><label class="form-field"><span>نظر مدیریت</span><textarea name="management_comment" rows="3"></textarea></label></div><div class="form-actions"><button class="btn btn-primary">ثبت پیشنهاد خرید</button></div></form>
<section class="card"><h2>لیست پیشنهادها</h2><div class="table-wrap"><table><thead><tr><th>تاریخ</th><th>مدیر فروش</th><th>لاین</th><th>برند</th><th>کالا</th><th>تعداد</th><th>اولویت</th><th>وضعیت</th><th>دلیل</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e(format_jalali_date($r['suggestion_date']))?></td><td><?=e($r['manager_name']??'-')?></td><td><?=e($r['sales_line']??'-')?></td><td><?=e((string)($r['brand_id']??'-'))?></td><td><?=e((string)($r['product_id']??'-'))?></td><td><?=e(number_format((float)$r['suggested_quantity']))?></td><td><?=e(SalesOperationsService::priorityLabel($r['priority']))?></td><td><span class="badge"><?=e(SalesOperationsService::statusLabel($r['status']))?></span></td><td><?=e(mb_substr((string)$r['reason'],0,100))?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="9">پیشنهادی ثبت نشده است.</td></tr><?php endif;?></tbody></table></div></section>
<?php require __DIR__ . '/../views/partials/admin-footer.php'; ?>
