<?php
require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../services/SalesOfferBudgetService.php';
SalesOfferBudgetService::repairSchema();SalesOfferBudgetService::requireAccess();$user=Auth::user();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST')try{if(!Auth::verifyCsrf($_POST['csrf_token']??null))throw new InvalidArgumentException('درخواست معتبر نیست.');$id=SalesOfferBudgetService::createRequest($_POST,(int)$user['id']);flash('استعلام بودجه آفر ثبت شد.');redirect('/admin/sales-offer-budget-view.php?id='.$id);}catch(Throwable $e){$errors[]=SalesOfferBudgetService::uiError($e,'ثبت استعلام انجام نشد.');}
$filters=$_GET;$rows=SalesOfferBudgetService::listRequests($filters,$user);$formulaSettings=SalesOfferBudgetService::getAvailableFormulaSettings();$defaultSettings=json_decode((string)($formulaSettings[0]['settings_json']??''),true)?:[];$defaultRate=(float)($defaultSettings['default_offer_rate']??0);$summary=['count'=>count($rows),'budget'=>array_sum(array_map(fn($r)=>(float)$r['provisional_budget'],$rows)),'pending'=>count(array_filter($rows,fn($r)=>in_array($r['status'],['submitted','under_review'],true))),'approved'=>count(array_filter($rows,fn($r)=>$r['status']==='approved'))];
$activeTab=(string)($_GET['tab']??'report');if(!in_array($activeTab,['requests','report'],true))$activeTab='report';$reportRows=[];$reportError='';if($activeTab==='report'){try{$reportRows=SalesOfferBudgetService::finalBrandReport($_GET,$user);}catch(Throwable $e){error_log('Offer budget report: '.$e->getMessage());$reportError='گزارش نهایی بودجه آفر در حال حاضر قابل بارگذاری نیست.';}}
$pageTitle='استعلام بودجه آفر';require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="offer-budget-page"><div class="section-heading-row"><div><h1>استعلام بودجه آفر</h1><p class="muted">گزارش نهایی به‌صورت خودکار از آخرین داده‌های فعال نمایش داده می‌شود؛ برای ثبت درخواست دستی، تب استعلام‌ها را باز کنید.</p></div><?php if(SalesOfferBudgetService::isAdmin($user)):?><a class="btn" href="/admin/sales-offer-formula-settings.php">تنظیمات فرمول</a><?php endif;?></div>
<?php foreach($errors as $error):?><div class="alert alert-danger"><?=e($error)?></div><?php endforeach;?>
<div class="grid grid-4 offer-budget-stats"><div class="card"><strong>تعداد استعلام‌ها</strong><h2><?=format_number($summary['count'])?></h2></div><div class="card"><strong>بودجه پیشنهادی کل</strong><h2><?=format_money($summary['budget'])?></h2></div><div class="card"><strong>در انتظار بررسی</strong><h2><?=format_number($summary['pending'])?></h2></div><div class="card"><strong>تأیید شده</strong><h2><?=format_number($summary['approved'])?></h2></div></div>
<nav class="card offer-budget-tabs" aria-label="بخش‌های بودجه آفر"><a class="btn <?=$activeTab==='report'?'btn-primary':''?>" href="/admin/sales-offer-budget.php?tab=report">مشاهده بودجه آفر</a><a class="btn <?=$activeTab==='requests'?'btn-primary':''?>" href="/admin/sales-offer-budget.php?tab=requests">استعلام‌ها</a></nav>
<?php if($activeTab==='requests'): ?>
<form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><h2>استعلام جدید</h2><div class="grid grid-4">
<label class="form-field"><span>دوره</span><?=app_period_select('period_key',$_POST['period_key']??null,[],['placeholder'=>'انتخاب دوره','custom_target'=>'#offer-custom-dates'])?></label>
<div class="app-custom-period grid grid-2" id="offer-custom-dates"><label class="form-field"><span>از تاریخ</span><?=app_date_input('date_from',$_POST['date_from']??null)?></label><label class="form-field"><span>تا تاریخ</span><?=app_date_input('date_to',$_POST['date_to']??null)?></label></div>
<?php foreach(['sales_line'=>'لاین فروش','product_code'=>'کد کالا','product_name'=>'نام کالا','brand_name'=>'برند','supplier_name'=>'تأمین‌کننده'] as $name=>$label):?><label class="form-field"><span><?=e($label)?></span><input name="<?=e($name)?>" value="<?=e($_POST[$name]??($name==='sales_line'?($user['sales_line']??''):''))?>"></label><?php endforeach;?>
<?php foreach(['purchase_price'=>'قیمت خرید','requested_offer_qty'=>'تعداد آفر درخواستی','sold_qty'=>'تعداد فروش','sold_amount'=>'مبلغ فروش','provisional_offer_rate'=>'نرخ موقت آفر (مثلاً 0.1)'] as $name=>$label):?><label class="form-field"><span><?=e($label)?></span><input type="number" min="0" step="0.0001" name="<?=e($name)?>" value="<?=e((string)($_POST[$name]??($name==='provisional_offer_rate'?$defaultRate:0)))?>"></label><?php endforeach;?></div><label class="form-field"><span>یادداشت مدیر</span><textarea name="manager_note" rows="3"><?=e($_POST['manager_note']??'')?></textarea></label><button class="btn btn-primary">ثبت و محاسبه مقدماتی</button></form>
<form class="card admin-form" method="get"><h2>فیلترها</h2><div class="grid grid-4"><label class="form-field"><span>دوره</span><?=app_period_select('period_key',$_GET['period_key']??null,['daily','weekly','monthly','quarterly','half_yearly','yearly'],['placeholder'=>'همه دوره‌ها'])?></label><label class="form-field"><span>از تاریخ</span><?=app_date_input('date_from',$_GET['date_from']??null)?></label><label class="form-field"><span>تا تاریخ</span><?=app_date_input('date_to',$_GET['date_to']??null)?></label><?php foreach(['sales_line'=>'لاین','product'=>'کد یا نام کالا','brand_name'=>'برند'] as $n=>$l):?><label class="form-field"><span><?=e($l)?></span><input name="<?=e($n)?>" value="<?=e($_GET[$n]??'')?>"></label><?php endforeach;?><label class="form-field"><span>وضعیت</span><select name="status"><option value="">همه</option><?php foreach(SalesOfferBudgetService::STATUSES as $s):?><option value="<?=e($s)?>" <?=($_GET['status']??'')===$s?'selected':''?>><?=e(SalesOfferBudgetService::statusLabel($s))?></option><?php endforeach;?></select></label></div><button class="btn">اعمال فیلتر</button></form>
<section class="card"><h2>تاریخچه استعلام‌ها</h2><div class="table-wrap"><table><thead><tr><th>کد</th><th>کالا / برند</th><th>لاین / دوره</th><th>بودجه مقدماتی</th><th>وضعیت</th><th>ثبت‌کننده</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['request_code'])?></td><td><?=e(trim(($r['product_code']??'').' '.($r['product_name']??'')))?><br><small><?=e($r['brand_name']??'')?></small></td><td><?=e($r['sales_line']??'-')?> / <?=e($r['period_key']??'-')?></td><td><?=format_money($r['provisional_budget'])?></td><td><span class="badge"><?=e(SalesOfferBudgetService::statusLabel($r['status']))?></span></td><td><?=e($r['requested_by_name']??'-')?></td><td><a class="btn" href="/admin/sales-offer-budget-view.php?id=<?=(int)$r['id']?>">مشاهده</a></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="7">استعلامی یافت نشد.</td></tr><?php endif;?></tbody></table></div></section>
<?php else: ?>
<section class="card offer-budget-report-panel"><div class="section-heading-row"><div><h2>مشاهده بودجه آفر</h2><p class="muted">معادل عملیاتی شیت «نهایی (2)»: ابتدا ستون‌های کلی و سپس ۱۲ ماه گردش از فروردین تا اسفند نمایش داده می‌شوند. بعد از فعال‌سازی هر Batch، این گزارش بدون ورود مجدد به Excel به‌روز می‌شود.</p></div></div><form class="admin-form offer-budget-report-filters" method="get"><input type="hidden" name="tab" value="report"><div class="grid grid-4"><label class="form-field"><span>سال شمسی</span><input name="year" inputmode="numeric" value="<?=e((string)($_GET['year']??''))?>" placeholder="مثلاً ۱۴۰۵"></label><label class="form-field"><span>ماه گردش</span><select name="month"><option value="">همه ماه‌ها</option><?php foreach(SalesOfferBudgetService::reportMonths() as $m=>$label):?><option value="<?=$m?>" <?=((string)($_GET['month']??''))===(string)$m?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label class="form-field"><span>برند</span><input name="brand" value="<?=e((string)($_GET['brand']??''))?>"></label><div class="form-actions"><button class="btn btn-primary">نمایش گزارش</button></div></div></form><?php if($reportError):?><div class="alert alert-danger"><?=e($reportError)?></div><?php endif;?><div class="table-wrap"><table class="offer-budget-report"><thead><tr><th>اسم برند</th><th>فروش کل</th><th>تخفیف کل</th><th>درصد تخفیف</th><th>بودجه کلی برند</th><?php foreach(SalesOfferBudgetService::reportMonths() as $label):?><th><?=e($label)?></th><?php endforeach;?><?php foreach(SalesOfferBudgetService::reportMonths() as $label):?><th>مشتری فعال <?=e($label)?></th><?php endforeach;?><th>توضیحات</th></tr></thead><tbody><?php foreach($reportRows as $reportRow):?><tr><td><?=e($reportRow['brand_name'])?></td><td><?=format_money($reportRow['gross_amount'])?></td><td><?=format_money($reportRow['discount_amount'])?></td><td><?=e(format_percent((float)$reportRow['discount_rate']*100,1))?></td><td><?=e(format_percent((float)$reportRow['budget_rate']*100,1))?></td><?php foreach(SalesOfferBudgetService::reportMonths() as $m=>$label):?><td><?=e(format_percent((float)($reportRow['discount_m'.$m]??0)*100,1))?></td><?php endforeach;?><?php foreach(SalesOfferBudgetService::reportMonths() as $m=>$label):?><td><?=e(format_number($reportRow['active_m'.$m]??0))?></td><?php endforeach;?><td><?=((float)$reportRow['discount_rate']>(float)$reportRow['budget_rate'])?'بررسی گردد':''?></td></tr><?php endforeach;?><?php if(!$reportRows):?><tr><td colspan="30">داده فعالی برای این فیلتر پیدا نشد.</td></tr><?php endif;?></tbody></table></div></section>
<?php endif; ?></div><style>.offer-budget-tabs{display:flex;gap:8px;flex-wrap:wrap;padding:8px}.offer-budget-stats{gap:10px}.offer-budget-stats .card{padding:12px 14px}.offer-budget-stats h2{margin:6px 0 0;font-size:1.2rem}.offer-budget-page .admin-form{padding:14px}.offer-budget-page .form-field{gap:4px}.offer-budget-report-panel{padding:14px}.offer-budget-report-filters{margin:0 0 12px}.offer-budget-report{min-width:1180px;font-size:.84rem}.offer-budget-report th,.offer-budget-report td{white-space:nowrap;padding:7px 9px}.offer-budget-report thead th{position:sticky;top:0;z-index:1}.offer-budget-report td:last-child{font-weight:700;color:#9a3412}.offer-budget-page .table-wrap{overflow:auto}</style>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
