<?php
require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../services/SalesOfferBudgetService.php';
SalesOfferBudgetService::repairSchema();SalesOfferBudgetService::requireAccess();$user=Auth::user();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST')try{if(!Auth::verifyCsrf($_POST['csrf_token']??null))throw new InvalidArgumentException('درخواست معتبر نیست.');$id=SalesOfferBudgetService::createRequest($_POST,(int)$user['id']);flash('استعلام بودجه آفر ثبت شد.');redirect('/admin/sales-offer-budget-view.php?id='.$id);}catch(Throwable $e){$errors[]=SalesOfferBudgetService::uiError($e,'ثبت استعلام انجام نشد.');}
$filters=$_GET;$rows=SalesOfferBudgetService::listRequests($filters,$user);$formulaSettings=SalesOfferBudgetService::getAvailableFormulaSettings();$defaultSettings=json_decode((string)($formulaSettings[0]['settings_json']??''),true)?:[];$defaultRate=(float)($defaultSettings['default_offer_rate']??0);$summary=['count'=>count($rows),'budget'=>array_sum(array_map(fn($r)=>(float)$r['provisional_budget'],$rows)),'pending'=>count(array_filter($rows,fn($r)=>in_array($r['status'],['submitted','under_review'],true))),'approved'=>count(array_filter($rows,fn($r)=>$r['status']==='approved'))];
$pageTitle='استعلام بودجه آفر';require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="section-heading-row"><div><h1>استعلام بودجه آفر</h1><p class="muted">محاسبه فعلی مقدماتی است؛ فرمول نهایی پس از دریافت فایل Excel تکمیل می‌شود.</p></div><?php if(SalesOfferBudgetService::isAdmin($user)):?><a class="btn" href="/admin/sales-offer-formula-settings.php">تنظیمات فرمول</a><?php endif;?></div>
<?php foreach($errors as $error):?><div class="alert alert-danger"><?=e($error)?></div><?php endforeach;?>
<div class="grid grid-4"><div class="card"><strong>تعداد استعلام‌ها</strong><h2><?=format_number($summary['count'])?></h2></div><div class="card"><strong>بودجه پیشنهادی کل</strong><h2><?=format_money($summary['budget'])?></h2></div><div class="card"><strong>در انتظار بررسی</strong><h2><?=format_number($summary['pending'])?></h2></div><div class="card"><strong>تأیید شده</strong><h2><?=format_number($summary['approved'])?></h2></div></div>
<form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><h2>استعلام جدید</h2><div class="grid grid-4">
<label class="form-field"><span>دوره</span><?=app_period_select('period_key',$_POST['period_key']??null,[],['placeholder'=>'انتخاب دوره','custom_target'=>'#offer-custom-dates'])?></label>
<div class="app-custom-period grid grid-2" id="offer-custom-dates"><label class="form-field"><span>از تاریخ</span><?=app_date_input('date_from',$_POST['date_from']??null)?></label><label class="form-field"><span>تا تاریخ</span><?=app_date_input('date_to',$_POST['date_to']??null)?></label></div>
<?php foreach(['sales_line'=>'لاین فروش','product_code'=>'کد کالا','product_name'=>'نام کالا','brand_name'=>'برند','supplier_name'=>'تأمین‌کننده'] as $name=>$label):?><label class="form-field"><span><?=e($label)?></span><input name="<?=e($name)?>" value="<?=e($_POST[$name]??($name==='sales_line'?($user['sales_line']??''):''))?>"></label><?php endforeach;?>
<?php foreach(['purchase_price'=>'قیمت خرید','requested_offer_qty'=>'تعداد آفر درخواستی','sold_qty'=>'تعداد فروش','sold_amount'=>'مبلغ فروش','provisional_offer_rate'=>'نرخ موقت آفر (مثلاً 0.1)'] as $name=>$label):?><label class="form-field"><span><?=e($label)?></span><input type="number" min="0" step="0.0001" name="<?=e($name)?>" value="<?=e((string)($_POST[$name]??($name==='provisional_offer_rate'?$defaultRate:0)))?>"></label><?php endforeach;?></div><label class="form-field"><span>یادداشت مدیر</span><textarea name="manager_note" rows="3"><?=e($_POST['manager_note']??'')?></textarea></label><button class="btn btn-primary">ثبت و محاسبه مقدماتی</button></form>
<form class="card admin-form" method="get"><h2>فیلترها</h2><div class="grid grid-4"><label class="form-field"><span>دوره</span><?=app_period_select('period_key',$_GET['period_key']??null,['daily','weekly','monthly','quarterly','half_yearly','yearly'],['placeholder'=>'همه دوره‌ها'])?></label><label class="form-field"><span>از تاریخ</span><?=app_date_input('date_from',$_GET['date_from']??null)?></label><label class="form-field"><span>تا تاریخ</span><?=app_date_input('date_to',$_GET['date_to']??null)?></label><?php foreach(['sales_line'=>'لاین','product'=>'کد یا نام کالا','brand_name'=>'برند'] as $n=>$l):?><label class="form-field"><span><?=e($l)?></span><input name="<?=e($n)?>" value="<?=e($_GET[$n]??'')?>"></label><?php endforeach;?><label class="form-field"><span>وضعیت</span><select name="status"><option value="">همه</option><?php foreach(SalesOfferBudgetService::STATUSES as $s):?><option value="<?=e($s)?>" <?=($_GET['status']??'')===$s?'selected':''?>><?=e(SalesOfferBudgetService::statusLabel($s))?></option><?php endforeach;?></select></label></div><button class="btn">اعمال فیلتر</button></form>
<section class="card"><h2>تاریخچه استعلام‌ها</h2><div class="table-wrap"><table><thead><tr><th>کد</th><th>کالا / برند</th><th>لاین / دوره</th><th>بودجه مقدماتی</th><th>وضعیت</th><th>ثبت‌کننده</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['request_code'])?></td><td><?=e(trim(($r['product_code']??'').' '.($r['product_name']??'')))?><br><small><?=e($r['brand_name']??'')?></small></td><td><?=e($r['sales_line']??'-')?> / <?=e($r['period_key']??'-')?></td><td><?=format_money($r['provisional_budget'])?></td><td><span class="badge"><?=e(SalesOfferBudgetService::statusLabel($r['status']))?></span></td><td><?=e($r['requested_by_name']??'-')?></td><td><a class="btn" href="/admin/sales-offer-budget-view.php?id=<?=(int)$r['id']?>">مشاهده</a></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="7">استعلامی یافت نشد.</td></tr><?php endif;?></tbody></table></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
