<?php
require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../services/SalesOfferBudgetService.php';SalesOfferBudgetService::repairSchema();SalesOfferBudgetService::requireAccess();$user=Auth::user();$id=(int)($_GET['id']??$_POST['id']??0);$request=SalesOfferBudgetService::getRequest($id,$user);if(!$request){http_response_code(404);die('استعلام یافت نشد یا دسترسی ندارید.');}$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST')try{if(!Auth::verifyCsrf($_POST['csrf_token']??null))throw new InvalidArgumentException('درخواست معتبر نیست.');if(($_POST['action']??'')==='status')SalesOfferBudgetService::changeStatus($id,(string)($_POST['status']??''),(string)($_POST['admin_note']??''),(int)$user['id']);else SalesOfferBudgetService::updateRequest($id,$_POST,(int)$user['id']);flash('تغییرات ذخیره شد.');redirect('/admin/sales-offer-budget-view.php?id='.$id);}catch(Throwable $e){$errors[]=SalesOfferBudgetService::uiError($e,'ذخیره تغییرات انجام نشد.');}
$request=SalesOfferBudgetService::getRequest($id,$user);$snapshot=json_decode((string)($request['formula_snapshot_json']??''),true)?:[];$logs=SalesOfferBudgetService::logs($id);$canEdit=SalesOfferBudgetService::isAdmin($user)||($request['status']==='draft'&&(int)$request['requested_by']===(int)$user['id']);$pageTitle='جزئیات استعلام بودجه آفر';require __DIR__.'/../views/partials/admin-header.php';
?>
<div class="section-heading-row"><div><h1><?=e($request['request_code'])?></h1><p class="muted">محاسبه مقدماتی provisional_v1؛ فرمول نهایی Excel هنوز اعمال نشده است.</p></div><a class="btn" href="/admin/sales-offer-budget.php">بازگشت</a></div><?php foreach($errors as $e1):?><div class="alert alert-danger"><?=e($e1)?></div><?php endforeach;?>
<section class="card"><h2>اطلاعات و نتیجه محاسبه</h2><div class="grid grid-4"><?php foreach(['product_code'=>'کد کالا','product_name'=>'نام کالا','brand_name'=>'برند','supplier_name'=>'تأمین‌کننده','sales_line'=>'لاین','period_key'=>'دوره','date_from'=>'از تاریخ','date_to'=>'تا تاریخ','purchase_price'=>'قیمت خرید','requested_offer_qty'=>'تعداد آفر','sold_qty'=>'تعداد فروش','sold_amount'=>'مبلغ فروش','provisional_offer_rate'=>'نرخ موقت','provisional_budget'=>'بودجه مقدماتی','status'=>'وضعیت','requested_by_name'=>'ثبت‌کننده'] as $k=>$l):?><div><small><?=e($l)?></small><div><?=e($k==='status'?SalesOfferBudgetService::statusLabel($request[$k]):(string)($request[$k]??'-'))?></div></div><?php endforeach;?></div><h3>Snapshot فرمول</h3><div class="table-wrap"><table><tbody><?php foreach($snapshot as $k=>$v):?><tr><th><?=e((string)$k)?></th><td><?=e(is_scalar($v)?(string)$v:json_encode($v,JSON_UNESCAPED_UNICODE))?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if($canEdit&&$request['status']==='draft'):?><form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><h2>ویرایش پیش‌نویس</h2><div class="grid grid-4"><?php foreach(['period_key'=>'دوره','date_from'=>'از تاریخ','date_to'=>'تا تاریخ','sales_line'=>'لاین','product_code'=>'کد کالا','product_name'=>'نام کالا','brand_name'=>'برند','supplier_name'=>'تأمین‌کننده','purchase_price'=>'قیمت خرید','requested_offer_qty'=>'تعداد آفر','sold_qty'=>'تعداد فروش','sold_amount'=>'مبلغ فروش','provisional_offer_rate'=>'نرخ موقت'] as $n=>$l):?><label class="form-field"><span><?=e($l)?></span><input name="<?=e($n)?>" value="<?=e((string)($request[$n]??''))?>"></label><?php endforeach;?></div><label class="form-field"><span>یادداشت</span><textarea name="manager_note"><?=e($request['manager_note']??'')?></textarea></label><button class="btn btn-primary">ذخیره و محاسبه مجدد</button></form><?php endif;?>
<?php if(!SalesOfferBudgetService::isAdmin($user)&&$request['status']==='draft'&&(int)$request['requested_by']===(int)$user['id']):?><form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="status"><input type="hidden" name="status" value="submitted"><p>پس از ارسال، پیش‌نویس دیگر توسط مدیر فروش قابل ویرایش نیست.</p><button class="btn btn-primary">ارسال جهت بررسی</button></form><?php endif;?>
<?php if(SalesOfferBudgetService::isAdmin($user)):?><form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="status"><h2>بررسی مدیریت</h2><label class="form-field"><span>وضعیت</span><select name="status"><?php foreach(['submitted','under_review','approved','rejected','needs_revision'] as $s):?><option value="<?=e($s)?>"><?=e(SalesOfferBudgetService::statusLabel($s))?></option><?php endforeach;?></select></label><label class="form-field"><span>یادداشت بررسی</span><textarea name="admin_note"><?=e($request['admin_note']??'')?></textarea></label><button class="btn btn-primary">ثبت نتیجه بررسی</button></form><?php endif;?>
<section class="card"><h2>تاریخچه تغییرات</h2><div class="table-wrap"><table><thead><tr><th>زمان</th><th>اقدام</th><th>کاربر</th><th>مقدار جدید</th></tr></thead><tbody><?php foreach($logs as $log):?><tr><td><?=e($log['created_at'])?></td><td><?=e($log['action'])?></td><td><?=e($log['performed_by_name']??'-')?></td><td><code><?=e($log['new_value_json']??'-')?></code></td></tr><?php endforeach;?></tbody></table></div></section><?php require __DIR__.'/../views/partials/admin-footer.php';?>
