<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/SmsGatewayService.php';
Auth::requirePermission('sms.manage');$pageTitle='ارسال و گزارش پیامک';$canSend=Auth::can('sms.manage','create');
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!$canSend){flash('برای ارسال پیامک دسترسی ندارید.','danger');redirect('/admin/sms-send.php');}
 if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('درخواست نامعتبر است.','danger');redirect('/admin/sms-send.php');}
 try{$service=SmsGatewayService::active();$message=trim((string)($_POST['message']??''));$input=preg_split('/[\s,;،]+/u',(string)($_POST['mobiles']??''),-1,PREG_SPLIT_NO_EMPTY)?:[];$mobiles=$service->normalizeMobiles($input);
   if($message===''||!$mobiles)throw new InvalidArgumentException('متن پیام و حداقل یک شماره معتبر الزامی است.');
   $sent=0;$failed=0;foreach(array_chunk($mobiles,90) as $chunk){$result=$service->sendSimpleSms($chunk,$message);$status=$result['success']?'sent':'failed';$pdo=Database::connection();$pdo->beginTransaction();try{Database::execute('INSERT INTO sms_messages(provider_name,sender,message_body,recipients_count,bulk_code,status,source_module,created_by,sent_at,error_code,error_message,created_at) SELECT provider_name,default_sender,?,?,?,?,"manual",?,IF(?="sent",NOW(),NULL),?,?,NOW() FROM sms_settings WHERE is_active=1 ORDER BY id DESC LIMIT 1',[$message,count($chunk),$result['bulk_code'],$status,(int)Auth::user()['id'],$status,$result['error_code'],$result['error_message']]);$id=(int)Database::lastInsertId();if($id<1)throw new RuntimeException('sms_message_log_failed');foreach($chunk as $mobile)Database::execute('INSERT INTO sms_message_recipients(message_id,mobile,normalized_mobile,delivery_status,created_at) VALUES(?,?,?,?,NOW())',[$id,$mobile,$mobile,$status]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}$result['success']?$sent++:$failed++;Auth::log((int)Auth::user()['id'],'sms_batch_'.$status,'sms_messages',$id);}
   flash("ارسال پردازش شد: {$sent} بسته موفق و {$failed} بسته ناموفق.",$failed?'danger':'success');
 }catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('SMS manual send: '.$e->getMessage());flash('ارسال پیامک انجام نشد. تنظیمات سرویس را بررسی کنید.','danger');}redirect('/admin/sms-send.php');
}
$rows=Database::fetchAll('SELECT m.*,u.name created_by_name FROM sms_messages m LEFT JOIN users u ON u.id=m.created_by ORDER BY m.id DESC LIMIT 100');require __DIR__.'/../views/partials/admin-header.php';
?>
<form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><h2>ارسال دستی</h2><p class="muted">شماره‌ها با فاصله، ویرگول یا خط جدید جدا شوند. ارسال خودکار در بسته‌های حداکثر ۹۰ شماره انجام می‌شود.</p><label class="form-field"><span>شماره‌های موبایل</span><textarea dir="ltr" name="mobiles" rows="5" required <?=$canSend?'':'disabled'?>></textarea></label><label class="form-field"><span>متن پیام</span><textarea name="message" rows="5" maxlength="2000" required <?=$canSend?'':'disabled'?>></textarea></label><?php if($canSend):?><button class="btn btn-primary">ارسال و ثبت گزارش</button><?php endif?> <a class="btn" href="/admin/sms-settings.php">تنظیمات و اعتبار</a></form>
<section class="card"><h2>۱۰۰ ارسال اخیر</h2><div class="table-wrap"><table><thead><tr><th>#</th><th>زمان</th><th>کاربر</th><th>گیرندگان</th><th>وضعیت</th><th>Bulk code</th><th>متن/خطا</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?=e((string)$row['id'])?></td><td><?=e($row['sent_at']?:$row['created_at'])?></td><td><?=e($row['created_by_name']?:'-')?></td><td><?=e((string)$row['recipients_count'])?></td><td><?=e($row['status'])?></td><td dir="ltr"><?=e($row['bulk_code']?:'-')?></td><td><?=e($row['error_message']?:$row['message_body'])?></td></tr><?php endforeach?><?php if(!$rows):?><tr><td colspan="7">ارسالی ثبت نشده است.</td></tr><?php endif?></tbody></table></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';
