<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/SmsGatewayService.php';
Auth::requirePermission('sms_send','create');$pageTitle='ارسال پیامک';$templates=Database::fetchAll('SELECT id,title,body FROM sms_templates WHERE is_active=1 ORDER BY title');
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('درخواست نامعتبر است.','danger');redirect('/admin/sms-send.php');}
 try{$input=preg_split('/[\s,;،]+/u',(string)($_POST['mobiles']??''),-1,PREG_SPLIT_NO_EMPTY)?:[];$message=trim((string)($_POST['message']??''));$service=SmsGatewayService::active();$result=$service->sendSimpleSms($input,$message,trim((string)($_POST['sender']??''))?:null,(int)Auth::user()['id'],'manual');$success=count(array_filter($result['batches'],static fn($b)=>!empty($b['success'])));$failed=count($result['batches'])-$success;$codes=array_values(array_filter(array_column($result['batches'],'bulk_code')));$text="گیرندگان معتبر: {$result['valid_count']}، نامعتبر/تکراری: {$result['invalid_count']}، بسته موفق: {$success}، ناموفق: {$failed}".($codes?'، کدها: '.implode('، ',$codes):'');flash($text,$failed||!$result['success']?'danger':'success');Auth::log((int)Auth::user()['id'],'sms_manual_send','sms_messages');}
 catch(Throwable $e){error_log('SMS manual page: '.get_class($e));flash('ارسال پیامک انجام نشد. تنظیمات و دسترسی سرویس را بررسی کنید.','danger');}redirect('/admin/sms-send.php');
}
$setting=Database::fetch('SELECT default_sender FROM sms_settings WHERE is_active=1 ORDER BY id DESC LIMIT 1');require __DIR__.'/../views/partials/admin-header.php';?>
<form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><h2>ارسال دستی</h2><p class="muted">شماره‌ها را با فاصله، ویرگول، سمی‌کالن یا خط جدید جدا کنید؛ موارد تکراری حذف و ارسال در بسته‌های ۹۰تایی انجام می‌شود.</p><div class="grid grid-2"><label class="form-field"><span>قالب اختیاری</span><select id="smsTemplate"><option value="">بدون قالب</option><?php foreach($templates as $template):?><option value="<?=e($template['id'])?>" data-body="<?=e($template['body'])?>"><?=e($template['title'])?></option><?php endforeach?></select></label><label class="form-field"><span>خط ارسال</span><input dir="ltr" name="sender" value="<?=e($setting['default_sender']??'')?>"></label></div><label class="form-field"><span>گیرندگان</span><textarea dir="ltr" name="mobiles" rows="6" required></textarea></label><label class="form-field"><span>متن پیام</span><textarea id="smsBody" name="message" rows="6" maxlength="2000" required></textarea></label><div class="form-actions"><button class="btn btn-primary">ارسال پیامک</button><a class="btn" href="/admin/sms-messages.php">گزارش ارسال</a></div></form>
<script>document.getElementById('smsTemplate')?.addEventListener('change',function(){const option=this.options[this.selectedIndex];if(option?.dataset.body)document.getElementById('smsBody').value=option.dataset.body;});</script>
<?php require __DIR__.'/../views/partials/admin-footer.php';
