<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/SmsGatewayService.php';
Auth::requireAnyRole(['admin','super_admin']);$pageTitle='تنظیمات سامانه پیامکی';$setting=Database::fetch('SELECT id,provider_name,wsdl_url,url_api_base,username,default_sender,is_active,last_credit,last_credit_checked_at,last_test_status,last_test_message,updated_at FROM sms_settings ORDER BY id DESC LIMIT 1');
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('درخواست نامعتبر است.','danger');redirect('/admin/sms-settings.php');}$action=(string)($_POST['action']??'save');
 try{
  if(in_array($action,['save','test_connection','get_credit','test_sms'],true)){$wsdl=trim((string)($_POST['wsdl_url']??''));$username=trim((string)($_POST['username']??''));$sender=trim((string)($_POST['default_sender']??''));$password=(string)($_POST['password']??'');if($wsdl===''||!str_contains(strtolower($wsdl),'?wsdl')||!filter_var($wsdl,FILTER_VALIDATE_URL)||$username===''||$sender===''||(!$setting&&$password===''))throw new InvalidArgumentException('آدرس WSDL، نام کاربری، رمز و خط ارسال را کامل و معتبر وارد کنید.');if($setting){$sql='UPDATE sms_settings SET provider_name=?,wsdl_url=?,url_api_base=?,username=?,default_sender=?,is_active=?,updated_at=NOW()';$params=['bazyabpayam',$wsdl,trim((string)($_POST['url_api_base']??''))?:null,$username,$sender,!empty($_POST['is_active'])?1:0];if($password!==''){$sql.=',password_encrypted=?';$params[]=SmsGatewayService::encrypt($password);}$sql.=' WHERE id=?';$params[]=(int)$setting['id'];Database::execute($sql,$params);}else{Database::execute('INSERT INTO sms_settings(provider_name,wsdl_url,url_api_base,username,password_encrypted,default_sender,is_active,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NOW(),NOW())',['bazyabpayam',$wsdl,null,$username,SmsGatewayService::encrypt($password),$sender,!empty($_POST['is_active'])?1:0,(int)Auth::user()['id']]);}$setting=Database::fetch('SELECT * FROM sms_settings ORDER BY id DESC LIMIT 1');if($action!=='save')$service=SmsGatewayService::configured();}
  if($action==='test_connection'){$_SESSION['sms_diagnostics']=$service->testConnection();flash($_SESSION['sms_diagnostics']['message'],$_SESSION['sms_diagnostics']['success']?'success':'danger');}
  elseif($action==='get_credit'){$result=$service->getCredit();$_SESSION['sms_diagnostics']=$service->getDiagnostics();flash($result['message'],$result['success']?'success':'danger');}
  elseif($action==='test_sms'){$mobile=trim((string)($_POST['test_mobile']??''));$result=$service->sendSimpleSms([$mobile],'پیام آزمایشی سامانه سبحان',null,(int)Auth::user()['id'],'settings_test');flash($result['success']?'پیام آزمایشی برای ارسال ثبت شد.':$result['message'],$result['success']?'success':'danger');}
  else flash('تنظیمات پیامکی ذخیره شد.');Auth::log((int)Auth::user()['id'],'sms_settings_'.$action,'sms_settings',(int)($setting['id']??0));
 }catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('SMS settings action: '.get_class($e));flash('عملیات تنظیمات پیامکی انجام نشد. وضعیت SOAP، WSDL و فعال‌بودن سرویس را بررسی کنید.','danger');}redirect('/admin/sms-settings.php');
}
$setting=Database::fetch('SELECT id,provider_name,wsdl_url,url_api_base,username,default_sender,is_active,last_credit,last_credit_checked_at,last_test_status,last_test_message,updated_at FROM sms_settings ORDER BY id DESC LIMIT 1');$diagnostics=$_SESSION['sms_diagnostics']??null;unset($_SESSION['sms_diagnostics']);require __DIR__.'/../views/partials/admin-header.php';?>
<form class="card admin-form" method="post" autocomplete="off"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><h2>اتصال SOAP پیامک</h2><p class="muted">رمز پس از ذخیره نمایش داده نمی‌شود. API مبتنی بر URL در این فاز استفاده نمی‌شود.</p><div class="grid grid-2"><label class="form-field"><span>سرویس‌دهنده</span><input name="provider_name" value="BazyabPayam" disabled></label><label class="form-field"><span>WSDL</span><input dir="ltr" name="wsdl_url" required value="<?=e($setting['wsdl_url']??'http://185.94.99.84/webservice/wsdl/server.php?wsdl')?>"></label><label class="form-field"><span>نام کاربری</span><input dir="ltr" name="username" required value="<?=e($setting['username']??'')?>"></label><label class="form-field"><span>رمز عبور</span><input dir="ltr" type="password" name="password" autocomplete="new-password" placeholder="<?=$setting?'برای حفظ رمز فعلی خالی بگذارید':'رمز عبور'?>"><small>رمز پس از ذخیره نمایش داده نمی‌شود.</small></label><label class="form-field"><span>خط پیش‌فرض</span><input dir="ltr" name="default_sender" required value="<?=e($setting['default_sender']??'')?>"></label><label class="form-field"><span>URL API اختیاری (غیرفعال)</span><input dir="ltr" name="url_api_base" value="<?=e($setting['url_api_base']??'')?>" readonly></label><label class="form-field"><span>شماره تست</span><input dir="ltr" name="test_mobile" placeholder="09123456789"></label><label class="checkbox-item"><input type="checkbox" name="is_active" value="1" <?=!$setting||!empty($setting['is_active'])?'checked':''?>> سرویس فعال باشد</label></div><div class="form-actions"><button class="btn btn-primary" name="action" value="save">ذخیره تنظیمات</button><button class="btn" name="action" value="test_connection">تست اتصال SOAP</button><button class="btn" name="action" value="get_credit">دریافت اعتبار</button><button class="btn" name="action" value="test_sms">ارسال پیام تست</button></div></form>
<section class="card"><h2>تشخیص اتصال</h2><div class="grid grid-3"><?php $labels=['soap_extension'=>'افزونه SOAP','wsdl_format'=>'قالب WSDL','wsdl'=>'دسترسی WSDL','credentials'=>'اطلاعات ورود','provider'=>'پاسخ سرویس‌دهنده'];foreach($labels as $key=>$label):$item=$diagnostics['items'][$key]??null;?><div class="stat-card"><span><?=e($label)?></span><strong><?=!$item?'بررسی نشده':($item['success']?'موفق':'ناموفق')?></strong><small><?=e($item['message']??'هنوز تست اجرا نشده است.')?></small></div><?php endforeach?></div><p>آخرین اعتبار: <strong><?=e($setting['last_credit']??'-')?></strong> — آخرین بررسی: <?=e($setting['last_credit_checked_at']??'-')?></p><p class="muted">آخرین پیام امن: <?=e($setting['last_test_message']??'-')?></p></section>
<section class="card"><div class="form-actions"><a class="btn" href="/admin/sms-send.php">ارسال پیامک</a><a class="btn" href="/admin/sms-templates.php">قالب‌ها</a><a class="btn" href="/admin/sms-messages.php">گزارش ارسال</a><a class="btn" href="/admin/sms-delivery-sync.php">وضعیت تحویل</a></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';
