<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';
Auth::requirePermission('sms_report_view');$pageTitle='گزارش پیامک‌ها';$where=[];$params=[];$filters=['status','sender','bulk_code','source_module'];foreach($filters as $field){$value=trim((string)($_GET[$field]??''));if($value!==''){$where[]="m.{$field}=?";$params[]=$value;}}if($from=app_date_to_iso($_GET['from']??'')){$where[]='DATE(m.created_at)>=?';$params[]=$from;}if($to=app_date_to_iso($_GET['to']??'')){$where[]='DATE(m.created_at)<=?';$params[]=$to;}if($mobile=trim((string)($_GET['mobile']??''))){$where[]='EXISTS(SELECT 1 FROM sms_message_recipients sr WHERE sr.message_id=m.id AND sr.normalized_mobile LIKE ?)';$params[]='%'.preg_replace('/[^0-9]/','',$mobile).'%';}$sql='SELECT m.*,u.name created_by_name FROM sms_messages m LEFT JOIN users u ON u.id=m.created_by'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY m.id DESC LIMIT 500';$rows=Database::fetchAll($sql,$params);
if(($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="sms-messages.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['شناسه','تاریخ','فرستنده','متن','کل','معتبر','نامعتبر','کد ارسال','وضعیت','منبع']);foreach($rows as $row){$safe=static fn($v)=>(is_string($v)&&preg_match('/^[=+\-@]/u',$v)?"'":'').$v;fputcsv($out,[$row['id'],$row['created_at'],$safe($row['sender']),$safe($row['message_body']),$row['recipients_count'],$row['valid_recipients_count'],$row['invalid_recipients_count'],$safe($row['bulk_code']),$row['status'],$safe($row['source_module'])]);}fclose($out);exit;}
$viewId=max(0,(int)($_GET['id']??0));$recipients=$viewId?Database::fetchAll('SELECT * FROM sms_message_recipients WHERE message_id=? ORDER BY id',[$viewId]):[];$gatewayLogs=Database::fetchAll('SELECT error_code,safe_message,context_json,created_at FROM sms_gateway_logs ORDER BY id DESC LIMIT 50');require __DIR__.'/../views/partials/admin-header.php';?>
<form class="card admin-form" method="get"><h2>فیلتر گزارش</h2><div class="grid grid-3"><label class="form-field"><span>از تاریخ</span><?=app_date_input('from',$_GET['from']??null)?></label><label class="form-field"><span>تا تاریخ</span><?=app_date_input('to',$_GET['to']??null)?></label><label class="form-field"><span>وضعیت</span><input name="status" value="<?=e($_GET['status']??'')?>"></label><label class="form-field"><span>فرستنده</span><input dir="ltr" name="sender" value="<?=e($_GET['sender']??'')?>"></label><label class="form-field"><span>Bulk code</span><input dir="ltr" name="bulk_code" value="<?=e($_GET['bulk_code']??'')?>"></label><label class="form-field"><span>ماژول</span><input dir="ltr" name="source_module" value="<?=e($_GET['source_module']??'')?>"></label><label class="form-field"><span>موبایل</span><input dir="ltr" name="mobile" value="<?=e($_GET['mobile']??'')?>"></label></div><div class="form-actions"><button class="btn btn-primary">اعمال فیلتر</button><button class="btn" name="export" value="csv">خروجی CSV</button><a class="btn" href="/admin/sms-messages.php">پاکسازی</a></div></form>
<section class="card"><h2>تاریخچه ارسال</h2><div class="table-wrap"><table><thead><tr><th>تاریخ</th><th>فرستنده</th><th>متن</th><th>کل/معتبر/نامعتبر</th><th>کد</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?=e($row['created_at'])?></td><td dir="ltr"><?=e($row['sender'])?></td><td><?=e(mb_substr($row['message_body'],0,100))?></td><td><?=e($row['recipients_count'].' / '.$row['valid_recipients_count'].' / '.$row['invalid_recipients_count'])?></td><td dir="ltr"><?=e($row['bulk_code']?:'-')?></td><td><?=e($row['status'])?></td><td><a class="btn btn-small" href="?id=<?=$row['id']?>">مشاهده گیرندگان</a><?php if($row['bulk_code']):?> <a class="btn btn-small" href="/admin/sms-delivery-sync.php?id=<?=$row['id']?>">بروزرسانی تحویل</a><?php endif?></td></tr><?php endforeach?><?php if(!$rows):?><tr><td colspan="7">هنوز پیامکی ارسال نشده است.</td></tr><?php endif?></tbody></table></div></section>
<?php if($viewId):?><section class="card"><h2>گیرندگان پیام #<?=e((string)$viewId)?></h2><div class="table-wrap"><table><thead><tr><th>موبایل ثبت‌شده</th><th>موبایل نرمال</th><th>شناسه سرویس‌دهنده</th><th>وضعیت</th><th>آخرین بررسی</th></tr></thead><tbody><?php foreach($recipients as $recipient):?><tr><td dir="ltr"><?=e($recipient['mobile'])?></td><td dir="ltr"><?=e($recipient['normalized_mobile'])?></td><td><?=e($recipient['provider_message_id']?:'-')?></td><td><?=e($recipient['delivery_status']?:'unknown')?></td><td><?=e($recipient['checked_at']?:'-')?></td></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<section class="card"><h2>۵۰ خطای امن اخیر درگاه</h2><div class="table-wrap"><table><thead><tr><th>زمان</th><th>کد</th><th>پیام امن</th><th>زمینه ماسک‌شده</th></tr></thead><tbody><?php foreach($gatewayLogs as $log):?><tr><td><?=e($log['created_at'])?></td><td dir="ltr"><?=e($log['error_code']?:'-')?></td><td><?=e($log['safe_message'])?></td><td dir="ltr"><?=e($log['context_json']?:'-')?></td></tr><?php endforeach?><?php if(!$gatewayLogs):?><tr><td colspan="4">خطایی ثبت نشده است.</td></tr><?php endif?></tbody></table></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';
