<?php
require_once __DIR__ . '/../core/Auth.php';
require_once __DIR__ . '/../core/Database.php';
require_once __DIR__ . '/../core/Response.php';
require_once __DIR__ . '/../services/SalesOperationsService.php';
SalesOperationsService::boot(); Auth::requirePermission('admin.supervisor_settings.manage');
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{if(!Auth::verifyCsrf($_POST['csrf_token']??null))throw new RuntimeException('درخواست نامعتبر است.');$supervisor=(int)($_POST['supervisor_id']??0);$visitor=(int)($_POST['visitor_id']??0);if(!$supervisor||!$visitor)throw new RuntimeException('سرپرست و ویزیتور اجباری هستند.');Database::execute('INSERT INTO sales_team_assignments(supervisor_id,visitor_id,sales_manager_id,sales_line,active,created_at,updated_at) VALUES (?,?,?,?,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE sales_manager_id=VALUES(sales_manager_id),sales_line=VALUES(sales_line),active=1,updated_at=NOW()',[$supervisor,$visitor,(int)($_POST['sales_manager_id']??0)?:null,trim((string)($_POST['sales_line']??''))?:null]);flash('تخصیص تیم فروش ذخیره شد.');redirect('/admin/supervisor-settings.php');}catch(Throwable $e){$errors[]=$e->getMessage();}}
$users=Database::fetchAll('SELECT id,name,role_key,sales_line FROM users WHERE status="active" ORDER BY name LIMIT 1000');$assignments=Database::fetchAll('SELECT a.*,s.name supervisor_name,v.name visitor_name,m.name manager_name FROM sales_team_assignments a LEFT JOIN users s ON s.id=a.supervisor_id LEFT JOIN users v ON v.id=a.visitor_id LEFT JOIN users m ON m.id=a.sales_manager_id WHERE a.active=1 ORDER BY a.updated_at DESC LIMIT 300');
$pageTitle='تنظیمات پنل سرپرستان';require __DIR__ . '/../views/partials/admin-header.php';
?>
<div class="section-heading-row"><div><h1>تنظیمات پنل سرپرستان فروش</h1><p class="muted">تعریف mapping سرپرست، ویزیتور، مدیر فروش و لاین برای محدودسازی دقیق گزارش‌ها.</p></div><div class="actions"><a class="btn" href="/admin/sales-script-fields.php">قالب فیلدها</a></div></div>
<?php foreach($errors as $error):?><div class="alert alert-danger"><?=e($error)?></div><?php endforeach;?>
<form class="card admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><h2>تخصیص ویزیتور به سرپرست</h2><div class="grid grid-4"><label class="form-field"><span>سرپرست</span><select name="supervisor_id" required><option value="0">انتخاب کنید</option><?php foreach($users as $u):?><option value="<?=(int)$u['id']?>"><?=e($u['name'].' - '.$u['role_key'])?></option><?php endforeach;?></select></label><label class="form-field"><span>ویزیتور</span><select name="visitor_id" required><option value="0">انتخاب کنید</option><?php foreach($users as $u):?><option value="<?=(int)$u['id']?>"><?=e($u['name'].' - '.$u['role_key'])?></option><?php endforeach;?></select></label><label class="form-field"><span>مدیر فروش</span><select name="sales_manager_id"><option value="0">بدون انتخاب</option><?php foreach($users as $u):?><option value="<?=(int)$u['id']?>"><?=e($u['name'].' - '.$u['role_key'])?></option><?php endforeach;?></select></label><label class="form-field"><span>لاین فروش</span><input name="sales_line"></label></div><div class="form-actions"><button class="btn btn-primary">ذخیره تخصیص</button></div></form>
<section class="card"><h2>تخصیص‌های فعال</h2><div class="table-wrap"><table><thead><tr><th>سرپرست</th><th>ویزیتور</th><th>مدیر فروش</th><th>لاین</th><th>آخرین بروزرسانی</th></tr></thead><tbody><?php foreach($assignments as $a):?><tr><td><?=e($a['supervisor_name']??'-')?></td><td><?=e($a['visitor_name']??'-')?></td><td><?=e($a['manager_name']??'-')?></td><td><?=e($a['sales_line']??'-')?></td><td><?=e($a['updated_at'])?></td></tr><?php endforeach;?><?php if(!$assignments):?><tr><td colspan="5">تخصیصی ثبت نشده است.</td></tr><?php endif;?></tbody></table></div></section>
<?php require __DIR__ . '/../views/partials/admin-footer.php'; ?>
