<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../lib/FileBackupService.php';Auth::requirePermission('file_backup.manage','view');$pageTitle='مدیریت بکاپ فایل‌های سایت';$adminExtraStylesheets=['/assets/css/file-backup.css'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('اعتبار درخواست منقضی شده است.','danger');redirect('/admin/uploaded-files-backup.php');}
    try{$action=(string)($_POST['action']??'');
        if($action==='scan'){if(!Auth::isAdmin()&&!Auth::can('file_backup.manage','edit'))throw new RuntimeException('permission_denied');$result=FileBackupService::scanUploads();Auth::log((int)Auth::user()['id'],'file_backup_scan','uploaded_files_backup');flash("اسکن انجام شد؛ {$result['registered']} فایل جدید، {$result['unchanged']} فایل موجود و {$result['errors']} خطا.");}
        elseif($action==='generate_key'){if(!Auth::isAdmin())throw new RuntimeException('permission_denied');$key='sbh_'.bin2hex(random_bytes(32));FileBackupService::setApiKey($key);Auth::start();$_SESSION['file_backup_api_key_once']=$key;FileBackupService::log(null,'api_key_rotated','success','کلید API بکاپ توسط ادمین تغییر کرد.','admin',(int)Auth::user()['id']);flash('کلید API جدید ساخته شد؛ آن را همین حالا در Windows Server ذخیره کنید.');}
        elseif($action==='save_ips'){if(!Auth::isAdmin())throw new RuntimeException('permission_denied');$ips=trim((string)($_POST['allowed_ips']??''));foreach(preg_split('/[\s,;]+/',$ips,-1,PREG_SPLIT_NO_EMPTY) as $rule)if(!FileBackupService::validIpRule($rule))throw new InvalidArgumentException('IP یا CIDR واردشده معتبر نیست: '.$rule);FileBackupService::setAllowedIps($ips);FileBackupService::log(null,'ip_allowlist_updated','success','فهرست IPهای مجاز بروزرسانی شد.','admin',(int)Auth::user()['id']);flash('محدودیت IP ذخیره شد.');}
        elseif($action==='delete_host'){if(!Auth::isAdmin())throw new RuntimeException('permission_denied');FileBackupService::deleteFromHost((int)($_POST['file_id']??0),(int)Auth::user()['id']);Auth::log((int)Auth::user()['id'],'file_backup_host_deleted','uploaded_files_backup',(int)$_POST['file_id']);flash('فقط نسخه فایل روی هاست حذف شد؛ بکاپ Windows Server دست‌نخورده باقی می‌ماند.');}
        else throw new InvalidArgumentException('عملیات معتبر نیست.');
    }catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('File backup admin: '.$e->getMessage());flash($e->getMessage()==='permission_denied'?'دسترسی لازم برای این عملیات را ندارید.':'عملیات بکاپ فایل انجام نشد.','danger');}
    redirect('/admin/uploaded-files-backup.php');
}
Auth::start();$plainKey=$_SESSION['file_backup_api_key_once']??null;unset($_SESSION['file_backup_api_key_once']);$status=(string)($_GET['status']??'');$deleted=(string)($_GET['deleted']??'');$q=trim((string)($_GET['q']??''));$where=['1=1'];$params=[];if(in_array($status,['pending','synced','error'],true)){$where[]='backup_status=?';$params[]=$status;}if(in_array($deleted,['0','1'],true)){$where[]='deleted_from_host=?';$params[]=(int)$deleted;}if($q!==''){$where[]='(original_name LIKE ? OR relative_path LIKE ? OR file_hash LIKE ?)';array_push($params,'%'.$q.'%','%'.$q.'%','%'.$q.'%');}$files=Database::fetchAll('SELECT * FROM uploaded_files_backup WHERE '.implode(' AND ',$where).' ORDER BY updated_at DESC,id DESC LIMIT 500',$params);$counts=['pending'=>0,'synced'=>0,'error'=>0,'deleted'=>0];foreach(Database::fetchAll('SELECT backup_status,COUNT(*) count FROM uploaded_files_backup GROUP BY backup_status') as $row)$counts[$row['backup_status']]=(int)$row['count'];$counts['deleted']=(int)(Database::fetch('SELECT COUNT(*) count FROM uploaded_files_backup WHERE deleted_from_host=1')['count']??0);$logs=Database::fetchAll('SELECT l.*,f.original_name,u.name actor_name FROM uploaded_files_backup_logs l LEFT JOIN uploaded_files_backup f ON f.id=l.file_id LEFT JOIN users u ON u.id=l.actor_user_id ORDER BY l.id DESC LIMIT 30');$allowedIps=FileBackupService::allowedIps();$hasKey=FileBackupService::apiKeyHash()!=='';require __DIR__.'/../views/partials/admin-header.php';?>
<div class="backup-head"><div><h1>مدیریت بکاپ فایل‌های سایت</h1><p>بکاپ یک‌طرفه Pull به Windows Server؛ بدون mirror یا حذف مقصد</p></div><div class="backup-actions"><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="scan"><button class="btn btn-primary">اسکن پوشه uploads</button></form></div></div>
<div class="backup-kpis"><article class="backup-kpi"><span>در انتظار بکاپ</span><strong><?=$counts['pending']?></strong></article><article class="backup-kpi"><span>بکاپ موفق</span><strong><?=$counts['synced']?></strong></article><article class="backup-kpi"><span>نیازمند تلاش مجدد</span><strong><?=$counts['error']?></strong></article><article class="backup-kpi"><span>حذف‌شده از هاست</span><strong><?=$counts['deleted']?></strong></article></div>
<?php if($plainKey):?><section class="card"><div class="backup-warning"><strong>این کلید فقط همین یک‌بار نمایش داده می‌شود.</strong> آن را در محل امن Windows Server ذخیره کنید.</div><code class="backup-key"><?=e($plainKey)?></code></section><?php endif?>
<div class="backup-layout"><main><section class="card"><form method="get" class="backup-filter"><label class="form-field"><span>جستجو</span><input name="q" value="<?=e($q)?>" placeholder="نام، مسیر یا هش"></label><label class="form-field"><span>وضعیت بکاپ</span><select name="status"><option value="">همه</option><option value="pending" <?=$status==='pending'?'selected':''?>>در انتظار</option><option value="synced" <?=$status==='synced'?'selected':''?>>موفق</option><option value="error" <?=$status==='error'?'selected':''?>>خطا / قابل تلاش مجدد</option></select></label><label class="form-field"><span>نسخه هاست</span><select name="deleted"><option value="">همه</option><option value="0" <?=$deleted==='0'?'selected':''?>>موجود</option><option value="1" <?=$deleted==='1'?'selected':''?>>حذف‌شده</option></select></label><div class="backup-actions"><button class="btn btn-primary">فیلتر</button><a class="btn" href="/admin/uploaded-files-backup.php">پاکسازی</a></div></form></section>
<section class="card"><div class="table-wrap"><table><thead><tr><th>فایل</th><th>مسیر نسبی</th><th>حجم</th><th>وضعیت</th><th>تأیید بکاپ</th><th>نسخه هاست</th><th>عملیات</th></tr></thead><tbody><?php foreach($files as $file):$canDelete=Auth::isAdmin()&&$file['backup_status']==='synced'&&!empty($file['backup_confirmed_at'])&&!(int)$file['deleted_from_host'];?><tr><td><strong><?=e($file['original_name'])?></strong><small><?=e($file['mime_type'])?></small><?php if($file['last_error']):?><small class="text-danger"><?=e($file['last_error'])?></small><?php endif?></td><td class="backup-path"><?=e($file['relative_path'])?></td><td><?=e(number_format((int)$file['file_size']/1024,1))?> KB</td><td><span class="backup-status backup-status-<?=e($file['backup_status'])?>"><?=e(['pending'=>'در انتظار','synced'=>'بکاپ موفق','error'=>'خطا / retry'][$file['backup_status']]??'')?></span></td><td><?=e($file['backup_confirmed_at']?format_jalali_datetime($file['backup_confirmed_at']):'—')?></td><td><?php if($file['deleted_from_host']):?><span class="backup-status backup-status-deleted">حذف‌شده</span><?php else:?>موجود<?php endif?></td><td><?php if($canDelete):?><form method="post" onsubmit="return confirm('فقط نسخه روی هاست حذف شود؟ این عملیات هیچ درخواست حذفی به Windows Server ارسال نمی‌کند.')"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="delete_host"><input type="hidden" name="file_id" value="<?=$file['id']?>"><button class="btn btn-small btn-danger">حذف از هاست</button></form><?php else:?><button class="btn btn-small" disabled>حذف غیرفعال</button><?php endif?></td></tr><?php endforeach?><?php if(!$files):?><tr><td colspan="7">فایلی مطابق فیلتر پیدا نشد. برای ثبت فایل‌های قبلی، اسکن را اجرا کنید.</td></tr><?php endif?></tbody></table></div></section></main>
<aside><section class="card"><h2>امنیت اتصال</h2><p class="backup-muted">کلید در دیتابیس به‌صورت SHA-256 ذخیره می‌شود.</p><p>وضعیت کلید: <strong><?=$hasKey?'تنظیم شده':'تنظیم نشده'?></strong></p><?php if(Auth::isAdmin()):?><form method="post" onsubmit="return confirm('کلید قبلی بلافاصله نامعتبر شود؟')"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="generate_key"><button class="btn btn-primary"><?=$hasKey?'ساخت کلید جدید':'ساخت کلید API'?></button></form><form method="post"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="save_ips"><label class="form-field"><span>IP یا CIDR مجاز</span><textarea name="allowed_ips" rows="5" dir="ltr" placeholder="203.0.113.20&#10;203.0.113.0/24"><?=e($allowedIps)?></textarea><small>خالی بودن یعنی محدودیت IP غیرفعال است.</small></label><button class="btn">ذخیره IPها</button></form><?php endif?></section><section class="card backup-endpoints"><h2 dir="rtl">APIهای Pull</h2><code>/api/file-backup/health.php</code><code>/api/file-backup/pending.php</code><code>/api/file-backup/download.php</code><code>/api/file-backup/ack.php</code><code>/api/file-backup/error.php</code><p dir="rtl">کلید در Header با نام <code>X-Backup-Api-Key</code> ارسال شود.</p></section></aside></div>
<section class="card"><h2>آخرین رویدادها</h2><div class="backup-log"><?php foreach($logs as $log):?><article><strong><?=e($log['action'].' — '.$log['status'])?></strong><p><?=e($log['message']?:'—')?></p><small><?=e(($log['original_name']?:'سیستم').' | '.($log['actor_name']?:$log['actor_type']).' | '.format_jalali_datetime($log['created_at']))?></small></article><?php endforeach?><?php if(!$logs):?><p class="backup-muted">هنوز رویدادی ثبت نشده است.</p><?php endif?></div></section>
<?php require __DIR__.'/../views/partials/admin-footer.php';?>
