<?php
require_once __DIR__.'/../core/Auth.php';require_once __DIR__.'/../core/Response.php';require_once __DIR__.'/../core/CeoDashboardExcel.php';require_once __DIR__.'/../lib/UserImportService.php';Auth::requirePermission('users.import_export','view');$pageTitle='ایمپورت و اکسپورت کاربران';$adminExtraStylesheets=['/assets/css/workforce.css'];
if($_SERVER['REQUEST_METHOD']==='POST'&&!Auth::can('users.import_export','create')){flash('برای ایمپورت کاربران دسترسی ندارید.','danger');redirect('/admin/users-import-export.php');}
$action=(string)($_GET['action']??'');
if($action==='template'){
    CeoDashboardExcel::output(['کاربران'=>[
        UserImportService::HEADERS,
        ['10001','KARA-10001','نام کاربر','','09120000000','user@example.com','فروش','ویزیتور','10000','A','10000','9000','ZAHEDAN_R1','active','']
    ]],'users-import-template.xlsx');
}
if($action==='export'){
    if(!Auth::can('users.import_export','view')){http_response_code(403);exit('دسترسی غیرمجاز است.');}
    $rows=[UserImportService::HEADERS];
    $users=Database::fetchAll(
        "SELECT u.*,ou.title unit_title,orr.title org_role_title,parent.employee_no manager_employee_no,
                supervisor.employee_no supervisor_employee_no,sales_manager.employee_no sales_manager_employee_no,
                (SELECT g.code FROM sales_visitor_territories vt JOIN sales_geographies g ON g.id=vt.geography_id
                 WHERE vt.visitor_user_id=u.id AND vt.active=1 ORDER BY vt.is_primary DESC,vt.id LIMIT 1) region_code
         FROM users u
         LEFT JOIN org_units ou ON ou.id=u.org_unit_id
         LEFT JOIN org_roles orr ON orr.id=u.org_role_id
         LEFT JOIN users parent ON parent.id=u.parent_user_id
         LEFT JOIN users supervisor ON supervisor.id=u.supervisor_id
         LEFT JOIN users sales_manager ON sales_manager.id=u.organization_manager_id
         ORDER BY u.id"
    );
    foreach($users as $u)$rows[]=[
        (string)$u['employee_no'],$u['kara_system_code'],$u['name'],$u['username'],$u['mobile'],$u['email'],
        $u['unit_title']?:$u['department'],$u['org_role_title']?:$u['role_key'],$u['manager_employee_no'],
        $u['sales_line'],$u['supervisor_employee_no'],$u['sales_manager_employee_no'],$u['region_code'],$u['status'],''
    ];
    CeoDashboardExcel::output(['کاربران'=>$rows],'sobhan-users-'.date('Y-m-d').'.xlsx');
}
if($action==='errors'){$batch=(int)($_GET['batch_id']??0);$rows=Database::fetchAll("SELECT source_row,employee_no,error_message FROM user_import_rows WHERE batch_id=? AND status IN ('error','skipped') ORDER BY source_row",[$batch]);header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="user-import-errors-'.$batch.'.csv"');echo "\xEF\xBB\xBF"; $out=fopen('php://output','wb');fputcsv($out,['source_row','employee_no','error_message']);foreach($rows as $row)fputcsv($out,$row);fclose($out);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Auth::verifyCsrf($_POST['csrf_token']??'')){flash('اعتبار درخواست منقضی شده است.','danger');redirect('/admin/users-import-export.php');}try{$postAction=(string)($_POST['action']??'preview');if($postAction==='commit'){if(!Auth::can('users.import_export','create'))throw new RuntimeException('permission_denied');$result=UserImportService::commit((int)$_POST['batch_id'],(int)Auth::user()['id']);flash("ثبت نهایی انجام شد؛ {$result['created']} ایجاد، {$result['updated']} بروزرسانی و {$result['skipped']} رد شد.");redirect('/admin/users-import-export.php?batch_id='.(int)$_POST['batch_id']);}$file=$_FILES['excel_file']??[];$ext=strtolower(pathinfo((string)($file['name']??''),PATHINFO_EXTENSION));if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file($file['tmp_name'])||($file['size']??0)>8*1024*1024||!in_array($ext,['xlsx','csv'],true))throw new InvalidArgumentException('فایل CSV یا XLSX معتبر تا حجم ۸ مگابایت انتخاب کنید.');$batch=UserImportService::preview($file['tmp_name'],$file['name'],(string)($_POST['mode']??'create'),isset($_POST['allow_empty_employee_no']),(int)Auth::user()['id']);flash('پیش‌نمایش ایمپورت آماده شد.');redirect('/admin/users-import-export.php?batch_id='.$batch);}catch(InvalidArgumentException $e){flash($e->getMessage(),'danger');}catch(Throwable $e){error_log('User import: '.$e->getMessage());flash('خواندن یا ثبت فایل کاربران انجام نشد.','danger');}redirect('/admin/users-import-export.php');}
$batchId=(int)($_GET['batch_id']??0);$batch=$batchId?Database::fetch('SELECT b.*,u.name importer_name FROM user_import_batches b LEFT JOIN users u ON u.id=b.imported_by WHERE b.id=?',[$batchId]):null;$preview=$batch?Database::fetchAll('SELECT * FROM user_import_rows WHERE batch_id=? ORDER BY source_row LIMIT 500',[$batchId]):[];$batches=Database::fetchAll('SELECT b.*,u.name importer_name FROM user_import_batches b LEFT JOIN users u ON u.id=b.imported_by ORDER BY b.id DESC LIMIT 30');require __DIR__.'/../views/partials/admin-header.php';?>
<div class="workforce-head"><div><h1>ایمپورت و اکسپورت کاربران</h1><p>پیش‌نمایش، اعتبارسنجی ساختار سازمانی و ثبت batch</p></div><div class="form-actions"><a class="btn" href="?action=template">دانلود قالب Excel</a><a class="btn btn-primary" href="?action=export">خروجی کاربران</a></div></div><div class="workforce-grid"><section class="card"><h2>فایل کاربران</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="preview"><label class="form-field"><span>حالت ایمپورت</span><select name="mode"><option value="create">فقط ایجاد کاربران جدید</option><option value="update">فقط بروزرسانی بر اساس شماره پرسنلی</option><option value="upsert">ایجاد و بروزرسانی همزمان</option></select></label><label class="form-field"><span>فایل Excel/CSV</span><input type="file" name="excel_file" accept=".xlsx,.csv" required></label><label class="checkbox-item"><input type="checkbox" name="allow_empty_employee_no"> اجازه شماره پرسنلی خالی</label><div class="form-actions"><a class="btn" href="?action=template">دانلود قالب Excel</a><button class="btn btn-primary">ساخت پیش‌نمایش</button></div></form></section><aside class="card"><h2>قواعد فایل</h2><p>واحد، نقش، کد لاین و کد منطقه باید از فهرست‌های مرکزی باشند. برای ویزیتور، لاین باید مدیر و سرپرست معتبر داشته باشد.</p><p class="muted">کد سیستم کارا یکتا است. در صورت خالی بودن رمز، رمز امن تصادفی ساخته و تغییر رمز اجباری می‌شود.</p></aside></div>
<?php if($batch):?><section class="card"><div class="section-heading-row"><div><h2>پیش‌نمایش Batch #<?=$batch['id']?></h2><p class="muted"><?=e($batch['file_name'])?> — معتبر: <?=$batch['success_count']?>، خطا: <?=$batch['error_count']?></p></div><div class="form-actions"><a class="btn" href="?action=errors&batch_id=<?=$batch['id']?>">دانلود خطاها</a><?php if($batch['status']==='preview'&&Auth::can('users.import_export','create')):?><form method="post" onsubmit="return confirm('ردیف‌های معتبر ثبت نهایی شوند؟')"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="action" value="commit"><input type="hidden" name="batch_id" value="<?=$batch['id']?>"><button class="btn btn-primary">ثبت نهایی</button></form><?php endif?></div></div><div class="table-wrap"><table><thead><tr><th>ردیف</th><th>شماره پرسنلی</th><th>نام</th><th>ایمیل</th><th>وضعیت</th><th>خطا</th></tr></thead><tbody><?php foreach($preview as $row):$raw=json_decode($row['raw_data_json'],true)?:[];?><tr><td><?=$row['source_row']?></td><td><?=e($row['employee_no']?:'—')?></td><td><?=e($raw['full_name']??'')?></td><td><?=e($raw['email']??'')?></td><td><span class="workforce-status status-<?=e($row['status'])?>"><?=e(['valid'=>'معتبر','error'=>'خطا','created'=>'ایجاد شد','updated'=>'بروزرسانی شد','skipped'=>'رد شد'][$row['status']]??'')?></span></td><td><?=e($row['error_message']?:'—')?></td></tr><?php endforeach?></tbody></table></div></section><?php endif?><section class="card"><h2>تاریخچه ایمپورت</h2><div class="table-wrap"><table><thead><tr><th>Batch</th><th>فایل</th><th>کاربر</th><th>حالت</th><th>موفق/خطا</th><th>وضعیت</th></tr></thead><tbody><?php foreach($batches as $b):?><tr><td><a href="?batch_id=<?=$b['id']?>">#<?=$b['id']?></a></td><td><?=e($b['file_name'])?></td><td><?=e($b['importer_name'])?></td><td><?=e(['create'=>'ایجاد','update'=>'بروزرسانی','upsert'=>'ترکیبی'][$b['mode']]??'')?></td><td><?=$b['success_count']?> / <?=$b['error_count']?></td><td><?=e(['preview'=>'پیش‌نمایش','committed'=>'ثبت‌شده','failed'=>'ناموفق'][$b['status']]??'')?></td></tr><?php endforeach?></tbody></table></div></section><?php require __DIR__.'/../views/partials/admin-footer.php';?>
