<?php
require_once __DIR__.'/../../core/Database.php';require_once __DIR__.'/../../lib/FileBackupService.php';
ini_set('display_errors','0');ini_set('display_startup_errors','0');header('Cache-Control: no-store, no-cache, must-revalidate');header('X-Content-Type-Options: nosniff');
function backup_json(int $status,bool $ok,mixed $data=null,?array $error=null,?array $meta=null,string $message=''): never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode(['success'=>$ok,'ok'=>$ok,'data'=>$ok?$data:null,'meta'=>$meta?:new stdClass(),'message'=>$message?:($error['message']??''),'error'=>$ok?null:($error['code']??'BACKUP_FAILED')],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function backup_fail(Throwable $e): never{$map=['backup_disabled'=>[503,'BACKUP_DISABLED','سرویس بکاپ غیرفعال است.'],'api_key_not_configured'=>[503,'SERVICE_NOT_CONFIGURED','کلید API بکاپ تنظیم نشده است.'],'invalid_api_key'=>[401,'UNAUTHORIZED','کلید API معتبر نیست.'],'ip_not_allowed'=>[403,'IP_NOT_ALLOWED','IP درخواست مجاز نیست.'],'method_not_allowed'=>[405,'METHOD_NOT_ALLOWED','متد درخواست مجاز نیست.'],'file_not_registered'=>[404,'NOT_FOUND','فایل ثبت‌شده پیدا نشد.'],'file_not_available'=>[410,'FILE_UNAVAILABLE','فایل روی هاست در دسترس نیست.'],'file_deleted_from_host'=>[410,'FILE_DELETED','فایل قبلاً از هاست حذف شده است.'],'hash_mismatch'=>[409,'HASH_MISMATCH','هش تأییدشده با فایل ثبت‌شده مطابقت ندارد.']];[$status,$code,$message]=$map[$e->getMessage()]??[500,'INTERNAL_ERROR','پردازش درخواست انجام نشد.'];if($status>=500)error_log('File backup API: '.$e->getMessage());backup_json($status,false,null,['code'=>$code,'message'=>$message]);}
function backup_request_data(): array{$contentType=strtolower((string)($_SERVER['CONTENT_TYPE']??''));if(str_contains($contentType,'application/json')){$decoded=json_decode((string)file_get_contents('php://input'),true);return is_array($decoded)?$decoded:[];}return $_POST;}
function backup_require_method(string $method): void{if(strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'))!==strtoupper($method))throw new RuntimeException('method_not_allowed');}
try{
    $provided=trim((string)($_SERVER['HTTP_X_API_KEY']??$_SERVER['HTTP_X_BACKUP_API_KEY']??''));if($provided===''){$authorization=trim((string)($_SERVER['HTTP_AUTHORIZATION']??''));if(preg_match('/^Bearer\s+(.+)$/i',$authorization,$match))$provided=trim($match[1]);}
    if($provided===''){FileBackupService::log(null,'auth','denied','کلید API ارائه نشد.','api');throw new RuntimeException('invalid_api_key');}
    $stored=FileBackupService::apiKeyHash();if($stored==='')throw new RuntimeException('api_key_not_configured');
    if(!hash_equals($stored,hash('sha256',$provided))){FileBackupService::log(null,'auth','denied','کلید API نامعتبر بود.','api');throw new RuntimeException('invalid_api_key');}
    if(!FileBackupService::enabled())throw new RuntimeException('backup_disabled');
    $ip=(string)($_SERVER['REMOTE_ADDR']??'');if(!FileBackupService::ipAllowed($ip,FileBackupService::allowedIps())){FileBackupService::log(null,'auth','denied','IP غیرمجاز: '.$ip,'api');throw new RuntimeException('ip_not_allowed');}
}catch(Throwable $e){backup_fail($e);}
