<?php
require_once __DIR__.'/../../core/Database.php';require_once __DIR__.'/../../lib/FileBackupService.php';
ini_set('display_errors','0');ini_set('display_startup_errors','0');header('Cache-Control: no-store, no-cache, must-revalidate');header('X-Content-Type-Options: nosniff');
function backup_json(int $status,bool $ok,mixed $data=null,?array $error=null,?array $meta=null): never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>$ok,'data'=>$data,'error'=>$error,'meta'=>$meta,'timestamp'=>gmdate('c')],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function backup_fail(Throwable $e): never{$map=['api_key_not_configured'=>[503,'service_not_configured','کلید API بکاپ تنظیم نشده است.'],'invalid_api_key'=>[401,'unauthorized','کلید API معتبر نیست.'],'ip_not_allowed'=>[403,'ip_not_allowed','IP درخواست مجاز نیست.'],'method_not_allowed'=>[405,'method_not_allowed','متد درخواست مجاز نیست.'],'file_not_registered'=>[404,'not_found','فایل ثبت‌شده پیدا نشد.'],'file_not_available'=>[410,'file_unavailable','فایل روی هاست در دسترس نیست.'],'file_deleted_from_host'=>[410,'file_deleted','فایل قبلاً از هاست حذف شده است.'],'hash_mismatch'=>[409,'hash_mismatch','هش تأییدشده با فایل ثبت‌شده مطابقت ندارد.']];[$status,$code,$message]=$map[$e->getMessage()]??[500,'internal_error','پردازش درخواست انجام نشد.'];if($status>=500)error_log('File backup API: '.$e->getMessage());backup_json($status,false,null,['code'=>$code,'message'=>$message]);}
function backup_request_data(): array{$contentType=strtolower((string)($_SERVER['CONTENT_TYPE']??''));if(str_contains($contentType,'application/json')){$decoded=json_decode((string)file_get_contents('php://input'),true);return is_array($decoded)?$decoded:[];}return $_POST;}
function backup_require_method(string $method): void{if(strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'))!==strtoupper($method))throw new RuntimeException('method_not_allowed');}
try{
    $stored=FileBackupService::apiKeyHash();if($stored==='')throw new RuntimeException('api_key_not_configured');
    $provided=trim((string)($_SERVER['HTTP_X_BACKUP_API_KEY']??''));if($provided===''){$authorization=trim((string)($_SERVER['HTTP_AUTHORIZATION']??''));if(preg_match('/^Bearer\s+(.+)$/i',$authorization,$match))$provided=trim($match[1]);}
    if($provided===''||!hash_equals($stored,hash('sha256',$provided))){FileBackupService::log(null,'auth','denied','کلید API نامعتبر بود.','api');throw new RuntimeException('invalid_api_key');}
    $ip=(string)($_SERVER['REMOTE_ADDR']??'');if(!FileBackupService::ipAllowed($ip,FileBackupService::allowedIps())){FileBackupService::log(null,'auth','denied','IP غیرمجاز: '.$ip,'api');throw new RuntimeException('ip_not_allowed');}
}catch(Throwable $e){backup_fail($e);}
